### ISSUE TITLE
AirtestIDE win10无法连接小米mix2

### ISSUE THREAD

**Issue by Archer456** [AirtestProject/Airtest#1]
![image](https://user-images.githubusercontent.com/18392901/35730698-059b804e-084e-11e8-9ba1-84287a74eb6b.png)

左下角已经显示Devices Conected后,那个窗口Device Screen闪了一下,无法显示手机界面.
看日志 有错误  请帮忙适配解决

![image](https://user-images.githubusercontent.com/18392901/35730798-65f9980e-084e-11e8-96d4-1909390a1aec.png)
自带的adb devices -l 是可以正常连接手机的

**Comment by Meteorix** [comment]
你好，感谢你给我们提第一个issue。
我们在win10上测试了小米MIX2，并没有出现问题，请确保你打开了这三项设置开关

![image](https://user-images.githubusercontent.com/3805278/35839935-16639794-0b2e-11e8-8da2-36903b585266.png)


如果还有问题，能提供更详细的报错信息吗？

**Comment by Archer456** [comment]
AirtestIDE_2018-02-27_4.zip    今天换了这个版本  已经可以了  谢谢

**Comment by Meteorix** [comment]
![image](https://user-images.githubusercontent.com/3805278/37022360-bbe75eb8-215d-11e8-930d-63bec05a1f06.png)

你好，本项目即将在3.20GDC发布，欢迎加入QQ讨论群：437119175
