### ISSUE TITLE
moudle not found ,airtest is not a pakage

### ISSUE THREAD

**Issue by Jeerui** [AirtestProject/Airtest#1003]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
pip 安装 airtest 后在python 虚拟环境中导入模块失败

```
发生异常: ModuleNotFoundError
No module named 'airtest.core'; 'airtest' is not a package

```
代码如下：
```
from airtest.core.android.adb import ADB
a = ADB.devices()
print(a)
```

**相关截图**

**pip安装提示**
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: airtest in g:\py_venv\wxpython\lib\site-packages (1.2.3)
Requirement already satisfied: Jinja2>=2.8 in g:\py_venv\wxpython\lib\site-packages (from airtest) (3.0.3)
Requirement already satisfied: Pillow>=3.4.0 in g:\py_venv\wxpython\lib\site-packages (from airtest) (8.4.0)
Requirement already satisfied: requests>=2.11.1 in g:\py_venv\wxpython\lib\site-packages (from airtest) (2.26.0)
Requirement already satisfied: six in g:\py_venv\wxpython\lib\site-packages (from airtest) (1.16.0)
Requirement already satisfied: mss==4.0.3 in g:\py_venv\wxpython\lib\site-packages (from airtest) (4.0.3)
Requirement already satisfied: numpy<=1.19.3 in g:\py_venv\wxpython\lib\site-packages (from airtest) (1.19.3)
Requirement already satisfied: opencv-contrib-python in g:\py_venv\wxpython\lib\site-packages (from airtest) (4.5.4.60)
Requirement already satisfied: facebook-wda>=1.3.3 in g:\py_venv\wxpython\lib\site-packages (from airtest) (1.4.3)
Requirement already satisfied: pywinauto==0.6.3 in g:\py_venv\wxpython\lib\site-packages (from airtest) (0.6.3)
Requirement already satisfied: pywin32 in g:\py_venv\wxpython\lib\site-packages (from airtest) (302)
Requirement already satisfied: comtypes in g:\py_venv\wxpython\lib\site-packages (from pywinauto==0.6.3->airtest) (1.1.10)
Requirement already satisfied: Deprecated~=1.2.6 in g:\py_venv\wxpython\lib\site-packages (from facebook-wda>=1.3.3->airtest) (1.2.13)
Requirement already satisfied: cached-property~=1.5.1 in g:\py_venv\wxpython\lib\site-packages (from facebook-wda>=1.3.3->airtest) (1.5.2)
Requirement already satisfied: retry in g:\py_venv\wxpython\lib\site-packages (from facebook-wda>=1.3.3->airtest) (0.9.2)
Requirement already satisfied: MarkupSafe>=2.0 in g:\py_venv\wxpython\lib\site-packages (from Jinja2>=2.8->airtest) (2.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in g:\py_venv\wxpython\lib\site-packages (from requests>=2.11.1->airtest) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in g:\py_venv\wxpython\lib\site-packages (from requests>=2.11.1->airtest) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in g:\py_venv\wxpython\lib\site-packages (from requests>=2.11.1->airtest) (2.0.9)
Requirement already satisfied: certifi>=2017.4.17 in g:\py_venv\wxpython\lib\site-packages (from requests>=2.11.1->airtest) (2021.10.8)
Requirement already satisfied: wrapt<2,>=1.10 in g:\py_venv\wxpython\lib\site-packages (from Deprecated~=1.2.6->facebook-wda>=1.3.3->airtest) (1.13.3)
Requirement already satisfied: decorator>=3.4.2 in g:\py_venv\wxpython\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest) (5.1.0)
Requirement already satisfied: py<2.0.0,>=1.4.26 in g:\py_venv\wxpython\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest) (1.11.0)

**python 版本:** `python3.8.2`

**airtest 版本:** `1.2.3`

**其他相关环境信息**
windows 10
VS CODE
python 虚拟环境已正确配置

**Comment by yimelia** [comment]
大概率是环境没选正确

**Comment by shixinzi** [comment]
我也是 换了几个环境 都不行 包都能找到，就是死活不行

**Comment by zdevc** [comment]
![b9d366d4a287ac6e6b97ae248098228](https://github.com/AirtestProject/Airtest/assets/40593221/8a77f2e8-07f0-406b-80a8-6c5da7d7ebe7)
我也遇到这个问题，最后发现是试验脚本也叫airtest，和包名重名了
