### ISSUE TITLE
【bug】图像匹配算法的问题，当识别文字/符号时经常会返回明显错误的图片匹配度

### ISSUE THREAD

**Issue by zongrongjin** [AirtestProject/Airtest#1004]
**问题bug**

图像匹配算法返回错误过于明显的匹配度，识别文字组成的图片时尤为明显

**相关截图**

**图1：**
![tpl1638515587967](https://user-images.githubusercontent.com/49151134/145767899-f6e9a3e6-72f1-4e41-af31-af3fb38d4f2f.png)
**图1对应截屏：**
![1639378734452](https://user-images.githubusercontent.com/49151134/145767191-580c69ea-a23c-4435-89f3-06c29f0e4f60.jpg)
**图1执行exists对应log：**
![image](https://user-images.githubusercontent.com/49151134/145768304-50dbc74b-6ae1-4415-ba1d-3ea6b2ab6323.png)

**因为图1和图2都有一个“公”字，所以匹配度直接高达0.7以上，显然是错误的**

**复现步骤**
```
>>> device = init_device()
>>> screen = device.snapshot(filename="图一对应截屏.png", quality=ST.SNAPSHOT_QUALITY)
>>> match_pos = Template("图1.png").match_in(screen)
>>> print(match_pos )
```

**python 版本:** `python3.6.8`

**airtest 版本:** `1.2.4`

**其他相关环境信息**
代码运行环境win10

**Comment by yimelia** [comment]
目前图像匹配不太适用于文字场景，这个问题暂时无解，可能考虑用poco或其他方式，如OCR来检测文字内容更好
