### ISSUE TITLE
当使用python多线程实例化AndroidUiautomationPoco，导致只有一个手机运行成功,且抛出异常

### ISSUE THREAD

**Issue by qwerdome** [AirtestProject/Airtest#1006]
import subprocess
from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
import threading
import logging
logger = logging.getLogger('airtest')
logger.setLevel(logging.INFO)
def start_app_my(devices_my):
    my_dev = connect_device("Android:///{}".format(devices_my))
    my_dev.start_app("com.android.chrome")
    my_dev.shell("ime set com.netease.nie.yosemite/.ime.ImeService")
    poco=AndroidUiautomationPoco(device=my_dev, use_airtest_input=True, screenshot_each_action=False)
    poco("com.android.chrome:id/menu_button").click()
    poco(text="设置").click()
    poco(text="搜索引擎").click()
    poco(text="搜狗").click()
    poco("转到上一层级").click()
    poco("转到上一层级").click()

if __name__ == '__main__':
    t1 = threading.Thread(target=start_app_my, args=("872QEDTP225SZ",))
    t2 = threading.Thread(target=start_app_my, args=('192.168.51.167:5555',))
    t1.start()
    t2.start()
    t1.join(130)
    t2.join(130)
<br>
当运行上诉代码，会抛出
   raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text=设置"

**Comment by yimelia** [comment]
报错内容是找不到设置这个节点
