### ISSUE TITLE
新版1.2.13 无法启动IDE

### ISSUE THREAD

**Issue by Conneraoge** [AirtestProject/Airtest#1016]
**Describe the bug**
从官网下载Airtest安装包后，解压放到D盘，然后双击AirtestIDE.exe 界面闪一下就什么都没有了
```



**Screenshots**
![image](https://user-images.githubusercontent.com/12369229/148190197-16a96bab-de99-4aa6-b382-4972808dcce4.png)



**python version:** `python3.7`

**Comment by yimelia** [comment]
尝试下载32位版本试试看？

**Comment by Conneraoge** [comment]
32位可以启动了，不过之前的版本（64位）是可以正常启动和使用的，后来过了一阵子再想使用时就启动不了；

所以想着换个新版再看看，结果64位的还是不可以，终归不影响使用了，谢谢~~@yimelia
