### ISSUE TITLE
airtest添加cookier绕过滑块验证码

### ISSUE THREAD

**Issue by Dawnbrilliance** [AirtestProject/Airtest#1021]
:bulb:**相关项目:** Airtest

**标题:** [问题咨询]airtest添加cookier绕过滑块验证码

**AirtestIDE版本:** 无

**未使用本地Pyhton环境运行脚本**

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;airtest测试的时候想绕过登录验证码，airtest添加cookier绕过滑块验证码，没找到相关方法和文档，麻烦给出文档和方法

**相关截图:**
无

**报错Log:**
```
无
```

**连接设备信息:**
设备类型 | 设备型号 | 系统版本号 | apk名称/下载链接
------------ | ------------- | ------------- | -------------
Android |  |  | 

**提供最小可复现此BUG的代码:**
```
无
```

**Comment by yimelia** [comment]
暂无接口。验证码的作用就是防止机器人操作，所以需要自行解决此问题，如果是贵公司自己的项目，可以通过让程序帮忙在调试环境下跳过验证步骤即可。
