### ISSUE TITLE
adb 自定义命令问题（adb push , adb pull）

### ISSUE THREAD

**Issue by Mav97** [AirtestProject/Airtest#1029]
看到源代码的方法里没有集成adb push或pull，是我没找到吗，还是没有对这个命令集成。

**Comment by yimelia** [comment]
https://airtest.readthedocs.io/en/latest/all_module/airtest.core.android.adb.html#airtest.core.android.adb.ADB.pull

dev = device()
dev.adb.pull(xx, xx)
