### ISSUE TITLE
Screen is None, may be locked，经常导致手机卡死，跪求解决方案。。所有手机都这样。。。最老的版本没事

### ISSUE THREAD

**Issue by QAwangyang** [AirtestProject/Airtest#103]
最新版本，0.1.4，在执行过程中中断脚本经常导致手机卡死，得重启手机

三星J7
![image](https://user-images.githubusercontent.com/18697155/42671716-13dfe054-8694-11e8-868f-463445a505a9.png)

**Comment by Meteorix** [comment]
你好，这个warning其实是因为手机卡死了才导致截屏为空。所以应该是其他原因导致手机卡死的。我们后续测试一下这个型号，感谢反馈

**Comment by QAwangyang** [comment]
我用最早的版本 0.0.8 没有遇到这个问题，相同的设备。。。所以已经把最新的版本卸了，用了稍微老的版本，另外最新的mac版也遇到了这个问题，在不同的手机上

**Comment by yimelia** [comment]
@QAwangyang 你好，这个问题比较特别，可能需要了解更多情况，请问你在我们的QQ讨论群里么（437119175）？或者愿意留下邮箱之类的联系方式么，我们可能需要了解下你使用的脚本内容（是特定脚本导致这样的问题，还是运行任意脚本都会这样？

**Comment by QAwangyang** [comment]
@yimelia 
![image](https://user-images.githubusercontent.com/18697155/42742170-6b1afa44-88eb-11e8-985e-625b1f5f97d5.png)
加群了~28444那个  冰河
 脚本内容挺简单的。 谢谢啦~

**Comment by yimelia** [comment]
@QAwangyang 最近的版本可以尝试一下，可能已经修复了这个问题
