### ISSUE TITLE
如何指定log内容文件夹的路径？

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#1059]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
我的项目需要在自定义的启动器中运行多个脚本，并把各个.air脚本的运行报告和日志信息都放到新增的单独的日志文件夹中

生成报告的方法是在启动器中使用simple_report()接口

但是使用simple_report()接口时，我发现**各个.air脚本的日志信息（log文件夹）默认放在了对应的.air脚本文件夹下**，如图

![image](https://user-images.githubusercontent.com/42226268/174036778-adb9148e-4c99-4afa-b089-750e7ef200ec.png)

airtest教程中log内容的路径应该是由 **logpath** 这个变量控制的，于是我修改了一下api，**强制指定logpath到日志文件夹中**，脚本也运行成功了，没有报错

**但是log信息仍然记录在.air脚本文件夹下，同时simple_report()接口的output变量导出的html报告，也变成了一片空白，没有填写到log的信息**

**预期效果**
我想搞明白的是，怎么才能指定log内容文件夹路径，让它不在.air脚本文件夹下出现呢？只修改simple_report()接口可以实现这个功能吗？

**python 版本:** `python3.6.8`

**airtest 版本:** `1.2.4`

**设备:**
 - 型号: PC电脑
 - 系统: windows7 x64

**Comment by niuniuprice** [comment]
@yimelia 请问log文件夹的路径应该怎么设置呢？

**Comment by skyfire1997** [comment]
@niuniuprice 试试添加下面代码
from airtest.core.settings import Settings as ST
ST.LOG_DIR = "指定log目录"

**Comment by niuniuprice** [comment]
> @niuniuprice 试试添加下面代码 from airtest.core.settings import Settings as ST ST.LOG_DIR = "指定log目录"

尝试了在启动器中run_script()之前设置、还有在对应的脚本中设置，但是都不起效，log文件夹仍然出现在脚本文件夹中

我猜想可能是某个api的默认设置是把log信息存放在basedir里面？

**Comment by niuniuprice** [comment]
问题原因是在脚本中又进行了带参数的auto_setup，导致日志存放位置更新，修改后问题解决
