### ISSUE TITLE
Mac os 10.11.2 AirtestIDE闪退，app无法正常打开

### ISSUE THREAD

**Issue by xushihao** [AirtestProject/Airtest#106]
已通过pip安装airtest及相关第三方模块，且允许授权应用使用，没有被防火墙拦截

> sudo -H pip install -U airtest  

请教一下怎么解决，thx
（不知道怎么插图，见谅~）

**Comment by yimelia** [comment]
系统要求是：macOS 10.12.1 或更高~可以更新一下macos再尝试
