### ISSUE TITLE
已存在的图片报错File not exist问题

### ISSUE THREAD

**Issue by wjwABCDEFG** [AirtestProject/Airtest#1063]
:bulb:**相关项目:** Airtest

**标题:** [BUG提交]已存在的图片报错File not exist问题

**AirtestIDE版本:** 1.2.11

- [x] **使用了本地Pyhton环境运行脚本**
- Python版本: 3.6.5
- Airtest版本: v1.2.4

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;该问题为偶现bug，但如果一次出现后，次次必现。
我使用airtest测某个工具，如果突然有一次工具升级，某些地方可能伴随UI的修改导致识图不准确，此处应该报错not find in screen，但是报的却是File not exist，且这张图片确实存在于.air文件夹中。
注：正常情况下脚本会有30分钟限制，如果超过30分钟会timeout，但是该错误会导致脚本一直卡在这里循环

**相关截图:**
![](https://hfc20-issue-helper.s3.nie.netease.com/media/2022/07/05/319/image.png)

**报错Log:**
```
无
```

**连接设备信息:**
无

**提供最小可复现此BUG的代码:**
```
建议重点排查代码：swipe(pic1, pic2)这个函数相关的代码
例如swipe(pic1, pic2)，由于pic1识别不到了，却是报File not exist: pic2.png
临时解决方法：重新截图pic1和pic2
```

**Comment by yimelia** [comment]
暂时没有能找到复现的办法，但是在这个commit里尝试做了兼容：https://github.com/AirtestProject/Airtest/pull/1083/commits/7358af62a4b94ac244f9c5c924b611e4d0aff7ce
会更新到1.2.7版本，后续可以再观察一下

**Comment by wjwABCDEFG** [comment]
非常感谢
