### ISSUE TITLE
Firebase Build Instrumentation APK crashes the app

### ISSUE THREAD

**Issue by edencakir** [AirtestProject/Airtest#109]
Firebase Build Instrumentation APK crashes the IDE on completion.

Here is the full log: https://gist.github.com/edencakir/a30aa8bd7174847706ddea4c827d761d

**Comment by zzldjkzxf** [comment]
@edencakir  Hi, I want to know more about your question. Were you using the target folder when you build instrumentation apk?  Like your terminal opened the built apk path. Have you ever build succeed? or it crashed every time?

**Comment by edencakir** [comment]
I'm just using the latest AirtestIDE with the script below. No additional configurations (like target folder -- not sure where to configure that too). And using the top menu for building instrumentation apk.

```
# -*- encoding=utf8 -*-
__author__ = "enes"

from airtest.core.api import *

auto_setup(__file__)

from poco.drivers.unity3d import UnityPoco
poco = UnityPoco()
```

This window opens and crashes.

<img width="402" alt="screen shot 2018-07-23 at 10 12 11 am" src="https://user-images.githubusercontent.com/6555480/43062275-f75c415a-8e60-11e8-99ee-28d42ffd778d.png">

**Comment by edencakir** [comment]
Update: with the latest version of Airtest(2018-07-20), the dialog just hangs at 85% instead of crashing.

**Comment by zzldjkzxf** [comment]
@edencakir  Do you have "jdk" environment on your local? 
You can print "jarsigner" on your terminal to verify this question. And can you screenshot the output of your terminal after you send "jarsigner". Thanks.

**Comment by edencakir** [comment]
Sure:

<img width="709" alt="screen shot 2018-07-23 at 11 44 33 am" src="https://user-images.githubusercontent.com/6555480/43066610-cb0fb4d0-8e6d-11e8-89fb-1ef5e495e29b.png">

**Comment by zzldjkzxf** [comment]
@edencakir  I found the problem.  I'm sorry about that. 
It because of the python3 bytes type. We will fix it on next version.

**Comment by edencakir** [comment]
Great, looking forward to that!

**Comment by edencakir** [comment]
any timeline for the release? @zzldjkzxf

**Comment by zzldjkzxf** [comment]
@edencakir  This issue has been resolved. Our next Airtest-IDE version would be released on next Tuesday. You can download it on that time.

**Comment by zzldjkzxf** [comment]
@edencakir  New Airtest-IDE has released.  You can check your problem on it. If this proble is still here, let us know.
