### ISSUE TITLE
支持IOS APP吗？

### ISSUE THREAD

**Issue by yili1992** [AirtestProject/Airtest#11]
支持IOS APP吗？

**Comment by Meteorix** [comment]
目前还在开发中
现在的代码里有一个基于facebook wda的实现，不太好用，如果感兴趣可以拿去试试

**Comment by candialala** [comment]
@Meteorix 可以给个支持ios的试用包吗

**Comment by Meteorix** [comment]
@candialala 目前的iOS支持还是一个没法发布的状态，主要是wda的底层太慢而且连接不稳定，等我们重写之后吧~

**Comment by candialala** [comment]
@Meteorix 有没有发布ios版的大致时间呢

**Comment by Meteorix** [comment]
iOS支持正在全力开发中，目测4月内会有一个版本

**Comment by Meteorix** [comment]
iOS支持已经开放测试，欢迎试用：

https://github.com/AirtestProject/iOS-Tagent
