### ISSUE TITLE
连接mumu模拟器，获取到界面是黑屏的~

### ISSUE THREAD

**Issue by erbozhao** [AirtestProject/Airtest#110]
可以连接mumu模拟器，但获取到界面是黑屏的~

**Comment by erbozhao** [comment]
我尝试执行 adb shell rm /data/local/tmp/minicap， 然后重连还是黑屏的~

**Comment by Meteorix** [comment]
你好，mumu模拟器要用javacap方式启动，参考[这里](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/6_device_connection/2_emulator_connection.html#id3)

**Comment by erbozhao** [comment]
@Meteorix 谢谢，可以了
