### ISSUE TITLE
How not to write log with function "exists ()" ?

### ISSUE THREAD

**Issue by Guest771** [AirtestProject/Airtest#112]
Hello! I need to skeep many steps logs in web-report for certain functions. Is it supported? Is it possible to do in the future?

![image](https://user-images.githubusercontent.com/41613144/43123431-5789c7b2-8f4e-11e8-9e60-a6da548544b8.png)

![image](https://user-images.githubusercontent.com/41613144/43123035-2ef29f3c-8f4d-11e8-9428-467a5fd73861.png)

**Comment by Meteorix** [comment]
You can write your own `exists` function, without `logwrap` decorator: [reference](https://github.com/AirtestProject/Airtest/blob/1f8acc45e8a88a4ed23927f888a12e36755d3dd9/airtest/core/api.py#L401)
