### ISSUE TITLE
selenium airtest图像识别模块报错

### ISSUE THREAD

**Issue by r455678** [AirtestProject/Airtest#114]
windows10+python3.7+airtest0.1.5
当执行如下语句时：
driver.airtest_touch()
报错
NameError: name 'Template' is not defined

driver.assert_template()同
![image](https://user-images.githubusercontent.com/28941025/43310838-4bbd7496-91bb-11e8-9575-d22f7ae65546.png)

**Comment by zzldjkzxf** [comment]
@r455678  selenium的airtest图像识别，不能把初始化的代码删掉哈 
"from airtest.core.api import *" 把这个加上就行了
