### ISSUE TITLE
Airtest Package Install Error (Could not find a version that satisfies the requirement opencv)

### ISSUE THREAD

**Issue by alirsaid** [AirtestProject/Airtest#115]
I use Python 3.7.0

Whenever I try to install the airtest module I get this error from Command Prompt

> Could not find a version that satisfies the requirement opencv-contrib-python = 3.2.0.7 (from airtest) (from versions: 3.4.2.16, 3.4.2.17)
> No matching distribution found for opencv-contrib-python == 3.2.0.7 (from airtest)

My cv2 version is 3.4.2 and when I try to `pip install opencv-contrib-python` Command Prompt reply as

>Requirement already satisfied: opencv-contrib-python in c:\python\lib\site-packages (3.4.2.17)
Requirement already satisfied: numpy>=1.14.5 in c:\python\lib\site-packages (from opencv-contrib-python) (1.15.0)

I've also tried to install this via git repo, however I get the same error message.

What should I do, please help.

**Comment by rockywhisper** [comment]
@alirsaid   Hi.

Python3.7.0 is pretty new, and many third-party libraries (like opencv-contrib-python) don't support this version yet.  I suggest you use python3.6 instead, and we'll add a note about this in the docs later.  ：）

**Comment by alirsaid** [comment]
@rockywhisper  Thank you so much!. I installed Python 3.6.5 and problem fixed.
