### ISSUE TITLE
如何生成在线报告

### ISSUE THREAD

**Issue by EdwardCheck** [AirtestProject/Airtest#1158]
**描述问题bug**
使用report.LogToHtml会生成一个.html报告，但是只能本地查看报告里面的图片路径，当我把报告上传服务器后图片就加载不了。
有办法提供报告远程查看吗？

**相关截图**
![image](https://github.com/AirtestProject/Airtest/assets/25213289/f0fd784d-0c2f-403d-af73-ad9301eb1923)

**Comment by yimelia** [comment]
可以添加export_dir参数去导出报告，这样生成的图片路径就都是相对路径了，再加上static_root参数，把静态文件都放在统一的静态服务路径就可以了，https://airtest.doc.io.netease.com/IDEdocs/airtest_framework/6_airtest_report/#2export_dir
https://airtest.doc.io.netease.com/IDEdocs/3.5about_report/Generate_report%20_command/#3outfileexport
