### ISSUE TITLE
How to disable Yosemite?

### ISSUE THREAD

**Issue by alirsaid** [AirtestProject/Airtest#116]
We generated a test scripts with airtest, however yosemite keyboard block our process. How can we disable yosemite with python script?

**Comment by edencakir** [comment]
We're unable to detect our inputs (unity game), thus can't enter text.

We were planning to install a 3rd party keyboard app and use it in our test devices, and use image rec. for each key stroke

**Comment by edencakir** [comment]
@alirsaid can you take a look at it based on what @adolli said?

**Comment by alirsaid** [comment]
@adolli We couldn't understand how to set keyboard input via using yosemite. English documents are insufficient for us to understand which methods does yosemite have and how to use. If you enlight us about usage of yosemite, we would be grateful.

**Comment by adolli** [comment]
I am sorry for the inconvenience of the current document state. There are some ways you can do to disable the Yosemite forcibly.
```python
from airtest.core.api import connect_device
dev = connect_device('Android:///?ime_method=adbime')  # initiallize the device object explicitly by given ime declaration
```
```python
from airtest.core.api import device as current_device
current_device().yosemite_ime.end()  # or get the current device object from context then call the ime apis
```
I am not sure how your script looks like. So please have a try the snippets above.

**Comment by yeziyfx** [comment]
> I am sorry for the inconvenience of the current document state. There are some ways you can do to disable the Yosemite forcibly.
> 
> ```python
> from airtest.core.api import connect_device
> dev = connect_device('Android:///?ime_method=adbime')  # initiallize the device object explicitly by given ime declaration
> ```
> 
> ```python
> from airtest.core.api import device as current_device
> current_device().yosemite_ime.end()  # or get the current device object from context then call the ime apis
> ```
> 
> I am not sure how your script looks like. So please have a try the snippets above. Hope this will help.

你好，像current_device().yosemite_ime.end()这行的yosemite_ime这个用法在哪能找到对应文档啊？
