### ISSUE TITLE
命令行版本和pip安装版本对应不上

### ISSUE THREAD

**Issue by aogg** [AirtestProject/Airtest#1161]
![image](https://github.com/AirtestProject/Airtest/assets/8998031/d4701858-f2ec-43e8-bcf9-e5f1ffd851bf)
![image](https://github.com/AirtestProject/Airtest/assets/8998031/59d207de-1f51-469c-9493-2983f5b55558)

**Comment by aogg** [comment]
pip缺少v1.2.15

**Comment by fishfish-yu** [comment]
pip install airtest
可以安装airtest库，第一张截图的版本是ide的版本，第二张截图是airtest库的最新版本
