### ISSUE TITLE
提问：使用ios设备测试的话，有没有像安卓的MotionEvent一样的方法可以使用？

### ISSUE THREAD

**Issue by SmallMousePP** [AirtestProject/Airtest#1164]
- 背景：想要实现长按并拖动到某个位置松开的操作，目前翻阅资料已知安卓设备使用MotionEvent可以实现该操作，但是没有找到ios对应的方法
- 问题：ios是否有自由手势操作组合的方法？如果没有的话能否实现呢，这个真的很希望能用到，谢谢🙏

**Comment by yimelia** [comment]
目前暂时是没有的
