### ISSUE TITLE
获取到的adb为空，导致运行失败

### ISSUE THREAD

**Issue by Pactortester** [AirtestProject/Airtest#1166]
https://github.com/AirtestProject/Airtest/blob/182d0be360059a79acf67b3356bc8169299379e1/airtest/core/android/adb.py#L75

**描述问题bug**

获取到的adb为空，导致运行失败

```
[19:14:59][DEBUG]<airtest.core.android.adb>  -s 172.17.30.19:5555 get-state
```

**相关截图**
![image](https://github.com/AirtestProject/Airtest/assets/29191106/4f34c888-c1c8-4c46-a1cd-b4012c810c74)

**python 版本:** `python3.8`

**airtest 版本:** `1.3.1`

**Comment by yimelia** [comment]
这个问题有没有可能的复现方式？我们尝试复现一下

**Comment by yimelia** [comment]
https://github.com/AirtestProject/Airtest/pull/1186/commits/5556daa9eaa92dc7a9c765457817a9b498e028b0
