### ISSUE TITLE
Android录屏使用FFmpeg格式，结束录屏参数is_interrupted=True没有效果（存在这个参数当前路径也存在视频）

### ISSUE THREAD

**Issue by qwerdome** [AirtestProject/Airtest#1167]
python：3.7.6
airtest: 1.3.1
用例如下
```
from airtest.core.api import *
import time
import logging
def luping(devices):
    url = f"Android:///{devices}"
    dev = connect_device(url)
    dev.start_recording(mode="ffmpeg")
    time.sleep(5)
    dev.stop_recording(is_interrupted=True)

if __name__ == '__main__':
    logger_ = logging.getLogger('airtest')
    logger_.setLevel(logging.INFO)
    luping("")
```
执行完成后当前文件夹还存在视频，如果将mode修改为ffmpeg或者没有mode参数就不存在视频，日志也显示的停止录屏
![image](https://github.com/AirtestProject/Airtest/assets/74087938/17875be7-955f-445a-9740-0e508e08d3bb)

**Comment by yimelia** [comment]
对，ffmpeg模式下，is_interrupted=True这个参数是无效的，我们后续更新一下注释

**Comment by qwerdome** [comment]
使用ffmpeg模式，没有中断录屏的其他参数嘛

**Comment by qwerdome** [comment]
> 对，ffmpeg模式下，is_interrupted=True这个参数是无效的，我们后续更新一下注释

使用ffmpeg模式，没有中断录屏的其他参数嘛

**Comment by yimelia** [comment]
对，中断可能会导致录屏文件有问题，之前的录屏文件是存在手机里的，所以可以用这个参数去把文件拉出来，但ffmpeg是一边录一边直接在pc上面写录屏，如果断了的话有可能文件就坏了。

我们后面应该还会再加一种新的录屏模式，用来代替之前旧的录屏方案，等我们测试过兼容性没问题之后会再更新
