### ISSUE TITLE
怎么实现断点续传呢

### ISSUE THREAD

**Issue by wcp1234** [AirtestProject/Airtest#117]
请问各位大神，Airtest里怎么实现断点续传呢。如连续执行N个步骤，但中间某个步骤由于找不到控件等原因执行失败后，后面的步骤可以继续执行

**Comment by yimelia** [comment]
@wcp1234 比较简单的方式可以先判断是否存在，再进行点击
```
if exists(图片):
    touch(图片)
```

如果觉得每次都这样写很麻烦，可以把它封装成一个你自己的点击操作。如果是poco控件也是同理。
