### ISSUE TITLE
微信h5 输入密码是出现 OSError: socket connection broken

### ISSUE THREAD

**Issue by aajustin** [AirtestProject/Airtest#1170]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
微信h5 输入密码是出现 OSError: socket connection broken

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
<img width="641" alt="image" src="https://github.com/AirtestProject/Airtest/assets/50102358/a17c7d4c-3083-4af9-842f-d46986ab0257">

**复现步骤**
1. h5页面，到输入密码步骤
2. 等待时间完毕后，报错

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号:三星s10
 - 系统: 安卓11
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by aajustin** [comment]
@yimelia

**Comment by yimelia** [comment]
大概率是手机设置里的安全输入选项没关闭，或者是防止录屏截屏的选项没有关闭，可以找一下看看

**Comment by aajustin** [comment]
> 大概率是手机设置里的安全输入选项没有关闭，或者是阻止录屏截屏的选项没有关闭，可以找一下看看

不可能的，我是单机跑，一天不断跑，用Jenkins执行，每次扫11种不同品类的二维码，前6种二维码基本不会出现这种情况，
第7种二维码开始，偶发现会在支付页面出现socket connection broken报错。安全输入选项没有关闭，或者是没有阻止录屏截屏，这些早就关闭了@yimelia
