### ISSUE TITLE
Yosemite啥时候开源？

### ISSUE THREAD

**Issue by MrGuoRanDuo** [AirtestProject/Airtest#1175]
公司内网开发环境遇到了录屏只有一半的问题  想查问题都没法查

**Comment by yimelia** [comment]
可以更到最新版，然后start_recording支持一个参数mode='ffmpeg'，用这个模式不会半屏

**Comment by MrGuoRanDuo** [comment]
ffmpeg是启动在本地或服务端的  而不是手机，这样会徒增服务器cpu压力   不知道ffmpeg有没有手机jar包

**Comment by MrGuoRanDuo** [comment]
@yimelia
