### ISSUE TITLE
minicap 资源收回问题。

### ISSUE THREAD

**Issue by liyuefeng** [AirtestProject/Airtest#1177]
minicap中下面的这个函数在关闭minicap的时候android7版本使用ps -A| grep minicap 找不到minicap进程，跑多个任务，minicap进程会越来越多，导致手机特别卡。
    def _cleanup_minicap(self):
        """
        Clean up the minicap process whose status is __skb_wait_for_more_packets or futex_wait_queue_me
        清理状态为__skb_wait_for_more_packets, futex_wait_queue_me的minicap进程

        Returns:

        """
        # 卡住的进程状态
        TASK_INTERRUPTIBLE1 = "__skb_wait_for_more_packets"
        TASK_INTERRUPTIBLE2 = "futex_wait_queue_me"

        try:
            shell_output = self.adb.shell("ps -A| grep minicap")
        except:
            pass
        else:
            if len(shell_output) == 0:
                return
            for line in shell_output.split("\r\n"):
                if TASK_INTERRUPTIBLE1 in line or TASK_INTERRUPTIBLE2 in line:
                    pid = line.split()[1]
                    try:
                        self.adb.shell("kill %s" % pid)
                    except:
                        pass

**Comment by yimelia** [comment]
这个是手机权限问题，不是所有手机都允许这样查询，或者你可以帮忙提供一下具体的手机型号？我们尝试测试一下

**Comment by liyuefeng** [comment]
手机型号vivo X9i   android版本：7.1.2
![微信截图_20231129151510](https://github.com/AirtestProject/Airtest/assets/15939108/58c6eff0-22ee-4351-a22e-ef13e54db0cd)

**Comment by yimelia** [comment]
感谢反馈，已经确认问题，将在下个版本修复
