### ISSUE TITLE
拿到元素后，get其中的text，中文字符"周生生"拿到的是\u5468\u751f\u751f\u4eac\u4e1c\u65d7\u8230\u5e97

### ISSUE THREAD

**Issue by carozuoP** [AirtestProject/Airtest#118]

**Comment by adolli** [comment]
请贴一下代码

**Comment by carozuoP** [comment]
__author__ = "zuoqiong"
from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
poco("com.jingdong.app.mall:id/a3q").click()
poco("com.jd.lib.search:id/search_text").set_text("周生生")
poco("com.jingdong.app.mall:id/awc").click()
poco("com.jd.lib.search:id/ads_shop_list_item_shopname").click()
#poco("com.jd.lib.jshop:id/jshop_shopname").click()
name = poco("com.jd.lib.jshop:id/jshop_shopname").get_text()
print(name)

**Comment by carozuoP** [comment]
除了修复上面问题外，我还想请问一下，有没有办法，可以直接写python的，调用python本身的方法，直接把字符转回来呢，这样我可以自己先解决下这个问题，谢谢

**Comment by adolli** [comment]
我们的脚本就是python脚本，你可以调用python的所有api，做所有python能做的事。

**Comment by adolli** [comment]
打印出来的中文无法正常显示是AirtestIDE里log panel的bug，我们正在修复中。

**Comment by carozuoP** [comment]
我直接调用了python的方法：
name = poco("com.jd.lib.jshop:id/jshop_shopname").get_text() 
#这个时候names是\u5468\u751f\u751f\u4eac\u4e1c\u65d7\u8230\u5e97
print(name.encode('utf-8')) 
#这个时候打印出来的是b'\xe5\x91\xa8\xe7\x94\x9f\xe7\x94\x9f\xe4\xba\xac\xe4\xb8\x9c\xe6\x97\x97\xe8\x88\xb0\xe5\xba\x97'
为什么打印的不是“周生生京东旗舰店”呢

我自己本地写的python脚本调试：
item = '\u5468\u751f\u751f\u4eac\u4e1c\u65d7\u8230\u5e97'
item.encode('utf-8')
print(item) # 这个打印出来是“周生生京东旗舰店”

**Comment by adolli** [comment]
这个不是你的代码的问题，是AirtestIDE里log panel处理中文转义导致的显示错误。在下一个版本会修复的。

**Comment by yimelia** [comment]
@carozuoP 你使用了本地的python2来运行脚本的吗？

**Comment by carozuoP** [comment]
本地安装的是python3，之前是python2，然后遇到这个错误，升级到了python3，还是遇到这个错误

**Comment by yimelia** [comment]
@carozuoP 该BUG已经修复，抱歉之前忘了回复，请试用下最新版本

**Comment by WindTraveler** [comment]
mac下这个bug还是存在。

代码：
```
text = poco("android.webkit.WebView").child("android.webkit.WebView").child("android.view.View")[1].get_text()

print(text)
```
log panel中的显示如下：
![image](https://user-images.githubusercontent.com/13325131/51362763-deec5380-1b0f-11e9-8c57-0593137216b2.png)

@yimelia @adolli

**Comment by yimelia** [comment]
求贴一下使用的app和场景？我们复现一下看看

**Comment by WindTraveler** [comment]
比如: 在【今日头条】中搜索【小程序能力展示】，进入该小程序
![image](https://user-images.githubusercontent.com/13325131/51363272-38ee1880-1b12-11e9-853e-45ae12e2bf56.png)

进入后，录制脚本，尝试print以下文字：
![image](https://user-images.githubusercontent.com/13325131/51363378-ac902580-1b12-11e9-910b-c96bb0023f12.png)

```
# -*- encoding=utf8 -*-
from poco.drivers.android.uiautomation import AndroidUiautomationPoco

poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

text=poco("com.ss.android.article.news:id/tma_swipe_target").child("android.webkit.WebView").child("android.webkit.WebView").child("android.view.View")[5].get_text()

print(text)
```

结果：
![image](https://user-images.githubusercontent.com/13325131/51363403-be71c880-1b12-11e9-94cc-358f49364ada.png)

@yimelia

**Comment by yimelia** [comment]
hi @WindTraveler 请问下是否在设置中，Python.exe那个设置里，指定了本地的python2来运行脚本的？

**Comment by WindTraveler** [comment]
你好，并没有修改过设置
![image](https://user-images.githubusercontent.com/13325131/51449636-e73ecb80-1d67-11e9-9b23-b438231e452a.png)

但是我发现，如果使用【只运行选中代码】功能，是可以正常打印出汉字的
![image](https://user-images.githubusercontent.com/13325131/51449689-2e2cc100-1d68-11e9-9b80-cc1766292860.png)

打印结果：
![image](https://user-images.githubusercontent.com/13325131/51449728-53b9ca80-1d68-11e9-8801-6dca60b13cf4.png)

**Comment by Sdot-Python** [comment]
可以试试下面这个：
如果是Python2
`text.decode('unicode-escape')`
如果是python3
`text.encode('utf-8').decode('unicode_escape')`
