### ISSUE TITLE
剪贴板设置和获取功能

### ISSUE THREAD

**Issue by Ymars1990** [AirtestProject/Airtest#1180]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues

**描述问题bug**
/venv/lib/python3.9/site-packages/airtest/core/android/static/adb/mac/adb -s 1A051FDEE00AEQ shell app_process -Djava.class.path=/data/app/~~WTAurYPHzHfjGzcyl0XUfg==/com.netease.nie.yosemite-siGNYHvhDCAvshw4PIw61w==/base.apk / com.netease.nie.yosemite.control.Control --DEVICE_OP clipboard_get
Could not invoke method java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, class java.lang.String, int]

**复现步骤**
剪贴板已有内容，调用get_clipboard()

**预期效果**
获取剪贴板内容
**airtest 版本:** `1.3.2`
 - 型号: 三星
 - 系统: android 14
执行平台：mac  intel芯片

**Comment by yimelia** [comment]
本问题在v1.3.3版本之后将会得到修复

**Comment by zhaomoqiang** [comment]
shell app_process -Djava.class.path=/data/app/com.netease.nie.yosemite-KM6U7aKhwL5T9S8RzIdKpA==/base.apk / com.netease.nie.yosemite.control.Control --DEVICE_OP clipboard_get
Could not invoke method java.lang.reflect.InvocationTargetException
null
airtest 版本: 1.3.4
如何定位是什么问题导致的。
