### ISSUE TITLE
开启IDE情况下，命令行执行时获取的adb进程路径有时候空的

### ISSUE THREAD

**Issue by lzus** [AirtestProject/Airtest#1189]
**Describe the bug**
get_adb_path return None

**To Reproduce**
1. 打开airtestIDE的情况下
2.  命令行执行airtest脚本

非必现，有的时候出现，发现adb进程被airtestIDE占用，但是exe路径是空的， 如截图所示

**Expected behavior**

**Screenshots**
调试信息：
<img width="1409" alt="image" src="https://github.com/AirtestProject/Airtest/assets/48306281/61fc769d-4164-4c71-b38f-137455b66d24">

进程信息：
<img width="1045" alt="image" src="https://github.com/AirtestProject/Airtest/assets/48306281/4a4e1ffa-d717-43f2-9098-e2cad6a7dee4">

**python version:** `python3.8`

**airtest version:** `1.3.2`

**Comment by Pactortester** [comment]
更新最新版 `pip install -U airtest` 已经修复了
