### ISSUE TITLE
How to run script simultaneously in multiple Android Device?

### ISSUE THREAD

**Issue by Al-Said** [AirtestProject/Airtest#119]
I prepared scripts and main test script call the other scripts. However I could not find a way to run tests in two or more devices from one computer. Could you enlight me how can I do this parallel testing ?

p.s. I found a subject on stackoverflow https://stackoverflow.com/questions/51147280/androidviewclient-how-to-run-a-python-script-simultaneously-in-multiple-devices but I unfortunately I could not understand what should I do.

**Comment by SUDARSHANCHAUDHARI** [comment]
you can run your script from bat file and change the device id

https://airtest.readthedocs.io/en/latest/README_MORE.html#running-air-from-cli

# run test test cases and scenarios on various devices
> airtest run "path to your .air dir" --device Android:///
> airtest run "path to your .air dir" --device Android://adbhost:adbport/serialno
> airtest run "path to your .air dir" --device Windows:///?title_re=Unity.*
> airtest run "path to your .air dir" --device iOS:///
...
# show help
> airtest run -h
usage: airtest run [-h] [--device [DEVICE]] [--log [LOG]]
                   [--recording [RECORDING]]
                   script

positional arguments:
  script                air path

optional arguments:
  -h, --help            show this help message and exit
  --device [DEVICE]     connect dev by uri string, e.g. Android:///
  --log [LOG]           set log dir, default to be script dir
  --recording [RECORDING]
                      record screen when running

**Comment by Meteorix** [comment]
As @SUDARSHANCHAUDHARI  suggested, you can run one script using airtest cli. Then start two CMD to run two scripts. Also you can use python subprocess to control multiple scripts.
