### ISSUE TITLE
使用Unity3D加入SDK后打包，adb无法连接到游戏

### ISSUE THREAD

**Issue by lucasLai** [AirtestProject/Airtest#122]
[描述]
使用Unity3D加入SDK（在camera增加pocomanger.cs）后打包，并无报错。打出包体使用IDE连接，但在poco选项中选择unity时，提示WinError 10053和10054。
[重现步骤]
1.接入SDK、打包
2.进入游戏，连接IDE
3.点击poco辅助下拉框，选择unity
4.观察cmd输出
[截图]
![default](https://user-images.githubusercontent.com/5735413/43637349-5911eece-9747-11e8-9513-aac704852944.png)
[其他]
设备：win7 64位
环境：自己安装了python3.6版本，加入了变量，后续有在软件内进行设置尝试
项目内：
项目内部署了NGUI和部分UGUI，删除UGUI处理；
项目内使用了Newtonsoft.Json.dll，后续删除项目Newtonsoft.Json.dll处理；

**Comment by lucasLai** [comment]
感觉很大程度上好像和软件自身没有关系……不过烦请看下

**Comment by adolli** [comment]
看下游戏的log里有没有异常的输出，有没有成功监听手机的5001端口

**Comment by lucasLai** [comment]
后续用了贵司的demo是没有问题的，应该是我本机设置问题，有劳，我再看看吧

**Comment by adolli** [comment]
如果还有遇到问题，可以继续在这个thread里描述一下。

**Comment by lucasLai** [comment]
好的，感谢
