### ISSUE TITLE
在Ubuntu 18.04 LTS上，v0.1.6版本起不来，直接崩溃报错，错误信息见

### ISSUE THREAD

**Issue by zhangxihao** [AirtestProject/Airtest#123]
![image](https://user-images.githubusercontent.com/22189731/43786310-edfb380a-9a9a-11e8-8d4b-83663bf7f15b.png)
复制不出来里面的具体错误信息，只能截图一个

**Comment by rockywhisper** [comment]
@zhangxihao 
您好，我们目前的AirtestIDE包暂时只提供了Ubuntu16.04版本，方便的话，还请直接使用Ubuntu16.04  :-)

这个issues暂时关闭了哈

**Comment by dadeshuo** [comment]
ubuntu 18好像qt报错
From this Qt bug report it looks like you can also just install the libglvnd-dev package on your system. I did this and can verify it fixes the issue on my Ubuntu 18.04 system when running with PyQt5.
我按照这个安装后可以在ubuntu18使用（但是不能在ide里输入中文）
