### ISSUE TITLE
Can somebody provide example of RECORDING and EXPORT agruments

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/Airtest#124]
Hello All,
I want to use RECORDING AND EXPORT arguments in my test execution.

Can anybody give me an example, how to use recording argument while running the script, I know how to use --device and --log but facing some problem with recording.

Same for the --export and --record for HTML report.

Let me know and thank you for the help.

link : http://airtest.readthedocs.io/en/latest/README_MORE.html#running-air-from-cli

![image](https://user-images.githubusercontent.com/25879455/43816570-9b860ce8-9aff-11e8-9578-c3f8163c54af.png)

**Comment by SUDARSHANCHAUDHARI** [comment]
Like how to save recorded MP4 file with custom name and path

**Comment by yimelia** [comment]
@SUDARSHANCHAUDHARI 
like this: `airtest run untitled.air --device Android:/// --log D:\log --record` 
you can find "recording_0.mp4" in D:\log\, recording_x.mp4 is the default name. if you have more than one device, that will be "recording_1.mp4"..."recording_n.mp4".

--export:  `airtest run untitled.air --device Android:/// --log D:\log --export D:\export`. and then you can copy the `D:\export\untitled.log` to anywhere.

**Comment by SUDARSHANCHAUDHARI** [comment]
Thank you very much for this information!!!

Also, we can not use the custom name for the video file, is that right?
