### ISSUE TITLE
脚本中使用了本地python安装的第三方库，提示找不到该库文件

### ISSUE THREAD

**Issue by wcp1234** [AirtestProject/Airtest#126]
如图设置了Add Python sys.path
![1](https://user-images.githubusercontent.com/40854525/43887274-da5fecf8-9bf0-11e8-8534-ca2b5efd7872.png)
email库在本地F:\Python27\Lib\site-packages路径下，脚本中正常引用如下：
from email.mime.text import MIMEText  
from email.mime.image import MIMEImage  
from email.mime.multipart import MIMEMultipart 
运行脚本提示：No module named text

**Comment by yimelia** [comment]
@wcp1234 请更新到官网最新版本，目前版本不需要填写python库文件夹位置，改为填写`python.exe`路径即可，详情请见 [使用本地Python环境运行脚本](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/6_settings/1_ide_settings.html#python)

**Comment by wcp1234** [comment]
@yimelia 使用0.1.5版本设置了python.exe路径，但执行脚本时提示F:\Python27\python.exe: No module named airtest。这个版本是不是不能直接解压缩使用呢

**Comment by wcp1234** [comment]
@yimelia 使用官网上的0.1.5版本，设置了本地安装的python.exe路径，运行脚本提示：No module named airtest。发现是本地安装的python中缺少airtest相关库文件，使用pip --default-timeout=100 install airtest ，提示：
Downloading/unpacking opencv-contrib-python==3.2.0.7 (from airtest)
  Could not find any downloads that satisfy the requirement opencv-contrib-pytho
n==3.2.0.7 (from airtest)
Cleaning up...
No distributions at all found for opencv-contrib-python==3.2.0.7 (from airtest)
Storing debug log for failure in C:\Users\yanghuijian\pip\pip.log
请问应该怎么解决呢

**Comment by wcp1234** [comment]
@yimelia 使用最新版本，填写python.exe路径，pip下载airtest和poco第三方库，可以正常使用了，感谢！
