### ISSUE TITLE
Getting Image not found when HTML report is generated from command line

### ISSUE THREAD

**Issue by rabbit0057** [AirtestProject/Airtest#129]
When I generate HTML report from command line.. In the report screenshot shows up as the image not found.
![screen shot 2018-08-10 at 2 52 20 pm](https://user-images.githubusercontent.com/5949627/43950168-373013ce-9cad-11e8-86bf-a6cc5294e40d.png)

And touch image resolution is too big.
![screen shot 2018-08-10 at 2 52 32 pm](https://user-images.githubusercontent.com/5949627/43950178-3fc79b88-9cad-11e8-9676-5d41c0eacb61.png)

Same code I ran in AirtestIDE -- Report is generated with the proper screenshot and touch image in the report.

How to solve this issue.

**Comment by rabbit0057** [comment]
Image from the report generated from AirtestIDE

<img width="1299" alt="screen shot 2018-08-10 at 3 31 27 pm" src="https://user-images.githubusercontent.com/5949627/43952139-a3c64152-9cb2-11e8-8fb7-c5cc8c7df357.png">

**Comment by rabbit0057** [comment]
Image from reported generated from AirtestIDE

<img width="1299" alt="screen shot 2018-08-10 at 3 31 27 pm" src="https://user-images.githubusercontent.com/5949627/43952240-f22e4c72-9cb2-11e8-8344-ddd68377b19f.png">

**Comment by zzldjkzxf** [comment]
@rabbit0057  I'm sorry for it. I want to know about your issue.  Your operation is on airtest or poco?  And can you show me your command which generate report.

**Comment by rabbit0057** [comment]
Operation = Airtest

- I use this command to run the script
python -m airtest run untitled.air --device Android:/// --log log

The test is running successfully with dumping screenshot.

Then I ran this command for report
python -m airtest report untitled.air --log_root log/ --outfile log/log.html

After this report was generated successfully with above issue

**Comment by Seeincup-Ming** [comment]
i was meeting the same question now. so ,how to deal with it.

**Comment by Seeincup-Ming** [comment]
@Meteorix

**Comment by yimelia** [comment]
@rabbit0057 @Seeincup-Ming sorry, it's a bug and it will be fixed soon. but now,  just use absolute path and try again~

**Comment by yimelia** [comment]
@rabbit0057 @Seeincup-Ming please update airtest and AirtestIDE, this bug has been fixed at latest version :)
