### ISSUE TITLE
connect_device() failing

### ISSUE THREAD

**Issue by ahsenqamar** [AirtestProject/Airtest#130]
Hi,

I am trying to run a simple connect_device() using a Galaxy S7 but seeing the following error:
```
airtest.core.error.AdbError: stdout[List of devices attached
adb server version (36) doesn't match this client (39); killing...
] stderr[error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
]
```
I tried running `adb kill-server` to make sure it was running from scratch but it still fails. 

Thanks in advance for the help!

**Comment by Meteorix** [comment]
you need to stop other applications running adb, like Android Studio

**Comment by ahsenqamar** [comment]
Hey,
I do not have any programs running. Also, wouldn't `adb kill-server` kill all applications running adb?

**Comment by adolli** [comment]
maybe as your system has already installed an older version of adb. please try upgrading to version `1.0.39` or simply uninstall the older one.

**Comment by ahsenqamar** [comment]
Sorry for the delay. Upgrading adb did not help. Uninstalling adb worked.
