### ISSUE TITLE
碰到一个诡异的识别问题

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Airtest#132]
我在1920x1080上用IDE截图及运行的case，然后换台1080x2160的手机去跑，发现脚本没有异常，但是运行一会就中断（用的是指令运行脚本，但是IDE运行时正常通过），没报任何错误。（同一分辨率运行也是没问题的）
我的代码也加入了
```python
def custom_resize_method(w, h, sch_resolution, src_resolution): 
    print(w, h, sch_resolution, src_resolution) 
    return int(w), int(h) 

ST.RESIZE_METHOD = custom_resize_method
```
你可以看一下我运行的结果报告
[对比报告.zip](https://github.com/AirtestProject/Airtest/files/2285234/default.zip)

**Comment by yimelia** [comment]
@lycfr 更新airtest与pocoui/hrpc到最新版本，再尝试运行看看？
