### ISSUE TITLE
点击运行后崩溃

### ISSUE THREAD

**Issue by aspeaky** [AirtestProject/Airtest#134]
今天想简单地使用一下，
![image](https://user-images.githubusercontent.com/37127771/44144127-e065d97e-a0b8-11e8-994f-16e0c59938b3.png)如图，但是一点击运行后程序崩溃。如下

![image](https://user-images.githubusercontent.com/37127771/44144038-9a54f79e-a0b8-11e8-946f-9580eb704bd7.png)

**Comment by yimelia** [comment]
@aspeaky 抱歉，这个是我们之前没测出来的一个BUG，将在下一个版本修复。可以重新新建一个脚本，换个路径再试试

**Comment by yimelia** [comment]
@aspeaky 抱歉，之前更新版本时漏了回复，该bug已经修复，我先关闭issue哈
