### ISSUE TITLE
可以支持 native 和 webview 的来回切换的测试场景吗？

### ISSUE THREAD

**Issue by lvfengwen** [AirtestProject/Airtest#135]
有的 Android 或者 iOS app 页面是由 native 和 webview  构成的，看了下官方文档，貌似没有支持像 appium  那种来回切换的方式，请问这个后续会有支持吗？或者暂时的解决办法是什么？

**Comment by adolli** [comment]
这个完全可以支持，通过实例化不同的poco instance来控制。你说的webview是哪里的webview？现在`AndroidUiautomationPoco`实例直接能读取标准webview的hierarchy。

**Comment by lvfengwen** [comment]
是 android 里面潜逃的 webview，我看官网貌似没有这方面的教程，只说了如何进行 web 测试，能否发个语句，或者链接我看下，感谢

**Comment by adolli** [comment]
只要该webview引擎是标准规范的（如基于chome内核），android里的webview就当做android原生控件来对待就好了。web测试是另一回事，跟这个无关。

目前并没有对android里的webview做特殊处理，后续可能会考虑使用webview sdk的方式。

**Comment by yimelia** [comment]
可以参考 [文档](http://airtest.netease.com/docs/cn/6_poco_framework/poco_webview.html)
