### ISSUE TITLE
1.0.2 在cli运行时，name ‘unichr’ is not defined

### ISSUE THREAD

**Issue by liangliangludan** [AirtestProject/Airtest#14]
![qq 20180321104018](https://user-images.githubusercontent.com/28750504/37692581-9a8814a4-2cf4-11e8-895b-97fe50a13697.png)

**Comment by kristynakitz** [comment]
what is the python version do you use?

**Comment by liangliangludan** [comment]
3.5.2

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/commit/dfc0c1aa170b048a2ccd93710adaaef71af65a1b 修复了py3下的这个bug

你可以先用源码来安装最新的版本
```
git clone https://github.com/AirtestProject/Airtest.git
pip install -e airtest
```

**Comment by Meteorix** [comment]
@liangliangludan 请确认下，没问题就close issue啦

**Comment by liangliangludan** [comment]
fiexed
