### ISSUE TITLE
图像识别到屏幕外的问题

### ISSUE THREAD

**Issue by lvkiess** [AirtestProject/Airtest#140]
![image](https://user-images.githubusercontent.com/40380950/44443299-aa7c7600-a609-11e8-9f37-5d6d777e066a.png)
![image](https://user-images.githubusercontent.com/40380950/44443308-b10aed80-a609-11e8-9258-9cfc91948adf.png)

如上图，把屏幕外的某块区域识别匹配了。
观察了该touch动作的参数，发现record_pos这个参数是负数，原来这个参数的原点是当前屏幕的中心点，但是图像识别时的坐标系又是以屏幕左上角为原点计算的，不知道是不是这个差别导致了sift识别时会选取到屏幕外边的点，望解答。

**Comment by lvkiess** [comment]
![image](https://user-images.githubusercontent.com/40380950/44515875-3370db80-a6f6-11e8-9066-6c3ae0cb1815.png)
![image](https://user-images.githubusercontent.com/40380950/44515893-41bef780-a6f6-11e8-9c34-2f300347e8a0.png)
再次遇到相似问题，但是并不是必现，有的时候却能正常识别，是否可以考虑在cvmatch时加入坐标大于0的机制呢

**Comment by rockywhisper** [comment]
@lvkiess  你好，这个问题在新版的airtest以及[AirtestIDE](http://airtest.netease.com/changelog.html)中都已经得到了修复。
