### ISSUE TITLE
python3.7环境搭建问题

### ISSUE THREAD

**Issue by webyabo** [AirtestProject/Airtest#141]
在python3.7环境下安装airtest，依赖opencv-contrib-python==3.2.0.7。
Could not find a version that satisfies the requirement opencv-contrib-python==3.2.0.7 (from versions: 3.4.2.16, 3.4.2.17)
No matching distribution found for opencv-contrib-python==3.2.0.7
但opencv-contrib-python==3.2.0.7，不支持python3.7，只支持py36及以下。请查看如下地址
https://pypi.org/project/opencv-contrib-python/3.2.0.7/#files
最新opencv-contrib-python 3.4.2.17 支持py37，建议更新依赖版本

**Comment by webyabo** [comment]
通过源码安装，已解决

**Comment by Meteorix** [comment]
@rockywhisper 可以验证下opencv的更新

**Comment by akbar4modn** [comment]
In English please

**Comment by rockywhisper** [comment]
@akbar4modn  Next version of Airtest will be OK for Python3.7, `opencv-contrib-python-3.2.0.7` doesn't support python3.7, and we'll change the dependency to 3.4.2.17 now.
