### ISSUE TITLE
Yosemite的Bug

### ISSUE THREAD

**Issue by sungtsai** [AirtestProject/Airtest#147]
很多APP搜索框没有按钮，当它获得焦点后，输入法会自动弹出，在输入关键词后直接点击输入法中的“搜索”键（一般在输入法的右下角）进行搜索，这样用户使用起来会更加的方便，但是使用键值66即回车键AirtestIDE运行结果却是换行，同样的测试在Appium中测试通过

**Comment by rockywhisper** [comment]
@sungtsai  
您好，目前部分没有搜索按钮的输入框，因为没有捕获adb-enter事件，会导致airtest的text输入无效。

目前可以利用底层ime_action强制完成输入：
``` python
text(“输入文字内容”)
device().adb.shell(["am", "broadcast", "-a", "ADB_EDITOR_CODE", "--ei", "code", "3"])
```

本周内即将放出的版本将在text中增加enter参数，届时可写为以下形式：
``` python
text("输入文字内容", search=True)
```

**Comment by Raphon** [comment]
> @sungtsai
> 您好，目前部分没有搜索按钮的输入框，可能因为搜索框自己的事件响应逻辑中没有捕获adb-enter事件，会导致airtest的text输入的搜索操作无效。
> 
> 目前可以利用底层ime_action强制完成输入：
> 
> ```python
> text(“输入文字内容”)
> device().adb.shell(["am", "broadcast", "-a", "ADB_EDITOR_CODE", "--ei", "code", "3"])
> ```
> 
> 本周内即将放出的版本将在text中增加enter参数，届时可写为以下形式：
> 
> ```python
> text("输入文字内容", search=True)
> ```

这个 
```
text("输入文字内容", search=True)
```
是不是还没支持 😭

**Comment by yimelia** [comment]
@Raphon 
关单了就是已经支持了，请更新到最新版本后试试，文档示例见[这里](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#id12)
