### ISSUE TITLE
脚本中android reboot之后重新连接，运行 touch等api报错 ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by cooldeaaap1** [AirtestProject/Airtest#149]
脚本中android reboot之后重新连接，运行 touch等api报错：

>  ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
 
![image](https://user-images.githubusercontent.com/26562987/44828320-f2268180-ac49-11e8-9b34-bfe570a41b64.png)
报错log:
> b'[11:34:47][INFO]<airtest.core.api> Try finding:\r\nTemplate(file:///E:/脚本/debugmenu.air/tpl1535598720546.png)\r\n'b'======================================================================\r\nERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File "airtest\\cli\\runner.py", line 66, in runTest\r\n  File "site-packages\\six.py", line 693, in reraise\r\n  File "airtest\\cli\\runner.py", line 62, in runTest\r\n  File "E:\\\xbd\xc5\xb1\xbe\\debugmenu.air\\debugmenu.py", line 16, in <module>\r\n    touch(Template(file:///E:/脚本/debugmenu.air/tpl1535598720546.png", record_pos=(-0.461, -0.171), resolution=(1920, 1080)))\r\n  File "airtest\\utils\\logwraper.py", line 72, in wrapper\r\n  File "airtest\\core\\api.py", line 256, in touch\r\n  File "airtest\\utils\\logwraper.py", line 72, in wrapper\r\n  File "airtest\\core\\cv.py", line 42, in loop_find\r\n  File "airtest\\core\\android\\android.py", line 206, in snapshot\r\n  File "airtest\\core\\android\\minicap.py", line 313, in get_frame_from_stream\r\n  File "airtest\\core\\android\\minicap.py", line 246, in _get_stream\r\n  File "airtest\\utils\\safesocket.py", line 30, in recv\r\nConnectionAbortedError: [WinError 10053] \xc4\xe3\xb5\xc4\xd6\xf7\xbb\xfa\xd6\xd0\xb5\xc4\xc8\xed\xbc\xfe\xd6\xd0\xd6\xb9\xc1\xcb\xd2\xbb\xb8\xf6\xd2\xd1\xbd\xa8\xc1\xa2\xb5\xc4\xc1\xac\xbd\xd3\xa1\xa3\r\n\r\n----------------------------------------------------------------------\r\nRan 1 test in 98.857s\r\n\r\nFAILED (errors=1)\r\n[11:34:47][DEBUG]<airtest.core.android.adb> D:\\airtest\\airtest\\core\\android\\static\\adb\\windows\\adb.exe -s 172.17.46.255:5555 forward --remove tcp:11191\r\n'[11:34:47][DEBUG]<airtest.core.android.adb> D:\airtest\airtest\core\android\static\adb\windows\adb.exe -s 172.17.46.255:5555 forward --remove tcp:15263
[Finished]
截图：
![image](https://user-images.githubusercontent.com/26562987/44828408-55b0af00-ac4a-11e8-9ba3-67db4067f983.png)

**Comment by yimelia** [comment]
重启手机后，可能需要重连一次才行

```
for i in range(3):
    #connect_device("Android://127.0.0.1:5037/9889db3057374c4544")
    auto_setup(__file__)
    adb = device().adb
    touch(Template(tpl1540349429429.png, record_pos=(-0.381, -0.475), resolution=(1440, 2960)))
    device().minicap.teardown_stream()
    device().minitouch.teardown()
    adb.kill_server()
    sleep(40)
    adb.start_server()
    sleep(5)
    device().minitouch.install_and_setup()
```
由于我本地环境有点问题，这个代码在运行到后期会报一个adb重连的错误，但是你可以尝试一下看看。
或者不需要写minicap和minitouch的断开与重连，直接connect_device也许也可以:

```

def test():
    adb = device().adb
    adb.kill_server()
    sleep(50)
    adb.start_server()
    sleep(5)
    connect_device("Android:///")
```

抱歉回复晚了，如果尝试后还有问题，请reopen这个issue
