### ISSUE TITLE
unity官方实例rollaball做测试发现的问题

### ISSUE THREAD

**Issue by drakedoglife** [AirtestProject/Airtest#15]
打开unity官方实例roll a ball，将unity3d sdk导入，挂载pocomanager于ground对象上，然后打apk包，安装至手机。打开airtest，选择unity，发现左侧poco辅助窗没有将原本所有的ui树遍历出来。比如，player对象，或是本能展开的节点也不能展开了。

**Comment by Meteorix** [comment]
@drakedoglife 你好，能贴一下你那边整个IDE的截图吗？我们也试试unity的例子

**Comment by drakedoglife** [comment]
![46bc5409-084e-4bab-b721-35b60a686510](https://user-images.githubusercontent.com/37531000/37749299-4f3f9854-2dc2-11e8-9041-e4af9f13271e.png)
![c98c7ccc-a551-400c-8498-a961013a3f86](https://user-images.githubusercontent.com/37531000/37749309-574898de-2dc2-11e8-9aaf-618d3a8d7ef6.png)

**Comment by Meteorix** [comment]
Thanks！我们这边看看

**Comment by adolli** [comment]
fixed at https://github.com/AirtestProject/Poco-SDK/commit/9cefa13840269d3b1a833b0e52c1d525174c080d
