### ISSUE TITLE
关于TargetNotFoundError错误的容错处理

### ISSUE THREAD

**Issue by wcp1234** [AirtestProject/Airtest#150]
如题，由于公司网络原因，用例执行过程中，很容易出现TargetNotFoundError错误（if语句判断也不可靠，很可能上一瞬间还存在的控件或图片，下一瞬间就找不到了），所以，有没有什么办法，在出现TargetNotFoundError错误时，不会自动终止用例执行，而进入指定的容错函数，或者是从头重新开始执行用例呢？

**Comment by yimelia** [comment]
Hi，建议可以自己封装一个自己专用的touch函数来处理这些异常逻辑哈~
