### ISSUE TITLE
在同一个.air导入多个.air,只执行了第一个导入.air

### ISSUE THREAD

**Issue by 305810827** [AirtestProject/Airtest#152]
![befe8c63-b783-4859-a61f-3618c6301399](https://user-images.githubusercontent.com/37141782/44988910-c8a98500-afbe-11e8-8f7e-04941a0855ca.png)
![c696635b-ca6a-4950-9c08-80fb11d7e0a4](https://user-images.githubusercontent.com/37141782/44988911-c8a98500-afbe-11e8-9455-b3d2f266aef9.png)

**Comment by yimelia** [comment]
应该是脚本的语法错误问题，跟airtest无关哈
