### ISSUE TITLE
同样的脚本，部署到jenkins怎么跑不起来

### ISSUE THREAD

**Issue by mkc-leslie** [AirtestProject/Airtest#154]
同样的脚本，部署到jenkins怎么跑不起来，有谁这样做过吗

**Comment by yimelia** [comment]
请提供更多具体的细节，否则帮不上忙

**Comment by yimelia** [comment]
部署一个python环境，安装好airtest和pocoui，然后再执行命令行，不太建议放到Jenkins上以后还用IDE来运行命令行。参考教程：[使用python运行脚本](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_run_script/run_script.html)

**Comment by mkc-leslie** [comment]
python、airtest和pocoui都已经安装过的，改成命令执行：
Windows Batch Script -- airtest run "C:\Program Files (x86)\Jenkins\workspace\Pipeline-Test\TestCases\OE_OrderingUI\UAT_CreateOrder.air" --device Android://127.0.0.1:5037/LGLS993e8fd7a23 -- (self time 595ms)
[Pipeline-Test] Running batch script

C:\Program Files (x86)\Jenkins\workspace\Pipeline-Test>airtest run "C:\Program Files (x86)\Jenkins\workspace\Pipeline-Test\TestCases\OE_OrderingUI\UAT_CreateOrder.air"  --device Android://127.0.0.1:5037/LGLS993e8fd7a23 
'airtest' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by yimelia** [comment]
python -m airtest run 试试
如果安装在虚拟环境，还需要使用虚拟环境里的python.exe

**Comment by mkc-leslie** [comment]
用python这个命令，提示python不是内部或外部命令，也不是可运行的程序
另外，jenkins环境是搭在我实体电脑上的

**Comment by yimelia** [comment]
写一个.bat脚本然后用jenkins的那个shell来跑就是了
