### ISSUE TITLE
操作UI的Click和Focus函数在调试Win下的Unity游戏会报错

### ISSUE THREAD

**Issue by zxc3246183** [AirtestProject/Airtest#155]
使用环境是Win平台，使用Poco调试Unity游戏
在我的游戏中，有一个按钮的锚点坐标是[0.5, 0]，在直接使用poco("xxx").click()的情况下，脚本会点击该UI元素上方的某一个位置而不会点击到UI检测区域内，为此我使用了click([0.5, 0.5])与focus([0.5, 0.5]).click()均会报一下错误提示：
![image](https://user-images.githubusercontent.com/12513067/45137968-52cf3480-b1dd-11e8-8247-afd768503178.png)

**Comment by adolli** [comment]
请麻烦在hierarchy面板中看下这个 `Area.1` 对应的`size`属性是否为一个2元数组？

**Comment by adolli** [comment]
https://github.com/AirtestProject/Poco/issues/79
