### ISSUE TITLE
yosemite输入法被自动切换

### ISSUE THREAD

**Issue by BigWay2018** [AirtestProject/Airtest#156]
设备输入法切换成yosemite之后，使用text方法，airtest点开输入框之后输入法又自动换成别的了

**Comment by yimelia** [comment]
@BigWay2018 麻烦提供一下手机型号、系统版本，以及当时使用text方法时的命令行窗口里的log，我们查一下问题

**Comment by yimelia** [comment]
如果是oppo和vivo系的手机，可以尝试在手机输入法设置中，将yosemite输入法设置为默认输入法后重新尝试。若还是不行，请reopen这个issue并提供对应的手机型号、系统版本等更多额外信息，方便我们查证问题，我先暂时关闭这个问题了哈
