### ISSUE TITLE
[cocos2dx-lua sdk 集成]刷不出控件树

### ISSUE THREAD

**Issue by Danieltdd** [AirtestProject/Airtest#158]
日志显示：
 [JAVA logInfo][GAME DEBUG] [LUA-print] [poco] server listens on tcp://*:15004
 [JAVA logInfo][GAME DEBUG] [LUA-print] [poco] new client accepted	127.0.0.1	nil

**Comment by Meteorix** [comment]
请使用issue template提供完整信息
