### ISSUE TITLE
命令行运行脚本出错

### ISSUE THREAD

**Issue by chorushe** [AirtestProject/Airtest#159]
命令行运行脚本有两种方式，一是安装airtest模块，用“airtest run ......”，二是用airtestide运行，“../airtestIDE runner .......”，用第二种方法基本没出现问题，但是第一种方法问题有点多：
1、安装新版本后airtest-scripy.py文件版本没有更新，导致airtest用不了，完全卸载删除文件后重装解决；
2、想多次运行，用bat文件复制多个命令如下：airtest run "D:\AirTest\AirTestScripts\2048test1.air" --device Android://127.0.0.1:5037/c25ada7d --log "D:\airtestworkspace\2048test16"，双击运行后，命令不起作用，里边的命令一直在刷，如下图：

![default](https://user-images.githubusercontent.com/4261896/45465681-d7273780-b748-11e8-8887-dec520e31b75.png)
3、重启电脑后，连上手机，adb devices连上手机后有设备！但是还是第二条的命令，出错，提示找不到设备，如下图：

![default](https://user-images.githubusercontent.com/4261896/45465785-50bf2580-b749-11e8-8943-fe54c4631ef0.png)

备注：以上出现的错误在同样情况下，用ide的命令行运行均没有问题，命令如下：
"D:\AirTest\AirtestIDE_2018-09-05\AirtestIDE" runner "D:\AirTest\AirTestScripts\2048test1.air" --device Android://127.0.0.1:5037/c25ada7d  --log "D:/airtestworkspace\2048test15"

烦请帮忙解决下~~

**Comment by yimelia** [comment]
@chorushe 看命令行好像没什么问题，似乎唯一的不同就是 --device Android://后面手机序列号不同，以及多一个斜杠，去掉斜杠看看？
是用了同一台手机么

**Comment by yimelia** [comment]
@chorushe 可以尝试下不要把命令行放在同一个bat里，而是一个bat只写一个命令行，用另外的bat来进行调度，同时检查下使用的命令行格式与设备号是否正确。如果还需要帮助，请reopen这个issue
