### ISSUE TITLE
请问新建用例的模版在哪儿修改呢

### ISSUE THREAD

**Issue by wcp1234** [AirtestProject/Airtest#162]
如题，点击新建用例，新创建的用例中都是如下固定的模版
![image](https://user-images.githubusercontent.com/40854525/45606859-423f7980-ba7b-11e8-936f-d1bdaafd6aed.png)
不满足日常需求，想修改这个模版，请问是在哪个文件里呢

**Comment by rockywhisper** [comment]
@wcp1234  Hi，你好。

对应的模板文件位置：
AirtestIDE\app\plugins\editor\template\base_template.py
![image](https://user-images.githubusercontent.com/8188879/45676470-5ca15200-bb64-11e8-81a3-8969264bcfb9.png)
可以直接在该文件中修改，改为你所需要的模板文件内容即可。

**Comment by wcp1234** [comment]
@rockywhisper 找到了，感谢！
