### ISSUE TITLE
使用脚本运行，模拟器的每步截屏操作为黑屏，手机正常

### ISSUE THREAD

**Issue by flewpos** [AirtestProject/Airtest#166]
目前只试了夜神模拟器，IDE运行截屏显示正常，脚本运行有截图，但全是黑屏，生成报告也是这样。

![image](https://user-images.githubusercontent.com/42636848/45864461-a4b2b580-bdac-11e8-80ae-d05420a10905.png)

**Comment by rockywhisper** [comment]
@flewpos  

Hi，如果你试用AirtestIDE连接模拟器时，是需要勾选“use javacap”的，运行时设备参数中也会自动附加对应的截图方式选择字符串，详情可以查看AirtestIDE在模拟器上运行脚本的log窗输出：
![image](https://user-images.githubusercontent.com/8188879/45864853-09badb00-bdae-11e8-923e-7f8143aebc66.png)

请尝试在运行脚本指令中修改你的设备参数，直接参考AirtestIDE运行时的设备参数，然后再次查看下运行报告的情况。

**Comment by flewpos** [comment]
@rockywhisper 

OK，解决了，感谢
