### ISSUE TITLE
在Pycharm的terminal下直接通过python test.py执行测试没问题，但是在cmd中执行python "e:\test.py"就会退出apk。

### ISSUE THREAD

**Issue by laihanhua** [AirtestProject/Airtest#168]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
在Pycharm的terminal下直接通过python test.py执行测试没问题，但是在cmd中执行python "e:\test.py"就会运行一段时间退出apk

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by Meteorix** [comment]
请按照issue模板贴上截图、log等信息，不然没法看出来问题

**Comment by adolli** [comment]
https://github.com/AirtestProject/Poco/issues/85
