### ISSUE TITLE
Win selenium in PyCharm

### ISSUE THREAD

**Issue by avto727** [AirtestProject/Airtest#169]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**
![2018-09-26 at 23-48-19](https://user-images.githubusercontent.com/28927018/46108457-cb2a8380-c1e6-11e8-8422-e07650f99cce.png)

**Comment by zzldjkzxf** [comment]
@avto727 I'm sorry for this issue, we have fixed it. We would release it asap.

**Comment by avto727** [comment]
Thank you. I'll wait for the update)

**Comment by zzldjkzxf** [comment]
@avto727  We have released new version,  you can check it.
