### ISSUE TITLE
Feature requested

### ISSUE THREAD

**Issue by YurieCo** [AirtestProject/Airtest#171]
Hi please add the following:
 - to see the CPU LOAD
 - Log cat

**Comment by Meteorix** [comment]
@YurieCo thanks for your advice.

CPU & Logcat can be done easily using `shell` API, like this:
```
shell("logcat")
```

Since airtest is designed to be an automation framework, it is better to implement these 2 features in your own script or as a separate lib.

**Comment by YurieCo** [comment]
@Meteorix 
Thanks a lot

**Comment by Meteorix** [comment]
You can either use poco or do it on your own. I think the `airtest engine` you mean does not handle xml. But you can write your python code to do anything.
