### ISSUE TITLE
Error is throwing during install the 'Airtest' module manually.

### ISSUE THREAD

**Issue by rvijai92** [AirtestProject/Airtest#173]
Version mismatching issue when trying to install the airtest manually.

Steps to reproduce:
1 Clone the Airtest repo.
2 go to the respective repo dir.
3 pip install -e airtest, Run this command in the cmd prompt.

Actual result: ** Could not find a version that satisfies the requirement opencv-contrib-python==3.2.0.7 (from airtest==1.0.22) (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18)
No matching distribution found for opencv-contrib-python==3.2.0.7 (from airtest==1.0.22)**

![image](https://user-images.githubusercontent.com/42532076/46285666-e0fac880-c599-11e8-8821-ba124bfbab6f.png)

**Comment by cptzheglov** [comment]
opencv-contrib-python 3.2.0.7 doesn't support python 3.7

source here:
https://pypi.org/project/opencv-contrib-python/3.2.0.7/#files

**Comment by Meteorix** [comment]
@rvijai92 please use python3.6 for now. python3.7 is not well supported yet.
