### ISSUE TITLE
Unable to see images on IDE while using custom path for images and getting the error while using absolute path for images

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/Airtest#174]
Remove any following parts if does not have details about

**Unable to see images on IDE while using custom path for images and getting the error while using absolute path for images**

I am facing two kinds of issue, Whenever I use custom path for images which I am going to use in a script.

I dont want to store all images in .air folder and i want to use one custom path. So that I can use same image for multiple scripts.

1) When I declared path for image library in script, for e.g.suppose C:/ABC/ABC path for image library, (in this folder I stored all the images)

I use the following format for WAIT or TOUCH action

for example:
 
image_path = C:/ABC/ABC

touch(Template(image_path+ "killapps_icon_homescreen.png", threshold=0.8, target_pos=5, rgb=True, record_pos=(-0.392, 0.531), resolution=(1440, 2560)))

This syntax works but then I can't see image on the airtestIDE screen

Also whenever I reopened this .air file in airtest IDE, the (") double quotation mark disappeared which present after *.png* text 

2) Another problem is I can't use absolute path for images.
like for following sample code -

touch(Template(absolute_path_of_image, threshold=0.8, target_pos=5, rgb=True, record_pos=(-0.392, 0.531), resolution=(1440, 2560)))

Is there anything wrong with above syntax?

Kindly check images for more information.

**Screenshots**
![i2](https://user-images.githubusercontent.com/25879455/46388013-0f8cb680-c6f4-11e8-9a01-726fcdb8dad7.PNG)
![i1](https://user-images.githubusercontent.com/25879455/46388014-0f8cb680-c6f4-11e8-88bf-e6c1574d28e2.PNG)

**python version:** `python2.7`

**airtest version:** `1.0.00`

**Comment by yimelia** [comment]
hi @SUDARSHANCHAUDHARI ,try this:
```
G.BASEDIR.append(image_path)
touch(Template(image_path+ "killapps_icon_homescreen.png", threshold=0.8, target_pos=5, rgb=True, record_pos=(-0.392, 0.531), resolution=(1440, 2560)))
```

**Comment by SUDARSHANCHAUDHARI** [comment]
Hello @yimelia , 
I tried the format and it is not working.

As I mentioned earlier in situation 1, the same thing happened with G.BASEDIR.append logic.
problem is whenever I reopened this .air file in airtest IDE, the (") double quotation mark disappeared which present after .png text (file name).


******************
before 
touch(Template(image_path+ "killapps_icon_homescreen.png", threshold=0.8, ......
******
after reopened the same file
touch(Template(image_path+ "killapps_icon_homescreen.png, threshold=0.8, ....
************
issue 
the (") double quotation mark disappeared
******************************

kindly check the ZIP file of video attachment

let me know if I did anything wrong

once again thank you for your help 

[issue_video.zip](https://github.com/AirtestProject/Airtest/files/2462934/issue_video.zip)

**Comment by yimelia** [comment]
@SUDARSHANCHAUDHARI sorry, it's a bug, which has been fixed it in v1.0.1, please [download](http://airtest.netease.com/changelog.html) and try again?

**Comment by SUDARSHANCHAUDHARI** [comment]
Hello @yimelia,
Thank you for the reply.
Yes issue has been fixed and now I can use the mentioned syntax

But can you tell me about images
I can't see image on the airtestIDE screen like when used default syntax.

How can I display the image also on Airtest IDE?

![image](https://user-images.githubusercontent.com/25879455/47057101-84c6b400-d1e9-11e8-8657-6547120225ba.png)


If you want I can create new issue for this and we can close this issue.
let me know
thank you

**Comment by yimelia** [comment]
hi @SUDARSHANCHAUDHARI , sorry, AirtestIDE use a fixed image name template (tpl\d+.png),  only the image which is matching the template and in the .air directory will be displayed.
