### ISSUE TITLE
Unable connect when are used an Android Device Emulator 

### ISSUE THREAD

**Issue by vitorc** [AirtestProject/Airtest#175]
**Describe the bug**

When I tried to connect an Android Device Emulator created at the Android Studio (AVD), Airtest's log show me this message:
Failed to execute ADB commands, please read [Docs](http://airtest.netease.com/docs/en/3_faq/android_connection.html)
But don't have any topics about AVD in the doc.
Sometimes the Ide crashed when tried to connect, but this is not usual.

**To Reproduce**
1. Go to 'Devices'
2. Click on 'refresh ADB'
3. Click on 'connect'
4. See the error on log 

**Expected behavior**
Connect on Device (Emulator or not) normally

**Screenshots**
![adb_airtestide](https://user-images.githubusercontent.com/19368300/46694323-d1efc800-cbe2-11e8-99fe-d03e0ea67dea.png)
![avd_capture](https://user-images.githubusercontent.com/19368300/46694325-d3b98b80-cbe2-11e8-9cb7-c98c146646a3.png)

**python version:** `python3.5`

**airtest version:** `V1.0.0(PREVIEW)`

**Smartphone (please complete the following information):**
 - Device: [Emulator Nexus 5]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by vitorc** [comment]
> ![image](https://user-images.githubusercontent.com/8390109/46787090-5c623400-cd69-11e8-8144-89b6256d167f.png)
> 
> have u tried this way? as emulators do not support Minicap module.

@adolli I tried right now, but Airtest show me the same error.

**Comment by yimelia** [comment]
@vitorc try this?
![image](https://user-images.githubusercontent.com/6896468/46853192-fb516380-ce2f-11e8-9972-f4ed0e293171.png)

**Comment by vitorc** [comment]
> @vitorc try this?
> ![image](https://user-images.githubusercontent.com/6896468/46853192-fb516380-ce2f-11e8-9972-f4ed0e293171.png)

Same error.

**Comment by rockywhisper** [comment]
@vitorc  
Hi, so sorry for this error. 
I tried `emulator connection` before, [here's the procedure.](http://airtest.netease.com/docs/cn/2_device_connection/3_emulator_connection.html#android-avd)
It's in Chinese, but I'm sure you can figure it out with the images in it..

And I'll have a try again tomorrow with the same emulator as yours, and tell you about the outcome. (It's late in China now.)

**Comment by rockywhisper** [comment]
@vitorc 
Hi, buddy. I've tried the Nuexus5 with Android8.1, seems fine.

Here's my operation:
![test-issues](https://user-images.githubusercontent.com/8188879/47057816-e3455f80-d1f4-11e8-9aa2-7bddf00181a7.gif)

If you still can't connect it, try [the latest version of AirtestIDE](http://airtest.netease.com/changelog.html#v1_0_1)      :-)

**Comment by rockywhisper** [comment]
@vitorc  Hi, I'll close this issue.
If you have further questions, please create a new one.      :-)
