### ISSUE TITLE
咨询一下关于日志导出html格式的问题

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/Airtest#177]
我现在导出的log.html在我本地可用，但是在别人机器上就不可用，图片样式均失效  
我查看了代码，应该是丢失了css js文件，于是我把Airtest/airtest/report 这个文件放在了输出日志的路径下，并且airtest report 的时候指定了参数--log_root "log/" --static_root "log/report/"  

这样就可以在别人的机器上查看正常样式的report了

所以请问这么操作蠢吗？感觉没什么别的办法了呀···

**Comment by yimelia** [comment]
如果需要将报告拷贝到另外一个目录，或者是打包发给别人查看，但是直接生成的报告是无法复制到别的目录下查看的。我们提供了一个导出模式，在刚才的report指令后面添加一个参数--export导出目录路径，即可将报告完整导出到一个文件夹中，方便查看。
这样：
`airtest report xxxxxxxxxxxx   --export D:\export`
