### ISSUE TITLE
Mac上讲AirtestIDE的custom python path指定为本地安装的python，无法执行用例

### ISSUE THREAD

**Issue by wcp1234** [AirtestProject/Airtest#178]
如题，由于要使用些python的第三方库，谷在IDE上设置custom python path为本地安装的python2.7，然后IDE上点击运行，提示无法执行，截图如下：
![image](https://user-images.githubusercontent.com/40854525/46852482-bc221300-ce2d-11e8-9d7b-c39d69285ed2.png)
在终端里使用命令行"airiest run xxx.air --device Android:///"的方式运行，提示bash: airtest: command not found

**Comment by yimelia** [comment]
需要附带更多的一点信息哈。你的本地python是否已经安装过airtest，如果要修改IDE使用的python为本地python，需要在本地Python环境中安装好airtest（以及pocoui，如果你用到了的话）

[参考文档](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python)

**Comment by yimelia** [comment]
顺便可以附带上你的IDE配置里，python.exe那一段的截图信息，方便我们定位问题

**Comment by wcp1234** [comment]
@yimelia IDE里的配置如下：
![image](https://user-images.githubusercontent.com/40854525/46853177-f42a5580-ce2f-11e8-9b02-cbe0649b9e12.png)
本地python安装了airtest和pocoui库的，可以成功import，如下：
![image](https://user-images.githubusercontent.com/40854525/46853263-28057b00-ce30-11e8-9ed3-7bccb59ac865.png)

**Comment by yimelia** [comment]
如果还是不行，请reopen这个issue哈

**Comment by wcp1234** [comment]
@yimelia 命令行里使用新的命令python -m airtest run xxx.air --device IOS:///已解决，感谢
