### ISSUE TITLE
snapshot会有两张只是文件名不一样的截图

### ISSUE THREAD

**Issue by magicedy** [AirtestProject/Airtest#180]
**描述问题bug**
snapshot会有两张只是文件名不一样的截图

**相关截图**
![image](https://user-images.githubusercontent.com/23083411/46925150-ffae9400-d05c-11e8-9253-9da28a4f9265.png)
![image](https://user-images.githubusercontent.com/23083411/46925158-09d09280-d05d-11e8-9951-85e311a13c5c.png)
![image](https://user-images.githubusercontent.com/23083411/46925165-0ccb8300-d05d-11e8-8991-f1445c76b177.png)

**预期效果**
snapshot预期只需要一张截图

**python 版本:** `python3.6`

**airtest 版本:** `1.0.23`

**Comment by yimelia** [comment]
收到，感谢反馈，我们查证一下

**Comment by yimelia** [comment]
该问题已修复，将在下一次airtest更新时放出，感谢反馈

**Comment by yimelia** [comment]
最新版本（1.0.24）的airtest已修复该问题，在截图时不会额外多保存一张截图了，并且也修复了windows应用截图会额外保存多余的tmp.png的问题
