### ISSUE TITLE
windows10环境下，使用IDE测试win10 桌面应用，cv报内存溢出

### ISSUE THREAD

**Issue by cooldeaaap1** [AirtestProject/Airtest#181]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
用例中包含 图像识别语句，循环执行几十上百次之后，会出现cv报内存问题。
被测为： win10 pc
执行环境： win10 
软件版本：1.0.1
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![5 v tb jc dshox jj g](https://user-images.githubusercontent.com/26562987/46933184-8d9e7500-d085-11e8-8d94-9d25f729372e.jpg)

**Comment by yimelia** [comment]
#182

**Comment by yimelia** [comment]
目前IDE已更新到最新版本，已经修复此问题，可以下载试用，airtest将随后更新
