### ISSUE TITLE
Airtest测试Windows应用出现Windows内存持续上涨，然后应用程序崩溃

### ISSUE THREAD

**Issue by RealMay** [AirtestProject/Airtest#182]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
Airtest测试Windows应用出现Windows内存持续上涨，然后应用程序崩溃

```
[（在这里粘贴traceback或其他报错信息）]
```

**相关截图**
![_20181016103605](https://user-images.githubusercontent.com/41311421/46989505-e7f41000-d12f-11e8-95e7-ad9ab74993b1.jpg)

![_20181016103752](https://user-images.githubusercontent.com/41311421/46989516-f04c4b00-d12f-11e8-810a-32a6afcb5355.jpg)

**复现步骤**
1. 应用之间两个按钮循环切换1000次
2. 观察windows任务管理器的内存情况
3. 内存开始40%，运行几十次之后涨到90%以上，然后崩溃。如上图

**预期效果**
预期：内存能够及时得到释放，不会出现崩溃的情况

**python 版本:** `python3.7.0`

**airtest 版本:** `1.0.0.RC`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: 
 - 系统: win10 64bit 
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by rockywhisper** [comment]
@RealMay   你好
是否可以提供下 脚本截图、连接的设备信息？ 我们本地确认一下  :-)

(ps: IDE的使用问题可以提到 [AirtestIDE-issues](https://github.com/AirtestProject/AirtestIDE/issues)里的哈)

**Comment by RealMay** [comment]
![_20181016143612](https://user-images.githubusercontent.com/41311421/46996948-dbcc7a80-d150-11e8-9339-0242fa309394.jpg)
![_20181016143615](https://user-images.githubusercontent.com/41311421/46996951-dcfda780-d150-11e8-8532-0a42ed8c28ff.jpg)

**Comment by RealMay** [comment]
![_20181016150912](https://user-images.githubusercontent.com/41311421/46998586-8cd51400-d155-11e8-96db-36e73113ad68.jpg)
@rockywhisper 贴上报错的信息

**Comment by yimelia** [comment]
@RealMay 感谢反馈，这是个IDE的BUG，已经修复了，将在下一次更新时提交此次修改。
目前暂时的解决方案是，当需要运行执行时间过长的脚本时，可以另行使用命令行来跑。非常抱歉这个BUG给大家带来的不便

**Comment by yimelia** [comment]
目前IDE已更新到最新版本，已经修复此问题，可以下载试用，airtest将随后更新
