### ISSUE TITLE
[Windows] RuntimeError: minitouch setup timeout

### ISSUE THREAD

**Issue by antarnis** [AirtestProject/Airtest#184]
I'm attempting to connect to Airtest IDE using the new Mi Pocophone F1. Here's my phone specs:
Model Number - POCOPHONE F1
Android version - 8.1.0 OPM1.171019.011

I am getting this error:
`Minitouch init failed, please select 'Use ADB touch' and try again`

I'm also seeing this in my console:
`<airtest.utils.nbsp> [minitouch_server]b'open: Permission denied'`

I tried to adhere to all instructions by trying to set only with "Use ADB touch" but it does not work - I'm still getting the same error. I cannot find sufficient information to solve this problem.

Previously, I had no problems connecting to my OnePlus 2. 

Is it possible for the Airtest not having support for Pocophone yet? 

Please let me know how can I work around this problem.

**Comment by rockywhisper** [comment]
@antarnis 
Mi PocoPhone is not released in China, so I can't have a test on it currently.
But I believe the OS system is MIUI, and we've met some problems of XiaoMi phones. There're some settings we should be careful in the developer options. Here is [the documentation](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id8)（Sorry this part is in Chinese, translation still ongoing）

You should check these settings on:
 - USB debug
 - allow install APK via USB
 - USB debug ( secure setting )

Please have a try.

**Comment by antarnis** [comment]
@rockywhisper 
Thank you for the fast reply!
I gave a quick try by enabling the USB debug (security setting) and I can interact with the screen on Airtest now. Not sure how the performance will be affected in the near future, but it is solved for now!

Thank you for helping!
