### ISSUE TITLE
Android录屏无法整合到测试报告中

### ISSUE THREAD

**Issue by saber-simon** [AirtestProject/Airtest#185]
测试脚本中通过Android().start_recording()和Android().stop_recording()录制视频，测试结束后视频会pull到PC端，但是在输出的测试报告中显示“暂无设备录屏信息”。请问我需要怎样做才能将视频整合到相应的测试报告中呢？是否有相应的方法或参数可以操作？

**Comment by yimelia** [comment]
拿到视频后，将视频重命名为 `设备号.mp4`，放置在log目录中，最后生成的报告里会自动加上这个视频。

或者在运行报告的命令行中，添加 `--recording` 参数，会有自动录屏
