### ISSUE TITLE
poco test result player怎么导入文件？

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/Airtest#188]
根据[https://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/poco-example/play_with_unittest_framework.html](url)这里描述，我看左侧文件是.owl，但是我只能导入我的文件夹，而且看不到代码，如图：
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/11660641/47211762-ec872580-d3c8-11e8-9275-967f3d9147ad.png">
求问到底咋玩儿呀？

**Comment by adolli** [comment]
这个本来就是只能打开文件夹的，含有`poco-result.log`的目录会被当做叶子节点，跟是否是`.owl`目录没有关系。使用poco test result player，请见[my-testflow](https://github.com/AirtestProject/my-testflow)
