### ISSUE TITLE
airtest断开连接：orientationWatcher has ended

### ISSUE THREAD

**Issue by silencesmile** [AirtestProject/Airtest#191]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
Python代码控制airtest时，中间使用adb命令可能导致airtest断开连接，当我使用多线程操作其他adb命令时，为什么同样也会断开连接，当断开连接后我重新创建爱airtest为什么还是不能继续使用

**描述问题bug**
Python代码控制airtest时，中间使用adb命令可能导致airtest断开连接，当我使用多线程操作其他adb命令时，为什么同样也会断开连接，当断开连接后我重新创建爱airtest为什么还是不能继续使用
```
[01:35:48][INFO]<airtest.core.api> Try finding:
zzz ./newGameICO1.1/home/home_level.png
Template(./newGameICO1.1/home/home_mouse.png)
[01:35:48][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
点击图片失败： ./newGameICO1.1/home/home_mouse.png
zzz ./newGameICO1.1/home/home_mouse.png
```

**相关截图**
![image](https://user-images.githubusercontent.com/11863270/47338226-9e746980-d6c9-11e8-8185-d53ca7ee6897.png)

**复现步骤**
# #点击某个图片，Airtest中基于图像识别语法，图片自己提供。
for img in imgs:
    airtest.touch_img(img)
    print('zzz', img)

    # # 开启多线程进行截图
    screen_path = './phoneIMG/' + img[20: -3] + 'PNG'
    thread = threading.Thread(target=getScreen, args=(screen_path,))
    thread.start()

**预期效果**
多线程(代码时通过adb截取手机屏幕)不影响airtest的继续运行

**python 版本:** `python3.5`
python3.6.5

**airtest 版本:** `1.0.69`
airtest：1.0.23

**设备:**
 - 型号: 红米note3
 - 系统: Android5.1.1

**Comment by yimelia** [comment]
不要在运行airtest脚本的同时运行ADB指令……会相互抢占导致ADB不断重启的

**Comment by silencesmile** [comment]
我再重新创建airtest，再抢占回来也不行吗

**Comment by yimelia** [comment]
目前暂时最好不要这么做，或者等待下一次airtest的版本更新ADB之后，统一你的本地adb环境之后可能可以解决

**Comment by silencesmile** [comment]
我需要在运行airtest步骤的中间去执行其他的adb命令，然后在回来接着执行airtest，现在有办法解决吗 ？

**Comment by yimelia** [comment]
可以用airtest里封装的adb来尝试执行，参考[文档](http://airtest.netease.com/docs/cn/1_quick_start/2_test_with_Android_device.html#adb)

**Comment by wcp1234** [comment]
@silencesmile 我也遇到相同的问题了，也是执行airtest过程中另外调用adb来截图出现的，请问你用airtest里封装的adb来解决这个问题了吗？

**Comment by silencesmile** [comment]
没有




| |
henan_youngstar
|
|
henan_youngstar@163.com
|
签名由网易邮箱大师定制


在2018年10月24日 09:46，wcp1234<notifications@github.com> 写道：

@silencesmile 我也遇到相同的问题了，也是执行airtest过程中另外调用adb来截图出现的，请问你用airtest里封装的adb来解决这个问题了吗？

**Comment by yimelia** [comment]
我给个代码范例吧，类似这样

```
def init_adb(serialno=None, adbhost=None):
    from airtest.core.android.adb import ADB
    if not serialno:
        serialno = ADB().devices(state="device")[0][0]
    adb = ADB(serialno, server_addr=adbhost)
    adb.wait_for_device()
    return adb

class Test(object):
    def __init__(self, adb):
        self.adb = adb
    
    def get_data(self):
        # 可以自行封装多线程来获取数据，这里只是个例子
        data = self.adb.shell("ls")
        return data
```

**Comment by yimelia** [comment]
像示例里那样，在收集数据时使用airtest中的adb，或者等下个版本更新后，将本地adb和airtest中使用的adb统一成同一个版本（目录位置`airtest\airtest\core\android\static\adb\windows`）即可。

**Comment by wcp1234** [comment]
@yimelia 
你好，我平时都是用命令行在跑命令，我看AirtestIDE 1.1.0版本上的adb版本已经更新到40，请问使用pip安装的airtest、pocoui库里的adb有同步更新吗？同步更新下本地的adb版本是否可以解决用例过程中另起线程执行adb命令的资源抢占问题了呢？

**Comment by yimelia** [comment]
@wcp1234 有同步更新，执行`pip install -U airtest` 即可更新到最新，同时需要注意替换掉本地所有的adb.exe，统一成同一个版本（哪怕不是最新的40也可以，只要是同一个版本）

**Comment by wcp1234** [comment]
明白了，谢谢 @yimelia
