### ISSUE TITLE
windows下使用start_app()无法启动程序

### ISSUE THREAD

**Issue by huaisha1224** [AirtestProject/Airtest#193]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
1、windows下测试程序的时候需要先绑定窗口句柄
2、绑定窗口句柄的时候需要先启动程序、才能获取到句柄
3、所以我使用start_app("C:\\Program Files\\Mozilla Firefox\\firefox.exe") 这样来启动程序
4、但是报错了
错误如下：
```
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "d:\Python_code\code\2018\Airtest\端游盒子.air\端游盒子.py", line 15, in <module>
    start_app("C:\\Program Files\\Mozilla Firefox\\firefox.exe")
  File "D:\Python3\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Python3\lib\site-packages\airtest\core\api.py", line 146, in start_app
    G.DEVICE.start_app(package, activity)
AttributeError: 'NoneType' object has no attribute 'start_app'
```
```
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "d:\Python_code\code\2018\Airtest\端游盒子.air\端游盒子.py", line 15, in <module>
    start_app("C:\\Program Files\\Mozilla Firefox\\firefox.exe")
  File "D:\Python3\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Python3\lib\site-packages\airtest\core\api.py", line 146, in start_app
    G.DEVICE.start_app(package, activity)
AttributeError: 'NoneType' object has no attribute 'start_app'
```

**设备:**
 - 系统: [Win10_64]

**Comment by rockywhisper** [comment]
@huaisha1224 你好，请问脚本是使用命令行运行的？还是在IDE里面运行的？

start_app是需要指定连接设备的，[详见文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#)。
![image](https://user-images.githubusercontent.com/8188879/47833602-ad989d00-ddd6-11e8-93ac-185e2c4b1901.png)

**Comment by huaisha1224** [comment]
start_app是需要指定连接设备的
这个就是问题所在了
1、我是测试windows程序、在连接窗口之前 是不是得先启动程序
2、但是启动程序的时候又需要先绑定窗口

**Comment by geonsme** [comment]
start_app不是写路径，是按照pywinauto的connect写

**Comment by rockywhisper** [comment]
@huaisha1224  
可以先使用桌面模式运行脚本：`window:///`，脚本内`start_app`之后再connect启动后的窗口。

**Comment by huaisha1224** [comment]
@rockywhisper 我单独用win32 来启动程序了
不过你这个办法也是一个解决方案哦、之前没想到
