### ISSUE TITLE
通过for循环多个.air文件来调用report.py来生成报告，会提示数据流未关闭

### ISSUE THREAD

**Issue by oyebino** [AirtestProject/Airtest#197]
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues

**描述问题bug**

通过fo循环历遍所.air,来调用AirtestProject框架的report.py生成报告，在控制台提示数据流未关闭，但没有提示报错。
```

```
![image](https://user-images.githubusercontent.com/27769968/48046912-1914ad00-e1d1-11e8-8ef9-0c9adaf5b76d.png)

**复现步骤**
1.for case_path in all_case:
2. argv = ["report", case_path, "--log_root", log_case_path, "--outfile", html_case_path_log]
3. main_parser(argv)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.23`
![image](https://user-images.githubusercontent.com/27769968/48047171-2da57500-e1d2-11e8-9ee8-6dd474c2e348.png)

**Comment by yimelia** [comment]
感谢反馈，本问题已修复，将在下一个版本放出

**Comment by geonsme** [comment]
你可以实现主动关闭。
`
            from poco.utils.simplerpc.transport.tcp.asynctcp import LOOP_THREAD
            LOOP_THREAD.kill()
            LOOP_THREAD.join(1.0)
`
