### ISSUE TITLE
This doc page is not useful

### ISSUE THREAD

**Issue by Whiteseeker** [AirtestProject/Airtest#2]
This link:

http://airtest.netease.com/docs/docs_AirtestIDE-en_US/2_references_and_glossary/airtest_reference.html 

shows:
![screen shot 2018-03-06 at 4 30 14 pm](https://user-images.githubusercontent.com/4581097/37044692-0be19df4-215c-11e8-888e-10e156a13d7e.png)

It would be better to have a list on link that redirect to the various part of the airtest doc or some intro text

**Comment by Meteorix** [comment]
@Whiteseeker   Hi, it is already fixed. And the docs will be continuously improved.
