### ISSUE TITLE
请问，什么时候Poco-sdk能有cocos2dx-lua的版本

### ISSUE THREAD

**Issue by dwyb2000** [AirtestProject/Airtest#20]

**Comment by adolli** [comment]
好了之后通知你。 @Meteorix please assign this issue to me.

**Comment by dwyb2000** [comment]
谢谢，期待中

**Comment by adolli** [comment]
@dwyb2000 see [here](http://poco.readthedocs.io/en/latest/source/doc/integration.html#cocos2dx-lua) for cocos2dx-lua poco-sdk integration . Any issues please let us know.
