### ISSUE TITLE
测试windows应用时，当鼠标移动后，要点击的元素就消失了，这种情况如何使用touch主动截图方式来编写脚本？

### ISSUE THREAD

**Issue by newlife099** [AirtestProject/Airtest#200]
请问下，测试windows应用时（一款聊天办公软件），鼠标右键后，页面出现菜单选项，而当鼠标移动时，菜单就消失了。请问出现这种情况，如何使用touch主动截图方式，来截取点击菜单上的按钮。试过自动录制的方式，但是录制出来的脚本会有问题，元素无法识别到，或点击到屏幕的其他位置了。
![20181107110820](https://user-images.githubusercontent.com/30133926/48113994-41b3aa00-e298-11e8-926c-9c4b9de684da.png)

**Comment by adolli** [comment]
这种估计得手动截图保存然后写进脚本里了

**Comment by newlife099** [comment]
> 这种估计得手动截图保存然后写进脚本里了

试过这种也不行，定位不到

**Comment by geonsme** [comment]
用截图工具截图，然后按照格式补充进脚本就行了

**Comment by yimelia** [comment]
可以先用IDE在相同位置截取一张差不多的图片，此时会自动帮你生成对应的语句，能在脚本.air目录下找到同名.py文件里看到该行语句，类似`Template("xx.png", , record_pos=xx, resolution=(1080, 1920))` 这样。自动生成的语句中已经包含了点击位置信息，以及屏幕分辨率信息，此时只需自己手工截一张类似的图片，替换掉IDE截取的即可，最好把名字也改为同样格式的tpl1234.png，方便IDE显示图片。

**Comment by adolli** [comment]
要不我们也加一个快捷键来触发touch的截图吧 @yimelia
