### ISSUE TITLE
在华为8.0设备上，device.get_top_activity返回结果是错误的，永远是系统的activity

### ISSUE THREAD

**Issue by johnnychan86** [AirtestProject/Airtest#201]
**描述问题bug**
华为8.0设备，通过device.get_top_activity获得的结果是错误的，无论当前是什么app在前台，一律返回系统activity act .recents.RecentsActivity
```

```

**相关截图**

**复现步骤**
1. 第三方app在前台时，使用get_top_activity接口获得当前activity
2. 返回系统act，activity act .recents.RecentsActivity

**预期效果**
返回正确的activity
原因是使用命令dumpsys activity top 时，返回多组activity数据，其中既包含系统ui activity，也包含第三方activity，应该过滤系统activity，只返回第三方activity

**python 版本:** `python2.7`

**airtest 版本:** `1.0.24`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: 华为麦芒6
 - 系统: Android 8.0
 - (别的信息)

**其他相关环境信息**

**Comment by yimelia** [comment]
感谢反馈，将在下个版本放出时修复此问题
