### ISSUE TITLE
设备下方的Home、Back键被遮住

### ISSUE THREAD

**Issue by zzldjkzxf** [AirtestProject/Airtest#204]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
连接多台机器时，可能会出现设备下面按钮被遮住

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1.  连接一台设备
2.  不要断开，再次连接另一台分辨率不同的其他设备
3.  按钮被隐藏

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by rockywhisper** [comment]
@Jimmy36506   你好，问题已经查清，下个版本将会修复。    :-)
