### ISSUE TITLE
Can't run test from terminal (and other problems)

### ISSUE THREAD

**Issue by krauklismarina** [AirtestProject/Airtest#205]
It says "command not found", when i run "airtest run -h"

**Comment by yimelia** [comment]
try `python -m airtest run` ?

**Comment by krauklismarina** [comment]
![2d19d0f736463db118e64fc53f724b59](https://user-images.githubusercontent.com/6553050/48550989-34746c00-e8e5-11e8-8717-93d7019f49d4.jpg)

**Comment by yimelia** [comment]
`pip install -U airtest` first?

**Comment by krauklismarina** [comment]
Thanks, it worked. But now im having next issue. 
![4a8412973cf1d8eb8941aec979dc70b5](https://user-images.githubusercontent.com/6553050/48613296-6399e480-e99c-11e8-9259-c2411e442f08.jpg)

**Comment by krauklismarina** [comment]
pip install pocoui helped.

Now, i wanna run my scenario with parameters sent from cli, can i do that, and how?

**Comment by yimelia** [comment]
see [run test case](https://airtest.readthedocs.io/en/latest/README_MORE.html#run-test-case) and [generate html report](https://airtest.readthedocs.io/en/latest/README_MORE.html#generate-html-report)

here is example:
```
airtest run untitled.air --device Android:///serialno --log log/
airtest report untitled.air --log_root log/ --outfile log/log.html 
```

**Comment by krauklismarina** [comment]
Thank you for answer! I managed to run test from cli, but i need to pass a parameter, as so:
airtest run untitled.air/untitled.py %param% --device Android:///serialno --log log/

Can i do that? I run my test in bash script, so i want to pass some data from this script to my test.

**Comment by yimelia** [comment]
Airtest do not support passing custom parameters yet, but you could use [airtest launcher](http://airtest.netease.com/docs/en/1_online_help/advanced_features.html#airtest-launcher) to do the same thing.

```
from airtest.cli.runner import AirtestCase, run_script
from airtest.cli.parser import runner_parser

class CustomAirtestCase(AirtestCase):

    def setUp(self):
        super(CustomAirtestCase, self).setUp()

    def tearDown(self):
        super(CustomAirtestCase, self).setUp()

if __name__ == '__main__':
    ap = runner_parser()
    # add new parameter
    ap.add_argument("--filepath", help="filepath")
    args = ap.parse_args()
    run_script(args, CustomAirtestCase)
```

and run it:
```
python custom_launcher.py test.air --device Android:///serial_num --log log_path --filepath testfile
```

**Comment by krauklismarina** [comment]
Thank you very much!

**Comment by Raphon** [comment]
> testfile

请问这样传入参数以后 怎么在*.air里取得这个参数 直接拿filepath好像拿不到

**Comment by yimelia** [comment]
@Raphon 
从args里取

**Comment by Raphon** [comment]
> testfile

请问这样传入参数以后 怎么在*.air里取得这个参数 直接拿filepath好像拿不到

> @Raphon
> 从args里取

拿到啦 多谢
