### ISSUE TITLE
Airtest IDE和使用snapshot()截图均为黑屏状态

### ISSUE THREAD

**Issue by Kevinchenzero** [AirtestProject/Airtest#208]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.
1、使用"python ../游戏名.air"执行脚本时，snapshot()截图操作后，发现截图为黑屏
2、此时使用Airtest IDE打开手机，也是黑屏状态...
3、重启手机后，恢复正常，但是差不多1天时间，又黑屏。

请问:这个有没有好的解决方式，或者有没有排查问题的方式？？
```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by Kevinchenzero** [comment]
手机是mate 10

**Comment by Kevinchenzero** [comment]
> 手机是华为mate 10

**Comment by yimelia** [comment]
在执行snapshot操作之前， 有没有正常执行那种touch类型的语句？

**Comment by Kevinchenzero** [comment]
> 在执行snapshot操作之前， 有没有正常执行那种touch类型的语句？

看样子应该是没有的，因为识别的图片都是黑屏的。

**Comment by yimelia** [comment]
本地安装的airtest版本号是多少？试一下更新到最新看看

**Comment by Kevinchenzero** [comment]
> 本地安装的airtest版本号是多少？试一下更新到最新看看

是3月16号的版本，那我更新一下试试吧。

**Comment by yimelia** [comment]
试一下如果用javacap模式看看会不会好一些，命令行的话需要在--device 的Android:///字符串后面加上 `cap_method=JAVACAP`，比如：
`Android://127.0.0.1:5037/127.0.0.1:7555?cap_method=JAVACAP`

**Comment by Kevinchenzero** [comment]
> 试一下如果用javacap模式看看会不会好一些，命令行的话需要在--device 的Android:///字符串后面加上 `cap_method=JAVACAP`，比如：
> `Android://127.0.0.1:5037/127.0.0.1:7555?cap_method=JAVACAP

我使用了connect_device()后面加上cap_method=JAVACAP也行对吧。
这个我试过了，截图还是黑屏状态。。

**Comment by Kevinchenzero** [comment]
> 试一下如果用javacap模式看看会不会好一些，命令行的话需要在--device 的Android:///字符串后面加上 `cap_method=JAVACAP`，比如：
> `Android://127.0.0.1:5037/127.0.0.1:7555?cap_method=JAVACAP`

我通过调整手机屏幕分辨率，就能恢复。
这个跟分辨率有关系么？

**Comment by yimelia** [comment]
@Kevinchenzero hi,，可以发一下设置手机分辨率界面的截图上来我们参考一下试试
