### ISSUE TITLE
firebase打包apk，安装以后，输入指令，停留在apk的loading界面，脚本运行失败

### ISSUE THREAD

**Issue by Princebin** [AirtestProject/Airtest#209]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
firebase打包apk，生成一个网易游戏的apk，安装以后，输入指令，停留在apk的loading界面，脚本运行失败
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1. firebase 打包
2. 安装apk
3. cmd 输入adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner
4. See error：Traceback (most recent call last):
  File "copy_app\main.py", line 81, in test
  File "/data/data/com.netease.open.airbase/files/app/ClearConfiguration.air/ClearConfiguration.py", line 7, in <module>
    touch(Template(r"tpl1543297469660.png", record_pos=(0.133, 0.251), resolution=(1080.0, 2244.0)))
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 256, in touch
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\cv.py", line 60, in loop_find
TargetNotFoundError: 'Picture Template(tpl1543297469660.png) not found in screen'
界面停留在打包生成的apkloading

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 9]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by rockywhisper** [comment]
@Princebin  应该是脚本逻辑问题，比如loading时间过长，脚本中要找的图片一直没有出现导致的？

**Comment by rockywhisper** [comment]
@Princebin   
你好，这里问题描述过少，无法判定问题的具体情况。目前推断为脚本逻辑导致的测试不通过。

如有更多问题可以新开issues，或者到我们的官方QQ技术交流群中提出。
![image](https://user-images.githubusercontent.com/8188879/50430642-16485580-0900-11e9-8d28-9fb8a6e6e2e9.png)

本issues暂时关闭了哈。
