### ISSUE TITLE
如何实现长按并拖动

### ISSUE THREAD

**Issue by NateRiverNaz** [AirtestProject/Airtest#21]
查看了api，发现只有swipe 和 pinch

是否可以实现swipe_press

**Comment by adolli** [comment]
目前还没有这种组合，下一个大版本会加上`MotionEvent`. 到时就可以自定义手势了

**Comment by NateRiverNaz** [comment]
好的 谢谢！

**Comment by Meteorix** [comment]
@NateRiverNaz 你好，目前版本已经提供了MotionEvent，可以自己拼装任意操作

https://github.com/AirtestProject/Airtest/blob/master/playground/android_motionevents.py

**Comment by sosocgx** [comment]
@Meteorix 
你好， 根据您的写了例子改了一下，变成简单的按住并拖拽指定位置的图标到指定位置的实验
from airtest.core.api import *
from airtest.core.android.minitouch import *
connect_device("Android:///")
swipe_event = [DownEvent((500, 500)), SleepEvent(1),MoveEvent((0, 0)),UpEvent(0)]
device().minitouch.perform(swipe_event)

我的问题是：
1.具体DownEvent, SleepEvent,MoveEvent 的相关API文档，我想要实现比如传入name,TextMatches 之类的.
2.哪些event可以组合成motionevent?
2.完成图标的按住并拖拽后，手机坐标还是处于图标位置调整的状态，需要按home键。这种需要触发系统事件的，应该怎么调用？

thanks in advanced!!

**Comment by adolli** [comment]
如果使用poco的话，可以用以下简单写法，实现将一个图标拖拽到另一个图标上面
```python
telephone = poco(text='电话')
folder = poco(text='文件夹')
telephone.start_gesture().hold(1).to(folder).hold(1).up()  # 最后面的up别忘了，hold时长根据实际情况调节
```

**Comment by IcyW** [comment]
@Meteorix 
同请问长按并拖动至指定位置的操作。
请问MotionEvent的文档写了吗~？

**Comment by yimelia** [comment]
@IcyW 
可以参考这个文档以及仓库里的playground里的相关代码：
http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#id15
