### ISSUE TITLE
配置使用本地py2.7环境，执行脚本报错

### ISSUE THREAD

**Issue by beckham2018** [AirtestProject/Airtest#212]
![image](https://user-images.githubusercontent.com/45450023/49206346-bfc52580-f3ec-11e8-8a08-075fc2cbaf81.png)

```
File "F:\AirtestIDE\AirtestIDE_2018-11-06_py3_win64\sample\custom_launcher.py", line 6, in <module>
    from airtest.cli.runner import run_script
  File "C:\Python27\lib\site-packages\airtest\cli\runner.py", line 105
    exec(compile(code.encode("utf8"), pyfilepath, 'exec'), cls.scope)
SyntaxError: unqualified exec is not allowed in function 'exec_other_script' it contains a nested function with free variables
```

**Comment by Meteorix** [comment]
@beckham2018 贴一下你的脚本呢？请不要删掉issue template，方便我们定位问题

**Comment by yimelia** [comment]
@beckham2018 我们需要更多信息才能定位问题（custom_launcher.py是否修改过，以及你的脚本内容，启动时的命令行，本地的python环境中的airtest版本号），请提供更多信息后reopen这个issue，我先暂时关闭了

**Comment by WangXueqiong** [comment]
> @beckham2018 我们需要更多信息才能定位问题（custom_launcher.py是否修改过，以及你的脚本内容，启动时的命令行，本地的python环境中的airtest版本号），请提供更多信息后reopen这个issue，我先暂时关闭了

你好，我也碰到了这个问题，可以跟进解决一下吗，同样的脚本在window7，pyhton3.6运行没问题，在linux，python2.7运行报这个错
![image](https://user-images.githubusercontent.com/34360520/54122616-8151f480-4438-11e9-9cfa-7bbac8a62259.png)

**Comment by yimelia** [comment]
hi @WangXueqiong 
帮忙看一下`pip list`里面airtest的版本号是多少？

**Comment by WangXueqiong** [comment]
@yimelia 你好，pip list里面airtest的版本是1.0.26
![image](https://user-images.githubusercontent.com/34360520/54167709-01627380-44a6-11e9-96ad-ed740f89b2d6.png)

**Comment by yimelia** [comment]
@WangXueqiong 把脚本内容也贴出来方便我们复现一下？

**Comment by WangXueqiong** [comment]
@yimelia 
![image](https://user-images.githubusercontent.com/34360520/54170588-44c2df00-44b2-11e9-8b3a-8ba2881ac532.png)


`# -*- encoding=utf8 -*-
__author__ = "wangxueiqong"

from airtest.core.api import *

auto_setup(__file__)

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)


stop_app('com.tianyancha.skyeye')
clear_app('com.tianyancha.skyeye')
sleep(2)

start_app('com.tianyancha.skyeye')
sleep(3)`

**Comment by S-Cheney** [comment]
python安装目录下，找到报错的依赖文件，我的是：C:\Python27\Lib\site-packages\airtest\cli下的runner.py。注释掉报错的第105行即可
![image](https://user-images.githubusercontent.com/10508730/54966641-e74d8880-4faf-11e9-8776-959c3c799514.png)

**Comment by yimelia** [comment]
这个问题应该是python版本低于`2.7.9`的时候可能出现的问题，由于python2已经停止维护，因此我倾向于不再对过低版本的python2进行额外的兼容，以及该方法已经是一个废弃方法，所以暂时先不做处理。
如果出现该报错，可以考虑升级python版本号到大于2.7.9版本，或者是将这个报错的方法代码直接删除即可。
