### ISSUE TITLE
使用poco时，如果断言一个元素是否存在呢？

### ISSUE THREAD

**Issue by newlife099** [AirtestProject/Airtest#217]
请问使用poco时，assert_exists(poco("com.lkk.tyj.ep:id/tv_textMatch"), "请填写测试点")，我这样写断言时，但是报错了，提示"AttributeError: 'UIObjectProxy' object has no attribute 'match_in'"。那应该要如何写呢？

![image](https://user-images.githubusercontent.com/30133926/49502370-ec2ae700-f8af-11e8-8b53-2e0aec9a3890.png)

**Comment by Meteorix** [comment]
```
poco("xxxx").exists()
```

可以参考 [poco文档](https://poco.readthedocs.io/en/latest/source/poco.proxy.html#poco.proxy.UIObjectProxy.exists)

**Comment by newlife099** [comment]
你这个不是断言哦

**Comment by newlife099** [comment]
这样是可以，但是用这种断言，在测试报告中，看不到详细的信息。而使用屏幕截图方式时，断言元素是否存在方法，生成的报告很详细。参照如下图
![image](https://user-images.githubusercontent.com/30133926/49569745-bfd69f80-f96f-11e8-988e-4a85d553d1ef.png)

**Comment by Meteorix** [comment]
多谢反馈，我们考虑下优化这里

**Comment by wyduhd** [comment]
poco断言的方式，优化了吗？
