### ISSUE TITLE
text中不允许输入括号吗

### ISSUE THREAD

**Issue by hyhmm** [AirtestProject/Airtest#22]
text("test(3")   报错  File "site-packages\pywinauto\keyboard.py", line 557, in parse_keys
KeySequenceError: `)` not found
text("test(3)") 没报错 但是输入的是test3  自动把括号去掉了

**Comment by Meteorix** [comment]
@hyhmm 抱歉，这个issue拖的有点久，windows底层是pywinauto实现的，可以通过转义来输入括号。
参考pywinauto的文档：https://pywinauto.readthedocs.io/en/latest/code/pywinauto.keyboard.html

我试了下，你的这个情况可以这么输入：
```
text("test+93+0")     # 即输入"test(3)" 
```
