### ISSUE TITLE
Capture device statistics

### ISSUE THREAD

**Issue by buihuuloc** [AirtestProject/Airtest#221]
Hi there!

How could I capture the device statistics(CPU, Ram, LogCat) and export these things along with report?

**Comment by yimelia** [comment]
hi @buihuuloc 
you could use some adb command to get the info, like:
```
shell("dumpsys battery")
```
or use thread to collect data, [code example](https://github.com/AirtestProject/Airtest/issues/191#issuecomment-432487390).

Our report does not currently support displaying these data.

If you need more help, please reopen this issue
