### ISSUE TITLE
text()中，不支持变量么？如果可以，可以举个例子么？

### ISSUE THREAD

**Issue by zgxzgxzg** [AirtestProject/Airtest#223]
text()中，不支持变量么？如果可以，可以举个例子么？

**Comment by zgxzgxzg** [comment]
![image](https://user-images.githubusercontent.com/13228580/49642679-b4a67100-fa4e-11e8-9fe1-713912159281.png)

**Comment by zgxzgxzg** [comment]
上面的图，发现还是报错，不应该啊～

**Comment by yimelia** [comment]
参数请使用字符串类型
pd="0"
