### ISSUE TITLE
紧急求助：Can't open carrierweekinfo-conf.xml【连接不到】

### ISSUE THREAD

**Issue by zgxzgxzg** [AirtestProject/Airtest#224]
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 161, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 84, in __init__
  File "app\plugins\device\android\android_phone.py", line 187, in startFrameStream
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\core\android\rotation.py", line 91, in start
  File "airtest\core\android\rotation.py", line 72, in _refresh_by_ow
ValueError: invalid literal for int() with base 10: b"Can't open carrierweekinfo-conf.xml\r\r\n"

**Comment by zgxzgxzg** [comment]
问题找到了：usb连接类型不能选只充电的，要选多媒体连接的

**Comment by zgxzgxzg** [comment]
设备：华为，已经root，同时安装了xposed框架

**Comment by yimelia** [comment]
请问是什么型号的华为设备？现在是否已经解决？

**Comment by zgxzgxzg** [comment]
机型：华为 H60-L02
目前还没有解决
紧急求助

**Comment by zgxzgxzg** [comment]
> 请问是什么型号的华为设备？现在是否已经解决？

机型：华为 H60-L02
目前还没有解决
紧急求助

**Comment by yimelia** [comment]
连接手机之前，先勾选下拉菜单中的第二个选项然后再点connect试试
![image](https://user-images.githubusercontent.com/6896468/50136695-8ab54000-02d3-11e9-8a4d-0d1f7e2455b5.png)

**Comment by zgxzgxzg** [comment]
> 连接手机之前，先勾选下拉菜单中的第二个选项然后再点connect试试
> ![image](https://user-images.githubusercontent.com/6896468/50136695-8ab54000-02d3-11e9-8a4d-0d1f7e2455b5.png)

好的，我试下，稍等...

**Comment by zgxzgxzg** [comment]
> 连接手机之前，先勾选下拉菜单中的第二个选项然后再点connect试试
> ![image](https://user-images.githubusercontent.com/6896468/50136695-8ab54000-02d3-11e9-8a4d-0d1f7e2455b5.png)

![image](https://user-images.githubusercontent.com/13228580/50137219-7b36f680-02d5-11e9-8744-2821292938d3.png)
还是不行

**Comment by rockywhisper** [comment]
@zgxzgxzg  

你好，这个问题这个之前没遇到过。
有可能跟某款华为系统root情况有关联，看到有人提到一些相关的情况：
 - [类似问题1](https://club.huawei.com/thread-3177694-1-1.html)
 - [类似问题2](https://www.jianshu.com/p/b291d94e457c)

不root也可以正常使用AirtestIDE的，如果实际情况允许的话，建议换一台手机，或者使用安卓模拟器试试看。    :-)

**Comment by zgxzgxzg** [comment]
> 况有关联，看到有人提到一些相关

好的
