### ISSUE TITLE
真机截屏后在模拟器运行识别很差

### ISSUE THREAD

**Issue by ljz2009y** [AirtestProject/Airtest#225]
我在真机小米2s运行720*1280的脚本没有问题，但是创建了个夜神模拟器（设置分辨率为720*1280）
在运行后，发现识别效果略查，请问是否有相关的解决方案？

**Comment by rockywhisper** [comment]
@ljz2009y 
Hi，你好。
你问的情况应该是纯图像识别的方式，在跨分辨率的识别成功率的问题了。

推荐尝试以下两种方法：
 -  改用Poco语句：
     - 如果是原生应用，不需要接入SDK可以直接使用poco脚本；
     - 如果是游戏应用，可以[接入poco-SDK](https://poco.readthedocs.io/en/latest/source/doc/integration.html)

 - [跨分辨率图像识别的自定义设置](https://github.com/AirtestProject/Airtest/issues/4)

**Comment by rockywhisper** [comment]
@ljz2009y 
Hi，您好，本issues将关闭，如果有问题欢迎随时交流  :-)
