### ISSUE TITLE
assert_exist方法，断言失败时，未抛出异常

### ISSUE THREAD

**Issue by newlife099** [AirtestProject/Airtest#228]
assert_exist()方法设置了threshold参数值为1.0。但是执行assert_exist()方法后，脚本仍然执行通过，未抛出AssertionError异常。如图所示
![image](https://user-images.githubusercontent.com/30133926/49773994-3687ea00-fd2e-11e8-850c-a3df40d609c9.png)
![image](https://user-images.githubusercontent.com/30133926/49774023-53bcb880-fd2e-11e8-98cd-4bea65833859.png)

**Comment by yimelia** [comment]
1. `assert_exists`使用了更加严格的全局参数 `THRESHOLD_STRICT`，详情请查阅 [文档](http://airtest.netease.com/docs/cn/5_airtest_framework/2_script_settings.html)，因此这里没有报出异常。
2. 不建议使用1作为阈值，因为100%的识别准确率是极其难达到的，如果设置成功了这条语句几乎很难运行通过
3. 可以尝试把放置脚本的文件夹放在更加简单的路径中（去掉下划线等特殊符号），这样可以在AirtestIDE里看到所截取的图片

**Comment by newlife099** [comment]
不对，改了这个值后，并不生效

**Comment by yimelia** [comment]
贴一下如何修改的代码，贴运行结果截图，贴log

**Comment by newlife099** [comment]
下面的例子该图片匹配度值为0.6左右，我把threshold值改为0.1时，运行脚本后，assert_exist()方法正常应该是执行通过的，但是却报错了。以及标题的那个例子，正常应该要报错，但是又执行通过了。
![image](https://user-images.githubusercontent.com/30133926/49783101-ac527c80-fd53-11e8-887e-6a96f4bf0415.png)
![image](https://user-images.githubusercontent.com/30133926/49783183-f76c8f80-fd53-11e8-871a-1e21860b0334.png)
![image](https://user-images.githubusercontent.com/30133926/49783269-40244880-fd54-11e8-9efe-c9db07c17e2e.png)
![image](https://user-images.githubusercontent.com/30133926/49783391-9beed180-fd54-11e8-9187-374757d18f61.png)

**Comment by yimelia** [comment]
你有看我的回复吗………………第一条说了，assert exists用的不是threshold，所以你直接改是没用的，以及用的是全局变量THRESHOLD_STRICT，要改需要改全局变量，详情点击文档进去看

**Comment by newlife099** [comment]
可以了，谢谢！
![image](https://user-images.githubusercontent.com/30133926/49783879-54694500-fd56-11e8-9409-e5d514ea73c5.png)
