### ISSUE TITLE
如何用selenium插件提取邮件中的验证码字段

### ISSUE THREAD

**Issue by cindy0403** [AirtestProject/Airtest#229]
**这不是一个bug，仅仅是一个问题需要您帮忙解答**
**应用场景**
通过手机注册APP服务后，需要给指定邮箱发送验证码(这里用的是yahoo日本邮箱)。
通过selenium_window打开指定邮件，目前的selenium插件是否支持提取邮件中的验证码部分，并写入到APP的验证脚本中。如果支持，烦请指导如何实现，谢谢。

**相关截图**
![snapshot](https://user-images.githubusercontent.com/42829330/49776027-62f33480-fd35-11e8-8b67-59eaf0abfef4.jpg)

**复现步骤**
1. 在安卓某APP上注册账号并绑定邮箱
2. 绑定邮箱时需要去指定邮箱提取验证码并写入脚本
3. 如何用selenium提取以上邮箱的验证码并写入脚本中

**预期效果**
脚本支持，提取windows PC上登录yahoo邮箱后的验证码，并写入安卓APP的输入框

**python 版本:** `python3.6.5`

**airtest 版本:** `1.0.24`

**设备:**
 - 型号: XPERIA SO-03J
 - 系统: Android 7.1.1

**其他相关环境信息**
(win7)

**Comment by yimelia** [comment]
我没有使用过selenium去做收邮件操作，但是单纯收取邮件、解析邮件内容的话，直接使用python脚本就足够做到了，直接到搜索引擎搜 `python 收发邮件`就有大量代码例子（比如 [这个](https://www.liaoxuefeng.com/wiki/001374738125095c955c1e6d8bb493182103fac9270762a000/001408244819215430d726128bf4fa78afe2890bec57736000)），收取邮件内容后再对内容进行一下正则解析，就能拿到验证码了
