### ISSUE TITLE
对安卓系统是否有root需求？

### ISSUE THREAD

**Issue by iamzhangbp** [AirtestProject/Airtest#23]
1.对安卓系统是否有 root要求？
2.华为、oppo等手机会杀后台程序，哪怕加入白名单也会被杀，airtest是否会被杀？
3.定位异常区域，是否有自动添加方框圆圈标识的功能？
4.能否一台控制多台终端？
5.底层点击、拖动是用的什么框架操作的？ minitouch？

**Comment by Meteorix** [comment]
@iamzhangbp 你好，其实你可以有更好的提issue的方式：每个issue讨论有一个价值的问题，并且可以让其他人获得参考

1.2.3.4 你试试就知道   5看代码也很容易确认

简单回答如下：
1. 无
2. 不会
3. 有
4. 可以
5. 是的

没有恶意，希望让交流更加有效 ：）

**Comment by iamzhangbp** [comment]
感谢提醒
