### ISSUE TITLE
VIVO安装密码问题

### ISSUE THREAD

**Issue by Topi9999** [AirtestProject/Airtest#230]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
就是vivo oppo类的手机，在安装应用的过程中，需要输入设备身份密码，否则无法安装

针对这一问题，airtest是否有相关的配置，只根据insll_app()安装api，和等待安装结束，只会终止安装，麻烦看下

相关问题：
http://bbs.vivo.com.cn/thread-3713263-1-1.html

http://bbs.vivo.com.cn/forum.php?mod=viewthread&tid=3875136

**相关截图**
![image](https://user-images.githubusercontent.com/38421083/49786004-40751180-fd5d-11e8-8f08-c5d0ead352cd.png)

**预期效果**
(预期想要得到什么、见到什么)
通过配置密码，来实现直接安装，或者什么方式可以去掉身份验证

**python 版本:** `python3.7`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2] VIVO X9S PLUS
 - 系统: [e.g. Android 8.1]  7.1.2
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
手机厂商的规定，暂时没有更好的解决方案，有人也问过他们的客服没办法取消这个限制。
这个[帖子](https://testerhome.com/topics/9192)也许有一点帮助，但是总体而言没有太好的办法解决这件事情

**Comment by Topi9999** [comment]
你们测试自动化的机型都没有用vivo oppo吗  你们是怎么解决的，监控下画面，再输入密码？？

**Comment by Topi9999** [comment]
= = 怎么就秒关闭了。。。

**Comment by yimelia** [comment]
我们另外跑脚本来自动输入密码的

**Comment by buffaloleo143** [comment]
另开一条线程监控弹窗
