### ISSUE TITLE
Unable to use adb logcat

### ISSUE THREAD

**Issue by danielchin1994** [AirtestProject/Airtest#232]
Hi, I want to use command 'adb logcat > log.txt'(which I usually does in cmd) in order to extract my android devices log.
<img width="734" alt="cmd" src="https://user-images.githubusercontent.com/45928137/50074769-461c9c80-0220-11e9-9144-331f004b9f07.png">

The device is using custom ROM and I have no idea how to extract the log file.
I tried with 'device().adb.logcat()' and no response.
Tried with 'shell("logcat > /tmp/log.txt")' but the directory not found as I am using custom ROM.
<img width="300" alt="adb" src="https://user-images.githubusercontent.com/45928137/50074708-0fdf1d00-0220-11e9-9e4b-7c03806130ac.png">

Trying to extract the log into my pc.

I am new to python and appreciate for the help.
Thanks.

**Comment by yimelia** [comment]
hi @danielchin1994 
if you just want to see the contents of logcat:
```
dev = device()  # get the current device
for i in dev.logcat():  # maybe very long
    print(i)
```

we didn't offer a method to export the log to file, but this is an example code :
```
import subprocess
dev = device()  # get the current device
with open('E:/test/test.log', 'w') as f:
    subprocess.call([dev.adb.cmd_options, '-s', dev.adb.serialno, 'logcat', '-d'], stdout=f)
```
it means run `adb -s serialno logcat -d` and redirect the output to test.log, hope it's helpful :)
if you need more help, please reopen the issue
