### ISSUE TITLE
Unable to use adb logcat (Cont with #232)

### ISSUE THREAD

**Issue by danielchin1994** [AirtestProject/Airtest#235]
Thanks for the help with issue #232 ^^

After trying your code
<img width="426" alt="code" src="https://user-images.githubusercontent.com/45928137/50132439-89334a00-02ca-11e9-85e2-40ca30298b05.png">

It only works if we input 'shell=True'.
If we do not input 'shell=True', it will give error that could not find the file
<img width="622" alt="error" src="https://user-images.githubusercontent.com/45928137/50132345-04483080-02ca-11e9-82e3-b890642687fd.png">

However, there seems to be something wrong in the code as it does not recognized this command.
<img width="679" alt="log" src="https://user-images.githubusercontent.com/45928137/50132307-d662ec00-02c9-11e9-8d04-249a9fbfed9c.png">

As you can see in the picture, after the getprop......
below command is adb.exe-P5037(without spacing), however for the rest of the commands are adb.ext -P 5037(with spacing).

I can see the log file is created in the destination folder but it is empty. TT

**Comment by yimelia** [comment]
sorry, i just try my code in python environment, but in AirtestIDE there is something wrong in it.
this may work in AirtestIDE:
```
with open('E:/test/adb/test.log', 'w') as f:
    subprocess.call(dev.adb.cmd_options[0] + " -s " + dev.adb.serialno + " logcat -d", stdout=f, shell=True)
```

**Comment by danielchin1994** [comment]
Thanks. It works now :)
But can I know if there is any other way to keep my log always override with latest log? 
The command seems to only run once to obtain the log. 

I need to get the log from the time I start the app till the end of a test (Need it to keep running till the end of program).
Need it to work like adb logcat while it always add new logs into the previous log file.

**Comment by yimelia** [comment]
you can use a thread to do this
```
with open('E:/test/adb/test.log', 'w') as f:
    for i in dev.logcat():
        f.write(i.decode("utf-8"))
```

**Comment by danielchin1994** [comment]
After creating the thread, it can continue to override log file.
However, the program stuck at home()
<img width="381" alt="stop" src="https://user-images.githubusercontent.com/45928137/50139373-da503780-02e4-11e9-8e6d-eedec31a8c37.png">

Any idea why this can happen?

**Comment by yimelia** [comment]
the code looks fine, i try it on my pc and it works
don't worry, the blue line may not be exactly correct
so does the `home()` runs successfully?

**Comment by danielchin1994** [comment]
It runs successfully for first home(), then it never runs sleeps(), home() etc.....
Maybe I should restart my pc?

**Comment by yimelia** [comment]
![adblog](https://user-images.githubusercontent.com/6896468/50145074-a6c4db80-02eb-11e9-8f44-e671b81361f2.gif)
i record my screen, and it seems well
how about run it in local python environment?  (see the [docs](http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#running-scripts-in-the-local-python-environment))

**Comment by danielchin1994** [comment]
After modifying the code, it works if I put in the sleep command first.
![image](https://user-images.githubusercontent.com/45928137/50191536-acfd9b00-0371-11e9-9ec4-144ba6718af2.png)
If I remove the first sleep command, it will run home() once and program stops. No idea why this can happen.

**Comment by MurphyLee2048** [comment]
很抱歉又重问这个问题，我执行了：
with open('E:/test/adb/test.log', 'w') as f:
    subprocess.call(dev.adb.cmd_options[0] + " -s " + dev.adb.serialno + " logcat -d", stdout=f, shell=True)
之后，虽然在目标文件夹成功新建了test.log文件且没有报错，但是不知道为什么文件是空的。想请问一下原因和解决办法。
真的感谢~

**Comment by Meteorix** [comment]
建议这么用，先logcat到手机上，再pull到本机
```
dev.adb.shell("logcat xxx > /data/local/tmp/test.log")
dev.adb.pull("/data/local/tmp/test.log", "E:/test/adb/test.log")
```

代码大概如上

**Comment by MurphyLee2048** [comment]
解决了，阿里嘎多，十分感谢

**Comment by loneyao** [comment]
> dev.adb.shell("logcat xxx > /data/local/tmp/test.log")

dev.adb.shell("logcat *:w > /data/local/tmp/test.log")
dev.adb.pull("/data/local/tmp/test.log", "/Volumes/HD/tggc.air/log/test.log")
不知道为什么，我这两句执行了第一句就没反应。

**Comment by loneyao** [comment]
> > dev.adb.shell("logcat xxx > /data/local/tmp/test.log")
> 
> dev.adb.shell("logcat *:w > /data/local/tmp/test.log")
> dev.adb.pull("/data/local/tmp/test.log", "/Volumes/HD/tggc.air/log/test.log")
> 不知道为什么，我这两句执行了第一句就没反应。
> 
> [09:34:33][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s B2NGAC6842303956 shell logcat *:w > /data/local/tmp/test.log


是不是要关闭掉adb shell的进程
然后才会去执行adb pull.

**Comment by yimelia** [comment]
可以先单独执行 `/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s B2NGAC6842303956 shell logcat *:w > /data/local/tmp/test.log` 这条指令看看是否能正常执行，并且在对应位置正确生成了test.log。
然后手工去执行一下 `/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb pull /data/local/tmp/test.log /Volumes/HD/tggc.air/log` 看看

**Comment by loneyao** [comment]
> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s B2NGAC6842303956 shell logcat *:w > /data/local/tmp/test.log

/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s B2NGAC6842303956 shell logcat *:w > /data/local/tmp/test.log
这条指令会提示-bash: /data/local/tmp/test.log: No such file or directory

**Comment by loneyao** [comment]
> > /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s B2NGAC6842303956 shell logcat *:w > /data/local/tmp/test.log
> 
> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s B2NGAC6842303956 shell logcat *:w > /data/local/tmp/test.log
> 这条指令会提示-bash: /data/local/tmp/test.log: No such file or directory
> 
> /data/local/tmp/目录是不是权限的问题。

**Comment by yimelia** [comment]
在mac下，重定向输出的方法有可能跟windows下不一样，你可以另外查一下再试看看 @loneyao

**Comment by loneyao** [comment]
> 在mac下，重定向输出的方法有可能跟windows下不一样，你可以另外查一下再试看看 @loneyao

dev.adb.pull("/data/local/tmp/test.log", "/Volumes/HD/tggc.air/log/test.log")
执行这条命令，是正常的。

**Comment by yimelia** [comment]
@loneyao 
出问题的是上一句`logcat *:w > /data/local/tmp/test.log`，你可以自己查一下看看怎么重定向log到文件中，我手头没有mac暂时没办法实验

**Comment by loneyao** [comment]
> @loneyao
> 出问题的是上一句`logcat *:w > /data/local/tmp/test.log`，你可以自己查一下看看怎么重定向log到文件中，我手头没有mac暂时没办法实验

dev.adb.shell("logcat -s *:w > /data/local/tmp/test.log") 我现在改了这个指令，是可以运行了。
但是要怎么终止去执行
dev.adb.pull("/data/local/tmp/test.log", "/Volumes/HD/tggc.air/log/test.log")
