### ISSUE TITLE
在安卓下double_click()打开视频文件没有起到双击的效果

### ISSUE THREAD

**Issue by RealMay** [AirtestProject/Airtest#237]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
在安卓通道下，使用双击的方法double_click()没有起到双击的效果
补充场景：我们是使用安卓TV，有个文件浏览器，里面放置mp4的文件，需要双击打开MP4进行播放；此外还有图片双击放大，均需要双击
猜测：有可能是双击速度太慢，导致双击效果没体现

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
在安卓下进行双击打开视频文件或者图片放大

**预期效果**
能够实现双击放大或者打开文件的效果

**Comment by RealMay** [comment]
希望双击的速度类似于鼠标的双击

**Comment by rockywhisper** [comment]
@RealMay  
你好，目前double_touch接口中，双击间隔时间是0.05秒，应该足够快了。

或者你这边自己尝试下设定点击间隔时间，试验方法：
 - 拿到待点击的坐标
     - ① 直接指定坐标pos
     - ② 使用pos = exists(图片)获取到坐标
 - 封装双击函数
     - ```python
       import time
       def custom_d_click(pos):
           device().touch(pos)
           time.sleep(0.1)  # 这里你可以调整时间，查看效果
           device().touch(pos) 
      custom_d_click(pos)
       ```

**Comment by yimelia** [comment]
hi @RealMay 
我这里试了几台手机的相册-查看图片，然后用`double_click()`接口进行双击放大缩小图片，运行都没有问题。有可能与你使用的手机型号/应用app的支持情况有关，这个issue我先暂时关闭了，如果有更多信息的反馈（具体使用app、手机型号、脚本内容）请重新打开这个issue
