### ISSUE TITLE
ValueError: generator already executing

### ISSUE THREAD

**Issue by danielchin1994** [AirtestProject/Airtest#239]
Hi guys, I encountered with this problem and I couldn't find any solutions to fix it.
Can anyone help me to look into it?
<img width="486" alt="error" src="https://user-images.githubusercontent.com/45928137/50412167-ff92f780-0848-11e9-862a-c3a72cde6b55.png">

currently, I got 3 threads running the program.
One is doing logcat
One is doing checkANR (Android crash problem detect)
One is doing automation test part(Simulation)

in the second and third thread, both have the exists() method and it always happens random and popup that error.

my checkExists method as below:
` def checkExist(img):

    lock.acquire()
    try:
        if exists(img):
            True
        if not exists(img):
            False
    finally:
        lock.release()

Automation part
<img width="312" alt="automation" src="https://user-images.githubusercontent.com/45928137/50412339-c4dd8f00-0849-11e9-8f1c-7e0558da12e0.png">

Check ANR part
<img width="663" alt="checkanr" src="https://user-images.githubusercontent.com/45928137/50412666-9ca35f80-084c-11e9-8732-b3dceb9752bd.png">

The error can also happen at the Automation simulation part.

**Comment by danielchin1994** [comment]
Once the error generated, that thread which encountered that error won't run anymore, it will stop.

**Comment by JustinToken** [comment]
请问这个问题在多线程下有解决方案了吗？我在多线程下使用touch命令 也出现ValueError: generator already executing

**Comment by yimelia** [comment]
@JustinToken 如果对运行时间要求比较低的话，可以在连设备时，加参数 `cap_method=ADBCAP` ，这样使用的是ADB截图，速度会比较慢，但是应该不会报这个错
