### ISSUE TITLE
无法操作图片

### ISSUE THREAD

**Issue by Blankofnothing** [AirtestProject/Airtest#240]
**(重要！问题分类)**
运行脚本，如下报错。
# coding=utf-8

from airtest.core.api import *
from selenium import webdriver
dr = webdriver.Chrome(chromedriver)
dr.get("http://xinsheng.huawei.com/cn/index.php")
dr.maximize_window()
time.sleep(5)
touch(Template(r"test.png", record_pos=(0.338, -0.058), resolution=(3840, 1080)))

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

[10:58:05][INFO]<airtest.core.api> Try finding:
Template(test.png)
Traceback (most recent call last):
  File "D:/OJ工程/Python/Up/UP_Air.py", line 24, in <module>
    touch(Template(r"test.png", record_pos=(0.338, -0.058), resolution=(3840, 1080)))
  File "D:\Program Files\Python\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\airtest\core\api.py", line 254, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "D:\Program Files\Python\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\airtest\core\cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
AttributeError: 'NoneType' object has no attribute 'snapshot'
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**预期效果**
(预期想要得到什么、见到什么)


**python 版本:** `python3.7`

**airtest 版本:** `1.0.24`


**设备:**
Windows
Chrome

**Comment by rockywhisper** [comment]
@Blankofnothing  

你好，看起来是没有正确连接设备，请在连接测试设备后运行脚本。

测试设备可以是android、iPhone、windows等等，具体设备连接方式可以参见[官网视频](http://airtest.netease.com/)。

**Comment by yimelia** [comment]
如果用的是selenium来进行操作，请使用selenium的专属接口`airtest_touch`，参考 [文档](http://airtest.netease.com/docs/cn/8_plugins/2_selenium.html#airtest-selenium)

**Comment by Blankofnothing** [comment]
> 如果用的是selenium来进行操作，请使用selenium的专属接口`airtest_touch`，参考 [文档](http://airtest.netease.com/docs/cn/8_plugins/2_selenium.html#airtest-selenium)

有用~多谢~
