### ISSUE TITLE
Yosemite启动异常

### ISSUE THREAD

**Issue by FuckyouBB** [AirtestProject/Airtest#242]
**描述问题bug**
Yosemite启动异常
在输入法设置里 默认输入法选择 Yosemite， 然后 点击 无论哪的输入框，vivo输入法就会自动被弹出，而不是弹出Yosemite输入法，设置里默认输入法 又被自动改成了 vivo输入法

**相关截图**

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`

**设备:**
 - 型号: vivo Y66
 - 系统: 6.0.1
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by FuckyouBB** [comment]
> @FuckyouBB
> 可以尝试下： 把vivo输入法卸载后重新安装到手机内存中，不要安装在SD卡上。

原生输入法 删不掉

**Comment by yimelia** [comment]
是否是远程连接的设备，可能与 #258 是同一个问题
