### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tester20183450** [AirtestProject/Airtest#243]
File "poco\proxy.py", line 201, in __getitem__
IndexError: list index out of range

steps：
start_app("app")成功了
执行操作，报错了

**Comment by yimelia** [comment]
请贴上报错时的运行代码，以及完整错误log，非常感谢

**Comment by rockywhisper** [comment]
@tester20183450  
看报错应该是脚本逻辑问题，比如：poco("xxx").child("xxx")[n]，这里的n数字已经超出了child数目，就会导致这个报错。

**Comment by zuiqingfengyang** [comment]
poco("Window").child("Other").child("Other").child("Other").child("Other").child("Other").child("Other").child("Other").child("Other").child("Other").child("Other").offspring("Table").child("Cell")[9].child("Other").child("Cell")[2].click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 250, in __getitem__
    return self._sorted_children[item][0]
IndexError: list index out of range

同问
