### ISSUE TITLE
mumu模拟器 2.0.31无法运行,2.0.25正常

### ISSUE THREAD

**Issue by huage2580** [AirtestProject/Airtest#244]
mumu模拟器2.0.25还能运行，昨天更新到2.0.31后，只要点击连接设备，就会导致mumu模拟器黑屏，，然后断开了链接，不是获取黑屏，而是模拟器黑屏，但mumu模拟器进程未关闭，稍等片刻它又有画面了。

airtest ：V1.1.0 
windows10 64位

**Comment by yimelia** [comment]
很抱歉，由于mumu模拟器更新非常频繁，我们暂时没有办法保证测试到每个版本可用，而且mumu模拟器在运行airtest脚本时可能会出现内存占用过高的问题，建议换一个模拟器来使用。
