### ISSUE TITLE
第一次添加操作后Device Screen不刷新了

### ISSUE THREAD

**Issue by yijianguxin** [AirtestProject/Airtest#246]
启动Airtest并连接手机成功后，Device Screen会实时显示手机操作
开始编辑脚本并加入touch行为或者进行录制后，touch操作脚本添加成功，这时Device Screen会卡住，停在之前的界面不刷新，之后无论任何操作都不起作用，只能重新连接手机

**Comment by yimelia** [comment]
这个问题是因为新版本更换了ADB40版本导致的冲突问题，下个版本我们会修复，目前暂时的处理方式是：

下载一个上一版本的AirtestIDE，例如 [1.0.1](http://airtest.netease.com/changelog.html#v1_0_1)，然后复制 `AirtestIDE\airtest\core\android\static\adb\windows` 目录下的3个ADB相关文件，覆盖掉现在使用的新版本AirtestIDE同一目录下文件

**Comment by yijianguxin** [comment]
问题已解决，非常感谢
