### ISSUE TITLE
三星手机部分地图pinch无效果， center=None , size_info长宽错误

### ISSUE THREAD

**Issue by Hepper0** [AirtestProject/Airtest#252]
**(重要！问题分类)**
* 图像识别、设备控制相关问题

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
三星手机在部分地图使用pinch('in')时，
未达到预期的地图缩小效果，实际是屏幕往右上角移动
Debug跟踪发现，默认的center坐标计算取的是竖屏时的宽高

**相关截图**
![image](https://user-images.githubusercontent.com/31428761/51374941-74530c00-1b3f-11e9-814a-a4c86bb9d96e.png)
![image](https://user-images.githubusercontent.com/31428761/51376143-969a5900-1b42-11e9-870b-05af496e20a9.png)

**复现步骤**
进入某些战斗地图时，在python中调用pinch('in')

**预期效果**
想要达到地图缩小
实际的效果是向右上角滚动

**python 版本:** `python3.6`

**airtest 版本:** `1.0.24`

**设备:**
 - 型号: [三星 Galaxy S8+]
 - 系统: [Android 8.0.0]

**其他相关环境信息**
windows python airtest

**Comment by yimelia** [comment]
感谢反馈，这是个BUG，原因不是横竖屏的问题，是没有进行一次Minitouch触摸点转换导致的。这个问题将在下一次更新时修复。
