### ISSUE TITLE
touch图片，‘只运行选中代码’，识别不了图片

### ISSUE THREAD

**Issue by songzhenhua** [AirtestProject/Airtest#257]
**描述问题bug**
touch图片，‘只运行选中代码’，识别不了图片，运行结果如下图；但是按F5执行，却可以成功。

**相关截图**
![ob_llt egvg d s9aas ig](https://user-images.githubusercontent.com/7867532/51544380-c3c86d80-1e9a-11e9-8476-c1d1ac7836f8.png)

**复现步骤**
1. 插入一个touch图片语句
2. 右击选择‘只运行选中代码’

**预期效果**
单步执行成功。
我认为运行单行代码是调试的重要手段，应该予以重视。除非你们的用户都是用POCO。如果有用户大部分操作都是图片识别，不可能写几十行代码，每次都要从头按F5调试。

**python 版本:** `python2.7`

**airtestIED 版本:** `1.2.0.`（pip freeze里没有airtest）

**设备:**
 - 型号: [小米NOTE顶配版]
 - 系统: [Android7.0，MIUI9.2]

**其他相关环境信息**
NOTE顶配版截的图，在小米1S上可以单步运行成功。
游戏使用的是你们提供的DEMO：com.netease.poco.u3d.tutorial.apk

**Comment by yimelia** [comment]
在右键单独运行脚本时，逻辑与正常跑脚本有一点点不一样，截图语句在运行时，全都是使用了ADB的screenshot指令截图，因此暂时怀疑这个问题跟MIUI的版本有关系（见 #259 这个issue)，但是目前我们暂时没拿到MIUI9的手机，所以还没办法进行具体测试。

**Comment by rockywhisper** [comment]
@songzhenhua 
你好，感谢你的反馈。

1、目前我们提供了图像调试的功能，可以双击进入图片编辑器：
![image](https://user-images.githubusercontent.com/8188879/51739423-5e5bc300-20cc-11e9-9097-3378b5ba944b.png)
 - 可以通过调整图片的阈值、rgb识别等来调整识别参数。

2、对于跨分辨率识别，可以通过自己设置全局的缩放机制来提高识别率：
 - See more details in #4

**Comment by yimelia** [comment]
Duplicate of #259 ，将于下个版本放出时修复
