### ISSUE TITLE
Yosemite无线连接状态下无法开启

### ISSUE THREAD

**Issue by buffaloleo143** [AirtestProject/Airtest#258]
描述问题bug
Yosemite无线连接状态下无法开启
Yosemite输入法必须连接USB线才能打开，把掉USB就切换不到
采用adb无线连接设备运行air脚本时就不能正常使用Yosemite输入文本

相关截图

复现步骤

预期效果
不连usb也可以打开Yosemite输入法

python 版本: python2.7
airtest 版本: 1.0.24

设备:

型号: 华为畅享9plus
Android版本: 8.1.0

**Comment by codeskyblue** [comment]
这个感觉要改yosemite apk的代码才行

**Comment by Meteorix** [comment]
@codeskyblue 有兴趣帮忙改改？

**Comment by codeskyblue** [comment]
我就是提供下思路  逃

**Comment by yimelia** [comment]
@codeskyblue 原理是什么？

**Comment by yimelia** [comment]
已修复，将于下个版本放出，感谢各位反馈和翔哥提供帮助
