### ISSUE TITLE
adb截图真的需要额外旋转吗？

### ISSUE THREAD

**Issue by startnothings** [AirtestProject/Airtest#259]
在airtest/core/android/android.py文件中snapshot方法

> #adb 截图总是要根据orientation旋转
            elif self.cap_method == CAP_METHOD.ADBCAP:
                 screen = aircv.rotate(screen, self.display_info["orientation"] * 90, clockwise=False)

经过我的测试，发现这可能是多此一举，adb截图后就是正确的方向了。旋转后反而是错误的方向

也可能和具体的手机系统或者adb版本有关，（我使用adb 1.0.40 手机小米MIUI10，模拟器genymotion都不需要额外旋转）

**Comment by yimelia** [comment]
我测试了小米的几个不同MIUI版本的手机，在MIUI10中，截图会直接是正确的方向，但是在MIUI的其他版本中都需要进行一次旋转判定。MIUI9由于没有找到手机因此尚未测试。

其他品牌的手机在ADB截图逻辑里都需要进行当前屏幕方向的判断，因此这里我们暂时无法修改代码。

**Comment by yimelia** [comment]
已确认问题，在Android7.1以下版本没问题，7.1及以上版本都有这个问题，将在下个版本更新时修复
