### ISSUE TITLE
查询设备UI snapshot是否过于频繁？

### ISSUE THREAD

**Issue by LeepengX** [AirtestProject/Airtest#263]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
「优化」连接charles代理发现接口疯狂请求snapshot。

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
Charles大量请求的截图
![image](https://user-images.githubusercontent.com/7345894/51881019-82f9b880-23b4-11e9-9dca-21ad36416492.png)

**复现步骤**
连接charles代理发现接口疯狂请求snapshot。将手机连接到电脑代理，试图在测试环境下进行UI自动化测试。
**预期效果**
是否在airtest上提供刷新按钮来更新布局，而不是时刻高频刷新？

**python 版本:** `python3.5`

**airtest 版本:** `1.2.0`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. iPhone]
 - 系统: [e.g. iOS 12.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
hi，可以看到我们官网的演示视频里，AirtestIDE是实时显示手机画面内容的，这样才能方便在IDE中进行手机的远程操作，因此这里会频繁刷新当前手机画面内容。
