### ISSUE TITLE
Run as standalone on device ? Read text/recognition ?

### ISSUE THREAD

**Issue by Enissay** [AirtestProject/Airtest#265]
Dear all,

Thank you for the great tool, just discovered it yesterday and looks very promising.

I have 2 questions though:

- Once the code is ready, can it somehow be exported then executed on the device as standalone ?
- How can I read some text using your tool ? or should I use some external libs ?

Finally, the swipe function seems to be harsh, in a 3d game, I simply want to move left/up/right/bottom to see the next invisible space immediately after the edge. The current swipe does a harsh one which sends me far far from where I want.
Full disclosure: I am not a game developer, I want to use this IDE to automate the daily repetitive tasks on my farms. I see that the poco option is more powerful, but can only used by devs :'(

Thank you :-)

**Comment by yimelia** [comment]
hi @Enissay 
Once the code is ready, can it somehow be exported then executed on the device as standalone ?
- yes, see [this](https://airtest.readthedocs.io/en/latest/README_MORE.html#running-air-from-cli), just like running a python script.

How can I read some text using your tool ? or should I use some external libs ?
- now we only use image recognition technology, but we are trying to add OCR in Airtest, it still needs more time.
- if you want to use external libs, see [this](http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#use-local-python-environment-to-run-scripts-trial)

**Comment by Enissay** [comment]
Hi @yimelia 
Thank you for the answer. Though, one is not clear in my mind yet:
When I say standalone, I mean running the code directly on my smartphone without any connection to my laptop. Will the CLI way still works ?

**Comment by Meteorix** [comment]
No, the script is python driven.

**Comment by JJunM** [comment]
> hi @Enissay
> Once the code is ready, can it somehow be exported then executed on the device as standalone ?
> 
> * yes, see [this](https://airtest.readthedocs.io/en/latest/README_MORE.html#running-air-from-cli), just like running a python script.
> 
> How can I read some text using your tool ? or should I use some external libs ?
> 
> * now we only use image recognition technology, but we are trying to add OCR in Airtest, it still needs more time.
> * if you want to use external libs, see [this](http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#use-local-python-environment-to-run-scripts-trial)

I want to know the ORC application schedule.

**Comment by rockywhisper** [comment]
@JJunM  
Hi, buddy.

OCR support is still in the development stage and there is no precise release date now. But it won't take too long. I think maybe some day in May.
