### ISSUE TITLE
Let us know the UI build command

### ISSUE THREAD

**Issue by hhh3h** [AirtestProject/Airtest#267]
Hi,
Could you let me know what to use UI build command? (by using Pyinstaller?)
Because I want to add the new function to it and use it after building it.

**Comment by hhh3h** [comment]
Could you tell me how to make Airtest.exe file?

**Comment by Meteorix** [comment]
You can start with:
```
pyinstaller airtest/cli/__main__.py
```

Then fix the 2 possible issues I mentioned earlier. It won't be to hard.

**Comment by hhh3h** [comment]
Thanks but it is used for CLI not UI.
Please let me know how to make "AirtestIDE.exe" for UI?

**Comment by Meteorix** [comment]
AirtestIDE is not open-sourced yet.
