### ISSUE TITLE
Mac系统录制了web脚本后，无法运行脚本。

### ISSUE THREAD

**Issue by sanasna** [AirtestProject/Airtest#268]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by Meteorix** [comment]
你好，请提供尽可能多的信息，不然没法帮到你（新建issue可以选中文模板）
