### ISSUE TITLE
能支持文本模糊匹配元素吗

### ISSUE THREAD

**Issue by csugzq** [AirtestProject/Airtest#270]
用poco能根据元素的文本内容进行模糊匹配吗，像uiautomator2里面的d(textContains="")

**Comment by Meteorix** [comment]
用textMatches，正则匹配
```
poco(textMatches='^据点.*$', type='Button', enable=True)
```

参考 https://github.com/AirtestProject/Poco#working-with-poco-objects

**Comment by csugzq** [comment]
谢谢

**Comment by MaNongXiaoGang** [comment]
> 用textMatches，正则匹配
> 
> ```
> poco(textMatches='^据点.*$', type='Button', enable=True)
> ```
> 
> 参考 https://github.com/AirtestProject/Poco#working-with-poco-objects

没有用啊
