### ISSUE TITLE
poco是否支持事件监听

### ISSUE THREAD

**Issue by csugzq** [AirtestProject/Airtest#272]
类似于uiautomator2的d.watcher().when()，poco是否也支持当某件事发生能够让监听器捕捉得到

**Comment by Meteorix** [comment]
有监听ui出现的接口，可以参考这里 https://poco.readthedocs.io/en/latest/source/doc/poco-example/waiting_events.html

**Comment by codeskyblue** [comment]
@Meteorix 他说的好像是用来处理弹窗的接口
