### ISSUE TITLE
When you enter text(text("Hello"))), the text is entered into the app player as an empty space.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#273]
Remove any following parts if does not have details about

**Describe the bug**
When you enter text(text("Hello"))), the text is entered into the app player as an empty space.

app player: nox (https://kr.bignox.com/)

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**
(https://user-images.githubusercontent.com/46311868/52838035-9044d000-3134-11e9-9afe-a60babdf675b.png)

**python version:** `python3.5`

**airtest version:** `1.0.22`
![2]

> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following [e.g. google pixel 2]):**
 - Device: nox applyer
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
in nox `Settings`-`Language&Input`, set `Hardware` off:

![image](https://user-images.githubusercontent.com/6896468/52839512-545c3b80-3131-11e9-8fa9-513e1e46da94.png)

if it doesn't work, click the `System settings`  in the upper right corner, and check the `soft keyboard`:

![image](https://user-images.githubusercontent.com/6896468/52839820-4c50cb80-3132-11e9-8a4e-3b485ae1db0f.png)

**Comment by Meteorix** [comment]
Another solution, use adb ime
```
>>> from airtest.core.api import *
>>> init_device("Android", ime_method="ADBIME")
>>> text("hello")
```
