### ISSUE TITLE
请问为什么我用pinch无法对图片进行放大操作？

### ISSUE THREAD

**Issue by MurphyLee2048** [AirtestProject/Airtest#276]
**bug**
-运行未报错，只是未见图片被放大

**复现步骤**
-代码：pinch('out')

**预期效果**
-pinch('out')应该能模拟放大图片的手势吧？

**python** 
-3.6

**airtest**
1.0.25

**设备:**
 - Device: [pixel]
 - Android version: [Android 9]

**环境**
-win7

**Comment by yimelia** [comment]
我们这里的pixel最近无法连上，目前还在排查问题，但是试过在其他品牌的Android9设备上可以正常运行pinch接口。
可以尝试开启手机上的显示指针轨迹（开发者选项 -> 输入 -> 显示点按操作反馈、指针位置都打开），查看一下执行pinch指令时屏幕滑动的位置是否正确（以及横屏和竖屏状态下都可以试试），如果有有位置偏移的情况可以再反馈一下~

**Comment by MurphyLee2048** [comment]
可以了，位置没有偏移，应该是需要再多点击一下隐藏分享、返回、图片信息那一列图标

**Comment by jeniva** [comment]
pinch可以对某个区域进行缩放吗？比如某个控件（目前会报错ImportError: cannot import name 'MoveEvent'）或者截图的区域进行缩放等。
