### ISSUE TITLE
airtest 是否提供鼠标悬停功能

### ISSUE THREAD

**Issue by linglingfa1212** [AirtestProject/Airtest#277]
**描述问题bug**
airtest 是否提供鼠标悬停功能

**预期效果**
在windows浏览器中，提供鼠标悬停功能

**Comment by Meteorix** [comment]
```
device().mouse.move(coords=(100, 200))
```
参考这里的用法 https://github.com/AirtestProject/Airtest/blob/0de6f6c84ae8fa956a38c22936fba5ed74c58213/airtest/core/win/win.py#L180

**Comment by linglingfa1212** [comment]
@Meteorix 感谢帮忙，已实现。
请问，浏览器右侧滚动条如何去控制，这个问题需不需要重新开个issue？

**Comment by Meteorix** [comment]
这个我也没试过，不过猜测可以模拟鼠标事件，或者键盘事件page_down

```
device().mouse.scroll(...)
```

mouse和keyboard的api参考 https://pywinauto.readthedocs.io/en/latest/code/pywinauto.keyboard.html

**Comment by linglingfa1212** [comment]
谢谢。
