### ISSUE TITLE
求助！！没有air，完全用python写的 如何生成report

### ISSUE THREAD

**Issue by JustinToken** [AirtestProject/Airtest#278]
RT

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/blob/0de6f6c84ae8fa956a38c22936fba5ed74c58213/playground/blackjack_example/test_blackjack.py#L47

参考这里 ``simple_report``

**Comment by JustinToken** [comment]
你好 出现以下错误。我的版本是1.0.74
![image](https://user-images.githubusercontent.com/47622050/53099357-9b4a9680-3560-11e9-948f-b89ebc9dada0.png)

**Comment by Meteorix** [comment]
你可以升级到github最新版本，或者用以前的写法
```
simple_report("log", __file__)
```

**Comment by JustinToken** [comment]
非常感谢，为题已经解决！
