### ISSUE TITLE
Problem with construction the UI-hierarchy tree to Unity Game

### ISSUE THREAD

**Issue by MuratovEgor** [AirtestProject/Airtest#28]
Hello! 
I have a problem with construction the UI-hierarchy tree to Unity Game. 

In AirtestIDE don't construction UI-hierarchy. Logs from console

![log](https://user-images.githubusercontent.com/34191121/38241712-994a2356-373b-11e8-8702-c09907d9c1e3.png)

All logs  - [log.txt](https://github.com/AirtestProject/Airtest/files/1870953/log.txt)

**Comment by Meteorix** [comment]
@MuratovEgor Thanks for you interest in Airtest.

Have you integrate our SDK into your Unity game? 
Reference is here: http://poco.readthedocs.io/en/latest/source/doc/integration.html#unity3d

**Comment by MuratovEgor** [comment]
Yes, of course

**Comment by MuratovEgor** [comment]
I am so sorry. You were right. The problem in integration. Now all right
