### ISSUE TITLE
Firebase 打包后安装到手机上无法使用

### ISSUE THREAD

**Issue by sunhailin-Leo** [AirtestProject/Airtest#281]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
SyntaxError: Non-ASCII character '\xf3' in file /data/user/0/com.netease.open.airbase/files/app/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/17564655/53289546-4910ac00-37d2-11e9-9ba5-12daec79442a.png">

**python 版本:** `python3.7`

**airtest 版本:** `最新版`

**设备:**
 - 型号: [e.g. 小米8]
 - 系统: [e.g. Android 9]
 - (别的信息)

**其他相关环境信息**
MacOS

**Comment by sunhailin-Leo** [comment]
代码如下: 

```python
# coding=utf-8
__author__ = "sunhailin"
import time
from airtest.core.api import *

auto_setup(__file__)

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

start_app("<软件包名>")
```

**Comment by yimelia** [comment]
hi @sunhailin-Leo 
在当前版本firebase打出来的包里，暂时还无法使用安卓原生的poco

**Comment by Meteorix** [comment]
目前firebase包只能使用airtest和游戏引擎的poco，后续可能会扩展安卓源生应用的支持。

**Comment by YanYoJun** [comment]
@Meteorix 发现同样的问题. 我确实是使用Android原生应用的poco. 建议支持吧, 因为我们可以在root过的手机上跑测试. 谢谢. PS: 这个工具真的很牛逼

**Comment by lijin-8** [comment]
发现同样的问题. 使用Android原生应用的poco. 建议支持吧
