### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by JustinToken** [AirtestProject/Airtest#284]
Remove any following parts if does not have details about

paste traceback here

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\aircv\sift.py", line 253, in _find_homography
    M, mask = cv2.findHomography(sch_pts, src_pts, cv2.RANSAC, 5.0)
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\calib3d\src\ptsetreg.cpp:169: error: (-215:Assertion failed) count >= 0 && count2 == count in function 'cv::RANSACPointSetRegistrator::run'

**python version:** `python3.7`

**airtest version:** `1.0.25`

**Comment by rockywhisper** [comment]
@JustinToken  Hi, buddy. 
I thought it was fixed already, seems not. Sorry about it. (#97 )

Would you mind giving me the image file in your script and the screenshot image file by [Email](breezejianjun@gmail.com) ?
It would help a lot to fix this problem.

**Comment by rockywhisper** [comment]
@JustinToken 
Hi, I re-checked the code.
It's just a traceback print message. You can just ignore it. [view code](https://github.com/AirtestProject/Airtest/blob/35b4661bb6ae90a033da07ac9073e1fcc7341bcc/airtest/aircv/sift.py#L255)

Does it cause any problem?

**Comment by JustinToken** [comment]
yes,Seems it was work normally.I will close the issue.Thanks a lot!
