### ISSUE TITLE
安卓包使用airtest连接后无法抓取UI

### ISSUE THREAD

**Issue by thisluren** [AirtestProject/Airtest#285]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
连接手机后选择unity，没有抓取UI，脚本运行无法，提示寻找不了UI控件

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
![image](https://user-images.githubusercontent.com/46642615/53539163-78654700-3b4b-11e9-9657-eda4af9f1522.png)
![image](https://user-images.githubusercontent.com/46642615/53539203-9a5ec980-3b4b-11e9-8594-32bca3700412.png)

**复现步骤**

**预期效果**
连接成功后，poco辅助窗成功抓取UI控件，运行脚本可正常运行

**python 版本:** `python3.7`

**airtest 版本:** `1.0.26`
> airtest版本通过`pip freeze`可以命令可以查到

**其他相关环境信息**

**Comment by yimelia** [comment]
请确认是什么类型的app
如果是安卓原生应用，请选择android类型

**Comment by thisluren** [comment]
公司项目的、使用unity3d

**Comment by yimelia** [comment]
是否已接入poco-SDK? 文档见 [这里](https://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/integration.html#unity3d)

**Comment by yimelia** [comment]
可以发一下报错内容, log等信息
在Unity窗口是否能够正常使用？

**Comment by thisluren** [comment]
> 可以发一下报错内容, log等信息
> 在Unity窗口是否能够正常使用？

**Comment by thisluren** [comment]
> 可以发一下报错内容, log等信息
> 在Unity窗口是否能够正常使用？

截图已上传
图1为连接安卓手机开启poco，log显示不断重复连接，但手机app已卡住
图2为unity中连接poco显示的ui树

**Comment by yimelia** [comment]
hi @thisluren 
我们这边看不到你的截图，可能需要重新确认一下？

**Comment by thisluren** [comment]
> hi @thisluren
> 我们这边看不到你的截图，可能需要重新确认一下？

已经找到问题了

**Comment by yimelia** [comment]
ok~如果没问题的话，我先把issue关闭了哈

**Comment by thisluren** [comment]
> ok~如果没问题的话，我先把issue关闭了哈

嗯，是项目跟airtest的加载相关出问题
