### ISSUE TITLE
What should you do to run the next script that does not stop if the script fails?

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#286]
Remove any following parts if does not have details about

**Describe the bug**
I want to run a scenario 2 that does not stop if the scenario 1 fails, how can I do it?
Run the next scenario(s2_test scenarios name) without stopping

[script]   airtestide> airtest(image)
[Script structure]

##test scenarios
def s1_test scenarios name(self)
    test script1: touch - Pass
    test script2: assert_ or touch - Fail (Run the next scenario(s2_test scenarios name) without stopping )
    test script3: touch
def s2_test scenarios name(self)
    test script1: touch
    test script2: touch

##test scenarios Run
s1_test scenarios name()
s2_test scenarios name()

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by Meteorix** [comment]
Why not just use python `try except`

```
try:
    s1_test()
except AirtestError:
    pass
s2_test()
```

**Comment by JJunM** [comment]
> Why not just use python `try except`
> 
> ```
> try:
>     s1_test()
> except AirtestError:
>     pass
> s2_test()
> ```



> try:
>     s1_test()
> except AirtestError:
>     pass
> s2_test()

It was applied as follows. Thank you.

test = [s1_test, s2_test, s3_test]
for i in test:
    try:
        i(test)
    except AirtestError:
        pass
