### ISSUE TITLE
一台手机单独跑脚本没问题，若两个手机一起跑就一台正常运行，另外一台手机没反应

### ISSUE THREAD

**Issue by igg-hzy** [AirtestProject/Airtest#29]
电脑4个usb接口，一台电脑连接一台手机进行自动化没问题，但是若多连一台手机，两台手机同时跑自动化脚本，另外一台就没反应。
两个bat脚本分别如下：
python -m airtest run D:\Airtest\airtest\hzy.air  --device Android:///4df150757e465fdb --log D:\Airtest\airtest\4df150757e465fdb
pause

python -m airtest run D:\Airtest\airtest\hzy.air  --device Android:///9aa768ee --log D:\Airtest\airtest\9aa768ee 
pause

运行结果：日志里变成了同个 设备ID 
图1： 两个脚本开始运行。   图2：两个脚本运行后。
![1](https://user-images.githubusercontent.com/28045961/38299155-d759388a-382b-11e8-8411-fc0635f881e9.png)
![2](https://user-images.githubusercontent.com/28045961/38299156-d79792d8-382b-11e8-9ca9-63122fd7beb0.png)

**Comment by Meteorix** [comment]
@igg-hzy 请问你的airtest是pip install airtest安装的吗？
