### ISSUE TITLE
需求：特殊使用场景，需要修改源码，又想使用IDE工具，希望能有些建议

### ISSUE THREAD

**Issue by 47045039** [AirtestProject/Airtest#291]
在电视机上使用airtest测试视频类的应用，截图不是太好用，需要扩展poco接口。
但使用pycharm开发脚本，好用的IDE截图工具就无法使用了。
所以，希望能有些建议。
或者说，我自己修改过的源码，怎么和IDE工具搭配使用呢？

**Comment by Meteorix** [comment]
http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python

参考这里，可以配置AirtestIDE使用本地的python解释器

**Comment by 47045039** [comment]
方法好使，thank u。
