### ISSUE TITLE
airiest 如何集成OCR

### ISSUE THREAD

**Issue by ghd214** [AirtestProject/Airtest#292]
现在项目的需求是，需要识别图片上的数字

**Comment by Meteorix** [comment]
自己使用python的ocr库解决，我们之前实验过tesseract

**Comment by ghd214** [comment]
我试了tesseract, 可以集成，但是现在snapshot方法截取的是全屏，我需要实现snapshot方法根据坐标截图，现在不知道airtest如何编译，大神有教程吗

**Comment by ghd214** [comment]
snapshot(x,y,width,height) 截图

**Comment by Meteorix** [comment]
不用编译，自己写一个mysnapshot函数，参考airtest的代码进行扩展

**Comment by ghd214** [comment]
我用 pip install aritest 安装的，自己写完了如何替换安装的，

**Comment by Meteorix** [comment]
不用替换呀，自己定义一个函数，import进来，使用自己的函数

**Comment by ghd214** [comment]
好吧，我试试，多谢

**Comment by Meteorix** [comment]
不用谢，你实验成功后欢迎提个pr过来，分享给其他用户
