### ISSUE TITLE
运行过程中pocoservice服务挂了，无法重启，并且程序死循环

### ISSUE THREAD

**Issue by StevenXUzw** [AirtestProject/Airtest#294]
/Users/***/Library/Python/3.7/lib/python/site-packages/poco/drivers/android/uiautomation.py:278: UserWarning: [pocoservice.apk] instrumentation test server process is no longer alive
  warnings.warn("[pocoservice.apk] instrumentation test server process is no longer alive")

**Comment by yimelia** [comment]
更新至最新版本poco即可
