### ISSUE TITLE
I think I know how to connect multiple devices with Airtest IDE.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#296]
Remove any following parts if does not have details about

**Describe the bug**

I think I know how to connect multiple devices with Airtest IDE.
I would like to connect multiple devices with AirtestIDE and run airtest script.

ex
-  android 2 + ios1

**Comment by EraChen233** [comment]
After connect Android phone and iPhone to computer, you can run Airtest script by switching phone. Note that iPhone needs to be deployed in Mac.
But if you want to run tests on these devices at the same time, you can try running aritest via cmd, or refer to [multi-device-runner](https://github.com/AirtestProject/multi-device-runner)

**Comment by giangnb-dev** [comment]
@EraChen233 hey bro, i run multi device include : LDPlayer and Android Phone. On Android Phone no problem while LDPlayer error as the picture below:
![image](https://user-images.githubusercontent.com/56757898/72050927-dbd80d80-32f4-11ea-9525-625fcae642af.png)
![image](https://user-images.githubusercontent.com/56757898/72050977-f4482800-32f4-11ea-8cde-f0c1be11f8df.png)

Give me solution please, thank !

**Comment by EraChen233** [comment]
[multi-device-runner](https://github.com/AirtestProject/multi-device-runner) is only a sample for running scripts in multi real devices. If you want to run scripts in emulators, you need to implement this function yourself.
Read the code, you will find the solution.

**Tips**
![image](https://user-images.githubusercontent.com/5961185/72055511-ef3fa480-3305-11ea-883d-ecbffcb43c4a.png)

 http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#running-scripts-with-pythons-command-line
