### ISSUE TITLE
swipe not working properly

### ISSUE THREAD

**Issue by Whiteseeker** [AirtestProject/Airtest#3]
I'm using: 
![screen shot 2018-03-06 at 4 41 06 pm](https://user-images.githubusercontent.com/4581097/37045176-39c782be-215d-11e8-91b4-370619bcc908.png)

I have a very simple script like that:

```
start_app("com.google.android.apps.santatracker")
sleep(5.0)
swipe(v1=[0.5, 0.3], v2=[0.5, 0.8])
```

Give the doc [here](http://airtest.readthedocs.io/en/latest/all_module/airtest.core.api.html#airtest.core.api.swipe) I would expect tit to swipe half the height of the screen starting at 30% of the screen and finishing at 80% of the screen (all happening at half the width, ie the middle of the screen).

Instead I can see the notification bar briefly appearing and nothing else. When I activate the debug option to show the input pointer it show the pointer quickly appearing an disapearing on the top left corner.

**Comment by Whiteseeker** [comment]
It looks like [0.5, 0.3] is interpreted as 0.5 px and 0.3 px.
I tried:
`swipe(v1=[200, 800], vector=[0.0, -0.5])`
That properly scroll half a screen from the pixel 200 and 800 up. That brings 2 questions:

1. Where is it documented that [0, 0] is top left corner (I was naively assuming bottom left)
2. why the first [200, 800] is interpreted in pixel and the second [0.0, -0.5] is interpreted as screen %age ?

Is there a way I can get v1 to be interpreted as %age ?

**Comment by Whiteseeker** [comment]
Still there in 0.0.5

**Comment by adolli** [comment]
`swipe` is the API function of airtest which is `from airtest.core.api import swipe`. This function takes absolute coordinates as the arguments, unlike `poco.swipe` which accepts uniform coordinates from 0 to 1.

**Comment by Whiteseeker** [comment]
Thx a lot @adolli  ! I'll just make a small function (with a different name like swipe_relative or so) and your your sample code (^_-)
