### ISSUE TITLE
Multi devices

### ISSUE THREAD

**Issue by Skisperd** [AirtestProject/Airtest#300]
Sorry again but:

What solution to run multiple scripts in sequence? on multiple devices

note: I did not find documentation about this

**Comment by EraChen233** [comment]
You can modify code in sample [multi-device-runner](https://github.com/AirtestProject/multi-device-runner) to run multiple scripts on multiple devices. Or you can give a glimpse to [AirLab](https://airlab.163.com/) which offers professional testing

**Comment by Skisperd** [comment]
Sorry you can make one exemple. Please :(
