### ISSUE TITLE
如何多点触控

### ISSUE THREAD

**Issue by jekiki** [AirtestProject/Airtest#301]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**异常原因**
使用airtest API 会出现报错
G.DEVICE.touch(pos)
G.DEVICE.swipe(pos1, pos2, duration=10, steps=1)

使用adb自己实现 对于swipe事件会被tap事件中断
os.system("adb shell input tap 1755 1030 ")
os.system("adb shell input swipe 290 970 330 910 10000")

**预期效果**
实现一边滑动，一边点击，代码中使用了 from multiprocessing import Process 多进程

通过使用多进程，使得swipe和touch事件可以非阻塞执行，touch事件不需要等待swipe事件结束后才才被执行，实现游戏中可以边走边放技能或者边走边平A

现在多点触控等操作没有试过，但相信应该会出现相同的问题

**python 版本:** `python3.7`

**airtest 版本:** `1.0.26`

**其他相关环境信息**
(其他运行环境，ubuntu使用异常，在windows使用不了Process多进程。)

**Comment by jekiki** [comment]
我们需要一种非阻塞式的方式来编写程序和组织代码，同步的执行方式会给开发中带来大量的问题！

**Comment by adolli** [comment]
我们有提供多点触控api，目前还没写到文档里，稍后我给你一个例子

iPhoneから送信

2019/03/09 11:26、jekiki <notifications@github.com>のメール:

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/blob/master/playground/android_motionevents.py

这里有例子，可以看看

**Comment by adolli** [comment]
@Meteorix 我有一个更上层的封装，不用计算坐标和比例

iPhoneから送信

2019/03/09 11:43、Meteorix <notifications@github.com>のメール:

**Comment by adolli** [comment]
在poco里面使用track来表示多点触控的每一个轨迹

```py
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
from poco.utils.track import MotionTrack

poco = AndroidUiautomationPoco()
tracks = [
    MotionTrack().start([0.5, 0.5]).move([0.5, 0.6]).move([0.6, 0.6]).hold(1),   # 可以连续move多次
    MotionTrack().start([0.6, 0.6]),                                             # 不move的话表示只点击这个点
]
poco.apply_motion_tracks(tracks)
```

[source code](https://github.com/AirtestProject/Poco/blob/2c559a586adf3fd11ee81cabc446d4d3f6f2d119/poco/utils/track.py#L41)

**Comment by adolli** [comment]
@yimelia @EraChen233 帮忙加一下文档

**Comment by loneyao** [comment]
> ```python
> from poco.drivers.android.uiautomation import AndroidUiautomationPoco
> from poco.utils.track import MotionTrack
> 
> poco = AndroidUiautomationPoco()
> tracks = [
>     MotionTrack().start([0.5, 0.5]).move([0.5, 0.6]).move([0.6, 0.6]).hold(1),   # 可以连续move多次
>     MotionTrack().start([0.6, 0.6]),                                             # 不move的话表示只点击这个点
> ]
> poco.apply_motion_tracks(tracks)
> ```

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
from poco.utils.track import MotionTrack

poco = AndroidUiautomationPoco()
tracks = [
    MotionTrack().start([0.5, 0.5]).move([0.5, 0.6]).move([0.6, 0.6]).hold(1),   # 可以连续move多次
    MotionTrack().start([0.6, 0.6]),                                             # 不move的话表示只点击这个点
]
poco.apply_motion_tracks(tracks)


有封装成一个函数吗？

**Comment by yimelia** [comment]
@loneyao 
安卓手机可以参考[这个](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#id15)

**Comment by loneyao** [comment]
> @loneyao
> 安卓手机可以参考[这个](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#id15)

from poco.drivers.std import StdPoco
poco = StdPoco()

cocos-lua可以用的吗？

**Comment by yimelia** [comment]
可以试一下，可能是不行的
