### ISSUE TITLE
An error(json.decoder.JSONDecodeError) will occur when running the script.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#303]
Remove any following parts if does not have details about

**Describe the bug**
An error(json.decoder.JSONDecodeError) will occur when running the script.
I think I know how to solve this problem.
![aaa 2](https://user-images.githubusercontent.com/46311868/54095180-2f35b280-43e9-11e9-847a-fc003e109be6.png)

**Comment by Meteorix** [comment]
The log you paste seems to be irrelevant to JSONDecodeError.
