### ISSUE TITLE
两个字符串相等时，使用assert_equal方法会断言失败(自定义的字符串和poco获得的test文本断言会失败)

### ISSUE THREAD

**Issue by jyl4944204** [AirtestProject/Airtest#305]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
两个字符串相等时，使用assert_equal方法会报不等；

（在这里粘贴traceback或其他报错信息）
AssertionError: 1 位群友参团 还差 1 人成团 and 1 位群友参团 还差 1 人成团 are not equal, message: 检查两个字符串是否相等

**相关截图**

**复现步骤**
aim = "1 位群友参团 还差 1 人成团"
re='1 位群友参团 还差 1 人成团'
result = poco("android.webkit.WebView").child("android.view.View")[1].child("android.view.View")[4].child("android.view.View").get_text()

print(aim)
print(result)
assert_equal(aim,result,"检查两个字符串是否相等")

实际结果：
1 位群友参团 还差 1 人成团
1 位群友参团 还差 1 人成团
======================================================================
FAIL: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\jyl\pick_tuan\tuanDetail.air\tuanDetail.py", line 76, in <module>
    assert_equal(aim,result,"检查两个字符串是否相等")
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 482, in assert_equal
AssertionError: 1 位群友参团 还差 1 人成团 and 1 位群友参团 还差 1 人成团 are not equal, message: 检查两个字符串是否相等

**预期效果**
断言成功

**python 版本:** `python3.7

**airtest 版本:** `1.2.0，2019-01-15_win64版本
**设备:**
android

**其他相关环境信息**
`windows`

**Comment by Meteorix** [comment]
猜测跟编码有关？试试 
```
print(repr(aim))
print(repr(result))
```

**Comment by jyl4944204** [comment]
> 猜测跟编码有关？试试
> 
> ```
> print(repr(aim))
> print(repr(result))
> ```

谢谢你的回答，试了一下，还是不行

**Comment by Meteorix** [comment]
看下print的输出是什么

**Comment by jyl4944204** [comment]
> 看下print的输出是什么
输出的结果后有一个/r，把/r去掉就可以啦，谢谢你的解答！！！！

**Comment by Meteorix** [comment]
ok~
