### ISSUE TITLE
如何输入支付密码，进行微信支付

### ISSUE THREAD

**Issue by jyl4944204** [AirtestProject/Airtest#307]

**Comment by yimelia** [comment]
部分型号手机在使用 text() 接口 输入密码 时，会输入失败，这是因为手机设置中的 语言与输入法-安全输入 没有打开，打开该选项后就可以使用非系统自带的输入法来输入密码了。

以及，每个应用对于密码的处理各不相同，部分应用是无法直接用text接口来输入密码的（例如银行类app）。此时可以考虑换用截图方式来截密码键盘进行输入

**Comment by jyl4944204** [comment]
> 部分型号手机在使用 text() 接口 输入密码 时，会输入失败，这是因为手机设置中的 语言与输入法-安全输入 没有打开，打开该选项后就可以使用非系统自带的输入法来输入密码了。
> 
> 以及，每个应用对于密码的处理各不相同，部分应用是无法直接用text接口来输入密码的（例如银行类app）。此时可以考虑换用截图方式来截密码键盘进行输入

谢啦
