### ISSUE TITLE
设备端pocoservice进程不断被杀死并重启，但无任何异常信息

### ISSUE THREAD

**Issue by 47045039** [AirtestProject/Airtest#309]
**描述问题bug**
PyCharm运行TestSuite，第一个TestCase正常运行，第二个总是失败。
pc端不断提示：[pocoservice.apk] retrying instrumentation PocoService
设备端pocoservice进程不断被杀死并重启，但无任何异常。

```
（在这里粘贴traceback或其他报错信息）
```
[06:18:56][DEBUG]<airtest.core.android.adb> E:\autotest\AutoTest\Airtest\airtest\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.52:5555 forward --no-rebind tcp:12068 tcp:10080
[06:18:56][DEBUG]<airtest.core.android.adb> E:\autotest\AutoTest\Airtest\airtest\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.52:5555 forward --no-rebind tcp:17736 tcp:10081
[06:18:56][DEBUG]<airtest.core.android.adb> E:\autotest\AutoTest\Airtest\airtest\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.52:5555 shell ps ; echo ---$?---
[pocoservice.apk] retrying instrumentation PocoService
[06:18:57][DEBUG]<airtest.core.android.adb> E:\autotest\AutoTest\Airtest\airtest\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.52:5555 shell pm path com.netease.nie.yosemite ; echo ---$?---
[pocoservice.apk] retrying instrumentation PocoService

**相关截图**

**复现步骤**
运行TestSuite，必现

**预期效果**
正常运行TestSuite

**python 版本:** `python3.72`

**airtest 版本:** `1.0.26`

**设备:**
 - 海信电视8800

**其他相关环境信息**
window7

**Comment by 47045039** [comment]
详细的错误信息见日志文件

**Comment by 47045039** [comment]
设备端如下错误信息：
03-13 18:18:18.354  5272  5272 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
03-13 18:18:18.359  5272  5272 D AndroidRuntime: CheckJNI is OFF
03-13 18:18:18.460  5272  5272 D AndroidRuntime: Calling main entry com.android.commands.am.Am
03-13 18:18:18.462  2348  2433 I ActivityManager: Force stopping com.netease.open.pocoservice appid=10081 user=0: from pid 5272
03-13 18:18:18.463  5272  5272 D AndroidRuntime: Shutting down VM

**Comment by yimelia** [comment]
更新poco到最新版本再试试 `pip install -U pocoui`

**Comment by 47045039** [comment]
重新安装了pocoui，问题未解决。
我是下载源码在pycharm里运行的脚本。
使用 pip install -e 安装airtest相关源码包之后，在AirtestIDE里使用本机python环境运行同样的脚本，状态正常。

**Comment by yimelia** [comment]
请提供一下pocoui版本，你安装的有可能不是最新版本

**Comment by 47045039** [comment]
pocoui版本是 1.0.76

**Comment by yimelia** [comment]
在pycharm里运行的内容，是否与IDE里的**完全一致** ？发一下pycharm的运行命令行+IDE里的运行命令行看看？

**Comment by yimelia** [comment]
现在需要确定的是TestSuite导致的问题，还是poco版本导致的问题。
如果可以的话，最好发一下代码内容，可以把主要内容发出来看看

**Comment by 47045039** [comment]
日志文件无法上传，只能贴出来了

**Comment by 47045039** [comment]
日志文件无法上传，直接贴出来有点大。请访问如下百度云盘链接：
链接: https://pan.baidu.com/s/1B_jfvgbi2HkJYE_NEJ2wgg  提取码: 3f2k

**Comment by 47045039** [comment]
链接: https://pan.baidu.com/s/1-oxnKy3UBiKck5pSFxgrqA 提取码: dqbn
文件无法直接上传，请访问如上百度云盘链接

**Comment by yimelia** [comment]
问题比较奇怪，首先是看到你的环境.txt里，同时安装了poco和pocoui，建议卸载掉那个poco，保留pocoui。
第二个是，pocoui看起来是最新的1.0.76版本，但是在pycharm的log里，看到了一条旧版本里才有的log，最新版本已经删掉了那条log了。。。
======================
先试一下卸载掉poco，然后将pocoui回退到1.0.74版本试试看， `pip install -U pocoui==1.0.74` （如果不成功，可以先卸载掉pocoui再安装）

**Comment by 47045039** [comment]
链接: https://pan.baidu.com/s/10hBl2Ltm4c7joUTm0dtPtg 提取码: 63jr 
卸载了poco，pocoui更新到了1.0.74版本，仍然出现相同问题，pocoservice还是不断被kill

**Comment by 47045039** [comment]
实测发现：
1、pip install -e poco-path，会自动安装pocoui-1.0.75
2、AirtestIDE使用系统python环境运行testsuit，也出现了连续的pocosevice进程重启
3、手动pip install -e pocoui-1.0.76-path，AirtestIDE运行testsuit，pocoservice不再重启

**Comment by 47045039** [comment]
实测发现：
1、源码目录下pip install -e poco-source-path，pocoui版本为1.0.75。
2、AirtestIDE下运行testsuit，设备端pocoservice进程不断重启。
3、手动安装pip install -e pocoui-1.0.76-path后，AirtestIDE可正常运行testsuit。

**Comment by 47045039** [comment]
更新全部源码，并pip install -e 后，使用pycharm运行testsuit不再出现pocoservice被kill的问题。
