### ISSUE TITLE
是否支持APP中的schema url跳转，没有找到提供的API

### ISSUE THREAD

**Issue by clgwlg** [AirtestProject/Airtest#310]
希望能够在APP中通过schema url跳转到指定的页面，框架中是否有对应的API? 或者能否提供一些些建议。
谢谢！

**Comment by Meteorix** [comment]
没有明白你的需求，什么平台，能提供例子吗？

**Comment by mackxu** [comment]
> 没有明白你的需求，什么平台，能提供例子吗？

我猜他是想问，start_app() 支不支持schema url。比如启动微信后直接进入扫一扫

**Comment by codeskyblue** [comment]
查了下，大概是这种
```
adb shell am start -a android.intent.action.VIEW -d "appname://appnamehost" your.package.name
```

From https://stackoverflow.com/questions/31876003/how-to-test-custom-url-scheme-in-android

**Comment by yimelia** [comment]
感谢 @codeskyblue ，如果楼上的回答是 @clgwlg 的需求，那可以这样来写：

`shell(['am', 'start', '后面依次跟上你所需要的参数即可，注意引号和逗号等符号')])`

**Comment by e790a8** [comment]
> 查了下，大概是这种
> 
> ```
> adb shell am start -a android.intent.action.VIEW -d "appname://appnamehost" your.package.name
> ```
> 
> From https://stackoverflow.com/questions/31876003/how-to-test-custom-url-scheme-in-android

请问如何使用airtest在IOS上也用schema启动app？
