### ISSUE TITLE
Please tell me how to use the Python(3.7.2) Package.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#311]
Remove any following parts if does not have details about

**Describe the bug**
Creating a script using the Python Package results in an error.
Please tell me how to use the Python Package.
- Python(3.7.2) 

install package
- pip install selenium
- pip install requests
- pip install bs4

1. airtest configuration information
![이미지 003](https://user-images.githubusercontent.com/46311868/54324744-491e0200-4642-11e9-8fdc-235ad94a2078.png)

2.  ModuleNotFoundError: No module named 'bs4'

![이미지 5](https://user-images.githubusercontent.com/46311868/54325031-951d7680-4643-11e9-82eb-eb3fababae2a.png)

3.  run script result
![이미지 4](https://user-images.githubusercontent.com/46311868/54324826-a619b800-4642-11e9-9cbe-22b44c53793c.png)

**Comment by Meteorix** [comment]
your python path setting is not right. please set it to your python.exe path, reference here: http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#use-local-python-environment-to-run-scripts-trial

**Comment by JJunM** [comment]
> your python path setting is not right. please set it to your python.exe path, reference here: http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#use-local-python-environment-to-run-scripts-trial

Creating a script using the Python Package results in an error.
![이미지 6](https://user-images.githubusercontent.com/46311868/54326843-483d9e00-464b-11e9-916a-8dc5efd9c7df.png)

**Comment by Meteorix** [comment]
![image](https://user-images.githubusercontent.com/3805278/54326947-45d74600-4643-11e9-9e32-1c5485cbdda2.png)
what is this character?

**Comment by JJunM** [comment]
> ![image](https://user-images.githubusercontent.com/3805278/54326947-45d74600-4643-11e9-9e32-1c5485cbdda2.png)
> what is this character?

1. Folder delimiter.

![이미지 7](https://user-images.githubusercontent.com/46311868/54330202-28f93d80-4658-11e9-8e35-a323cf6e7209.png)

2. ModuleNotFoundError: No module named 'airtest'
![이미지 8](https://user-images.githubusercontent.com/46311868/54330269-66f66180-4658-11e9-808e-a3839f0372f1.png)

**Comment by JJunM** [comment]
> ![image](https://user-images.githubusercontent.com/3805278/54326947-45d74600-4643-11e9-9e32-1c5485cbdda2.png)
> what is this character?

I want to create various scripts using Python package in aitestide. An error occurs because you set the Python path. Please tell me how.

python version: 3.7.2
custom python path: D:/Program/Dev/Python/Python37-32/python.exe

![이미지 9](https://user-images.githubusercontent.com/46311868/54331392-2816da80-465d-11e9-8c70-9949000d221c.png)

**Comment by JJunM** [comment]
thanks you
