### ISSUE TITLE
windows上安装 pip install airtest包的时候一直报错，为何啊

### ISSUE THREAD

**Issue by bolt163** [AirtestProject/Airtest#316]
![企业微信截图_15525352142398](https://user-images.githubusercontent.com/25170435/54330457-c05a9280-4650-11e9-8d0b-4ee2cf0c8c8a.png)

【setup.py 是正常的】
![企业微信截图_155253606628](https://user-images.githubusercontent.com/25170435/54330509-f1d35e00-4650-11e9-9eb4-3d339ecb8293.png)

【同样的命令在 mac上 pip install是正常的】

**Comment by Meteorix** [comment]
看起来是你自己搭建的内部pypi？可能是那个版本的代码不对吧

**Comment by bolt163** [comment]
> 看起来是你自己搭建的内部pypi？可能是那个版本的代码不对吧

不是啊，这个源头只是一个镜像而已。。。 macos上也是用的同一个源头去 pip的，windows上的安装很奇怪，一安装就报这个错。。。

**Comment by bolt163** [comment]
这个问题我知道咋回事了，自己解决了，回头我写一下解决方案

**Comment by Meteorix** [comment]
@bolt163 good to hear. 最好能写一下到这个issue，谢谢

**Comment by yimelia** [comment]
这个镜像上的airtest版本好像有点低。。。

**Comment by bolt163** [comment]
【问题的解决方案， 左边是我修改之后的，右边是AirTest源代码包里的，在windows上可能是个bug（参考：https://github.com/mgedmin/check-manifest/commit/e5cb6c55884bad02d5e6ecc7944201767496f
500），AirTest的作者提个merge修复一下吧】

![图片1](https://user-images.githubusercontent.com/25170435/54408613-6e337300-471d-11e9-8bb0-2725300d4d84.png)


【可能的问题】
1.可能是windows 上python2.7 setuptools/pip 版本低所引发的问题
setuptools/pip 修复的方案
https://github.com/arieb/python-testdata/issues/3
https://github.com/arieb/python-testdata/issues/3

**Comment by bolt163** [comment]
> 这个镜像上的airtest版本好像有点低。。。

不是这个镜像版本低的问题，你在windows上测试一下这个库的安装就知道了啊！如果这个库开源出来想走的更远，我觉得windows是绕不过去的吧，毕竟不是每个人都有macosx或习惯用 linux系的来做app开发吧

**Comment by Meteorix** [comment]
@bolt163 多谢反馈，我们查下这个问题

另外说一下，这个问题当然是验证过的，只是在你这种特定情况下才会出现。问版本号也是为了定位问题，所以你上一句话没有必要了

**Comment by yimelia** [comment]
hi @bolt163 
之前我们曾经修复过一个跟这个问题类似的，在特定低版本下才出现的pip安装失败的问题，那是几个版本之前的提交，因此才问你安装的版本是否是最新版，方便我们后续继续查证是否是曾经修过的旧问题。

以及我们测试过windows/linux下py2和py3的安装，但是没有办法验证所有的pip版本，因此airtest并没有限制需要linux环境或是macos下才能使用，windows下的用户占比是更多的。

最后非常感谢你帮忙查证和提交的这个修改，我们已经进行了修改，将在下个版本里放出这个改动。

**Comment by bolt163** [comment]
> hi @bolt163
> 之前我们曾经修复过一个跟这个问题类似的，在特定低版本下才出现的pip安装失败的问题，那是几个版本之前的提交，因此才问你安装的版本是否是最新版，方便我们后续继续查证是否是曾经修过的旧问题。
> 
> 以及我们测试过windows/linux下py2和py3的安装，但是没有办法验证所有的pip版本，因此airtest并没有限制需要linux环境或是macos下才能使用，windows下的用户占比是更多的。
> 
> 最后非常感谢你帮忙查证和提交的这个修改，我们已经进行了修改，将在下个版本里放出这个改动。


=================================================================
另外我发现airtest可能对 python2.7的兼容性不是特别好，python2.7下安装完之后跑不动，经常报一堆莫名其妙的问题，包括 open-cv 版本也不太对，不应该在 requirements里面写死一个 版本...

同样的airtest 1. 0.26 我在python3.5下安装没有问题，可以正常跑

**Comment by yimelia** [comment]
@bolt163 
opencv的那个问题，我们最近几天在测试和优化相关的代码，在下个版本中可能会去除对opencv-contrib-python这个库的依赖，这样会减少很多安装时这个库的兼容性问题（之前在python3.7中，opencv-contrib可能会安装失败等）。在当前版本中，非python3.7环境下，建议直接安装3.2.0.7版本，`pip install opencv-contrib-python==3.2.0.7`，这个版本适配性较好。

但是其他的问题，例如python2.7下无法正常运行以及有报错的问题，很可能是代码bug，需要发一下相关的报错信息方便我们修复。

**Comment by bolt163** [comment]
> @bolt163
> opencv的那个问题，我们最近几天在测试和优化相关的代码，在下个版本中可能会去除对opencv-contrib-python这个库的依赖，这样会减少很多安装时这个库的兼容性问题（之前在python3.7中，opencv-contrib可能会安装失败等）。在当前版本中，非python3.7环境下，建议直接安装3.2.0.7版本，`pip install opencv-contrib-python==3.2.0.7`，这个版本适配性较好。
> 
> 但是其他的问题，例如python2.7下无法正常运行以及有报错的问题，很可能是代码bug，需要发一下相关的报错信息方便我们修复。

2.7感觉从安装到使用过程感觉都一直在躺坑，我是python 2.7.5; 我现在先在python3.4下跑，回头我搞回 python2.7来复现一下相关的问题再发上来(本来想分析一下，暂时时间不允许)，

**Comment by yimelia** [comment]
ok，感谢，我们后续也会增加更多对py2的测试工作
