### ISSUE TITLE
I want to create various scripts using Python package in aitestide. 

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#317]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

I want to create various scripts using Python package in aitestide. 
An error occurs because you set the Python path. Please tell me how.

python version: 3.7.2
airtest version:** `1.2.0
airtestide Settings> custom python path: D:/Program/Dev/Python/Python37-32/python.exe

python pip install
selenium, bs4, airtest, poco, requests, etc

[error log]

![이미지 9](https://user-images.githubusercontent.com/46311868/54333382-a1b2c680-4665-11e9-964b-d2793dcf414b.png)

**Comment by Meteorix** [comment]
```
pip install airtest-selenium
```
