### ISSUE TITLE
webview poco 解析时不时的解析不出来，感觉无规律

### ISSUE THREAD

**Issue by wuqingabc** [AirtestProject/Airtest#324]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤
环境： Mac Mojava，夜神模拟器

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
用 poco 解析 UI 结构，结构中包含 webview，经常会时不时解析不出结构信息
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

这是解析不出来的情况：
![image](https://user-images.githubusercontent.com/4350871/54421384-93969180-46c9-11e9-9540-817f30a85fcf.png)

![image](https://user-images.githubusercontent.com/4350871/54421431-add06f80-46c9-11e9-8f0b-e06d5afd3879.png)

如下为正常解析的情况：
![image](https://user-images.githubusercontent.com/4350871/54421639-14ee2400-46ca-11e9-93e0-3b9c6ab659db.png)

![image](https://user-images.githubusercontent.com/4350871/54421653-1d465f00-46ca-11e9-92ec-9ed0ef2e913c.png)

**复现步骤**

启动代码：
![image](https://user-images.githubusercontent.com/4350871/54421737-4c5cd080-46ca-11e9-85e1-af5f3184fccf.png)

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`
Python 3.6.1

**airtest 版本:** `1.0.69`
1.2.0

**设备:**
 - 型号: 夜神模拟器 Mac 版本
 - 系统: 4.4
 - (别的信息)

**其他相关环境信息**
Mac Mojava

**Comment by yimelia** [comment]
请问解析失败是同样的环境+同样的模拟器版本下，偶尔出现解析失败的情况，还是在特定环境/条件下会出现的？
顺便可以提供一下使用的webview实现内核，参考[文档](http://airtest.netease.com/docs/cn/6_poco_framework/poco_webview.html#id2)这里查看一下当前设置是什么。

**Comment by wuqingabc** [comment]
在锤子 T1 真机下也是同样的情况；360N4S 没有此情况。大概率出现解析失败的情况，环境和条件没有找到规律。夜神模拟器默认webview内核的情况下有这个情况，安装了Android System WebView v72.0.3626.121 后依旧还是出现这种情况。

我真机和模拟器的开发者模式里面，都没有找到 WebView 实现这个选项。

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/issues/336#issuecomment-478410363 同样的问题，目前只能绕过。如果以后有解决方案，再讨论吧

**Comment by xufki2-webgiw-qeDsop** [comment]
Thanks
