### ISSUE TITLE
不同分辨率的设备下进行位置计算

### ISSUE THREAD

**Issue by 3638836363** [AirtestProject/Airtest#327]
airtest\core\cv.py  ：263
        if image_resolution:
            predict_x_radius = int(image_wh[0] * screen_resolution[0] / (2 * image_resolution[0])) + cls.DEVIATION
            predict_y_radius = int(image_wh[1] * screen_resolution[1] / (2 * image_resolution[1])) + cls.DEVIATION

cls.DEVIATION 默认值为100

**Comment by 3638836363** [comment]
偏差值默认是100 这个100有具体原因么

**Comment by 3638836363** [comment]
get_predict_area(cls, record_pos, image_wh, image_resolution=(), screen_resolution=()):

**Comment by rockywhisper** [comment]
@3638836363  
你好，这里涉及到对图像识别结果区域的预测。
在跨分辨率识别时，UI面临一定的位置偏差，这就涉及到偏差容忍距离的设定DEVIATION。

如果这个值过大，可能导致预测范围很大，预测本身就没有了意义。
在实际情况中，大部分跨分辨率的位置移动偏差都在100以内，所以这里设为了100。

**Comment by 3638836363** [comment]
@

> @3638836363
> 你好，这里涉及到对图像识别结果区域的预测。
> 在跨分辨率识别时，UI面临一定的位置偏差，这就涉及到偏差容忍距离的设定DEVIATION。
> 
> 如果这个值过大，可能导致预测范围很大，预测本身就没有了意义。
> 在实际情况中，大部分跨分辨率的位置移动偏差都在100以内，所以这里设为了100。
record_pos=(0.295, 1.006) 如果1.006是指超过了边界么？

**Comment by 3638836363** [comment]
> @3638836363
> 你好，这里涉及到对图像识别结果区域的预测。
> 在跨分辨率识别时，UI面临一定的位置偏差，这就涉及到偏差容忍距离的设定DEVIATION。
> 
> 如果这个值过大，可能导致预测范围很大，预测本身就没有了意义。
> 在实际情况中，大部分跨分辨率的位置移动偏差都在100以内，所以这里设为了100。
Template(r"tpl1552632923088.png", record_pos=(0.295, 1.006), resolution=(1080, 2244))
858.5999999999999 2046.48
image_wh is:
(165, 49)
(1080, 1920)
(1080, 2244)
(676.5999999999999, 1926.48, 1040.6, 2166.48)

**Comment by 3638836363** [comment]
> @3638836363
> 你好，这里涉及到对图像识别结果区域的预测。
> 在跨分辨率识别时，UI面临一定的位置偏差，这就涉及到偏差容忍距离的设定DEVIATION。
> 
> 如果这个值过大，可能导致预测范围很大，预测本身就没有了意义。
> 在实际情况中，大部分跨分辨率的位置移动偏差都在100以内，所以这里设为了100。

在设备1（1080,2244）编写脚本
在设备2（1080,1920）回放
x, y = cls.get_predict_point(record_pos, screen_resolution)

image_wh = (165, 49)
计算x,y= 858.5999999999999 2046.48

area = (x - predict_x_radius, y - predict_y_radius, x + predict_x_radius, y + predict_y_radius)
计算area=(676.5999999999999, 1926.48, 1040.6, 2166.48)
是否超过了当前屏幕

**Comment by rockywhisper** [comment]
@3638836363 
当然是有可能超过呀，超过也没关系，在截取预测区域的时候做了安全处理就行。

**Comment by 3638836363** [comment]
> @3638836363
> 当然是有可能超过呀，超过也没关系，在截取预测区域的时候做了安全处理就行。

您所指的安全处理是？是否已经实现了

**Comment by rockywhisper** [comment]
@3638836363 
当然已经做了呀。
![image](https://user-images.githubusercontent.com/8188879/54576553-ae536800-4a33-11e9-8e79-dd2e07929202.png)
![image](https://user-images.githubusercontent.com/8188879/54576571-bb705700-4a33-11e9-9c1e-bb23d361fe82.png)

**Comment by 3638836363** [comment]
> @3638836363
> 当然已经做了呀。
> ![image](https://user-images.githubusercontent.com/8188879/54576553-ae536800-4a33-11e9-8e79-dd2e07929202.png)
> ![image](https://user-images.githubusercontent.com/8188879/54576571-bb705700-4a33-11e9-9c1e-bb23d361fe82.png)
嗯 好的谢谢
