### ISSUE TITLE
I want to send an email automatically after the test runs.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#328]
Remove any following parts if does not have details about

**Describe the bug**

I want to send an email automatically after the test runs. The test results storage location changes dynamically, and you can not set the email attachment path. Is there any way to set the attachment path?

The test run and the generated test results folder will continue to change dynamically.
With this value, it is difficult to specify the file path to send the mail.
Is there a way to dynamically flip the file path and attach a test result file to an email each time you run a test?

+ phthon
import smtplib
from email.message import EmailMessage
(...)
filepath = '/log.html'

![이미지 2](https://user-images.githubusercontent.com/46311868/54581250-2e3afb80-4a4f-11e9-880b-6e8a857d7eac.png)

**Comment by EraChen233** [comment]
How do you run the test to get these folders?
If you run the test on AirtestIDE, you can export report as shown below after the test is finished. In this way, you can select the folder for the log and report.

![image](https://user-images.githubusercontent.com/5961185/54584495-79a2d900-4a52-11e9-8660-1372cc0a04fb.png)

**Comment by JJunM** [comment]
> How do you run the test to get these folders?
> If you run the test on AirtestIDE, you can export report as shown below after the test is finished. In this way, you can select the folder for the log and report.
> 
> ![image](https://user-images.githubusercontent.com/5961185/54584495-79a2d900-4a52-11e9-8660-1372cc0a04fb.png)

![image](https://user-images.githubusercontent.com/46311868/54588504-8e896780-4a66-11e9-84d8-69078e71b230.png)

I am wondering if I can specify the file attachment path settings for the email by replacing the file path generated when the test was run.

**Comment by EraChen233** [comment]
The picture you pasted shows that you only run test in AirtestIDE but did not export report. It 's two steps, run test and export report.

**Comment by EraChen233** [comment]
If you want to run your test, export report and send a email automatically, we suggest you run Airtest script with python. Like:

``` python
import subprocess
# run test
cmd = ["airtest", "run", your_air, "--device", your_device, "--log", your_log_dir]
runTest = subprocess.Popen(cmd)
runTest .wait()

# export report
import subprocess
# run test
cmd2 = ["airtest", "report", your_air,  "--log_root", your_log_dir, "--outfile", your_report_dir+ 'log.html', "--lang", "zh"]
runReport = subprocess.Popen(cmd2)
runReport .wait()

# send email
# ......
```

Here's the detail about how to run scripts using command line.
http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#running-scripts-using-the-command-line

**Comment by JJunM** [comment]
> If you want to run your test, export report and send a email automatically, we suggest you run Airtest script with python. Like:
> 
> ```python
> import subprocess
> # run test
> cmd = ["airtest", "run", your_air, "--device", your_device, "--log", your_log_dir]
> runTest = subprocess.Popen(cmd)
> runTest .wait()
>

When I run a script with Run Script in AirTestIDE, I set up a setting and created a dynamic folder in the Default Log Path path, and saved the log.

If you send test results by email, you need to set the attachment path. The log path of the test results was dynamically changed and the attachment path could not be set.

Thank you for telling me how I can specify where to save the logs when running tests with the cmd command.

Run runscript with airtestide Is there any way to change the setting and optionally specify where to save the log?


> # export report
> import subprocess
> # run test
> cmd2 = ["airtest", "report", your_air,  "--log_root", your_log_dir, "--outfile", your_report_dir + 'log.html', "--lang", "en"]
> runReport = subprocess.Popen(cmd2)
> runReport .wait()
> 
> # send email
> # ......
> ```
> 
> Here's the detail about how to run scripts using command line.
> http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#running-scripts-using-the-command-line

**Comment by yimelia** [comment]
hi @JJunM 
http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#airtest
`Default Log Path` is used to specify the log directory when AirtestIDE is running scripts.

**Comment by yimelia** [comment]
or just try [auto_setup](https://airtest.readthedocs.io/en/latest/all_module/airtest.core.api.html#airtest.core.api.auto_setup)

like this:
```
auto_setup(__file__, logdir=r"D:\test\log", devices=[
        "Android:///?cap_method=javacap&ori_method=adbori",
    ])
```
