### ISSUE TITLE
点我点我！新增特性投票【Click Me! New Feature Voting】

### ISSUE THREAD

**Issue by Meteorix** [AirtestProject/Airtest#33]
大家好，感谢大家对Airtest Project的兴趣。

我们开发团队在考虑后续的开发计划，目前的开发方向包括：
* iOS支持
* Windows应用的控件级自动化
* Web应用的控件级自动化，基于Selenium的脚本录制
* Android模拟器的支持

希望各位同学们参与讨论，以上几项直接在对应楼层**点大拇指**，其余的**新开楼层**。

Hi all, thanks for you interest in Airtest Project !

Our dev team is making future development plan, currently including:
* iOS support
* Windows desktop automation on UI widget layer
* Web page's automation on UI widget layer, Selenium based tests recording
* Android emulator support

Please feel free to comment here. Click the thumbs up if the feature is already listed.

**Comment by sosocgx** [comment]
有Mac的支持吗？ 比如在IDE里面调试运行时，也可以执行测试脚本，不需要安装到测试手机。

**Comment by uniwang** [comment]
iOS支持

**Comment by bittern** [comment]
iOS支持 +1   期望优先支持，这样移动端就全了

**Comment by supreye** [comment]
web

**Comment by Meteorix** [comment]
Android模拟器支持
Android emulator support

**Comment by Meteorix** [comment]
更新一下最新进展：

* iOS支持 
> 已经开放测试：https://github.com/AirtestProject/iOS-Tagent

* Windows应用的控件级自动化
> 开发中

* Web应用的控件级自动化，基于Selenium的脚本录制
> 已经开放测试：http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_advanced_features/4_selenium.html

* Android模拟器的支持
> 已发布： http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html#

欢迎大家试用，并给我们反馈

Latest updates:

* iOS support
> Open beta: https://github.com/AirtestProject/iOS-Tagent

* Windows desktop automation on UI widget layer
> under development

* Web page's automation on UI widget layer, Selenium based tests recording
> Open beta: http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_advanced_features/4_selenium.html (maybe you need google translate for now)

* Android emulator support
> Already supported: http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html#  (maybe you need google translate for now)

Please try these new features and give us feedbacks. Thanks!

**Comment by wanghaisheng** [comment]
zan
Windows应用的控件级自动化
