### ISSUE TITLE
断言截图失败

### ISSUE THREAD

**Issue by ceshi2018** [AirtestProject/Airtest#330]
断言截图失败，一直提示不在框内，touch截图没问题
![1](https://user-images.githubusercontent.com/42505276/54670730-45511a80-4b2f-11e9-96e5-f746a624c4ab.JPG)

**Comment by yimelia** [comment]
运行环境，连的是手机还是windows窗口？

**Comment by Meteorix** [comment]
请按照issue template填写问题，不然我们也无法帮到你
