### ISSUE TITLE
图像识别多个相同对象问题

### ISSUE THREAD

**Issue by ant0x00** [AirtestProject/Airtest#331]
**需求，功能增强**

**图像识别多个相同对象问题**
比如在选择日期时，需要尽可能往后面选择
如图，首先识别多个 ￥5999 的日期，然后选取最后一个

**相关截图**
![calendar](https://user-images.githubusercontent.com/2776620/54673944-5a7d7780-4b36-11e9-9318-6b51df838d4c.png)

**预期效果**
是不是可以在touch()方法中增加相关功能？

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`

**设备:**
 - 型号: 一加6
 - 系统: android 9.0

**其他相关环境信息**
windows 64bit

**Comment by yimelia** [comment]
如果要用airtest的话，目前可选的方案有：
1. 目前已经有提供接口`find_all` 可以返回所有查找出来的结果，然后再选最后一个即可
2. 参考[文档](http://airtest.netease.com/docs/cn/5_airtest_framework/2_script_settings.html#target-pos)，可以识别出一片区域，然后选择要点击哪个位置，来控制点到哪个对象
3. 图像识别方案在比较精细的小文字上，有比较大的失败率，可能识别到的结果不如预期，比如你提出来的场景下建议尝试用poco来选取，会很容易而且准确度很高。

**Comment by ant0x00** [comment]
哎呀，谢谢 @yimelia，没好好看文档
