### ISSUE TITLE
求助connect_device远程连接ios设备

### ISSUE THREAD

**Issue by mackxu** [AirtestProject/Airtest#332]
**描述问题bug**
目前在windows上做开发，用 wdaproxy为苹果手机做的代理。
使用接口init_device()可以正常工作, 代码如下:
 `init_device(platform="IOS", uuid='192.168.123.90:8100')`

请教下使用connect_device远程链接苹果手机的正确姿势。

**Comment by yimelia** [comment]
应该是类似于 `connect_device("IOS:///192.168.123.90:8100")` ，如果不对的话也没事，先用IDE连上这台手机，点一下运行按钮，log窗口里会显示出完整可用的命令行，其中的 `--device IOS:///XXX` 就是对应的设备，把IOS那句代码复制出来就可以在connect_device接口当中用了。

**Comment by mackxu** [comment]
> 应该是类似于 `connect_device("IOS:///192.168.123.90:8100")` ，如果不对的话也没事，先用IDE连上这台手机，点一下运行按钮，log窗口里会显示出完整可用的命令行，其中的 `--device IOS:///XXX` 就是对应的设备，把IOS那句代码复制出来就可以在connect_device接口当中用了。

谢谢，有用
