### ISSUE TITLE
使用Yosemite输入法之后，text输入了文本，之后如何发送出去呢？

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/Airtest#334]
Remove any following parts if does not have details about

**Describe the bug**

**To Reproduce**
1. 文本输入框输入文本
2. 之后如何发送出去?默认输入法是有发送按键的，Yosemite没有

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Comment by yimelia** [comment]
请参考[文档](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#id11)

**Comment by xin7c** [comment]
尝试使用：

dev = device()  
dev.yosemite_ime.code("2")  

运行报错：  

> 'YosemiteIme' object has no attribute 'code'

**Comment by xin7c** [comment]
shell("am broadcast -a ADB_EDITOR_CODE --ei code 2")    
亲测，这一句好用。

**Comment by yimelia** [comment]
@xin7c 那个code接口是后来加的，如果你使用的IDE或airtest版本过低，就确实没有这个接口。
建议升级一下版本

**Comment by xin7c** [comment]
> @xin7c 那个code接口是后来加的，如果你使用的IDE或airtest版本过低，就确实没有这个接口。
> 建议升级一下版本

多谢
