### ISSUE TITLE
测试手机wap页面时，有时候控件可以用poco识别出来，有时候又显示为webview

### ISSUE THREAD

**Issue by newlife099** [AirtestProject/Airtest#336]
测试手机wap页面时，有时候控件可以用poco识别出来，有时候又显示为webview，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/30133926/54910536-7ebac900-4f27-11e9-9fc8-27c4ba0a0e2d.png)

**Comment by yimelia** [comment]
可以参考下这个[文档](http://airtest.netease.com/docs/cn/6_poco_framework/poco_webview.html)
很多app是混合了webview和原生app的，如果是webview需要单独设置一下

**Comment by newlife099** [comment]
已经设置了还是不行

**Comment by rockywhisper** [comment]
@newlife099  
方便提供一下手机型号吗？

可以在设置google webview渲染后重启下手机，然后使用IDE再试试看。
如果还不行，可以考虑更换一台手机。经过实际测试，设置了google webview渲染后一般都可以正常稳定解析的。

**Comment by newlife099** [comment]
手机型号：oppo r11

**Comment by Meteorix** [comment]
webview的兼容性确实不太好，Android厂商各自实现比较乱。如果不考虑兼容性问题，建议换台手机或者模拟器来做自动化
