### ISSUE TITLE
how to apply OCR ????

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#338]
There is an OCR python Live Roy developed by my company.
I want to apply to aitest and use it. Is there a way?

**Comment by Meteorix** [comment]
2 steps:

1. use your local python to run the script, find the settings in IDE

![image](https://user-images.githubusercontent.com/3805278/55204608-a56c4e80-520a-11e9-9f83-4e4987d26e3e.png)

2. then you case use any python library installed to your local python environment

**Comment by JJunM** [comment]
> 2 steps:
> 
> 1. use your local python to run the script, find the settings in IDE
> 
> ![image](https://user-images.githubusercontent.com/3805278/55204608-a56c4e80-520a-11e9-9f83-4e4987d26e3e.png)
> 
> 1. then you case use any python library installed to your local python environment

Can I execute a test with the airtest command on the text extracted by OCR?

**Comment by Meteorix** [comment]
definitely, you can. airtest is just a python library. use any airtest command like normal python function.

**Comment by JJunM** [comment]
> 물론 가능합니다. airtest는 파이썬 라이브러리 일뿐입니다. 일반적인 파이썬 함수처럼 airtest 명령을 사용하십시오.

Does it work even if you enter as below?
ex: touch(ocr_txt)

**Comment by JJunM** [comment]
> definitely, you can. airtest is just a python library. use any airtest command like normal python function.

Does it work even if you enter as below?
ex: touch(ocr_txt)

**Comment by Meteorix** [comment]
maybe you orc function should return position & txt, then you can either
```
touch(position)
```

or use poco

```
poco(text=txt).click()
```

**Comment by JJunM** [comment]
> 어쩌면 orc 함수가 position & txt를 반환해야합니다.
> 
> ```
> touch(position)
> ```
> 또는 poco 사용
> 
> ```
> poco(text=txt).click()
> ```

Apply OCR to the screen to be tested and save the character of the value.

Operate the app by entering aritest api for the character position value.

There is a problem that does not work according to the resolution of the screen.

**Comment by Meteorix** [comment]
you can get the resolution 
```
device().get_current_resolution()
```
