### ISSUE TITLE
真机测试，\airtest\core\api.py 里报错误 'NoneType' object has no attribute 'home'

### ISSUE THREAD

**Issue by Ddd1101** [AirtestProject/Airtest#339]
配置环境： win10  anaconda3_5.3.0  python3.7  / poco pocoui airtest 都装了

  File "D:\Anaconda3\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\airtest\core\api.py", line 240, in home
    G.DEVICE.home()
AttributeError: 'NoneType' object has no attribute 'home'

**Comment by EraChen233** [comment]
请确认是否使用USB数据线，把手机连接到电脑，并且在命令行运行

```adb devices```

能获取到手机设备信息

**Comment by Meteorix** [comment]
连接设备的代码没写？```auto_setup()``` or ```connect_device(...)```
