### ISSUE TITLE
airtest通过命令批量执行脚本时中文的用例集会报错找不到路径，编码格式有问题

### ISSUE THREAD

**Issue by jeniva** [AirtestProject/Airtest#341]
环境：airtest版本应该是最新的，1.0.26，Python版本是27，Windows 10，（都没执行起来应该和手机没关系）是通过Pycharm调试执行的。
PyCharm 2018.3.4 (Professional Edition)
Build #PY-183.5429.31, built on January 29, 2019
Licensed to Nss Im
Subscription is active until November 7, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
问题：通过变量一个中文命名的txt文件，里面有用例的顺序，用例名也是中文的.air，执行过程中编码格式报错，设置了编码格式后找不到路径，设置了很多编码格式都不成功，支持中文的用例名执行吗？我的错误提示下面的信息，请帮忙看一下谢谢：
FAILED (errors=1)
line1 =回放.air
filename=回放 <type 'unicode'>
airtest run "D:\AirTest\checklist自动化\回放.air" --device android://127.0.0.1:5037/FA6950304672 --log "D:\AirTest\checklist自动化\log\jeniva\20190401162243\回放"
save log in 'D:\AirTest\checklist鑷姩鍖朶log\jeniva\20190401162243\鍥炴斁'
[04:22:47][DEBUG]<airtest.core.android.adb> D:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s FA6950304672 wait-for-device
[04:22:48][DEBUG]<airtest.core.android.adb> D:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s FA6950304672 shell getprop ro.build.version.sdk
======================================================================
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\airtest\cli\runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "D:\Python27\lib\site-packages\airtest\cli\runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root)
  File "D:\Python27\lib\site-packages\airtest\core\api.py", line 115, in auto_setup
    set_logdir(logdir)
  File "D:\Python27\lib\site-packages\airtest\core\helper.py", line 62, in set_logdir
    os.mkdir(dirpath)
WindowsError: [Error 3] : u'D:\\AirTest\\checklist\u95bc\u5949\u4e9c\u6fee\u2545\u5d20\u93c8\u79ceog\\jeniva\\20190401162243\\\u95b8\u30e7\u505e\u93c2?'

----------------------------------------------------------------------
Ran 0 tests in 0.538s

FAILED (errors=1)
Traceback (most recent call last):
  File "D:\AirTest\case\report.py", line 119, in <module>
    for subdir in os.listdir(logdir):
WindowsError: [Error 3] : 'D:\\AirTest\\checklist\xe8\x87\xaa\xe5\x8a\xa8\xe5\x8c\x96\\log\\jeniva\\20190401162243/*.*'

**Comment by EraChen233** [comment]
这个问题不是编码格式的问题，是因为文件路径不存在。

先判断这个logdir是否存在，如果不存在，创建文件夹。

![image](https://user-images.githubusercontent.com/5961185/55317312-d4045680-54a2-11e9-88c3-2a86bc6580b4.png)

**Comment by jeniva** [comment]
![image](https://user-images.githubusercontent.com/8514029/55322753-ca352000-54af-11e9-892e-03ff57cd59b8.png)
因为 路径变成这样了才找不到啊，就是编码格式引起的，英文的我已经调试成功过的，换成中文的就失败了

**Comment by EraChen233** [comment]
方便把你的脚本贴出来吗？

**Comment by Meteorix** [comment]
看起来就是python的中文编码问题，建议换成python3.6，对中文处理比较简单些

**Comment by jeniva** [comment]
#coding:utf-8
import os
import time
import io


class AirtestRun(object):
    def __init__(self, user):
        self.user = user

    def airtest_run(self,project_path, devices, excute_time, user, testplan=""):
        # 报告存放地址
        logpath = os.path.join(project_path, "log", user, excute_time)
        if not os.path.exists(logpath):
            os.makedirs(logpath)
        # logpath=logpath.decode('gbk').encode('utf-8')
        print ("logpath=",logpath)
        # 获取所有用例集
        if testplan != "":
            print (u"存在测试计划")
            for line in io.open(os.path.join(project_path, testplan)):
                line = line.strip("\n")
                if not line:
                    break
                print ("line1 =" , line)
                filename = line.replace('.air', '')
                print ("filename="+filename, type(filename))
                cmd = "airtest run " + '"' +os.path.join(project_path,line) + '"'+ " --device android://127.0.0.1:5037/" + devices\
                      + " --log " + '"' +os.path.join(logpath,filename) + '"'
                # cmd = "D:\AirtestIDE_2019-01-15_py3_win64\AirtestIDE runner "  + os.path.join(project_path,
                #                                           line) + " --device android://127.0.0.1:5037/" + devices \
                #       + " --log "  + os.path.join(logpath, filename)
                print (cmd)
                os.system(cmd)
        else:
            for f in os.listdir(project_path):
                if f.endswith("air"):
                    f = os.path.join(project_path, f)
                    if os.path.isdir(f):
                        filename=f.split('\\')[-1].split(".")[0]
                        cmd = "airtest run " + f + " --device android://127.0.0.1:5037/" + devices + " --log "+os.path.join(logpath, filename)
                        print (cmd)
                        os.system(cmd)

        return logpath


if __name__ == '__main__':
    test = AirtestRun('jeniva')
    logpath = test.airtest_run("D:\\AirTest\\checklist自动化","FA6950304672",time.strftime('%Y%m%d%H%M%S'),'jeniva','测试计划.txt')
    # print "logpath="+logpath
    os.system("python D:\\AirTest\\case\\report.py "+logpath)

**Comment by jeniva** [comment]
上面是我的代码，文件夹是中文命名的，然后有个测试计划的txt和几个中文文件夹的用例。我试了3.6的python,可能我电脑Python环境太多了，我把27的重新命名后，用3.6的python配置环境变量后执行的时候提示'airtest' 不是内部或外部命令，也不是可运行的程序，不知道怎么解决

**Comment by EraChen233** [comment]
切换python版本后，要重新安装各个依赖
```
pip install airtest
```

**Comment by jeniva** [comment]
安装了，重新安装提示我已经安装了，而且里面有airtest文件,你可以用我的代码试一下python27的，是我代码需要在哪设置一下编码格式吗？还是你们没有兼容
![image](https://user-images.githubusercontent.com/8514029/55323504-ce623d00-54b1-11e9-9adf-5b9b911aaf4d.png)

**Comment by EraChen233** [comment]
> 安装了，重新安装提示我已经安装了，而且里面有airtest文件,你可以用我的代码试一下python27的，是我代码需要在哪设置一下编码格式吗？还是你们没有兼容
> ![image](https://user-images.githubusercontent.com/8514029/55323504-ce623d00-54b1-11e9-9adf-5b9b911aaf4d.png)



这里描述不清楚。你的文字提到的你用的是python27，但是截图却是python36

可以把完整的错误信息截图贴出来吗？

**Comment by jeniva** [comment]
你说Python36需要重新安装，我截图说我安装了，但是还是有提示'airtest' 不是内部或外部命令，也不是可运行的程序。现在有两个问题：1、Python36我提示“'airtest' 不是内部或外部命令，也不是可运行的程序”，已安装，对应的Python36也配置了环境变量还需要配置什么才行？2、Python27的中文编码格式问题，第一次留言就是对应的错误信息，而且我的代码也贴出来的。错误日志看不出来的话你用代码运行看看有什么问题？麻烦你们看下怎么解决

**Comment by jeniva** [comment]
![image](https://user-images.githubusercontent.com/8514029/55369501-6b13f180-5529-11e9-8651-9a3646d383ea.png)
python27运行的截图

**Comment by EraChen233** [comment]
- 问题1、对于python36，airtest的安装需要装在python36的情况下，按照你的理解，最简单的方法就是环境变量设置成36，然后重新pip install

- 问题2，关于python2环境下，中文乱码问题，你可以试一下
logpath.decode('utf8').encode('GBK')

![image](https://user-images.githubusercontent.com/5961185/55370657-bfb96b80-552d-11e9-89af-104a7e3b9827.png)


最后，为了后续减少此类问题的发生，我们建议你把开发环境切换成python 36

**Comment by jeniva** [comment]
问题1、对于python36，airtest的安装需要装在python36的情况下，按照你的理解，最简单的方法就是环境变量设置成36，然后重新pip install------------------我是这样做的，但是还是出现了'airtest' 不是内部或外部命令，也不是可运行的程序，这个问题怎么解决你并没有说清楚？

问题2，关于python2环境下，中文乱码问题，你可以试一下
logpath.decode('utf8').encode('GBK')---------------我添加了这个，还是会报错
![image](https://user-images.githubusercontent.com/8514029/55370963-fd6ac400-552e-11e9-955d-d2ff360a777d.png)

**Comment by jeniva** [comment]
我用Python36可以了正常执行生成报告了，改动，但是如果你们有空的话最好是兼容一下Python27的哈，因为很多人还是用python27的

**Comment by YuanjieWang** [comment]
> 我用Python36可以了正常执行生成报告了，改动，但是如果你们有空的话最好是兼容一下Python27的哈，因为很多人还是用python27的

python官方已声明今年将放弃维护python2😂
