### ISSUE TITLE
调用本地环境的第三方模块bs4 一直失败  python IDE调用 是成功的

### ISSUE THREAD

**Issue by xiaoxuanxuanlady** [AirtestProject/Airtest#342]
Remove any following parts if does not have details about

**Describe the bug**

[DEBUG][Start debugging...]
D:\AirtestIDE_2019-01-15_py3_win64\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 54dc383c0804 wait-for-device
D:\AirtestIDE_2019-01-15_py3_win64\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 54dc383c0804 shell getprop ro.build.version.sdk
Traceback (most recent call last):
  File "app\widgets\code_runner\run_manager.py", line 206, in my_exec
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bs4'
python本地环境3.7 设置里面已经填写了python.exe路径。
**To Reproduce**
1. python3.7安装bs4.. (python IDE调用bs4是成功的)
2. airtest设置python.exe路径保存。重启airtest。
3.   选中 from bs4 import BeautifulSoup   。只运行选中代码。
4. 不存在bs4

**Expected behavior**

**Screenshots**

![debug](https://user-images.githubusercontent.com/48239803/55329098-66ffb980-54c0-11e9-8dd7-d35fcddff514.png)
![设置](https://user-images.githubusercontent.com/48239803/55329236-b0500900-54c0-11e9-9d19-a7406984c79b.png)

**python version:** `python3.7`

**airtest version:** `1.2.0
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: 小米5plus
 - OS: [e.g. Android 7.0]
 - more information if have

**Additional context**
换了两台电脑  同样的环境同样的报错

**Comment by xiaoxuanxuanlady** [comment]
教程不是说自带3.6吗   查了下本地电脑自带的是python2.7  坑啊

**Comment by EraChen233** [comment]
你可以先看一下你配置的python环境下，是否存在airtest文件夹，目录为：
>D:\python3.7\Lib\site-packages

**Comment by xiaoxuanxuanlady** [comment]
> 你可以先看一下你配置的python环境下，是否存在airtest文件夹，目录为：
> 
> > D:\python3.7\Lib\site-packages

你好   我本地python3.7   D:\python3.7\Lib\site-packages   不存在airtest文件夹

**Comment by EraChen233** [comment]
不存在文件夹的意思是，你的本地环境，也就是 `D:\python3.7\python.exe`，没有安装airtest

所以你可以使用命令行，切换到这个python版本，重新安装airtest等依赖

**Comment by xiaoxuanxuanlady** [comment]
> 不存在文件夹的意思是，你的本地环境，也就是 `D:\python3.7\python.exe`，没有安装airtest
> 
> 所以你可以使用命令行，切换到这个python版本，重新安装airtest等依赖

x刚刚安装了  airtest有了  poco和airtest 都安装了  还是报错 bs4不存在

**Comment by EraChen233** [comment]
那同样的目录下，可以找到 bs4 的安装文件夹吗？

**Comment by xiaoxuanxuanlady** [comment]
不可以  没有
bs4文件夹  我安装别的文件夹了    这个文件夹有个beautifulsoup4-4.7.0-py3.7.egg

**Comment by EraChen233** [comment]
那么在命令行打开`D:\python3.7\python.exe`环境，执行 `from bs4 import BeautifulSoup`是否有报错信息？类似下图
![image](https://user-images.githubusercontent.com/5961185/55331740-7da90f00-54c6-11e9-98dc-ae88e7694ce1.png)

**Comment by xiaoxuanxuanlady** [comment]
![image](https://user-images.githubusercontent.com/48239803/55333619-40468080-54ca-11e9-91aa-af3b49cd07dd.png)
哎   pip显示已经安装了
