### ISSUE TITLE
为什么script中的图片和实际程序的截图识别吻合度相差很大？

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#346]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
使用airtestIDE直接连接整个windows屏幕。

分别在不同分辨率下进行测试图像识别（用了[#4](https://github.com/AirtestProject/Airtest/issues/4)提到的方法之后，使用运行很好，没有问题）

之前发现如果连接整个屏幕的话，script框内的图片也会被识别到

但是在不同分辨率下运行之后，我发现对于**其他程序识别度99.9%的图片，在script框内的识别度只有40-60%**

明明script框里的图片和实际程序的截图应该是一样的，为什么识别度会不一样呢？

**Comment by yimelia** [comment]
建议增加图片来帮助我们更好地理解你的提问
