### ISSUE TITLE
The process (adb.exe) does not terminate automatically once finished running the script.

### ISSUE THREAD

**Issue by DanielCYJ94** [AirtestProject/Airtest#349]
Hi, I met with a problem that if I run my script as in below, it will keep grow the adb.exe processes. Can I know how can I terminate all processes once I finish the for loop (for SN in tempSN)?

Each for loop will create new process and I need a way to kill the processes after for loop.
![image](https://user-images.githubusercontent.com/49393530/55765224-bb4efe80-5aa9-11e9-8321-b75c99ee258b.png)

Appreciate for the help
````
```
def ANRThread():
    sleep(5)
    process = list()
    while True:
        tempSN = serialNumber
        for SN in tempSN:
            try:
                if SN in serialNumber:
                    connect_device("Android://127.0.0.1:5037/"+SN)
                    #set_current(SN)
                    checkANR(SN)
            except (DeviceConnectionError, ConnectionAbortedError) as e:
                print(SN + " is disconnected")
        sleep(1)
```

def checkANR(SN):
    try:
        if exists(Template(r"tpl1553567879301.png", record_pos=(-0.324, 0.001), resolution=(720, 1280))) or exists(Template(r"tpl1553567885317.png", record_pos=(-0.319, 0.131), resolution=(720, 1280))):
            subprocess.Popen("adb -s "+ SN +" pull /data/anr/traces.txt", shell=True)
    except (DeviceConnectionError, ConnectionAbortedError) as e:
        print(SN + " is disconnected") `
```

**Comment by EraChen233** [comment]
You wrote an infinite loop. It will continue to create new processes when the old ones is not completed.

![image](https://user-images.githubusercontent.com/5961185/55767584-17b31d80-5aac-11e9-9cc5-b65a9ecfa5ef.png)

**Comment by yimelia** [comment]
in Windows, you can run `taskkill /f /im adb.exe` to kill all `adb.exe` process:

```
subprocess.Popen("taskkill /f /im adb.exe", shell=True)
```

**Comment by DanielCYJ94** [comment]
I want this script to run forever, I know that if I disconnect device, it will show something orientation ended and adb.exe process will auto terminate. Anyway I want to manually control so that every for loop, it will auto terminate the adb.exe process. Please advise or if there is no any way to do it.

**Comment by EraChen233** [comment]
Sorry, your issue is not related to Airtest. Please solve it yourself.
