### ISSUE TITLE
RotationWatcher.apk 安装失败

### ISSUE THREAD

**Issue by lichen228** [AirtestProject/Airtest#35]
![123](https://user-images.githubusercontent.com/4326872/38970159-74671f8e-43c6-11e8-8374-c38012286f39.png)
USB安装相关开关全打开，使用真机或模拟器安装均失败，导致Airtest无法连接设备
修改后缀为zip后无法解压，查不到minSDK的要求，请问下apk是否做了特殊处理？

**Comment by Meteorix** [comment]
重现不了你的问题，检查一下apk的md5

```
md5 RotationWatcher.apk 
MD5 (RotationWatcher.apk) = d24057f2784dd8dca5f5df349c7d332a
```

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/tree/master/airtest/core/android/static/apks 

是从这里拿到的apk吧？

**Comment by lichen228** [comment]
![123](https://user-images.githubusercontent.com/4326872/38971445-d125d34e-43cd-11e8-9e25-2aa68830f54d.png)
apk是从IDE文件里拿的。我通过链接里这个apk查了下包名，重装就可以了。
应该是我本地首次安装失败了，个例问题。感谢回复，可以close了

**Comment by Meteorix** [comment]
@rockywhisper 看看ide包的apk
