### ISSUE TITLE
When you execute iOS Game App and execute touch command, 'Picture  not found in screen'

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#353]
When you execute iOS Game App and execute touch command, the following error occurs.
- iphone 6s(os 11.2.1)
- airtestide 1.2.0
- xcode 10.1

error:
airtest.core.error.TargetNotFoundError: 'Picture  not found in screen'

![a12](https://user-images.githubusercontent.com/46311868/55922485-46f89480-5c3c-11e9-8c1c-4170ecf04ab7.jpg)

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/en/1_online_help/airtest_intro.html#image-editor-feature

**Comment by JJunM** [comment]
> http://airtest.netease.com/docs/en/1_online_help/airtest_intro.html#image-editor-feature

![a13](https://user-images.githubusercontent.com/46311868/55930029-6bfc0000-5c5a-11e9-9f39-c958f72d7c7a.jpg)

**Comment by JJunM** [comment]
> http://airtest.netease.com/docs/en/1_online_help/airtest_intro.html#image-editor-feature

**Comment by yimelia** [comment]
try to change the `threshold` < 0.9?

**Comment by JJunM** [comment]
> try to change the `threshold` < 0.9?

By default, the image can not be found and the setting value is 0.9. I can not find the image yet.

The Android game app has no image recognition for iOS app games because image recognition is better.

**Comment by yimelia** [comment]
try to set `threshold` = 0.7?

**Comment by JJunM** [comment]
Yes, try to set threshold = 0.7 find not image

**Comment by JJunM** [comment]
> try to set `threshold` = 0.7?

yes, It was not possible to find the image by default (set`threshold` = 0.7?).
