### ISSUE TITLE
图像识别不够准确,"立即查看“匹配“立即租凭”返回success

### ISSUE THREAD

**Issue by rossoneri520** [AirtestProject/Airtest#354]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
图像识别不够准确

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
![image](https://user-images.githubusercontent.com/33311868/55925833-82499200-5c41-11e9-9b3a-9c958ad6b727.png)

**复现步骤**

**预期效果**
截图按钮文案是“立即查看”
图像对比成功按钮的文案是“立即租凭”

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: oppo r9s
 - 系统: android
 - (别的信息)

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/cn/5_airtest_framework/airtest_api_info.html#id8
