### ISSUE TITLE
可以连接局域网内远程电脑上的Android模拟器吗？

### ISSUE THREAD

**Issue by chengyifly** [AirtestProject/Airtest#357]
还有想知道是否会增加对iOS模拟器的支持呢？

**Comment by yimelia** [comment]
1. 可以连接局域网内远程电脑上的Android模拟器吗？
我没有试过，可以参考这个[文档](https://notes.mengxin.science/2017/07/19/how-to-connect-android-emulator-in-lan/)，以及[这个](https://stackoverflow.com/questions/1754162/remote-debugging-with-android-emulator/1931633#1931633) 自行尝试一下

2. 是否会增加对iOS模拟器的支持呢？
暂时还没有计划，目前市面上也暂时没有可用性比较高的ios模拟器，如果有的话欢迎推荐

**Comment by chengyifly** [comment]
已解决。端口转发就可以，Mac上用这个 https://www.dnsjia.com/m/view.php?aid=1310

**Comment by chengyifly** [comment]
iOS官方的模拟器不行吗？

**Comment by yimelia** [comment]
IOS官方的模拟器是指？

**Comment by chengyifly** [comment]
就是Xcode自带的

**Comment by yimelia** [comment]
应该不行

**Comment by chengyifly** [comment]
像Appium、Calabash等好多都支持模拟器的，也都是用WebDriver原理。想了解下你们是有什么原因无法支持呢？

**Comment by yimelia** [comment]
@chengyifly 我们后续会看一下对这个功能的支持的。
或者你也可以直接试一下，如果都是基于wda的话，说不定是可以的。

**Comment by chengyifly** [comment]
好的，辛苦啦~ 感谢🙏

**Comment by chengyifly** [comment]
果然可以诶~ 而且不需要proxy。。你们文档里没写，还以为不支持呢😅
