### ISSUE TITLE
请问连接windows桌面的--device参数是什么？

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#358]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
请问连接windows桌面的--device参数是什么？
我在查看Airtestproject文档关于[python命令行运行脚本的部分](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_run_script/run_script.html#python)时，发现文档好像只给出了连接android和windows部分窗口的方法，但是没有给出连接windows桌面的方法。

请问这个方法能在哪里找到呢？
另外伸手一下求问如何寻找windows窗口句柄

**Comment by yimelia** [comment]
连接桌面就不填写参数就可以了： `--device Windows:///`
查看句柄可以用 Spy++
![image](https://user-images.githubusercontent.com/6896468/56022801-151c2680-5d3f-11e9-8102-017d2ed699f8.png)
