### ISSUE TITLE
Couldn't find any place to ask - a few questions

### ISSUE THREAD

**Issue by NiviJah** [AirtestProject/Airtest#359]
1. How can I import modules between files ?

`from myModule.air import MyClass` does not work.
`ModuleNotFoundError: No module named 'myModule'`

2. any way I can make a file/script run forever, without the use of code ?
i.e - after file is done, repeat from top infinite times

**Comment by NiviJah** [comment]
Update,
found this in the docs, see if it help.

`using("common.air")

from common import common_function

common_function()`

**Comment by EraChen233** [comment]
For the first question, yes, you find the right docs.
https://airtest.readthedocs.io/en/latest/README_MORE.html#import-from-other-air

For the second, you can do everything with python script.

**Comment by Meteorix** [comment]
@NiviJah you can ask questions here https://groups.google.com/forum/#!forum/airtestproject
