### ISSUE TITLE
脚本其他参数传递

### ISSUE THREAD

**Issue by linjinghui01** [AirtestProject/Airtest#360]
**(重要！问题分类)**

脚本中是否能增加自定义传参的功能，

除了传入设备号，脚本名之外的参数，还可以传递其他的，

比如测试包的路径，一些请求的参数等等。

以便于在air脚本中运行

**Comment by yimelia** [comment]
你好，可以的，请参考[文档](http://airtest.netease.com/docs/cn/5_airtest_framework/3_launcherpy.html#id14)

**Comment by annane** [comment]
想请问如果只是传简单的变量，在air 脚本中应该怎么引用？能详细说明吗谢谢！
