### ISSUE TITLE
连接不上MuMu

### ISSUE THREAD

**Issue by Flyerison** [AirtestProject/Airtest#363]
不知道为何Mumu始终offline，而其他的真机和BlueStacks虚拟机确没问题，adb devices没有显示出来，文档说要手机对应的官方驱动，不知道这是什么，能说的详细点吗

**Comment by yimelia** [comment]
模拟器连接文档见这里：http://airtest.netease.com/docs/cn/2_device_connection/3_emulator_connection.html

目前的mumu最新版本可能有兼容性问题，不建议使用，建议换一个模拟器。
