### ISSUE TITLE
图片内容少了一个字，阈值设置1，勾选rgb，仍然会识别相同

### ISSUE THREAD

**Issue by rossoneri520** [AirtestProject/Airtest#371]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
图片内容少了一个字，阈值设置1，勾选rgb，仍然会识别相同

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/33311868/56634712-8d66de00-6695-11e9-9483-01fdcd02489d.png)

![image](https://user-images.githubusercontent.com/33311868/56634727-a2dc0800-6695-11e9-9f8b-f9fbb753b08b.png)

**复现步骤**

**预期效果**
这种内容完全少了一部分的，是不是应该识别为不同呢？
并且报告里的相似度也没有达到1

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by rockywhisper** [comment]
@rossoneri520 
你好，请尝试下在IDE中显示脚本代码。
![image](https://user-images.githubusercontent.com/8188879/56636682-27ca2000-669c-11e9-84f0-b7441a99743f.png)

将脚本代码截图回复看一下？

**Comment by rossoneri520** [comment]
![image](https://user-images.githubusercontent.com/33311868/56637813-20584600-669f-11e9-97be-794615770d64.png)
我改成了0.9
并且我在生成的log里面看，这个0.9是没有效果的，所有的阈值都是初始的0.7
![image](https://user-images.githubusercontent.com/33311868/56637887-55fd2f00-669f-11e9-8551-f4f842c5b2ca.png)
这个时候我手动改log里面的阈值，改成0.9再生成报告，还是success

**Comment by rossoneri520** [comment]
版本号：AirtestIDE_2019-04-16_py3_win64

**Comment by yimelia** [comment]
assert_exists 接口用的threshold值不一样，详见[文档](http://airtest.netease.com/docs/cn/5_airtest_framework/2_script_settings.html#id7)

**Comment by rossoneri520** [comment]
更正一下，代码的截图是新的图片，但是和之前的issue是同一个逻辑，有一个字不同
![image](https://user-images.githubusercontent.com/33311868/56638359-81344e00-66a0-11e9-9a46-ee1fb9f9b3b3.png)

**Comment by rockywhisper** [comment]
@rossoneri520 
好的，原来你用的是assert_exists(图片)，[查看代码](https://github.com/AirtestProject/Airtest/blob/21583da2698a601cd632228228fc16d41f60a517/airtest/core/api.py#L448) ，看到目前是强制使用的是ST.THRESHOLD_STRICT

可以在脚本的开始位置单独统一设置assert语句的阈值：
```python
from airtest.core.settings import Settings as ST
ST.THRESHOLD_STRICT = 0.9
```

其他的语句可以正常设置

**Comment by rossoneri520** [comment]
@rockywhisper 好的，加上之后确实成功了，非常感谢。
但是还有一个问题请教一下，我直接改代码里面的setting，为啥就生效不了呢？
![image](https://user-images.githubusercontent.com/33311868/56638853-c6a54b00-66a1-11e9-965f-d68ce97b5e56.png)

**Comment by yimelia** [comment]
因为IDE里面用的airtest代码是打包过的，用的不是直接放在里面的那个文件夹里的代码

**Comment by rockywhisper** [comment]
因为IDE里面运行的话，使用的是封装在IDE内的环境，你在你的本地python环境改的内容自然不会生效。


可以在设置里面配置一下使用本地python环境，这样就会用你的本地环境跑，改动就会生效了。




在2019年04月24日 15:01，rossoneri520 写道：

@rockywhisper 好的，加上之后确实成功了，非常感谢。
但是还有一个问题请教一下，我直接改代码里面的setting，为啥就生效不了呢？

**Comment by rossoneri520** [comment]
嗦嘎，了解了，谢谢

**Comment by rossoneri520** [comment]
你好，再问一下，rgb=True双击图片勾选是有效的，但是加在代码的前面貌似是无效的，如果要全局的这个要怎么用呢？
