### ISSUE TITLE
都勾选rgb情况下，相同文案比不同文案的匹配度还要低（购票专享和购票专门）

### ISSUE THREAD

**Issue by rossoneri520** [AirtestProject/Airtest#372]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
都勾选rgb情况下，相同文案比不同文案的匹配度还要低

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
购票专享VS购票专享，匹配度0.76
![image](https://user-images.githubusercontent.com/33311868/56644761-ed1db300-66ae-11e9-8e8b-b0742df150c2.png)

购票专享VS购票专门，仔细看可以看到截图里面是个“门”字，匹配度0.84
![image](https://user-images.githubusercontent.com/33311868/56644835-13dbe980-66af-11e9-82a9-208b35f4edb6.png)

**复现步骤**

**预期效果**
这个匹配度逻辑，很难让用户去判断最后的验证结果呀。应该是不同文案比相同文案匹配度要低吧

**python 版本:** `python3.5`

**airtest 版本:AirtestIDE_2019-04-16_py3_win64
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by rockywhisper** [comment]
@rossoneri520 
对于文字类识别，在正式OCR版本放出前，可以先尝试使用poco脚本解决哈  :-)

**Comment by rossoneri520** [comment]
好的，谢谢。顺便问一下，你们的OCR版本是个什么样的版本？

**Comment by rockywhisper** [comment]
@rossoneri520 
具体形式还没定.      :-）
