### ISSUE TITLE
多点触控-边滑动边点击

### ISSUE THREAD

**Issue by jekiki** [AirtestProject/Airtest#373]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**

* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
（在这里粘贴traceback或其他报错信息）
```
在进行测试时希望实现边滑动边点击，类似游戏里的边移动边攻击。
<pre>
这是使用minitouch 实现的代码测试可行
from airtest.core.android.minitouch import *
from airtest.core.android.rotation import XYTransformer
def transform_xy(tuple_xy, display_info):
    x, y = tuple_xy
    x, y = XYTransformer.up_2_ori(
            (x, y),
            (display_info["width"], display_info["height"]),
            display_info["orientation"]
        )
    return x, y

multitouch_event = [
    DownEvent(transform_xy((260, 970), dev.display_info),0),
    MoveEvent(transform_xy((340, 880), dev.display_info),0),
    DownEvent(transform_xy((1570, 1100), dev.display_info),1),
    UpEvent(1),
	SleepEvent(1),
    DownEvent(transform_xy((1570, 1100), dev.display_info),1),
    UpEvent(1),
	SleepEvent(1),
    DownEvent(transform_xy((1570, 1100), dev.display_info),1),
    UpEvent(1),
	SleepEvent(1),
    DownEvent(transform_xy((1570, 1100), dev.display_info),1),
    UpEvent(1),
	SleepEvent(1),
    DownEvent(transform_xy((1570, 1100), dev.display_info),1),
    UpEvent(1),
	SleepEvent(1),
    DownEvent(transform_xy((1570, 1100), dev.display_info),1),
    UpEvent(1),
	SleepEvent(1),
    UpEvent(0)
]

dev.minitouch.perform(multitouch_event)
</pre>

但是实现起来较为复杂，代码不优雅
如何使用poco多点触控实现
<pre>
tracks = [
    MotionTrack().start([0.14, 0.8]).move([0.17, 0.7]).hold(10),  
   <strong> ??? MotionTrack().start([0.8, 0.9]).hold(1).start([0.8, 0.9]), ???</strong>                                        
]
poco.apply_motion_tracks(tracks)
</pre>

**Comment by yimelia** [comment]
```
tracks = [
    MotionTrack().start([0.5, 0.5]).move([0.5, 0.6]).move([0.6, 0.6]).hold(1),   # 可以连续move多次
    MotionTrack().start([0.6, 0.6]),                                             # 不move的话表示只点击这个点
]
poco.apply_motion_tracks(tracks)
```

**Comment by jekiki** [comment]
非常抱歉，您所提供的代码仅可以点击一次，比如我想实现连续移动十秒，每隔一秒点击一次。还请您详细阅读一下我的代码，您可能误会了我的意思。

**Comment by yimelia** [comment]
很抱歉，涉及到具体的代码逻辑实现问题的话，可以自行根据文档现有接口来实现，这个需求应该是可以用Poco实现的。
移动速度是固定的，所以移动相同距离所花费的时间一样，因此只需要两个手指分开写，对上时间就行了，具体实现可以自行实现一下。

**Comment by jekiki** [comment]
其中一只手指是滑动，另一只手是以某种频率点击，poco只有move，没有downevent 和 upevent，第二只手指落下后不能抬起再落下，因此无法实现多次点击。两只手不是全部滑动，也不是全部点击。

**Comment by jekiki** [comment]
airtest.core.android.minitouch 
DownEvent    MoveEvent    DownEvent    UpEvent	SleepEvent
minitouch模块有以上四种事件，因此可以实现以上操作，但是无法实现链式操作，一个手指的事件一条语句。
poco可以实现链式操作，但是只有start MoveEvent  SleepEvent，没有UpEvent	Downevent因此无法实现操作

**Comment by jekiki** [comment]
poco如何实现 按下/抬起/等待  这三种事件呢
两次start 同一点，仅有一次点击效果

**Comment by yimelia** [comment]
我问了一下，这个比较复杂，可能需要自己继承MotionTrack类来实现了

**Comment by jekiki** [comment]
那您说，minitouch能不能进行链式操作，minitouch里有现成的事件，就是写起来太杂乱，多点的事件交错不利于理解。motiontrack如何实现，downevent和upevent，发送底层adb代码吗？

**Comment by loneyao** [comment]
> tracks = [
>     MotionTrack().start([0.5, 0.5]).move([0.5, 0.6]).move([0.6, 0.6]).hold(1),   # 可以连续move多次
>     MotionTrack().start([0.6, 0.6]),                                             # 不move的话表示只点击这个点
> ]
> poco.apply_motion_tracks(tracks)

tracks = [
    MotionTrack().start([0.5, 0.5]).move([0.5, 0.6]).move([0.6, 0.6]).hold(1),   # 可以连续move多次
    MotionTrack().start([0.6, 0.6]),                                             # 不move的话表示只点击这个点
]
poco.apply_motion_tracks(tracks)

有封装成一个函数？
