### ISSUE TITLE
airtest是否支持react native上面查找testID或者accesibilityLabel？

### ISSUE THREAD

**Issue by juntongli** [AirtestProject/Airtest#379]
在ios上面是可以用testID找到对应原素的
但是在android上面，无论是testID还是accesibilityLabel都找不到
在appium中有find_element_by_accessibility_id方法，不知道在airtest中有没有对应的方法？

**Comment by coolguy001tv** [comment]
弱弱弱地问一下，airtest支持RN么……

**Comment by yimelia** [comment]
支持原生和webview，但是RN暂时还不支持
