### ISSUE TITLE
'Windows' object has no attribute 'display_info'

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/Airtest#382]
Bug description 
Hi I'm trying to get the Windows resolution with the getPortSize() function in airtestScreen, but I get this error when running the getPortSize() function when connected to a windows build unity window

Stacktrace 
-> line 13, in getPortSize
    disp = current_device().display_info
AttributeError: 'Windows' object has no attribute 'display_info'

**To Reproduce**
1. Copy the below code 

"""
from poco.utils.airtest.screen  import AirtestScreen
airtestScreen = AirtestScreen() 
screenPixels = airtestScreen.getPortSize()
"""

2. Open a new airtest project 
3. Connect to a unity window
4. Run code 

**Expected behavior**
"Get windows window resolution from getPortSize() function

**python version:**  Python 3.7

**airtest version:** `1.2.0

**Comment by yimelia** [comment]
try this:
```
from airtest.core.api import *
disp = device().get_current_resolution()
```

**Comment by phantomsom** [comment]
It doesn't output an exception on windows build testing, but If I select a windowed mode resolution in a unity build
![image](https://user-images.githubusercontent.com/19833754/57292846-91631900-70f5-11e9-80b4-61036bf8e611.png)

device().get_current_resolution() doesn't return exactly 640 x 480, but
![image](https://user-images.githubusercontent.com/19833754/57292887-a8097000-70f5-11e9-9c47-6fab31957b9d.png)
 
If I select 1152 x 854 as the resolution,

device().get_current_resolution() returns
![image](https://user-images.githubusercontent.com/19833754/57292939-cec7a680-70f5-11e9-82c0-11685ed5971b.png)

instead. This means that the button clicks are off by a bit, and at some cases my written airtest poco bot even managed to close the game window

**Comment by phantomsom** [comment]
![image](https://user-images.githubusercontent.com/19833754/57293245-b3a96680-70f6-11e9-8043-8b2a5b0aa89c.png)
It may be caused by the top bar on the unity game window

**Comment by yimelia** [comment]
or you can adjust the value manually:
```
device().focus_rect =  [int, int, int, int]  # the "margin" of the real game window : [left, top, right, bottom] , like: [8, 38, 8, 1]
device().get_current_resolution()
```

**Comment by phantomsom** [comment]
Thank you yimelia, now I get the correct resolution after using the function you suggested,
now I got another issue, if you're interested :

https://github.com/AirtestProject/Airtest/issues/389

**Comment by phantomsom** [comment]
Hi, Is the windows unsynchronized problem fixed by any chance? 
![image](https://user-images.githubusercontent.com/19833754/61513362-6f5c1000-aa2f-11e9-96b7-20d709f29e15.png)
Right now I have to include this code to provide the correct focus_rect() for poco.
