### ISSUE TITLE
Run a function from another airtest script.

### ISSUE THREAD

**Issue by YuuKwn** [AirtestProject/Airtest#385]
I want to run a sign in function in my scripts, and use this function on all scripts. But I can't find a way to run the signin script from within the other script because the airtest sample png images are in the other folder (in signIn.air) while the script search for files in the other .air folder.

Is there a way to run this kind of test?

**Comment by SUDARSHANCHAUDHARI** [comment]
you can try the following the approach :

create one separate python file and store attribute of all images.

then call that file in your .air python file

we can create a centralise path for images for . air files

**Comment by yuzhujiutian** [comment]
please try the using [using](http://airtest.netease.com/docs/en/2_references_and_glossary/airtest_scripts_settings.html?highlight=using#project-root) function 

e.g.

proj_root_dir = F:\helloc\aircraft
test_a_dir = F:\helloc\aircraft\test_a.air\test_a.py
test_b_dir = F:\helloc\aircraft\test_b.air\test_b.py

 
in test_b.py file

`
ST.PROJECT_ROOT = os.path.dirname(os.getcwd())    # Depends on the relative location of the file directory
print('ST.PROJECT_ROOT =', ST.PROJECT_ROOT)    # to check your file directory
using('test_a.air')
from  test_a import your_function
`

**Comment by YuuKwn** [comment]
I was able to figure it after some testing
The url below is where I found all the information I needed:
https://airtest.readthedocs.io/en/latest/README_MORE.html
