### ISSUE TITLE
[BUG] Importing a function with using .air runs the function even when not calling it

### ISSUE THREAD

**Issue by YuuKwn** [AirtestProject/Airtest#387]
I'm using the "using ('name.air')" and "from name import functionName".

When I run the script, the functionName runs from the "from name import functionName" line. It shouldn't happen because I'm just importing the function, not calling it yet.

**Comment by yimelia** [comment]
try to check that there are only function definitions in `name.air` , no calls in it

**Comment by yuzhujiutian** [comment]
before call using function, try to add code as follows:

ST.PROJECT_ROOT = os.path.dirname(os.getcwd())

**Comment by YuuKwn** [comment]
> try to check that there are only function definitions in `name.air` , no calls in it

That was definitely the problem. Thanks!
