### ISSUE TITLE
If you run the airtest script using external Python, an error occurs.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#388]
If you run the airtest script using external Python, an error occurs.

+  airtest.core.error.TargetNotFpundError: picture (image) not found in screen

With the internal Python, running the airtest script works fine.

external Python: 3.7.2

**Comment by SUDARSHANCHAUDHARI** [comment]
what syntax you are using?
can you give more details?
I am using the following syntax for python 2.7

import sys
sys.path.append('Library/Python/2.7/site-packages')

also, provide a log file

thank you

**Comment by JJunM** [comment]
> what syntax you are using?
> can you give more details?
> I am using the following syntax for python 2.7
> 
> import sys
> sys.path.append('Library/Python/2.7/site-packages')
> 
> also, provide a log file
> 
> thank you

custom python path
options> setting>custom python path : python 3.7.2 python path (library>frameworks>python.framework>versions>3.7>bin>python3) 

When airtest is executed in Python with custom python path set, an error occurs.
> airtest.core.error.TargetNotFpundError: picture (image) not found in screen
