### ISSUE TITLE
Script execution error after setting custom python with mac airtestide

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#392]
After setting custom python with mac airtestide
When I run the airtest script, an error occurs.

airtest.core.error.TargetNotFpundError: picture (image) not found in screen
With the internal Python, running the airtest script works fine.

external Python: 3.7.2

**Comment by SUDARSHANCHAUDHARI** [comment]
what syntax you are using?
can you give more details?
I am using the following syntax for python 2.7

import sys
sys.path.append('Library/Python/2.7/site-packages')

also, provide a log file

thank you

**Comment by JJunM** [comment]
> 어떤 구문을 사용하고 있습니까? 
> 더 자세한 정보를 제공 할 수 있습니까? 
> 파이썬 2.7에 대해 다음 구문을 사용하고 있습니다.
> 
> import sys 
> sys.path.append ( '라이브러리 / Python / 2.7 / site-packages')
> 
> 또한 로그 파일을 제공하십시오.
> 
> 고맙습니다

**Comment by JJunM** [comment]
> what syntax you are using?
> can you give more details?
> I am using the following syntax for python 2.7
> 
> import sys
> sys.path.append('Library/Python/2.7/site-packages')
> 
> also, provide a log file
> 
> thank you

custom pthon path 3.7.2 was set.
+ pip install -U airtest
When I execute a test script, the following error occurs.
error: airtest.core.error.TargetNotFpundError: picture (image) not found in screen

**Comment by SUDARSHANCHAUDHARI** [comment]
can share sample code
are you changing anything in the image template syntax?
