### ISSUE TITLE
AirtestIDE v1.2.1 不兼容小米6

### ISSUE THREAD

**Issue by WalkerMe** [AirtestProject/Airtest#393]
**描述问题bug**
IDE连接小米6，在Win10上，得到的UI树不正确，而且只能拿到主界面的UI，应用的信息得不到；在Win7，UI树直接就看不到了，点击模拟屏也没反应。

**python 版本:** `python3.5`

**airtest 版本:** `1.2.1`

**设备:**
 - 型号: [小米6]
 - 系统: [Android 8.0/MIUI 10.2稳定版]

![图片](https://user-images.githubusercontent.com/30628456/57436152-b381a600-7271-11e9-9df4-5a6868b058f7.png)

**Comment by yimelia** [comment]
请提供更多信息：小米6上运行的是什么样的应用拿到的ui树不正确，是否是Android原生，还是混合了H5页面。
请提供与IDE一同启动的黑色命令行窗口里的报错信息截图 http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2

**Comment by WalkerMe** [comment]
> 
> 
> 请提供更多信息：小米6上运行的是什么样的应用拿到的ui树不正确，是否是Android原生，还是混合了H5页面。
> 请提供与IDE一同启动的黑色命令行窗口里的报错信息截图 http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2

截图更新到提问里了

**Comment by yimelia** [comment]
点击无效的问题：取消connect按钮的adb touch勾选。
UI树不正确的问题，从已有信息里不能得出结论，请提供更多信息

**Comment by WalkerMe** [comment]
> 
> 
> 点击无效的问题：取消connect按钮的adb touch勾选。以及查看文档，确认小米手机的几个选项都打开了（允许模拟点击）http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id8
> UI树不正确的问题，从已有信息里不能得出结论，请提供更多信息

Win7上好了，是我一些设置被手机安全中心恢复了，可能Win10上也是没问题的，感谢
