### ISSUE TITLE
使用自定义启动器，增加了--recording 参数不会记录视频

### ISSUE THREAD

**Issue by Chersh-Pan** [AirtestProject/Airtest#395]
使用自定义启动器，增加了--recording 参数不会记录视频，这是bug？ 还是设计如此？

**Comment by yimelia** [comment]
并没有特地设计，默认情况下，是可以记录视频的。
请提供更多信息以帮助我们分析问题

**Comment by Chersh-Pan** [comment]
没有报错，就是用自定义启动器执行脚本后，录屏是有开启，但是脚本执行结束的时候并没有去停止录屏，并保留视频信息

**Comment by yimelia** [comment]
可以看一下AirtestCase的源码的[这里](https://github.com/AirtestProject/Airtest/blob/master/airtest/cli/runner.py#L43)
自定义的启动器如果重写了teardown，可能就没有默认调用到这段代码，可以加一下`super().tearDown()`
