### ISSUE TITLE
[Image editor] - Snapshot+Recognition black screen when selecting one window

### ISSUE THREAD

**Issue by i-nunes** [AirtestProject/Airtest#397]
**Steps to reproduce**
1. Click Window;
2. In Windows App Connection, click "Select Window";
3. Select a window;
4. Try any Airtest Assistant command and open the image editor;
5. Click "Snapshot+recognition";
6. Observe;

**Observed Behavior**
The screen is black and Airtest can't recognize the window image

**Expected behavior**
It should be possible to see the window image.

**python version:** 'Python 3.6.4' 
**airtest version:** 'v1.2.1'

**Tested on Windows 10**

**Additional context**
The bug happened in more than one instance and more than one desktop and the STR does not always reproduce the bug, sometimes it works properly.

**Comment by yimelia** [comment]
our screenshot function in some window may not work well, just try "connect desktop":
![image](https://user-images.githubusercontent.com/6896468/57591391-aa3f5480-7563-11e9-9d82-c739db96ef2a.png)
