### ISSUE TITLE
用Mac连接Chrome窗口，一直报错：当前系统不是Windows

### ISSUE THREAD

**Issue by ywhxauat** [AirtestProject/Airtest#398]
![image](https://user-images.githubusercontent.com/49389360/57566310-82ce7780-73fd-11e9-8e18-ca9ae83170ef.png)

**Comment by ywhxauat** [comment]
怎么用Mac连接Chrome窗口？？？

**Comment by yimelia** [comment]
请问具体操作是什么？
是希望使用airtest-selenium功能，还是？
如果是单纯想连接一个窗口，那么mac上暂时还不支持，现在连接窗口功能是windows平台才有的。
如果是希望使用airtest-selenium，直接在窗口菜单中找到selenium插件，然后从插件窗口里的按钮来启动关联的chrome窗口就可以了。
