### ISSUE TITLE
Please tell us how to get your test app on iOS.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#399]
Please tell me the details of how to install ios app using install () api in airtest.core.api module.

airtest.core.api module

- install()

**Comment by EraChen233** [comment]
All interfaces for iOS can be found in https://airtest.readthedocs.io/zh_CN/latest/_modules/airtest/core/ios/ios.html

If you want to install app in iOS by Airtest, use [install_app](https://airtest.readthedocs.io/zh_CN/latest/_modules/airtest/core/ios/ios.html#IOS.install_app)

**Comment by JJunM** [comment]
> All interfaces for iOS can be found in https://airtest.readthedocs.io/zh_CN/latest/_modules/airtest/core/ios/ios.html
> 
> If you want to install app in iOS by Airtest, use [install_app](https://airtest.readthedocs.io/zh_CN/latest/_modules/airtest/core/ios/ios.html#IOS.install_app)


Should I do the following?

from airtest.core.ios,ios impror *

instapp_app("filepath/bundle identifier") ""

**Comment by EraChen233** [comment]
My mistake... `install_app` is not implemented in iOS yet.

![image](https://user-images.githubusercontent.com/5961185/57600127-81cb5080-758b-11e9-9e7c-96409d352e2d.png)

For now, app can only be installed in iOS by manually.
