### ISSUE TITLE
When running airtest with custom python with MAC aitest ide, an error occurs.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#407]
When running airtest with custom python with MAC aitest ide, an error occurs.

**airtestide ver: mac Airtest IDE 1.2.1**

**custom python path**
- options> setting>custom python path : python 3.7.2 path 
- python 3.7.2 path: library>frameworks>python.framework>versions>3.7>bin>python3.7

**custom python airtest ver**
- library>frameworks>python.framework>versions>3.7>lib>python3.7>site-packages
- airtest-1.0.26-py3.7.egg.info install

**custom python scripr run error**
<img width="1174" alt="스크린샷 2019-05-17 오전 9 23 38" src="https://user-images.githubusercontent.com/46311868/57895540-1cc37380-7887-11e9-9aa9-bc9b7e423463.png">
<img width="1070" alt="스크린샷 2019-05-17 오전 9 23 57" src="https://user-images.githubusercontent.com/46311868/57895542-2056fa80-7887-11e9-9151-b7fb35eb8b4c.png">

**Comment by SUDARSHANCHAUDHARI** [comment]
Hello @JJunM ,

what about adding sys library in a scripting file
like
import sys
sys.path.append('PYTHON PATH.')

**Comment by JJunM** [comment]
> Hello @JJunM ,
> 
> what about adding sys library in a scripting file
> like
> import sys
> sys.path.append('PYTHON PATH.')

Should I do the following?

import sys
sys.path.append('library>frameworks>python.framework>versions>3.7>bin>python3.7')
sys.path.append('library>frameworks>python.framework>versions>3.7>lib>python3.7>site-packages')

**Comment by SUDARSHANCHAUDHARI** [comment]
after opening Library Folder, can you see any Python folder?

**Comment by yimelia** [comment]
hi @JJunM
this error is just telling you: airtest can't find this picture on the current screen, you can check the HTML report and see if the screenshot is wrong(like black screen).
if the screenshot is right , you can try to set the `threshold` higher, see [this](http://airtest.netease.com/docs/en/2_references_and_glossary/airtest_quick_start.html#settings-for-image-recognition)

**Comment by JJunM** [comment]
> hi @JJunM
> this error is just telling you: airtest can't find this picture on the current screen, you can check the HTML report and see if the screenshot is wrong(like black screen).
> if the screenshot is right , you can try to set the `threshold` higher, see [this](http://airtest.netease.com/docs/en/2_references_and_glossary/airtest_quick_start.html#settings-for-image-recognition)

 I set the threshold 0.70 ~ 1.00 value and executed touch (imgae), but the match result: none value is returned.

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/58152295-c7c89880-7c9e-11e9-9cd8-f9537758a897.png)

click the report button to see if the screenshot is black?

**Comment by JJunM** [comment]
> ![image](https://user-images.githubusercontent.com/6896468/58152295-c7c89880-7c9e-11e9-9cd8-f9537758a897.png)
> 
> click the report button to see if the screenshot is black?

@yimelia 
<img width="889" alt="스크린샷 2019-05-22 오후 3 50 14" src="https://user-images.githubusercontent.com/46311868/58153260-8a1d3d00-7ca9-11e9-8fa7-dd2126d7f437.png">

**Comment by yimelia** [comment]
try these ways, maybe some of them would help you:
1. update your airtest from 1.0.26 to 1.0.27(latest), `pip install -U airtest`, and try again. (the latest version added several new image recognition algorithms, maybe helpful )
2. try to take some other new picture and run again, the failed maybe just because of the picture with words is too hard to recognize.

**Comment by JJunM** [comment]
> try these ways, maybe some of them would help you:
> 
> 1. update your airtest from 1.0.26 to 1.0.27(latest), `pip install -U airtest`, and try again. (the latest version added several new image recognition algorithms, maybe helpful )
> 2. try to take some other new picture and run again, the failed maybe just because of the picture with words is too hard to recognize.

@yimelia 

<img width="939" alt="스크린샷 2019-05-22 오후 5 01 35" src="https://user-images.githubusercontent.com/46311868/58157639-bc339c80-7cb3-11e9-974e-aef6fa1f3492.png">

<img width="548" alt="스크린샷 2019-05-22 오후 5 04 33" src="https://user-images.githubusercontent.com/46311868/58157653-c5bd0480-7cb3-11e9-8d75-dddfd6e7bd93.png">

**Comment by yimelia** [comment]
hi @JJunM 
double click the picture to open the "Image Editor" (see [this](http://airtest.netease.com/docs/en/1_online_help/airtest_intro.html#image-editor-feature))

Clicking the `Snapshot Recognition` button in the image editor will capture the current screen of the mobile phone and perform a recognition. There must be something wrong in it, please take a screenshot, thank you...

**Comment by JJunM** [comment]
> hi @JJunM
> double click the picture to open the "Image Editor" (see [this](http://airtest.netease.com/docs/en/1_online_help/airtest_intro.html#image-editor-feature))
> 
> Clicking the `Snapshot Recognition` button in the image editor will capture the current screen of the mobile phone and perform a recognition. There must be something wrong in it, please take a screenshot, thank you...

hi @yimelia 
<img width="946" alt="스크린샷 2019-05-22 오후 5 20 55" src="https://user-images.githubusercontent.com/46311868/58158964-762c0800-7cb6-11e9-927b-094530e8c0b1.png">

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/58159774-c784c900-7caf-11e9-9346-ede91f8bb385.png)
right click the script title and click `view report` to open the report folder, see what's in the log.txt?

**Comment by JJunM** [comment]
> ![image](https://user-images.githubusercontent.com/6896468/58159774-c784c900-7caf-11e9-9346-ede91f8bb385.png)
> right click the script title and click `view report` to open the report folder, see what's in the log.txt? and the screenshot .

hi,@yimelia
sorry for the late reply

<img width="1003" alt="스크린샷 2019-05-23 오전 8 18 57" src="https://user-images.githubusercontent.com/46311868/58215232-ceedb600-7d33-11e9-9e7d-be1672e799ee.png">

**Comment by yimelia** [comment]
if you don't use the `custom python.exe`, can the script run?

**Comment by SUDARSHANCHAUDHARI** [comment]
@JJunM 

also, can you share a screen shot of the script?

what exact syntax you are using?

**Comment by JJunM** [comment]
> if you don't use the `custom python.exe`, can the script run?

hi, @yimelia 
yes, custom python path
- options> setting>custom python path : python 3.7.2 path
- python 3.7.2 path: library>frameworks>python.framework>versions>3.7>bin>python3.7

**Comment by JJunM** [comment]
> @JJunM
> 
> also, can you share a screen shot of the script?
> 
> what exact syntax you are using?
use touch() 

<img width="547" alt="스크린샷 2019-05-23 오후 1 18 07" src="https://user-images.githubusercontent.com/46311868/58225502-41bf5700-7d5d-11e9-9634-462d463de214.png">

**Comment by JJunM** [comment]
> @JJunM
> 
> also, can you share a screen shot of the script?
> 
> what exact syntax you are using?

hi, @SUDARSHANCHAUDHARI

i used touch() api

<img width="547" alt="스크린샷 2019-05-23 오후 1 18 07" src="https://user-images.githubusercontent.com/46311868/58225553-81863e80-7d5d-11e9-8578-72c92e293725.png">

**Comment by JJunM** [comment]
> if you don't use the `custom python.exe`, can the script run?

**Comment by yimelia** [comment]
hi @JJunM 
try to [start AirtestIDE with command line](http://airtest.netease.com/docs/en/3_faq/ide_crash.html#how-can-i-check-the-cause-of-airtestide-crash), and if any problem occurs, you can see the trace log in the command line.
------------
or 
clear the log directory, and you can copy this:
![image](https://user-images.githubusercontent.com/6896468/58230486-117cb600-7d67-11e9-8a78-642c7b37b1dd.png)
then run it in your command line, see what happen next?
we think maybe because it doesn't have permissions to write log into your log dir

**Comment by JJunM** [comment]
> hi @JJunM
> 
> try to [start AirtestIDE with command line](http://airtest.netease.com/docs/en/3_faq/ide_crash.html#how-can-i-check-the-cause-of-airtestide-crash), and if any problem occurs, you can see the trace log in the command line.
> 
> or
> clear the log directory, and you can copy this:
> ![image](https://user-images.githubusercontent.com/6896468/58230486-117cb600-7d67-11e9-8a78-642c7b37b1dd.png)
> then run it in your command line, see what happen next?
> we think maybe because it doesn't have permissions to write log into your log dir

hi @yimelia 
<img width="1166" alt="스크린샷 2019-05-23 오후 4 50 10" src="https://user-images.githubusercontent.com/46311868/58235121-22372700-7d7b-11e9-8070-58afd74bbac0.png">
<img width="1165" alt="스크린샷 2019-05-23 오후 4 50 57" src="https://user-images.githubusercontent.com/46311868/58235139-2cf1bc00-7d7b-11e9-9d81-cfb0bf94f658.png">
<img width="1166" alt="스크린샷 2019-05-23 오후 4 51 14" src="https://user-images.githubusercontent.com/46311868/58235165-39761480-7d7b-11e9-8345-7be5cb11e6f0.png">

**Comment by JJunM** [comment]
> > hi @JJunM
> > try to [start AirtestIDE with command line](http://airtest.netease.com/docs/en/3_faq/ide_crash.html#how-can-i-check-the-cause-of-airtestide-crash), and if any problem occurs, you can see the trace log in the command line.
> > or
> > clear the log directory, and you can copy this:
> > ![image](https://user-images.githubusercontent.com/6896468/58230486-117cb600-7d67-11e9-8a78-642c7b37b1dd.png)
> > then run it in your command line, see what happen next?
> > we think maybe because it doesn't have permissions to write log into your log dir
> 
> hi @yimelia
> 
> If you look at the log below, it seems that someone else accesses the PC and loads the Python library.
> Reconnect the network and check again.
> -test device: iphone 8plus (os 11.0.3)
> 
> <img alt="스크린샷 2019-05-23 오후 4 50 10" width="1166" src="https://user-images.githubusercontent.com/46311868/58235121-22372700-7d7b-11e9-8070-58afd74bbac0.png">
> 
> <img alt="스크린샷 2019-05-23 오후 4 50 57" width="1165" src="https://user-images.githubusercontent.com/46311868/58235139-2cf1bc00-7d7b-11e9-9d81-cfb0bf94f658.png">
> 
> <img alt="스크린샷 2019-05-23 오후 4 51 14" width="1166" src="https://user-images.githubusercontent.com/46311868/58235165-39761480-7d7b-11e9-8345-7be5cb11e6f0.png">

hi,@yimelia

<img width="969" alt="스크린샷 2019-05-24 오전 9 02 18" src="https://user-images.githubusercontent.com/46311868/58294007-e47de100-7e02-11e9-8b3b-8ef2cf77cb99.png">

[log.txt](https://github.com/AirtestProject/Airtest/files/3214534/log.txt)

**Comment by yimelia** [comment]
@JJunM 
run this command in your CMD and see what happens(make sure all the command in one line) 
![image](https://user-images.githubusercontent.com/6896468/58298148-fcf2f900-7e0c-11e9-9445-1afcc9c35f25.png)

**Comment by JJunM** [comment]
hi, @yimelia 
<img width="965" alt="스크린샷 2019-05-24 오후 1 50 52" src="https://user-images.githubusercontent.com/46311868/58303426-055a2c80-7e2b-11e9-9b65-c32d93cda163.png">
<img width="1068" alt="스크린샷 2019-05-24 오후 1 49 04" src="https://user-images.githubusercontent.com/46311868/58303434-0c813a80-7e2b-11e9-914a-98aacc9905f7.png">

**Comment by yimelia** [comment]
copy the command:
```
"/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7" -u "/applications/AirtestIDE.app/Contents/MacOS/sample/custom_launcher.py" "/Users/jjun.m/Downloads/WorkSpace/AirtestIDE/untitled.air" --device ios:///http://127.0.0.1:8100 --log "/Users/jjun.m/Downloads/WorkSpace/AirtestIDE/Scripts/c376e5f667163e06786133632724692e"
```
in your CMD

**Comment by JJunM** [comment]
> "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7" -u "/applications/AirtestIDE.app/Contents/MacOS/sample/custom_launcher.py" "/Users/jjun.m/Downloads/WorkSpace/AirtestIDE/untitled.air" --device ios:///http://127.0.0.1:8100 --log "/Users/jjun.m/Downloads/WorkSpace/AirtestIDE/Scripts/c376e5f667163e06786133632724692e"

hi,@yimelia
cmd run result
<img width="1435" alt="스크린샷 2019-05-24 오후 4 15 57" src="https://user-images.githubusercontent.com/46311868/58309508-6ab81880-7e3f-11e9-92b3-20faca30d75a.png">
<img width="1439" alt="스크린샷 2019-05-24 오후 4 16 21" src="https://user-images.githubusercontent.com/46311868/58309516-70adf980-7e3f-11e9-8edb-c18fb065ba3c.png">
<img width="1436" alt="스크린샷 2019-05-24 오후 4 16 41" src="https://user-images.githubusercontent.com/46311868/58309524-7572ad80-7e3f-11e9-9d69-4728fd82b531.png">

**Comment by yimelia** [comment]
hi @JJunM 
just try to set `threshold` to 0.6 and try again?
double click the image:
![image](https://user-images.githubusercontent.com/6896468/58312351-b1a50e80-7e3d-11e9-9875-1ddb07c8a8e8.png)

**Comment by JJunM** [comment]
> hi @JJunM
> just try to set `threshold` to 0.6 and try again?
> double click the image:
> ![image](https://user-images.githubusercontent.com/6896468/58312351-b1a50e80-7e3d-11e9-9875-1ddb07c8a8e8.png)

hi, @yimelia 

<img width="1105" alt="스크린샷 2019-05-27 오전 8 56 16" src="https://user-images.githubusercontent.com/46311868/58388729-813bbb00-805d-11e9-965b-12c745d724de.png">

**Comment by yimelia** [comment]
hi @JJunM 
our algorithm tries to find the best match in the screenshot, but sometimes the result is not as good as expected.
try to make your image like this may be helpful (remove the white background) :
![image](https://user-images.githubusercontent.com/6896468/58391209-60786300-8067-11e9-96a6-1b9b269255dd.png)
or check the "rgb" option and try again?

we are so sorry about the image recognition algorithm makes you so many trouble...if your game is Unity or cocos2dx, our [Poco](https://github.com/AirtestProject/Poco) is more useful.

by the way, we are in Guangzhou China, and it rains all day for several weeks :)

**Comment by JJunM** [comment]
> hi @JJunM
> our algorithm tries to find the best match in the screenshot, but sometimes the result is not as good as expected.
> try to make your image like this may be helpful (remove the white background) :
> ![image](https://user-images.githubusercontent.com/6896468/58391209-60786300-8067-11e9-96a6-1b9b269255dd.png)
> or check the "rgb" option and try again?
> 
> we are so sorry about the image recognition algorithm makes you so many trouble...if your game is Unity or cocos2dx, our [Poco](https://github.com/AirtestProject/Poco) is more useful.
> 
> by the way, we are in Guangzhou China, and it rains all day for several weeks :)

hi,@yimelia

I do not understand the problem that airtest api does not work properly with custom python.exe.
Both game image and iOS image can not be found properly.

I confirmed that touch was successfully executed during airtest api in internal Python.

I do not know whether the difference will occur in the execution result in internal Python and custom python.exe.

**Comment by SUDARSHANCHAUDHARI** [comment]
@JJunM, if you want to minimize this issue then set high threshold value ().
In your image, remove extra white space, 
try to use exact image portion

![image](https://user-images.githubusercontent.com/25879455/58395855-5d37a400-8074-11e9-8710-b00f5932418c.png)

**Comment by yimelia** [comment]
Hi @JJunM 
I'm also feeling confused about this problem.
what's the version of airtest in your python environment? the latest version is 1.0.27

**Comment by JJunM** [comment]
> Hi @JJunM
> I'm also feeling confused about this problem.
> what's the version of airtest in your python environment? the latest version is 1.0.27

hi,@yimelia

<img width="668" alt="스크린샷 2019-05-27 오후 4 01 19" src="https://user-images.githubusercontent.com/46311868/58401445-cfba7b00-8098-11e9-8e4c-0713e90ca32f.png">

**Comment by yimelia** [comment]
@JJunM 
sorry! we forgot to upgrade the version of airtest in PyPI ...
you can pip install -U airtest to 1.0.27 right now.
we add some new image recognition algorithm, and AirtestIDE use the 1.0.27 version, you can try it first.

this is the log in my AirtestIDE:
![image](https://user-images.githubusercontent.com/6896468/58403044-5587f780-8094-11e9-8565-39b0443409b6.png)
it shows that we are trying to use several different algorithms, and the result is `confidence`, and it must be bigger than the `threshold` to success

**Comment by JJunM** [comment]
> @JJunM
> sorry! we forgot to upgrade the version of airtest in PyPI ...
> you can pip install -U airtest to 1.0.27 right now.
> we add some new image recognition algorithm, and AirtestIDE use the 1.0.27 version, you can try it first.
> 
> this is the log in my AirtestIDE:
> ![image](https://user-images.githubusercontent.com/6896468/58403044-5587f780-8094-11e9-8565-39b0443409b6.png)
> it shows that we are trying to use several different algorithms, and the result is `confidence`, and it must be bigger than the `threshold` to success

<img width="1046" alt="스크린샷 2019-05-27 오후 4 44 30" src="https://user-images.githubusercontent.com/46311868/58404226-9afdf200-809f-11e9-958b-7c6cc2606195.png">
<img width="655" alt="스크린샷 2019-05-27 오후 4 45 06" src="https://user-images.githubusercontent.com/46311868/58404237-a4875a00-809f-11e9-87a6-4e824e2b5e2e.png">

**Comment by yimelia** [comment]
>.< very strange!

show me more log before the traceback?

**Comment by JJunM** [comment]
> very strange!
> 
> show me more log before the traceback?

hi,@yimelia
<img width="1432" alt="스크린샷 2019-05-27 오후 5 01 12" src="https://user-images.githubusercontent.com/46311868/58405041-80c51380-80a1-11e9-9abe-1ba91075a267.png">
<img width="1434" alt="스크린샷 2019-05-27 오후 5 01 32" src="https://user-images.githubusercontent.com/46311868/58405055-8a4e7b80-80a1-11e9-9612-bdb5501068be.png">
<img width="1426" alt="스크린샷 2019-05-27 오후 5 01 52" src="https://user-images.githubusercontent.com/46311868/58405074-90dcf300-80a1-11e9-8296-a16e5592c946.png">
<img width="1431" alt="스크린샷 2019-05-27 오후 5 02 22" src="https://user-images.githubusercontent.com/46311868/58405094-9afef180-80a1-11e9-8a0f-5a73ea2865fe.png">
<img width="1434" alt="스크린샷 2019-05-27 오후 5 02 56" src="https://user-images.githubusercontent.com/46311868/58405105-a520f000-80a1-11e9-82c3-d812806dc02d.png">

**Comment by yimelia** [comment]
hi @JJunM 
sorry for the late reply, i think it may be because of the portrait and landscape orientation 
![image](https://user-images.githubusercontent.com/6896468/58411641-51b1a080-80a7-11e9-899b-47073595a4cc.png)

right click the editor and chose the `Image render/Code`, your pictures will turn to code like this:
![image](https://user-images.githubusercontent.com/6896468/58411779-a0f7d100-80a7-11e9-91cc-2d00fc04b608.png)
the `resolution=(1280, 720)` is my phone's resolution, and it's in `landscape` mode.

add this code before your `touch` and see what's the result
```
auto_setup(__file__)
dev = device()
print(dev.get_current_resolution())
```
if the `cureent resolution` is not `(2208, 1242)`, maybe it's the problem(airtest reads a wrong resolution)

**Comment by JJunM** [comment]
> 
> 오른쪽 편집기를 클릭하고를 선택 `Image render/Code`: 사진은 같은 코드에 켜집니다 (가) 내 휴대폰의 해상도이며,에서의 모드.
> ![영상](https://user-images.githubusercontent.com/6896468/58411779-a0f7d100-80a7-11e9-91cc-2d00fc04b608.png)
> `resolution=(1280, 720)``landscape`
> 
> 전에이 코드를 추가 `touch`하고 결과가 무엇인지 확인하십시오.
> 
> ```
> auto_setup(__file__)
> dev = device()
> print(dev.get_current_resolution())
> ```
> 
> 그렇지 `cureent resolution`않다면 `(2208, 1242)`아마도 문제 일 것입니다 (공기 검사는 잘못된 해결책을 읽습니다)

**Comment by JJunM** [comment]
hi,@yimelia
 
<img width="1064" alt="스크린샷 2019-05-28 오전 8 58 29" src="https://user-images.githubusercontent.com/46311868/58442688-caf0d800-8127-11e9-8463-0fcb094539c0.png">

**Comment by yimelia** [comment]
@JJunM 
what's your iOS version?

**Comment by JJunM** [comment]
@yimelia 

iphone 8plus (os 11.0.3)

**Comment by JJunM** [comment]
> @JJunM, if you want to minimize this issue then set a high threshold value (more than 80 or 95 depends).
> In your image, remove extra white space,
> try to use exact image portion
> 
> for example, In UI automation "number 10" and "18" has near about 90 % same look.
> 
> for me, custom python works perfectly fine, I run on both Windows and iOS.
> also with airtest IDE and cmd/terminal prompt.
> 
> also, don't use touch() directly and use with wait function.
> 
> search for other images (as a dependency) and then use the click button.
> 
> ![image](https://user-images.githubusercontent.com/25879455/58395855-5d37a400-8074-11e9-8710-b00f5932418c.png)

hi @SUDARSHANCHAUDHARI
thanks for letting me know.

**Comment by yimelia** [comment]
what's the result of this code:
```
dev = device()
print(dev.display_info())
```

please run it in your python.exe env and internal python in AirtestIDE, post the two result to us
i think one of them is incorrect, but I don't know why...

**Comment by JJunM** [comment]
hi,@yimelia

<img width="804" alt="스크린샷 2019-05-28 오후 5 00 54" src="https://user-images.githubusercontent.com/46311868/58461276-39ef2080-816a-11e9-8d5d-db52ce8101e9.png">

**Comment by yimelia** [comment]
ah, sorry @JJunM 
dev.display_info() -> print(dev.display_info)

**Comment by JJunM** [comment]
@yimelia 

**custom python**
<img width="854" alt="스크린샷 2019-05-29 오전 9 20 35" src="https://user-images.githubusercontent.com/46311868/58520728-27212e00-81f4-11e9-92b2-89991b755171.png">
<img width="1437" alt="스크린샷 2019-05-29 오전 9 21 31" src="https://user-images.githubusercontent.com/46311868/58520732-2e483c00-81f4-11e9-9735-b5cc3fddb520.png">

**internal python** 
<img width="857" alt="스크린샷 2019-05-29 오전 9 23 56" src="https://user-images.githubusercontent.com/46311868/58520644-ad894000-81f3-11e9-9e9c-9c41863ef37f.png">

**Comment by yimelia** [comment]
hi @JJunM 
the version of airtest in the AirtestIDE is the same as the airtest in your local python environment, so I'm not sure why this happens.
but a temporary solution is to delete two lines in the airtest code in your python env( in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/ios/ios.py):

in [line 131](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/ios/ios.py#L131)
```
if self.display_info["orientation"] in [LANDSCAPE, LANDSCAPE_RIGHT]:
            w, h = h, w
```
delete this and try again may solve your problem temporary, we need more time to test if it in other versions of iOS is ok.

We are very sorry about this BUG, and we'll fix this as soon as possible.

**Comment by EraChen233** [comment]
@JJunM  After fully test we have found the very solution for your problem. Correct the way @yimelia offers.

Find `ios.py` in your python env( in `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/ios/ios.py`):

Comment these statements in function `snapshot`

![image](https://user-images.githubusercontent.com/5961185/58616370-16ee7900-82f0-11e9-8b6b-b12e6d5602f5.png)

**Comment by JJunM** [comment]
> @JJunM 테스트를 마친 후 문제에 대한 해결책을 찾았습니다. @yimelia가 제공 하는 방법을 수정하십시오 .
> 
> `ios.py`python env (in `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/ios/ios.py`) 에서 찾으십시오 .
> 
> 함수에서이 명령문을 주석으로 처리하십시오. `snapshot`
> 
> ![영상](https://user-images.githubusercontent.com/5961185/58616370-16ee7900-82f0-11e9-8b6b-b12e6d5602f5.png)
hi, @yimelia,@erachen223
When will the issue be fixed?

**Comment by dumplingroll** [comment]
这个问题没有解决啊，按照说的改了，照样报错
使用pip安装的airtest进行swipe报错，使用airtestide正常，右键运行选定代码正常
`File "/usr/local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airtest/core/api.py", line 322, in swipe
    G.DEVICE.swipe(pos1, pos2, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airtest/core/ios/ios.py", line 240, in swipe
    tx * self._touch_factor, ty * self._touch_factor, duration)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 557, in swipe
    x1, y1 = self._percent2pos(x1, y1, size)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 505, in _percent2pos
    assert w >= x >= 0
AssertionError`
