### ISSUE TITLE
如何在另一台电脑上查看测试报告

### ISSUE THREAD

**Issue by kongguliu** [AirtestProject/Airtest#413]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
        我们的项目是通过Jenkins集成的，通过Jenkins，在流水线里面写代码，在节点电脑A上运行测试脚本，测试报告也在节点电脑上。然后我们想在Jenkins工作空间里，设置一个类似按钮类型，在电脑B上点击就直接打开了网页的测试报告。
       但是我发现HTML文件的测试报告，对所有资源的加载都是采用绝对路径，比如图片。
       或者有什么办法，可以在电脑B上查看电脑A里的测试报告。
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
请查看[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id14)
