### ISSUE TITLE
安卓环境AirtestIDE使用问题—如何进行身份证验证

### ISSUE THREAD

**Issue by Ironman12138** [AirtestProject/Airtest#415]
**描述问题bug**
在业务进行到需要做身份证的验证和人脸识别，但是不知道怎么样在按了拍摄按钮后可以提交照片。（对应WEB的是send key的方法）
```
**相关截图**
![微信图片_20190528155402](https://user-images.githubusercontent.com/51112427/58460782-df9d9200-8160-11e9-918c-475f86005ddd.png)
![20190528155220](https://user-images.githubusercontent.com/51112427/58460790-e3311900-8160-11e9-8ce2-562370758837.png)

**预期效果**
想用这按钮过后就直接可以提交对应的图片，就是不知道用哪个方法


**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

在windows上

**Comment by Ironman12138** [comment]
Path from root node: [0, 0, 0, 0, 0, 0, 2, 0]
Payload details:
	  type :  android.widget.ImageButton 
	  name :  com.bonade.xfh:id/oliveapp_face_takePictureButton 
	  enabled :  True 
	  visible :  True 
	  checkable :  False 
	  pos :  [0.5, 0.8888888888888888] 
	  resourceId :  b'com.bonade.xfh:id/oliveapp_face_takePictureButton' 
	  scrollable :  False 
	  boundsInParent :  [0.26666666666666666, 0.08888888888888889] 
	  selected :  False 
	  anchorPoint :  [0.5, 0.5] 
	  size :  [0.26666666666666666, 0.08888888888888889] 
	  zOrders :  {'global': 0, 'local': 1} 
	  editalbe :  False 
	  checked :  False 
	  focused :  False 
	  touchable :  True 
	  package :  b'com.bonade.xfh' 
	  scale :  [1, 1] 
	  dismissable :  False 
	  longClickable :  False 
	  focusable :  True 
按钮的属性

**Comment by yimelia** [comment]
抱歉，既然是人脸识别，就是要保证是真人在使用，用自动化的方式很难绕开，而且暂时也没有相关接口。
如果是你们自己的产品，可以考虑让程序帮你实现一个内部版本绕开这个验证。

**Comment by Ironman12138** [comment]
好的，thanks!






在 2019-05-28 15:00:32，"yimelia" <notifications@github.com> 写道：


抱歉，既然是人脸识别，就是要保证是真人在使用，用自动化的方式很难绕开，而且暂时也没有相关接口。
如果是你们自己的产品，可以考虑让程序帮你实现一个内部版本绕开这个验证。
