### ISSUE TITLE
QtWebEngineProcess.exe 有严重内存泄漏

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/Airtest#417]
![image](https://user-images.githubusercontent.com/386347/58676298-51a4ef80-838a-11e9-8483-755ed9fd051c.png)

挂机1晚上（昨晚1点左右离开的，今早9点半发现 QtWebEngineProcess.exe 占了99%的内存，如上图所示）

启动airtestIDE.exe 没有日志，即昨晚离开前，airtestIDE.exe只是挂机，没有在跑脚本。
另外，本机同时启动了 pycharm v2018.1.1，也是挂机状态，
链接电脑的vivi x6d屏保状态。
没有其他日志信息（airtestIDE日志正常，因为昨晚下班前，airtestIDE.exe没有链接手机设备）

环境信息
windows 7 64位 专业版 Service Package 1，16GB内存
vivo x6d手机，android 5.1，vivo ROM: Funtouch OS_2.5
airtestIDE: AirtestIDE_v1.2.1_2019-04-16_py3_win64_20190509161900
![image](https://user-images.githubusercontent.com/386347/58676707-c75d8b00-838b-11e9-8159-4f4edc68fe29.png)

**Comment by yimelia** [comment]
昨天是否有IDE卡死/闪退等情况。
有一种情况是，IDE闪退后，进程内残留了这个QtWebEngineProcess.exe，下次再开也不会自动被销毁，导致它一直在占用着系统资源

**Comment by Meteorix** [comment]
先关issue了，有后续情况请留言

**Comment by 18569256105** [comment]
我也遇到了，用的3dmax。经常这个应用就自动跑起来占到百分之百。软件闪退，电脑卡死。
![QQ截图20230820175922](https://github.com/AirtestProject/Airtest/assets/142721077/3cde9dc1-3ccc-4771-8f2f-1309b295e11d)
![QQ截图20230820175951](https://github.com/AirtestProject/Airtest/assets/142721077/3883a8f9-d187-4fe8-842a-2dafa88e7bb8)
