### ISSUE TITLE
ios多台手机同时执行如何实现，目前我插了两台手机在一个mac上，只有一台能执行

### ISSUE THREAD

**Issue by jeniva** [AirtestProject/Airtest#419]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

ios多台手机同时执行能不能提供一个demo,之前看人家提问里面有个Android的，我把Android换成iOS就不行，只有一台能执行。我说一下我的尝试，我是通过xcodebuild -project WebDriverAgent.xcodeproj
   -scheme WebDriverAgentRunner -destination id=xxxx  clean test的方式分别对两个手机进行build都提示成功了，然后另外开启一个窗口执行iproxy 8100 8100,再另启了两个或一个窗口执行airtest，执行命令尝试了对于uuid序列号的或者不传序列号的，比如：airtest run /Users/test01/Downloads/test.air --device ios:///http://127.0.0.1:8100  --log /Users/test01/Downloads/case_report 或者  airtest run /Users/test01/Downloads/test.air --device ios:///d939d7220c15b489e5acf8b22a7a36350b983635/  --log /Users/test01/Downloads/case_report   或者 device ios:///http://127.0.0.1:8100/d939d7220c15b489e5acf8b22a7a36350b983635等等。

不知道ios是怎么对于不同手机序列号进行执行的，iOS多台手机同时执行成功的案例是否能提供借鉴一下，谢谢。另外IDE里面也能同时执行多台手机吗？

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by EraChen233** [comment]
目前的iOS-tagent 对端口使用了硬编码的方式，所以一个Mac只能通过iOS-tagent控制一台iPhone
Duplicate of #322

**Comment by jeniva** [comment]
那就是一台mac只能执行一个手机是吗？后续iOS-tagent会更新控制多台手机吗？我看到yimelia说的有点不确定是否可以？如果可以的话我再想办法实现。
![image](https://user-images.githubusercontent.com/8514029/58694557-d5300200-83c5-11e9-950a-b02735239074.png)

**Comment by EraChen233** [comment]
一台MAC只能控制一个手机。

IDE一次 **也是** 只能连接一个iOS设备的，你可以打开IDE看看它的设备连接，没有连接多台设备的选项
假设：你已经使用 n 台 Mac 控制 n 台 iPhone
为了在iOS上运行多机脚本，你还要另外写运行脚本，而不能直接使用IDE执行你的脚本

**Comment by jeniva** [comment]
好的，谢谢，后续你们有打算支持一台mac跑多台手机吗
