### ISSUE TITLE
支持单PC连接多设备并发执行吗

### ISSUE THREAD

**Issue by lxf920125** [AirtestProject/Airtest#420]

**Comment by EraChen233** [comment]
目前不支持

**Comment by lxf920125** [comment]
好的谢谢，如果能够支持了就舒服了，多个手机并发测试，效率更高

**Comment by EraChen233** [comment]
IDE可以连接多个安卓设备。
iOS 多设备如果需求大，我们回考虑进行扩展的

**Comment by lxf920125** [comment]
嗯 我这边遇到的是单PC连接多个设备，然后并发执行，存在部分手机操作失败的情况，好像是ADB互相干扰造成的

**Comment by EraChen233** [comment]
新建一个issue，说明一下你的具体操作，还有报错日志贴上来吧

**Comment by lxf920125** [comment]
内网安全管控发不出来，我是底层SDK的GameObject后去信息这层跟airtest一样，其余的全是自行开发的，python客户端这一层，我是通过uiautomator对adb的封装处理，向设备发起操作的，单设备执行没发现问题每天执行测试时长达8个小时以上

**Comment by lxf920125** [comment]
但是我多线程执同一个脚本，通过设备序列号控制消息发送的对象，此时单我做滑动和点击操作，部分手机会无响应，adb操作失败

**Comment by EraChen233** [comment]
根据现有信息，无法定位问题。
另外我们这边不负责解答airtest以外的问题，鉴于你是自行开发的，所以我们也无法帮你
建议使用多进程执行airtest测试脚本，可以参考这个例子
https://github.com/AirtestProject/multi-device-runner

**Comment by lxf920125** [comment]
好的 感谢

**Comment by yuzhujiutian** [comment]
@lxf920125 
厉害，都自行开发。

你们的开发思路方法，如果可以的话，去掉项目信息，搞个demo代码出来让大家一起膜拜学习。

**Comment by lxf920125** [comment]
@yuzhujiutian 抱歉哦 在内网发不出来 底层使用Unity方法处理gameobject信息，建立server，Python客户端向游戏底层发送消息并接受反馈的信息进行处理就行 操作手机方式很多 adb uiautomator等都行 只是稳定性这块就要靠自己调试了

**Comment by lxf920125** [comment]
@EraChen233 单PC连多设备 脚本并发实行 我这边adb操作改用python adbClient 和4037建立socket连接，一定程度上减小了adb互相干扰的问题，目前3个设备并行执行统一脚本效果还行，但还不保证不出问题 希望大佬们能够有更好方案
