### ISSUE TITLE
check_app检测不到app时报错，而不是返回False

### ISSUE THREAD

**Issue by WalkerMe** [AirtestProject/Airtest#422]
**描述问题bug**
check_app文档对返回值的描述是：
`True or False whether the package exists on the device or not`
实际上，找不到app时会抛出异常，而不会返回False。

```
  File "G:\Workspace\PyCharm\AirtestSign\venv\lib\site-packages\airtest\core\android\android.py", line 105, in check_app
    return self.adb.check_app(package)
  File "G:\Workspace\PyCharm\AirtestSign\venv\lib\site-packages\airtest\core\android\adb.py", line 1169, in check_app
    raise AirtestError('package "{}" not found'.format(package))
airtest.core.error.AirtestError: 'package "com.xxx.yyy" not found'
```

**期待结果**
android.py中的实现应该捕捉adb.py里的异常，然后返回False，而不是直接return调用

**复现步骤**
调用check_app检测一个设备上没安装的应用。

**python 版本:** `python3.5`
**airtest 版本:** `1.0.26`

**Comment by yimelia** [comment]
hi @WalkerMe 
这个属于之前的代码注释和文档写错了，在最新版本中已经修改为：找不到对应的app时将会抛出异常，而不是返回False。
对应代码和文档注释详见 [这里](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/android.py#L102)

**Comment by WalkerMe** [comment]
> 
> 
> hi @WalkerMe
> 这个属于之前的代码注释和文档写错了，在最新版本中已经修改为：找不到对应的app时将会抛出异常，而不是返回False。
> 对应代码和文档注释详见 [这里](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/android.py#L102)

为什么这样实现？这样设计接口的意义是什么？从易用性上讲，返回False对高层代码更友善。

**Comment by yimelia** [comment]
这个问题可以让 @Meteorix 帮你解答一下
