### ISSUE TITLE
Mac配置使用本地python3 运行时出错

### ISSUE THREAD

**Issue by Chersh-Pan** [AirtestProject/Airtest#426]
ile "/usr/local/lib/python3.7/site-packages/wda/__init__.py", line 89, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value='bundleId' desired capability not provided)

如果不配置本地python是没有问题的，这是为什么呢？

**Comment by yimelia** [comment]
贴一下你的IDE的配置里，python那行配置出来看看
如果条件允许的话，可以简单写个touch语句，然后用android手机再试试看，看看是否能排除掉本地python的问题

**Comment by Chersh-Pan** [comment]
这个我把旧的wda模块拷贝过去就解决了，是python中wda那个模块出问题了
