### ISSUE TITLE
使用命令行执行web自动化脚本生成的html没有界面截图

### ISSUE THREAD

**Issue by wuzechuan** [AirtestProject/Airtest#428]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
使用命令行运行airtest脚本运行app自动化html是有截图展示的，但是使用命令行运行web自动化的html没有截图展示，用IDE运行web自动化有html截图展示
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
命令行运行的html报告效果图
![20190619141007](https://user-images.githubusercontent.com/14210962/59740884-ff296580-929b-11e9-81b1-00019e377de9.png)

**复现步骤**
1、命令行运行web自动化脚本，通过 report.LogToHtml生成html报告

**预期效果**
(预期想要得到什么、见到什么)
1、与IDE报告展示内容一致，目前有的展示内容有一些偏差且没有截图展示

**python 版本:** `python3.6.4`

**airtest 版本:** `1.0.27`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
参考一下这个[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#selenium)
在命令行后面加上 `--plugin airtest_selenium.report`
记得确保本地python环境已经装了`airtest_selenium`
