### ISSUE TITLE
log.txt文件中的filepath是写死的绝对路径。能否改成（主程序）的相对路径

### ISSUE THREAD

**Issue by cccthon** [AirtestProject/Airtest#433]
log.txt文件中的filepath是写死的绝对路径。
通过log.txt生成的report.html 所读取的文件资源都是通过这些绝对路径获取。
一旦我需要把报告，打包给别人或更换位置（比如放nginx服务器上）那么都会读取不到文件资源而打开报告失败。

以下是 log.tx日志。   当我打包报告给别人是，打开报告还是会去以下filepath路径获取资源。

{"data": {"call_args": {"screen": "array([[[202, 167, 141],\n        [200, 164, 140],\n        [202, 160, 141],\n        ...,\n        [207, 167, 139],\n        [208, 168, 140],\n        [209, 169, 141]],\n\n       [[203, 166, 140],\n        [200, 162, 138],\n        [201, 159, 140],\n        ...,\n        [209, 169, 141],\n        [209, 169, 141],\n        [209, 169, 141]],\n\n       [[209, 169, 144],\n        [207, 165, 142],\n        [203, 160, 141],\n        ...,\n        [212, 172, 144],\n        [210, 170, 142],\n        [208, 168, 140]],\n\n       ...,\n\n       [[  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       [[  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       [[  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]]], dtype=uint8)", "self": {"filename": "/home/gitlab-runner/builds/5VAdgMWr/0/FollowmeTest/appuitest/item/picture/android/CN/Home/pendingAccProcess.jpg", "_filepath": "/home/gitlab-runner/builds/5VAdgMWr/0/FollowmeTest/appuitest/item/picture/android/CN/Home/pendingAccProcess.jpg", "threshold": 0.7, "target_pos": 5, "record_pos": null, "resolution": [], "rgb": false, "__class__": "Template"}}, "start_time": 1561023054.4419475, "end_time": 1561023055.4388847, "name": "_cv_match", "ret": null}, "depth": 3, "tag": "function", "time": "2019-06-20 17:30:55"}

**Comment by EraChen233** [comment]
用 [auto_setup](https://airtest.readthedocs.io/zh_CN/latest/all_module/airtest.core.api.html#airtest.core.api.auto_setup) 吧

``` python
from airtest.core.api import *
auto_setup(__file__, logdir=r"D:\test\log",)
```

**Comment by yimelia** [comment]
如果是要发送报告给别人看，可以用`--export dir`指令导出一个完整的报告，包含静态文件的，参考[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id14)

**Comment by cccthon** [comment]
非常感谢。

**Comment by WindInMay524** [comment]
@yimelia ，我用jenkins执行用例，跑失败的时候就会出现图片没有加载到log文件夹下，单独执行是可以的，可能是哪些原因造成的
![image](https://user-images.githubusercontent.com/38344643/59918913-a9e68300-9458-11e9-8d58-141ab43ea6bd.png)

**Comment by yimelia** [comment]
@WindInMay524 请描述一下具体的操作流程、错误原因、报错log

**Comment by cccthon** [comment]
@yimelia   通过 --export导出的报告， 预期图片资源路径还是写死的。  打包移动报告后，导致报告 "exists" 节点图片资源无法加载。 如下图：

![image](https://user-images.githubusercontent.com/19815750/60068054-b4966600-973f-11e9-9326-410ac824740e.png)

**Comment by yimelia** [comment]
是用了我们的多设备的项目来跑的吗？https://github.com/AirtestProject/multi-device-runner ？

**Comment by cccthon** [comment]
对哟， 经过了一些改装。      
         但是我单独测试  --export，   生成的报告预期图片资源路径也是写死的（即exists 节点）。

**Comment by WindInMay524** [comment]
@ 


> @WindInMay524 请描述一下具体的操作流程、错误原因、报错log

1.我脚本创建的是air文件
2.我写了一个python文件循环遍历air文件，使用run，report文件定义的方法批量执行
3.我是通过windows10机器执行的，svn管理代码
4.我用jenkins调用windows窗口执行python脚本

运行成功后打开log.html文件，如果脚本运行是失败的（根据断言判定的），脚本中断言的图片未加载出来，但是能找到的没有报错，如果脚本运行是成功的，显示正常

**Comment by EraChen233** [comment]
> 对哟， 经过了一些改装。
> 但是我单独测试 --export， 生成的报告预期图片资源路径也是写死的（即exists 节点）。

@cccthon 
预期资源查找不到的问题，是因为脚本有误，需要检查一下你编写的 airtest 脚本，可以使用IDE打开测试脚本，更直观一些。

**Comment by yimelia** [comment]
@cccthon 
单独export报告，脚本文件夹、图片资源会被一起拷贝到export出来的文件夹里，在HTML中是可见的：
![image](https://user-images.githubusercontent.com/6896468/60074128-c59da200-9754-11e9-82e2-84d3ca3f91a8.png)

log中确实有写死的图片静态路径，但是单独export出来的报告是可以看的。

**Comment by cccthon** [comment]
找到问题点了。 
我定义了一个project_dir ， 然后所有的预期对比图片都放在了project_dir/item下面。所有的测试脚本都会去这个目录下面获取通用图片资源。导致出现的这个问题。
我测试了，如果把图片资源放到 xx.air目录里面 即脚本的当前路径是没有问题的 。。。 
就算放到脚本的上一级路劲或写成相对路径也是有问题的，比如： 
wait(Template('../recommend_cn.jpg'), timeout=5)   
![image](https://user-images.githubusercontent.com/19815750/60081242-ff29d980-9763-11e9-9c10-60020d5c4cdf.png)

希望可以提供灵活指定资源位置的方法，因为多个测试脚本很多图片是通用的。也便于管理
