### ISSUE TITLE
【控件识别】屏幕发生旋转时(竖屏到横屏)，poco计算控件位置不正确，ios

### ISSUE THREAD

**Issue by jianmei1987** [AirtestProject/Airtest#435]
在iphone7上，下载游戏后打开，弹出“通知权限请求”框体时，poco定位到的“允许”按钮的位置已经超出了屏幕，截图及调试信息如下：
<img width="550" alt="屏幕快照 2019-06-26 下午4 15 41" src="https://user-images.githubusercontent.com/13903783/60163823-f94cfa80-982e-11e9-9fca-8208a1cc0c72.png">
![IMG_9741](https://user-images.githubusercontent.com/13903783/60163948-429d4a00-982f-11e9-81bd-3669e92ab43f.PNG)

poco版本：1.0.76
<img width="302" alt="屏幕快照 2019-06-26 下午4 24 06" src="https://user-images.githubusercontent.com/13903783/60164021-62347280-982f-11e9-8d58-f97d53dfc58c.png">

通过计算，只要将x的坐标百分比和y的坐标百分比互换一下，便可以得到正确的位置

重现步骤：
1、下载“朕的江山”(也可以是其他有权限请求的横屏app)
2、打开app，等待弹窗出现
3、使用poco去点击“允许”按钮

运行环境：
iphone7、mac、python3.7

**Comment by EraChen233** [comment]
这个问题我们已经修复，会在下一个版本发出
