### ISSUE TITLE
JSONDecodeError : Expecting value : line 1 column 1 (char 0) when connecting to Nox Android Emulator

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/Airtest#439]
Remove any following parts if does not have details about

**Describe the bug**
JSONDecodeError message received when trying to connect to an Android Emulator.

![image](https://user-images.githubusercontent.com/19833754/60177662-075d4400-984c-11e9-9a28-1e1f20fb52e0.png)

1. Download Nox
2. In settings, enable root
![image](https://user-images.githubusercontent.com/19833754/60177684-180dba00-984c-
11e9-91c5-574e4c2df297.png)
3. Then, enable ADB
![image](https://user-images.githubusercontent.com/19833754/60177711-29ef5d00-984c-11e9-9671-85f5799ae747.png)
4. Then, connect to the Nox-given IP using Airtest.
5. Encounter error.

**Expected behavior**
Airtest should able to connect to an android emulator.

**python version:** `python3.7.2`

**airtest version:** `1.2.0`

**Smartphone (please complete the following information):**
 - Nox default settings

**Additional context**
Trying to run air test on Android Emulator.

**Comment by yimelia** [comment]
hi @phantomsom 
just check the `use javacap` option before connecting to the Nox
![image](https://user-images.githubusercontent.com/6896468/60180808-6e322b80-9853-11e9-8a6a-2a4b47d636f2.png)

**Comment by phantomsom** [comment]
![image](https://user-images.githubusercontent.com/19833754/60227670-ca806400-98c2-11e9-9436-273498aa4dce.png)

![image](https://user-images.githubusercontent.com/19833754/60227684-d79d5300-98c2-11e9-97e5-db161577fe3e.png)

( Still doesn't work :[ )

Tried ADB Orientation and Touch, but I get black screen instead of Android Emulator screen
![image](https://user-images.githubusercontent.com/19833754/60227809-3e227100-98c3-11e9-9c38-a1e8c0315f14.png)

**Comment by yimelia** [comment]
This is our step to connect to the emulator:

1. check the `USB debugging` option in developer options:
![image](https://user-images.githubusercontent.com/6896468/60228445-49769c00-98c5-11e9-9548-815d8407b037.png)

2. connect to localhost:62001, not the emulator's IP:
![image](https://user-images.githubusercontent.com/6896468/60228504-75921d00-98c5-11e9-8dd8-37066e939f80.png)

3. check the `use javacap` and `use ADB orientation` options, then click `connect`

we've tried NOX v6.1.1 is ok, hope this helps you

**Comment by yimelia** [comment]
if you can't find `Developer options`, try to click `Settings`-`About` multiple times

**Comment by phantomsom** [comment]
Thanks. This solved my issue!
