### ISSUE TITLE
python3.7在windows命令行运行air脚本提示do not save log

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#449]
安装python3.7，并且安装了airtest和pocoui包，使用命令py -3 -m airtest run E:\scripts\test\test1.air  --device Android://127.0.0.1:5037/91b28dec?ori_method=ADBORI&&touch_method=ADBTOUCH
脚本可以正常运行但是提示do not save log，无法生成日志（加了--log参数及路径也无法生成日志）

**Comment by yimelia** [comment]
在命令行中添加`--log log/`后运行，然后贴一下log看看。

**Comment by ymdhtt** [comment]
![1](https://user-images.githubusercontent.com/26775694/60793903-33a58880-a19b-11e9-9347-75bc166d5534.jpg)

**Comment by ymdhtt** [comment]
@yimelia 加了--log log/还是提示do not save log

**Comment by yimelia** [comment]
看一下airtest的版本号是多少？
以及贴一下脚本内容看看，脚本里的auto_setup接口那里是怎么写的？

**Comment by ymdhtt** [comment]
# -*- encoding=utf8 -*-
__author__ = "mj"

from airtest.core.api import *
from poco.drivers.unity3d import UnityPoco

auto_setup(__file__)

def login():
    mypoco = UnityPoco()
    login_ui = mypoco("content").wait(5)
    if login_ui.child("Text_Name").get_text() == "test1":
        mypoco("Btn_Login").click()
    else:
        creataccount()

**Comment by ymdhtt** [comment]
@yimelia auto_setup(__file__)没有修改东西，用的默认，这个auto_setup是作什么用的
另外airtest的版本是1.0.27

**Comment by yimelia** [comment]
`auto_setup(file)`不会报错么？
应该是 `auto_setup(__file__)`

这个接口是和命令行一起，对脚本的各项环境进行初始化的。理论上不传参数的话，默认是会保存log的。

**Comment by ymdhtt** [comment]
@yimelia 是auto_setup(__file__)贴上去的时候贴错了，脚本里是auto_setup(__file__)

**Comment by ymdhtt** [comment]
@yimelia 我在auto_setup(\_\_file\_\_,logdir=True)，设置参数logdir=True，虽然控制台还是显示do not save log，但是已经能在脚本所在目录生成log了（之前无法生成）

**Comment by Meteorix** [comment]
@ymdhtt 感谢反馈，这可能是新版本的bug，我们会修复

**Comment by yimelia** [comment]
hi @ymdhtt 
我验证了一下这个问题，应该不是BUG，是windows下输入命令行的转义问题，详情请查看[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id10)
直接执行命令行，会导致`&&`符号没有被正确解析，所以命令行其实在第一个&&符号出现的时候已经中断了，后续的内容都没有正确传入airtest，添加转义符号之后就可以了

**Comment by ymdhtt** [comment]
@yimelia 
你说的没错，这个问题，我后来也发现是转义问题，已经解决，没有及时反馈给你，给你添麻烦了，抱歉
