### ISSUE TITLE
用pycharm运行脚本报RpcTimeoutError

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#450]
@yimelia 
同一份脚本在airtestIDE里正常运行，在pycharm环境下运行报RpcTimeoutError
附报错截图：
![2](https://user-images.githubusercontent.com/26775694/60812200-8b57ea00-a1c3-11e9-8214-96348a564666.jpg)

附脚本：
[test1.txt](https://github.com/AirtestProject/Airtest/files/3368445/test1.txt)

**Comment by yimelia** [comment]
初始化一次poco对象即可，没必要在每个子函数里都初始化一次
