### ISSUE TITLE
win10环境最新版airtest脚本编辑视图窗口不起作用，录制脚本没有任何反应，后台提示QQuickWidget鼠标控件失效，请教

### ISSUE THREAD

**Issue by dxjnb233** [AirtestProject/Airtest#452]
![O6LA K _N3DP(80_NM7%3T](https://user-images.githubusercontent.com/33518209/61183945-66a7ba80-a67a-11e9-8b6f-986bce246d36.png)
![E(QV2E9F5YSOXBQ6(A{VD)I](https://user-images.githubusercontent.com/33518209/61183976-bab29f00-a67a-11e9-95ad-458614bd0ac4.png)
求教！

**Comment by yimelia** [comment]
参考这个： https://github.com/AirtestProject/AirtestIDE/issues/438#issuecomment-504846599
