### ISSUE TITLE
资源混淆的apk，能否在提供资源文件的情况下，直接增加支持混淆前后的id自动匹配映射？

### ISSUE THREAD

**Issue by jiuyuejiu** [AirtestProject/Airtest#457]
遇到apk被混淆的情况，获取到的控件和布局都是被混淆后的，随着版本会随机变化，能否提供支持，使在拿到资源文件后，能自动映射被混淆的资源？
--- 期待支持---

**Comment by yimelia** [comment]
这个需求其实不在poco的考虑范围内，所以暂时不会纳入开发计划中。
不过利用现有接口，你们可以自行实现对应功能：在dump到整棵树的内容后，用你们的资源映射文件复原出原先的树，再进行后续操作。
