### ISSUE TITLE
曲面屏手机点击位置错位

### ISSUE THREAD

**Issue by youhayouha** [AirtestProject/Airtest#46]
vivo xplay6  曲面屏   脚本的实际点击位置会比录制位置高
  有错位
![qq 20180427101447](https://user-images.githubusercontent.com/18697420/39341027-d764e54c-4a03-11e8-9636-f20411f7acb7.jpg)

**Comment by rockywhisper** [comment]
@youhayouha  Hi，已经收到你的QQ私信消息了，我们查证下。

**Comment by wwllss** [comment]
好像是手机为了省电降低了分辨率导致，华为Mate 10也是这样，改成最高分辨率之后便好了。

**Comment by Dannie1932** [comment]
我的三星曲面屏手机（三星盖乐世S7edge）也有类似的情况，设备屏幕区获取的设备屏幕只占整个区域的左上角大约2/3
![default](https://user-images.githubusercontent.com/44199168/47545145-3cac3d80-d91d-11e8-8ca6-9f93f1e4f348.jpg)

**Comment by yimelia** [comment]
@Dannie1932 请查阅设置[文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id9)，将分辨率调大即可
