### ISSUE TITLE
Wrong resolution on a few devices in airtest panel

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/Airtest#460]
My pixel 2 and Xaomi MiMix 2 work perfect, but Huawei p20 give me this result when i connect device to Airtest, how to fix it?
![Без названия](https://user-images.githubusercontent.com/46621847/61456590-c34ef200-a966-11e9-8fba-bc965158b602.png)
![Без названия (1)](https://user-images.githubusercontent.com/46621847/61456591-c3e78880-a966-11e9-9bfd-b8f931208e6c.png)

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/en/3_faq/android_connection_new.html#samsung

try to set the resolution to maximum
