### ISSUE TITLE
新版本airtest调用底层LogToHtml.report()生成测试报告时出错

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#461]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 报告生成问题

**描述问题bug**
你好，我之前曾在网上使用airtest生成聚合测试报告的myRunner启动器进行测试（具体代码可见https://blog.csdn.net/u010127154/article/details/83375659），这个启动器的核心是调用airtest.cli.runner中的run_script()运行脚本，然后用airtest.report.report中的LogToHtml.report()生成报告。
这个启动器在使用AirtestIDE V1.2.0时运行正常，但使用了AirtestIDE V1.2.1，或airtest-1.0.27之后，**却一直在运行脚本之后报错，无法生成报告**，报错信息如下：

File "D:/自动化回归测试/AirTest/myRunner.py", line 87, in run_air
    rpt.report("log_template.html", output_file=output_file)
  
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 340, in report
    info = json.loads(get_script_info(script_path))
  
File "C:\Users\tanjiahao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\info.py", line 23, in get_script_info
    with open(pyfilepath, encoding="utf-8") as pyfile:

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\自动化回归测试\\AirTest\\win7x64\\main.air\\'

**最后提到的脚本文件是存在的，路径完全正确**。所以我也不明白为什么会找不到。。

我找到了airtest.report.report模块，但是也没发现LogToHtml类中相较前一版本有什么变化。希望能给予解答，**最好能说明一下report()方法是否需要修改传入的参数**，不胜感激。

**python 版本:** `python3.6.8`

**airtest 版本:** `1.0.27`

 - 系统: Windows7-amd64

**其他相关环境信息**
在使用AirtestIDE V1.2.0时运行正常，在使用AirtestIDE V1.2.1，或airtest-1.0.27之后出错

**Comment by yimelia** [comment]
问题可能不在report部分，报错好像是找不到脚本.air目录里面的.py文件，在`airtest/cli/info.py`的`get_script_info()`入口那里把script_path打印出来看看是什么

**Comment by niuniuprice** [comment]
> 问题可能不在report部分，报错好像是找不到脚本.air目录里面的.py文件，在`airtest/cli/info.py`的`get_script_info()`入口那里把script_path打印出来看看是什么

我打印了script_path，结果为'D:\自动化回归测试\AirTest\win7x64\main.air\'，到了脚本目录。但我查看了info.py，里面有另一个变量为script_name为py文件的名字。另外，info.py中对于打开.air和.py是作出了判断的，从逻辑上看就算打开的是.air，最终也会得到.py的pyfile脚本

**Comment by yimelia** [comment]
是的，会去获取.air里的同名.py，但是你的报错信息里面，路径是不完整的，最后没有找到对应的.py文件，报错的路径结尾还有一个斜杠，应该是路径有问题，还需要再调试一下

**Comment by niuniuprice** [comment]
> 是的，会去获取.air里的同名.py，但是你的报错信息里面，路径是不完整的，最后没有找到对应的.py文件，报错的路径结尾还有一个斜杠，应该是路径有问题，还需要再调试一下

尝试把运行脚本的脚本路径改成其目录下同名py文件路径，如 ../abc.air   -->   ../abc.air/abc.py之后，问题解决

**Comment by niuniuprice** [comment]
> 是的，会去获取.air里的同名.py，但是你的报错信息里面，路径是不完整的，最后没有找到对应的.py文件，报错的路径结尾还有一个斜杠，应该是路径有问题，还需要再调试一下

我发现我早上的操作不对，启动器直接跳过了运行脚本。。。。把所有路径都改成.py之后，仍然是报错

报错信息为：
OSError: [Errno 22] Invalid argument: 'D:\\自动化回归测试\\AirTest\\win7x64\\main.air\\main.py\\'

另外，路径结尾那个斜杠应该无伤大雅。。。因为写和不写都是在那个目录里面。。。

**Comment by yimelia** [comment]
文件路径的最后是不能出现斜杠的，否则会报错，需要再调试一下那部分代码，查一下看看为什么最后会多一个斜杠？

![image](https://user-images.githubusercontent.com/6896468/61521710-6b39ed80-aa43-11e9-9122-33af69fb9fe1.png)

**Comment by niuniuprice** [comment]
> 文件路径的最后是不能出现斜杠的，否则会报错，需要再调试一下那部分代码，查一下看看为什么最后会多一个斜杠？
> 
> ![image](https://user-images.githubusercontent.com/6896468/61521710-6b39ed80-aa43-11e9-9122-33af69fb9fe1.png)

在info.py中第一个if判断之前加入了script_path = script_path.strip('\\')后，最后斜杠被删除，程序能够顺利运行。

之后我又试了试，想直接对.air脚本进行斜杠过滤，失败，**如果是用了问题描述中的聚合方法**的朋友，估计只能在新版本里把.air脚本路径换成.py文件的路径，再在运行环境中的cli/info.py中加上这样一行代码进行过滤了。

另外，airtest在report方法中传入的script_path路径从.air变成.py，但是看样子并没有过滤掉内部某些步骤产生的路径末尾斜杠？（也可能是把这个步骤放到了其他地方，但是我调用底层时跳过了），也许下个版本可以考虑一下在这里加上过滤的代码？

**Comment by yimelia** [comment]
好的，感谢提醒，我后续补充一下

**Comment by niuniuprice** [comment]
尝试了一下，在AirtestIDE V1.2.1的cli/info.py中加上这行代码之后仍然无效，但是在本地python环境中可以顺利运行。

**Comment by yimelia** [comment]
不能直接在IDE目录里的代码上面加，因为并不会读取到它们。
只能改本地Python环境里的airtest代码，然后在IDE的设置里，设置本地python.exe路径为自定义python路径
