### ISSUE TITLE
纯python如何打包测试报告

### ISSUE THREAD

**Issue by GitHub-Jatom** [AirtestProject/Airtest#462]
我用纯python写 调用simple_report() 方法发现生成的测试报告带了我本地的绝对路径，请问一下python里还有其他方法类似于airtest report 指令下的--export 功能吗？因为我需要把测试报告提供给其他人

**Comment by GitHub-Jatom** [comment]
看了下源码 可以自己实现 谢谢了

**Comment by yuzhujiutian** [comment]
咋个实现的？
方便的时候，帮忙贴下实现思路和代码块

@GitHub-Jatom
