### ISSUE TITLE
Running .air from CLI has slower slower tests compared to running .air from Airtest IDE

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/Airtest#466]
============================================================
**Describe the bug**
Running .air from CLI has slower tests compared to Running .air from Airtest IDE

Is there a difference between the runner code found in Airtest IDE [Code shown below],
![image](https://user-images.githubusercontent.com/19833754/61527641-84e13200-aa4f-11e9-9e3d-8dfe8e3e69e4.png)

And the runner code used for running .air in CLI?

```
python "-m airtest run $airtestProjectPath\GameRobot.air --device Windows:///?$gameString --log $airtestProjectPath\TestPocoLogs\Run[$i]"
```
```
Reference : https://airtest.readthedocs.io/en/latest/README_MORE.html
``` 

This is because I have multiple tests that works really fast when test is run in Airtest IDE, [ when it comes to storing 100 unity object into python memory.] 

But then when I use CLI to run the same test, the speed greatly reduced and it is about 30 times slower. 

============================================================

**To Reproduce**
![image](https://user-images.githubusercontent.com/19833754/61528892-8829ed00-aa52-11e9-881e-c9937b032887.png)
```
Reference : https://poco.readthedocs.io/en/latest/source/doc/poco-example/advanced_selections.html
```

1. Write Airtest code that uses advanced selection, and store 100 unity objects [For example]

```
testDictionary = [] 
for object in poco("main_node").child('list_item').offspring('name'):
     print("Starting the storing of 100 objects...")
     testDictionary[object.attr('text')] = object 
print("Done!") 
```
2. Run script on Airtest IDE, note the time taken
3. Run script on CLI, note the time taken
4. Compare the time taken
 [running the above code in CLI should take a way longer time compared to Airtest IDE]

============================================================
**Expected behavior**
Make CLI code run faster, or make both Airtest IDE and CLI run code at the same speed 

**python version:** `python3.7`

**airtest version:** `1.2.0`

My scripts are run on the below devices
**Smartphone (please complete the following information):**
 - Device: Windows 10 PC, F1 Pocophone
 - OS: [My python test scripts both tested on Windows and Android], face same CLI speed issue. But no speed problem when run using Airtest IDE

**Comment by phantomsom** [comment]
Edit : I realized the speed of the AirtestIDE is slower as well, once I set up a custom python path in Airtest.
![image](https://user-images.githubusercontent.com/19833754/61610694-687e0900-ac8c-11e9-9fc1-b6103e2abb20.png)

This means that the default path Airtest uses brings fast results, what is the default python path which Airtest uses?

**Comment by phantomsom** [comment]
![image](https://user-images.githubusercontent.com/19833754/61611704-138fc200-ac8f-11e9-8e83-b17b08a802d2.png)
Found it. Does that mean if I use runner.py to call this function, I won't face this problem anymore? 
runner.py "-m airtest run $airtestProjectPath\GameRobot.air --device Windows:///?$gameString --log $airtestProjectPath\TestPocoLogs\Run[$i]"

**Comment by yimelia** [comment]
what's the version of your airtest/pocoui?

**Comment by phantomsom** [comment]
> what's the version of your airtest/pocoui?

I tried reinstall them to find out, turns out I have the newest version
![image](https://user-images.githubusercontent.com/19833754/61612058-117a3300-ac90-11e9-9461-f68f186b1a03.png)

**Comment by yimelia** [comment]
try `pip install -U airtest` to update to 1.0.27, then try again?

**Comment by phantomsom** [comment]
Updated airtest to newest version, it's still the same. 

I realized my question title should now change. I'm going to close this issue and ask a better question.
