### ISSUE TITLE
测试报告指定目录预期不符

### ISSUE THREAD

**Issue by GitHub-Jatom** [AirtestProject/Airtest#469]
我在python项目common目录下定义了一个公共类，然后在根目录运行我的脚本，脚本里指定了log和report路径在base_dir下，最终生成的测试报告不是在report的目录下，而是在report/common下，类似于：
![image](https://user-images.githubusercontent.com/22453572/61622775-08955b80-aca8-11e9-9929-7e683abe35c4.png)
然后我看了下源码，发现里面有这样一行代码，不知道作者是有意为之吗？
![image](https://user-images.githubusercontent.com/22453572/61622835-2b277480-aca8-11e9-81bc-74c94b6890a3.png)

**Comment by yimelia** [comment]
是的。
在正常情况下，运行脚本时，这里的self.script_root会是一个 `脚本名.air` 的路径，因此这里是去获取到脚本名，替换后缀为.log之后，再拼到export_dir里面获得最终输出的路径。
如果你是自行调用接口，修改了运行方式来跑脚本的话，需要调试一下`self.script_root`这个变量在哪里进行了设置（设成了common的路径）

**Comment by GitHub-Jatom** [comment]
嗯嗯 了解了  感谢回答
