### ISSUE TITLE
加--export参数后，如何不生成.log目录 

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#472]
@yimelia 
使用report命令导出报告，加--export参数后面跟上路径，总会在路径下生产一个.log目录
比如--export F:/report，那么就会在F:/report下生产一个xxx.log目录(xxx为具体的用例名)，然后将所有的报告放在xxx目录内
我不想再生成一个.log目录，直接把报告放在report目录下，该如何做（像--log参数，后面跟上路径之后就不会在该路径下又生成一个log目录，而是将日志直接放进指定目录）

**Comment by yimelia** [comment]
可以自行修改源码达成你的需求的。
