### ISSUE TITLE
Template()里的图片路径会影响BeautifulReport生成的前端img标签

### ISSUE THREAD

**Issue by a3247858** [AirtestProject/Airtest#481]
比如某一代码if exists(Template(r"..\oppoimg\shiming.png", record_pos=(-0.033, -0.0), resolution=(2340, 1080)))!=False:
          Screencap.GetScreen(time.time(), devices, "AA")
生成的测试报告会看不到图片，但实际已经截到图，查看报告里的img路径
发现是这样的<oppoimg src=".........."><oppoimg>
从而导致图片不显示，想知道为啥会影响，目前找不到BeautifulReport和Template联合生成报告图片标签的相关代码，求大神指点

**Comment by yimelia** [comment]
>查看报告里的img路径
发现是这样的

是怎样的？没看懂你的问题描述
请补充描述清楚你的问题

**Comment by a3247858** [comment]
发现是这样的后面：<oppoimg src='**********'><oppoimg>

**Comment by a3247858** [comment]
就是img标签变成oppoimg了

**Comment by a3247858** [comment]
所以图片不显示出来

**Comment by yimelia** [comment]
1. 不清楚oppoimg是什么标签，这个和airtest无关，建议自行排查
2. 在没有更多信息的情况下，没办法帮助到你，很抱歉，我先关单了
