### ISSUE TITLE
airtest命令行，在使用纯py脚本生成报告的时候，使用--export，会复制多余文件

### ISSUE THREAD

**Issue by EraChen233** [AirtestProject/Airtest#484]
使用airtest命令行对纯py脚本生成报告的时候，复制多余文件
如下文件结构的纯py脚本，运行airtest命令生成报告
 `airtest report d:\\scripts\\test.py --log_root 2391e6b --export d:\\sciprts`

    D:\scripts
        \test.py
        \2391e6b
            \log.txt
        \folder
            \a.txt

会复制   D:\scripts 下的所有文件到export指定目录

![image](https://user-images.githubusercontent.com/5961185/62341790-21f39e80-b517-11e9-8123-2e0f58201331.png)

所以还会有这样的情况
![image](https://user-images.githubusercontent.com/5961185/62341952-c5dd4a00-b517-11e9-908f-ffec76358375.png)

<!-- 
    D:\scripts
        \test.py
        \2391e6b
            \log.txt
        \folder
            \a.txt
        \scripts
            \test.py
            \2391e6b
                \log.txt
            \folder
                \a.txt
            \log
                \log.txt
            \static
                ....
            log.html
            
-- !>

**Comment by GitHub-Jatom** [comment]
今天也发现了这个问题 不知道什么时候可以解决
