### ISSUE TITLE
Airtest IDE corrupts Script code, If Windows 10 is not responding and a restart is needed.

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/Airtest#487]
**Describe the bug**
Airtest IDE corrupts Script code, If Windows 10 is not responding and a restart is needed.

**To Reproduce**
1. Wait for Windows 10 to crash while airtest project is on
2. When Windows 10 is unresponsive, force restart PC
3. Encounter error when airtest project is reopened

**Expected behavior** 
1. Project shouldn't be corrupted

**Screenshots**
Error Screenshot : 
![image](https://user-images.githubusercontent.com/19833754/62590624-8dff4980-b8ff-11e9-8a4a-077627b6120b.png)

Expected Result : 
![image](https://user-images.githubusercontent.com/19833754/62590748-fbab7580-b8ff-11e9-879c-3c58bb8d9e57.png)

**python version:** `python3.7`

**airtest version:** `1.0.27`

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: Android

**Comment by yimelia** [comment]
hi @phantomsom 
we feel sorry for this problem, and AirtestIDE has an auto-save feature that lets you retrieve scripts:
http://airtest.netease.com/docs/en/3_faq/script_related_faqs.html#automatic-save-of-scripts-and-retrieval-of-cache-files
