### ISSUE TITLE
run air script on ubuntu which is connected with android phone, occure "Permission denied" Error

### ISSUE THREAD

**Issue by oaktester** [AirtestProject/Airtest#49]
```
test@ubuntu:~/work$ airtest run main_ui3.air --device Android://127.0.0.1:5037/VS7STS6TUKAU5TBE
[08:51:01][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE wait-for-device
======================================================================
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/cli/runner.py", line 37, in setUpClass
    connect_device(dev)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/api.py", line 46, in connect_device
    dev = cls(uuid, **params)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/android.py", line 35, in __init__
    self.adb.wait_for_device()
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 271, in wait_for_device
    proc = self.start_cmd("wait-for-device")
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 146, in start_cmd
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

----------------------------------------------------------------------
Ran 0 tests in 0.316s

FAILED (errors=1)
exiting.......
```

**Comment by adolli** [comment]
hi @oaktester, please grant executable permission for the following file manually. This is a bug in the setup script currently.
```
chmod a+x /home/qatest/.local/lib/python2.7/site-packages/airtest/airtest/core/android/static/adb/linux/adb
```

**Comment by oaktester** [comment]
Hi @adolli ，I have followed your tips to chmod the adb.py. but it does not work. Hope for ur next tips.

![image](https://user-images.githubusercontent.com/38458667/39610463-14fb62da-4f83-11e8-90ab-cb672212e3e1.png)

![image](https://user-images.githubusercontent.com/38458667/39610444-ed63d90a-4f82-11e8-9719-4281c4e94ef6.png)

**Comment by adolli** [comment]
Just this file `/home/qatest/.local/lib/python2.7/site-packages/airtest/airtest/core/android/static/adb/linux/adb`, not adb.py.

**Comment by oaktester** [comment]
@adolli  Thank you so much. And I found that there is no ..../linux/adb file,but adb.py. Therefore，I think something must be wrong when I install airtest through "sudo pip install airtest". then i install airtest again by "git clone https://github.com/AirtestProject/Airtest.git" and "python setup.py install"
After that Permission denied Error is gone. But another problem occur:
![image](https://user-images.githubusercontent.com/38458667/39612602-766a4102-4f93-11e8-9bbf-3188313a8b40.png)

**Comment by adolli** [comment]
What is the `adb version` in your Ubuntu system? As airtest require `adb 1.0.39`. I am not sure why your adb installation failed.

**Comment by oaktester** [comment]
qatest@ubuntu:~/work$ adb version
Android Debug Bridge version 1.0.32

**Comment by oaktester** [comment]
Thanks sincerely，Permission Denied Error has been fixed.
The second path you gave is right.
^___________^

**Comment by adolli** [comment]
So is there still be a "device not ready" exception?

**Comment by oaktester** [comment]
Yes~
![image](https://user-images.githubusercontent.com/38458667/39615621-d799efc0-4fa9-11e8-81b7-17211ab47135.png)

**Comment by adolli** [comment]
I think this is because there are two different adb versions. They may compete with each other. Can u upgrade your system adb to `1.0.39` or just simply uninstall it?

**Comment by oaktester** [comment]
let me have a try,thanks

**Comment by oaktester** [comment]
Problem fixed. adb 's version 1.0.32 is not suitable . upgrade it to 1.0.39 .
this link for reference
https://androideputies.com/2016/12/11/linux-update-adb-fastboot-to-the-latest-version/

thank you @adolli
