### ISSUE TITLE
编辑好的脚本是否支持脱机运行，通过apk中的service进行调度？

### ISSUE THREAD

**Issue by Raphon** [AirtestProject/Airtest#492]
http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id19

官方文档提供了运行AIrtest脚本的几种方法，包括AirtestIDE和命令行

请问有没有方案可以支持脱机运行脚本呢

目前的一个需求是希望可以通过在手机上的一个apk中的service来进行任务调度（类似Robotium和uiautomator那样通过am命令进行任务下发），可以实现循环多次、定时的任务执行。

不知有没有类似这种的方案？或者大家帮忙提供看有没有什么可行的思路？

谢谢

**Comment by yimelia** [comment]
可以参考这个：http://airtest.netease.com/docs/cn/8_plugins/1_firebase.html
目前有一些接口还不够完善，以及还不支持poco，但是是一个可用的方案。
