### ISSUE TITLE
请问各位使用airtest做ui自动化时，如何组织、管理测试用例？

### ISSUE THREAD

**Issue by ldonlytest** [AirtestProject/Airtest#496]
主要场景：
   1. 一个设备，多个测试用例？
   2. 多个设备，多个测试用例？

**Comment by EraChen233** [comment]
可以通过命令行运行手机的方式来实现批量多机运行脚本
http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id19

我们提供了一个例子，实现了多个设备执行同一个用例
https://github.com/AirtestProject/multi-device-runner

如需更多功能，可联系我们了解Pro版IDE，可以实现你需要的这些需求，或者试用Airlab
https://airlab.163.com/

**Comment by LuanShiZhiJian** [comment]
> 可以通过命令行运行手机的方式来实现批量多机运行脚本
> http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id19
> 
> 我们提供了一个例子，实现了多个设备执行同一个用例
> https://github.com/AirtestProject/multi-device-runner
> 
> 如需更多功能，可联系我们了解Pro版IDE，可以实现你需要的这些需求，或者试用Airlab
> https://airlab.163.com/

请问在多个测试脚本中，当元素发生变动我们如何快速修改呢？一个个查脚本修改吗？

**Comment by yimelia** [comment]
@LuanShiZhiJian 
这些涉及到自动化测试脚本的编写技巧、代码层级设计的问题，建议可以上网查一些UI自动化相关的资料来学习
