### ISSUE TITLE
无论怎么按输入框 yosemite都启动不起来 

### ISSUE THREAD

**Issue by wenzhaoxian** [AirtestProject/Airtest#498]
手机信息
![image](https://user-images.githubusercontent.com/48466044/63164779-17c7b900-c05c-11e9-996e-09e67b496dea.png)

airtest ide 版本
![image](https://user-images.githubusercontent.com/48466044/63164808-30d06a00-c05c-11e9-81f1-d8b9958f42dc.png)

**Comment by yimelia** [comment]
@wenzhaoxian 
vivo和oppo系手机的话，可以在设置-输入法设置那里，先把yosemite输入法启用，并且**设置为默认输入法**，然后确认它已经是当前输入法之后再回去尝试点输入框看看
