### ISSUE TITLE
Samsung S7 edge is not working properly in poco

### ISSUE THREAD

**Issue by dipsyHOZ** [AirtestProject/Airtest#5]
![image](https://user-images.githubusercontent.com/3030360/37188756-c2e8377a-238b-11e8-9014-db75e427dce5.png)
The clicked point is out of the monitor.

**Comment by Meteorix** [comment]
Hi, it is a known issue with some Samsung phones. 
Just change screen resolution to max in phone's settings to get over this issue.
![image](https://user-images.githubusercontent.com/3805278/37193199-ece7e4d6-23a3-11e8-9b68-02d0e6c5f1de.png)

**Comment by adolli** [comment]
This is only the problem of the video recording file, not the incorrect clicked position. I think issues of poco are better to discuss here [poco issues](https://github.com/AirtestProject/Poco/issues).
