### ISSUE TITLE
Q-upgrade support

### ISSUE THREAD

**Issue by itstimetochange** [AirtestProject/Airtest#504]
please let us know when you are planning to support Android Q-upgrade. i see there are issues with Android Q. 

adb: error: cannot stat 'AirtestIDE_2019-04-16_py3_win32\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory

**Comment by EricInCD** [comment]
same issue, please fix it

**Comment by jsmerdon98** [comment]
Has there been any progress on this? Having the same issue.

**Comment by Meteorix** [comment]
@brantxiong @yimelia take a look at this pr https://github.com/openstf/minicap/pull/190, hopefully we can build a new version to support Android Q.

**Comment by yimelia** [comment]
see https://github.com/AirtestProject/Airtest/pull/618

**Comment by yimelia** [comment]
> 你好, 该问题有什么进展吗? @yimelia

请问你这边是什么问题？目前安卓支持到11版本，下载最新的AirtestIDE即可
