### ISSUE TITLE
图像识别错误，在一片灰色区域中识别到图片，准确度达到1.0

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#506]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
我的脚本中需要进入Adobe Acrobat Reader DC中进行操作，为了更加完善自动化，我添加了一个关闭初次使用acrobat阅读器的chrome插件提示（见下图）的操作
![tpl1553650383950](https://user-images.githubusercontent.com/42226268/63659224-ca2d1800-c7e2-11e9-81f4-727ebe15d523.png)

然后，它在一个灰色区域中识别到了这幅图，图像准确度达到前无古人的1.0
**相关截图**
这是日志中的报告截图
![chrome插件识别错误](https://user-images.githubusercontent.com/42226268/63659304-4a537d80-c7e3-11e9-8f5b-9e6a497a1896.png)

似乎在acrobat reader dc 2019版中才会出现这个情况，2017版则没有出现，请问这个图像识别错误是什么原因呢？

**复现步骤**
1. 使用新安装的Adobe acrobat reader dc 2019，截下使用chrome插件的提示
2. 在一份pdf文件中（100%缩放）选择识别它

**python 版本:** `python3.6.8`

**airtest 版本:** `1.0.27`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 系统: win7x64,sp1
 - adobe acrobat reader DC 2019(最新版)

**其他相关环境信息**
在adobe acrobat reader DC 2017中能正常识别，但2019中识别错误且准确度达到1.0

**Comment by yimelia** [comment]
脚本内容只保留这一个识别语句，然后运行一下，把运行时的log贴出来看看？

**Comment by niuniuprice** [comment]
> 脚本内容只保留这一个识别语句，然后运行一下，把运行时的log贴出来看看？

非常奇怪的是，只有在运行整个脚本的时候才会出现这个错误，把语句独立出来使用则正常运行...这样的话我只能放弃这一段代码了
