### ISSUE TITLE
脚本编辑窗显示黑屏

### ISSUE THREAD

**Issue by ww54490** [AirtestProject/Airtest#509]
1.win7 64位系统
2.重装了和每次打开都这样
3.代码也显示不出来
![image](https://user-images.githubusercontent.com/54787691/64088499-53f55c00-cd74-11e9-989e-b9bca2a73fb2.png)

**Comment by EraChen233** [comment]
AirtestIDE控制台黑窗口是否有报错，如有，请贴图。

**Comment by yimelia** [comment]
参考这个 https://github.com/AirtestProject/AirtestIDE/issues/438#issuecomment-504846599
