### ISSUE TITLE
Trulbeshooting with poco(pos=[0.376650631, 0.467089951]).click()

### ISSUE THREAD

**Issue by slewmf** [AirtestProject/Airtest#51]
Crash on poco(pos=[0.376650631, 0.467089951]).
If i change poco(pos=[0.376650631, 0.467089951]) on poca('something') script it will worked.
```
  poco(pos=[0.376650631, 0.467089951]).click()
  File "poco\pocofw.py", line 100, in __call__
  File "poco\proxy.py", line 65, in __init__
  File "poco\utils\query_util.py", line 57, in build_query
  File "poco\utils\query_util.py", line 46, in ensure_string_value
AttributeError: 'list' object has no attribute 'decode'
```

**Comment by adolli** [comment]
for now, you should not use any `list`-like attributes to select UIs. I think there's a bug of syntax auto-generation in older IDE. You can download the latest IDE [here](http://airtest.netease.com/changelog.html) if you like.
