### ISSUE TITLE
命令行传递参数时，脚本内容不能写在main入口中

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#511]
@yimelia 
py -3 -m airtest run E:\scripts\test\test1.air  --device android:///10.0.2.55:7556?ori_method=ADBORI&&touch_method=ADBTOUCH
在命令行运行上述命令的时候，test1.air脚本里不能写if __name__ == "__main__":，写在main入口里的内容都不会执行，去掉if __name__ == "__main__"则正常

**Comment by yimelia** [comment]
用airtest run的方式来运行时，会自动用airtest的启动入口来跑，具体可以参考源码https://github.com/AirtestProject/Airtest/blob/master/airtest/cli/runner.py

或者你可以在新建脚本时，选择新建纯py文件，然后根据模板来传入对应的设备参数/log路径等，具体可以参考：http://airtest.netease.com/docs/cn/3_record_script/0_script_faq.html#air-py
