### ISSUE TITLE
how to use python code to connect to the emulator ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [AirtestProject/Airtest#521]
Airtest IDE can connect to the emulator successfully when I turn on the javacap and the adb orientation option in IDE connect. 

But when I use the python code to connect to the emulator, 
the code will get the device not ready error, when I try to connect the emulator by the function `connect_device` in airtest core module. 
The code I use is 

```
# both uri(with or without touch_method) occurs the same error device not ready
                    uri = "android://127.0.0.1:62001/1234566?cap_method=javacap&touch_method=adb&ori_method=adbori"
                    uri = "android://127.0.0.1:62001/1234566?cap_method=javacap&ori_method=adbori"
                    dev = connect_device(uri)

```

The Error is device not ready :

![image](https://user-images.githubusercontent.com/11295355/64335842-40652200-d00e-11e9-80e7-c67d42331e2f.png)

So how to fix this problem?

**Comment by yimelia** [comment]
hi @woshichuanqilz 
When the AirtestIDE runs the script, the run command output is printed in the Log Viewer window:
![image](https://user-images.githubusercontent.com/6896468/64419827-5a673900-d0d0-11e9-911a-4d208a546e72.png)

you can connect the emulator and run it in AirtestIDE, then copy the `Android:///` into your code

**Comment by woshichuanqilz** [comment]
> hi @woshichuanqilz
> When the AirtestIDE runs the script, the run command output is printed in the Log Viewer window:
> ![image](https://user-images.githubusercontent.com/6896468/64419827-5a673900-d0d0-11e9-911a-4d208a546e72.png)
> 
> you can connect the emulator and run it in AirtestIDE, then copy the `Android:///` into your code

Thank you. When you connect to the device through IDE you can exec a simple script and then get the uri from the log window
![image](https://user-images.githubusercontent.com/11295355/64474167-87d0e700-d1a3-11e9-9633-e400b4bde188.png)
