### ISSUE TITLE
关于手机型号咨询

### ISSUE THREAD

**Issue by wenzhaoxian** [AirtestProject/Airtest#523]
备注：找了好久都没有找到你们的相关联系方式，只能在issue向你们咨询了！
 我想咨询一下你们都是用什么类型的手机来调试的，安卓系统的分别是什么类型的品牌和机型，苹果还是什么机型的。

**Comment by wenzhaoxian** [comment]
因为我现在用的安卓机型都基本上没有办法在Yosemite 的输入下能正常的输入

**Comment by yimelia** [comment]
基本上市面上绝大多数机型都是可用的（Android 10暂时还没有完全支持）
你可以提供一下你的手机型号看看
如果是OPPO和VIVO手机在yosemite输入法调用有问题的话，可以到手机设置里，将yosemite输入法设置为默认输入法+当前输入法，然后再试试

**Comment by wenzhaoxian** [comment]
![photo_2019-09-09_13-51-32](https://user-images.githubusercontent.com/48466044/64506151-127f2680-d309-11e9-88f6-25ca891e4d6c.jpg)

![photo_2019-09-09_13-35-33](https://user-images.githubusercontent.com/48466044/64506152-1448ea00-d309-11e9-8567-22918598b9a0.jpg)

Samsung（SM-G610Y） 和 华为 mate20 的
PS：其实我还是想您推荐一款相对该该框架比较稳定的手机型号给我，谢谢了

**Comment by yimelia** [comment]
我们这里支持的手机有几百台。。。。没有固定的型号，基本上大部分手机都可以用
你可以把你遇到的报错内容贴出来，方便定位问题

**Comment by wenzhaoxian** [comment]
没有报错哦，就是切换到yYosemite 输入法的时候，点击任何输入框都是没有办法拉起手机输入键的例如：下图

![7fa2m-e5s8h(1)](https://user-images.githubusercontent.com/48466044/64524356-ee374000-d330-11e9-839a-f064b3bcbb56.jpg)

**Comment by yimelia** [comment]
这是正确的效果，yosemite输入法已正常启动，此时使用text()接口就可以输入文字。
请参考文档： http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#airtesttext
