### ISSUE TITLE
airtest的环境变量设置

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#524]
@yimelia 
部分电脑（已下载airtestIDE）在命令行里输入airtest提示
''airtest'' 不是内部或外部命令，也不是可运行的程序
或批处理文件
airtest的环境变量需要怎样设置

**Comment by yimelia** [comment]
pip install airtest后，会自动添加这个指令
如果依然不行，可以使用 `python -m airtest run xxx`来跑
