### ISSUE TITLE
启动app超时（requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)）

### ISSUE THREAD

**Issue by agoraHan** [AirtestProject/Airtest#529]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
start_app(”xx.xxx.xx“)
```
（在这里粘贴traceback或其他报错信息）
```
self = <urllib3.connectionpool.HTTPConnectionPool object at 0x11df52898>, err = timeout('timed out',), url = '/session', timeout_value = 60.0

    def _raise_timeout(self, err, url, timeout_value):
        """Is the error actually a timeout? Will raise a ReadTimeout or pass"""
    
        if isinstance(err, SocketTimeout):
>           raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
E           urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py:309: ReadTimeoutError

During handling of the above exception, another exception occurred:

self = <testcase.ios.test_function.TestIOS object at 0x11df522b0>

    @pytest.mark.tags(case_tag.iOS,case_tag.MEDIUM,case_tag.AUTOMATED,case_tag.FUNCTIONALITY)
    def test_getAppVersion(self):
        avc = self.avc
        avc.setCurrentDevice(0)
>       avc.startAVC(self.packageName)

testcase/ios/test_function.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/avc_common.py:21: in startAVC
    start_app(packageName)
../Library/Python/3.6/lib/python/site-packages/airtest/utils/logwraper.py:78: in wrapper
    res = f(*args, **kwargs)
../Library/Python/3.6/lib/python/site-packages/airtest/core/api.py:148: in start_app
    G.DEVICE.start_app(package, activity)
../Library/Python/3.6/lib/python/site-packages/airtest/core/ios/ios.py:259: in start_app
    self.driver.session(package)
../Library/Python/3.6/lib/python/site-packages/wda/__init__.py:413: in session
    res = self.http.post('session', data)
../Library/Python/3.6/lib/python/site-packages/wda/__init__.py:165: in fetch
    return self._fetch_no_alert(method, url, data)
../Library/Python/3.6/lib/python/site-packages/wda/__init__.py:171: in _fetch_no_alert
    return httpdo(target_url, method, data)
../Library/Python/3.6/lib/python/site-packages/wda/__init__.py:110: in httpdo
    return _unsafe_httpdo(url, method, data)
../Library/Python/3.6/lib/python/site-packages/wda/__init__.py:127: in _unsafe_httpdo
    timeout=HTTP_TIMEOUT)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py:58: in request
    return session.request(method=method, url=url, **kwargs)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py:508: in request
    resp = self.send(prep, **send_kwargs)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py:618: in send
    r = adapter.send(request, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <requests.adapters.HTTPAdapter object at 0x11df52710>, request = <PreparedRequest [POST]>, stream = False, timeout = <urllib3.util.timeout.Timeout object at 0x11df52a20>, verify = True
cert = None, proxies = OrderedDict()

    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        """Sends PreparedRequest object. Returns Response object.
    
            :param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
            :param stream: (optional) Whether to stream the request content.
            :param timeout: (optional) How long to wait for the server to send
                data before giving up, as a float, or a :ref:`(connect timeout,
                read timeout) <timeouts>` tuple.
            :type timeout: float or tuple or urllib3 Timeout object
            :param verify: (optional) Either a boolean, in which case it controls whether
                we verify the server's TLS certificate, or a string, in which case it
                must be a path to a CA bundle to use
            :param cert: (optional) Any user-provided SSL certificate to be trusted.
            :param proxies: (optional) The proxies dictionary to apply to the request.
            :rtype: requests.Response
            """
    
        conn = self.get_connection(request.url, proxies)
    
        self.cert_verify(conn, request.url, verify, cert)
        url = self.request_url(request, proxies)
        self.add_headers(request)
    
        chunked = not (request.body is None or 'Content-Length' in request.headers)
    
        if isinstance(timeout, tuple):
            try:
                connect, read = timeout
                timeout = TimeoutSauce(connect=connect, read=read)
            except ValueError as e:
                # this may raise a string formatting error.
                err = ("Invalid timeout {0}. Pass a (connect, read) "
                       "timeout tuple, or a single float to set "
                       "both timeouts to the same value".format(timeout))
                raise ValueError(err)
        elif isinstance(timeout, TimeoutSauce):
            pass
        else:
            timeout = TimeoutSauce(connect=timeout, read=timeout)
    
        try:
            if not chunked:
                resp = conn.urlopen(
                    method=request.method,
                    url=url,
                    body=request.body,
                    headers=request.headers,
                    redirect=False,
                    assert_same_host=False,
                    preload_content=False,
                    decode_content=False,
                    retries=self.max_retries,
                    timeout=timeout
                )
    
            # Send the request.
            else:
                if hasattr(conn, 'proxy_pool'):
                    conn = conn.proxy_pool
    
                low_conn = conn._get_conn(timeout=DEFAULT_POOL_TIMEOUT)
    
                try:
                    low_conn.putrequest(request.method,
                                        url,
                                        skip_accept_encoding=True)
    
                    for header, value in request.headers.items():
                        low_conn.putheader(header, value)
    
                    low_conn.endheaders()
    
                    for i in request.body:
                        low_conn.send(hex(len(i))[2:].encode('utf-8'))
                        low_conn.send(b'\r\n')
                        low_conn.send(i)
                        low_conn.send(b'\r\n')
                    low_conn.send(b'0\r\n\r\n')
    
                    # Receive the response from the server
                    try:
                        # For Python 2.7+ versions, use buffering of HTTP
                        # responses
                        r = low_conn.getresponse(buffering=True)
                    except TypeError:
                        # For compatibility with Python 2.6 versions and back
                        r = low_conn.getresponse()
    
                    resp = HTTPResponse.from_httplib(
                        r,
                        pool=conn,
                        connection=low_conn,
                        preload_content=False,
                        decode_content=False
                    )
                except:
                    # If we hit any problems here, clean up the connection.
                    # Then, reraise so that we can handle the actual exception.
                    low_conn.close()
                    raise
    
        except (ProtocolError, socket.error) as err:
            raise ConnectionError(err, request=request)
    
        except MaxRetryError as e:
            if isinstance(e.reason, ConnectTimeoutError):
                # TODO: Remove this in 3.0.0: see #2811
                if not isinstance(e.reason, NewConnectionError):
                    raise ConnectTimeout(e, request=request)
    
            if isinstance(e.reason, ResponseError):
                raise RetryError(e, request=request)
    
            if isinstance(e.reason, _ProxyError):
                raise ProxyError(e, request=request)
    
            if isinstance(e.reason, _SSLError):
                # This branch is for urllib3 v1.22 and later.
                raise SSLError(e, request=request)
    
            raise ConnectionError(e, request=request)
    
        except ClosedPoolError as e:
            raise ConnectionError(e, request=request)
    
        except _ProxyError as e:
            raise ProxyError(e)
    
        except (_SSLError, _HTTPError) as e:
            if isinstance(e, _SSLError):
                # This branch is for urllib3 versions earlier than v1.22
                raise SSLError(e, request=request)
            elif isinstance(e, ReadTimeoutError):
>               raise ReadTimeout(e, request=request)
E               requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)
![image](https://user-images.githubusercontent.com/37997041/64940346-525c8580-d896-11e9-9749-8e452e6524f1.png)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1. 调用start_app()方法
2.APP 打开了但是报超时的错误
**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.6`

**airtest 版本:** `1.2.2`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**ios
 - 型号: iPhone X
 - 系统: ios 12.4.1
 - (别的信息)

**其他相关环境信息**
iPhone 6（ios 11）的系统可以正常运行

**Comment by chase-wen-hs** [comment]
遇到同样问题 请问有解决方法了吗

**Comment by agoraHan** [comment]
没有

**Comment by chase-wen-hs** [comment]
我用facebook-wda 0.2.2 可以解决

**Comment by agoraHan** [comment]
> 把facebook-wda 降到0.2.2 可以解决

降级之后可以解决，多谢

**Comment by weiyanfen** [comment]
> 把facebook-wda 降到0.2.2 可以解决

你好，请教怎么把facebook-wda 降到0.2.2
