### ISSUE TITLE
运行脚本时出现cv2.error：The function/feature is not implemented

### ISSUE THREAD

**Issue by shijianzhihu** [AirtestProject/Airtest#532]
**描述问题bug**
我使用自定义Airtest启动器，在Win10命令行下运行脚本时，有如下异常报错，我没查到如何解决这个问题，请求帮助。
```
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv_contrib\modules\xfeatures2d\src\surf.cpp:1029: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'cv::xfeatures2d::SURF::create'
```
![image](https://user-images.githubusercontent.com/26112446/65295974-9c46b380-db95-11e9-8f6a-a63d95726c08.png)

**opencv-contrib-python 版本:** `4.1.1.26`
**python 版本:** `python3.7.0`
**airtest 版本:** `latest`

**Comment by dinghongyi** [comment]
你好，看看这个能不能解决
https://stackoverflow.com/questions/52305578/sift-cv2-xfeatures2d-sift-create-not-working-even-though-have-contrib-instal

**Comment by shijianzhihu** [comment]
感谢回复，问题解决了，记录了一下过程：https://www.jianshu.com/p/f9fedd1154a7
