### ISSUE TITLE
Javacap模式和mumu模拟器是否不兼容，ide中多次运行脚本后socket connection broken

### ISSUE THREAD

**Issue by violet4783** [AirtestProject/Airtest#534]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
![企业微信截图_1d61dc5f-c8f2-43f5-b3f1-430e4827514b](https://user-images.githubusercontent.com/18345833/65312233-a9c76200-dbc4-11e9-9e55-f2c1e7797c99.png)
按照官方的文档，连接后127.0.0.1:7555一直都是offline状态，但是通过restartADB会出现一个设备。
![image](https://user-images.githubusercontent.com/18345833/65312361-ec893a00-dbc4-11e9-8402-26fbfe0436c6.png)
给这个设备勾选了javacap和Use ADB orientation，顺利地显示出了模拟器的画面内容

但是在使用过程中，在ide中反复运行脚本会较高可能性地出现 socket connection broken，断开重连偶尔会解决问题，但多数时候会一直连不上设备
![image](https://user-images.githubusercontent.com/18345833/65314576-26f4d600-dbc9-11e9-8156-01ee133094f6.png)

并且从游戏里拉起QQ登陆授权申请后，touch就失效了
![image](https://user-images.githubusercontent.com/18345833/65315464-be0e5d80-dbca-11e9-9f22-82f334dfbed6.png)

当去掉javacap选项后，上述一切都正常了。

**预期效果**
Javacap模式和mumu模拟器是否不兼容？还是因为本地操作有问题？
如果是bug，希望修复一下。
如果真的不兼容，麻烦官方文档上更新一下吧。

**python 版本:** 
IDE自带的python
IDE版本1.2.2
操作系统macOS
模拟器mumu

**Comment by yimelia** [comment]
是的，不兼容。
