### ISSUE TITLE
A机器上的报告在B机器上查看时（A、B在一个局域网，而且A使用nginx做代理），B总是看不到运行时的截图，看不到的截图参数是：step.screenshot

### ISSUE THREAD

**Issue by ASmallListener** [AirtestProject/Airtest#54]
![image](https://user-images.githubusercontent.com/35556979/39986878-964e8708-5795-11e8-8c67-0631f1edade2.png)

**Comment by ASmallListener** [comment]
单独访问这个链接又是可以看到截图的，为什么啊？

**Comment by Meteorix** [comment]
用chrome的inspect看看图片的url吧。

另外建议可以用[report命令](http://airtest.readthedocs.io/en/latest/README_MORE.html#generate-html-report)的`--export`参数，将整个报告文件夹导出，并放到nginx上

**Comment by ASmallListener** [comment]
这是资源的元素信息：<img class="fancybox scale lazyload" data-src="http://192.168.147.128/Autotest/common/log/Login/1526033506261.jpg" url="" title="http://192.168.147.128/Autotest/common/log/Login/1526033506261.jpg">

url显示为空的，但是我看是在log_template.html里面就把他置空了的啊

**Comment by Meteorix** [comment]
👍 不用客气，看来你已经深入使用airtest了

**Comment by ASmallListener** [comment]
还得感谢你们提供这么好的工具啊

**Comment by InferiorCoder** [comment]
> 单独访问这个链接又是可以看到截图的，为什么啊？




test
