### ISSUE TITLE
图像识别匹配问题，竖屏下截取的桌面图标，能匹配，横屏就匹配不了

### ISSUE THREAD

**Issue by bill68551632** [AirtestProject/Airtest#542]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

图像识别匹配问题，竖屏下截取的桌面图标，进行识别点击，可信0.98，识别准确，点击正确
然后手机横屏之后，匹配不到，可信 0.45，无法定位到图像

touch(Template(r"tpl1569467254330.png", record_pos=(-0.366, -0.094), resolution=(1440, 1920)),times=1)

1440，1920 是竖屏，横屏是 1920，1440

```
（在这里粘贴traceback或其他报错信息）
```
airtest.core.error.TargetNotFoundError: 'Picture Template(C:\\Users\\bbl\\airtest\\untitled.air\\tpl1569467254330.png) not found in screen'

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

[横竖屏都能准确定位匹配查找]

**python 版本:** `python3.7`

**airtest 版本:** `1.2.2`
匹配图像
![tpl1569467254330](https://user-images.githubusercontent.com/25445941/65662432-dff25f00-e066-11e9-9cfa-e9905d81a492.png)

横屏
![1569475895614](https://user-images.githubusercontent.com/25445941/65662512-0e703a00-e067-11e9-83f6-0b1d2b30f254.jpg)
竖屏
![1569475986197](https://user-images.githubusercontent.com/25445941/65662521-13cd8480-e067-11e9-973b-09b8dd1a96b7.jpg)

> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [柔派]
 - 系统: [e.g. Android 9]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by bill68551632** [comment]
在 airtest\core\cv.py  中函数 _resize_image  添加了代码，

        # 如果分辨率一致，则不需要进行im_search的适配:
        if tuple(self.resolution) == tuple(screen_resolution) or resize_method is None:
            return image
        **# 如果是横屏切换，同一台手机，dip是没有改变，图标是不需要伸缩
        resolution_t = (self.resolution[1], self.resolution[0])
        if resolution_t == tuple(screen_resolution):
            return image**
       
使用airtest命令可以匹配上了，可是把IDE目录下airtest中代码修改了，IDE执行没有成功，代码没有能够生效

**Comment by yimelia** [comment]
@bill68551632 
修改IDE目录里的airtest是不会起效果的，因为IDE使用的airtest是打在exe里面的。
如果要让修改的airtest生效，可以设置你自己的Python.exe来运行脚本：http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python
