### ISSUE TITLE
AirtestIDE_2019-09-11_py3_win64 修改了里面的airtest中代码，执行的没有按修改执行，怎么让airtest代码修改生效

### ISSUE THREAD

**Issue by bill68551632** [AirtestProject/Airtest#543]
Remove any following parts if does not have details about

希望能够修改airtest中代码，可以在IDE中生效

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by EraChen233** [comment]
使用本地python环境运行
http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python
