### ISSUE TITLE
I hope the test will improve the form.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#547]
There is an opinion that it is difficult to confirm the contents of the test results in the company.

**Comment by EraChen233** [comment]
Can you describe it in more detail?

**Comment by JJunM** [comment]
> Can you describe it in more detail?
@EraChen233 testresult image attach
![testresult](https://user-images.githubusercontent.com/46311868/66542007-3df56b00-eb6c-11e9-882e-e0842fddc06b.jpg)

**Comment by EraChen233** [comment]
Have you tried the latest airtest report? The latest report looks like this. Did it help you?

![image](https://user-images.githubusercontent.com/5961185/66544695-70eb2f00-eb6b-11e9-965b-ab5ecb1b2449.png)
