### ISSUE TITLE
device对象得内容在pycharm中感应不出来

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Airtest#55]
def wakeUpToIdle(self):
        wake()
        keyevent("POWER")
        scrollUI = self.poco("com.android.systemui:id/notification_stack_scroller")
        scrollUI.scroll('vertical')
        #get_top_activity_name()
        #device().get_top_activity_name()  
        #current_device().get_top_activity_name()
        self.device.get_top_activity_name()

上面得current_device().后面的方法感应不出来

**Comment by Meteorix** [comment]
感谢你的issue，我们稍后fix一下，会支持感应出跨平台的接口。

但是每个平台有些额外的平台特有的接口，没法通过`current_device().`感应出来，请查文档或者用`Android().`感应

**Comment by Meteorix** [comment]
fixed in this commit: https://github.com/AirtestProject/Airtest/commit/36a2363e00dcd5ee4d2af7c04804c6e0b594713d

`pip install -U airtest` to upgrade
