### ISSUE TITLE
关于text用法的疑问

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#551]
@yimelia 
点击文本框，使用text函数输入信息，如果文本框原本有内容的话，text输入的信息是直接添加在原内容后面，我想要覆盖原内容（即text输入的信息覆盖文本框原有的内容），需要怎么操作呢

**Comment by yimelia** [comment]
查看文档： https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#pocoset_text
可以用Poco去set_text
或者是先输入若干个删除键的响应，删干净内容后再进行输入
