### ISSUE TITLE
Can't launch IDE on macOS Catalina

### ISSUE THREAD

**Issue by igorakintev** [AirtestProject/Airtest#560]
**Describe the bug**
It just tries to start but just closes without any errors.

**To Reproduce**
1. Download latest IDE for mac from http://airtest.netease.com
2. Install it.
3. Try to run

**Comment by EraChen233** [comment]
Start AirtestIDE in command line, and see if any traceback printed
http://airtest.netease.com/docs/en/3_faq/ide_crash.html#how-can-i-check-the-cause-of-airtestide-crash

**Comment by igorakintev** [comment]
Hi. It starts now. 

But I have two icons in the dock and one is always jumping (like app starting)

[https://pasteboard.co/IC2SptQ.png](url)

**Comment by EraChen233** [comment]
When the Airtest IDE is running, there are exactly two icons and one bounce. This is an old issue, we have not found a suitable way to solve it. So AirtestIDE run normally now?

Link cannot be visited.

**Comment by igorakintev** [comment]
Ok, I think I'm good now.
I'm closing the ticket.

Thnaks.

**Comment by returnzer0** [comment]
Hey, what scripts did you use to run it on a mac? I am trying to run it using a script but it says command not found: airtest.

**Comment by yimelia** [comment]
@returnzer0 
see this: https://airtest.doc.io.netease.com/en/IDEdocs/run_script/1_useCommand_runScript/#2-run-the-script-using-the-local-python-environment

or try: `python -m airtest run xx.air xxxxxx`
