### ISSUE TITLE
日志输出等级设置

### ISSUE THREAD

**Issue by ly1n** [AirtestProject/Airtest#562]
在通过python脚本批量执行时，希望可以控制Log的输出显示。刷新的信息太多，无法有效提取有用的信息。如--log参数，为设置log路径，希望能够设置log等级或取消log显示。

![图片](https://user-images.githubusercontent.com/17906006/66901663-a28e4b00-efee-11e9-8204-cb65cbe5ea28.png)

**Comment by yimelia** [comment]
可以在脚本代码开头加上log级别的设定：
```
# -*- encoding=utf8 -*-
__author__ = "user"
import logging
logger = logging.getLogger("airtest")
logger.setLevel(logging.ERROR)
from airtest.core.api import *
auto_setup(__file__)
```
这样运行时只会在初始化手机时会有少量log输出，初始化完毕后就能够对logger进行过滤了。
批量运行的话， 可能需要你自行尝试一下

**Comment by ly1n** [comment]
> 
> 
> 可以在脚本代码开头加上log级别的设定：
> 
> ```
> # -*- encoding=utf8 -*-
> __author__ = "user"
> import logging
> logger = logging.getLogger("airtest")
> logger.setLevel(logging.ERROR)
> from airtest.core.api import *
> auto_setup(__file__)
> ```
> 
> 这样运行时只会在初始化手机时会有少量log输出，初始化完毕后就能够对logger进行过滤了。
> 批量运行的话， 可能需要你自行尝试一下

尝试过了，可行。只在初始化有少量log输出。感谢

**Comment by yimelia** [comment]
@Meteorix 
只是做一个标记，在批量运行脚本的情况下还没有写示例，后续打算写进公众号里

**Comment by ranhuan** [comment]
auto_setup里不会重新设置日志级别吗，代码顺序似乎不对

**Comment by jennywu0802** [comment]
您好，我也想提問和樓上相同問題，我同時有使用自己的log，倘若把設定更改一樣會吐debug訊息，由於我還同時使用pytest結合log，會導致全部都會跑出來，這讓我很頭疼，是否能幫忙？

**Comment by Crapulence123** [comment]
> 

Hello!请问你解决log的问题了吗？ 我也在使用pytest+airtest，也遇到了这个问题，求解决方式！

**Comment by Crapulence123** [comment]
> Hello!请问你解决log的问题了吗？ 我也在使用pytest+airtest，也遇到了这个问题，求解决方式！



> 您好，我也想提問和樓上相同問題，我同時有使用自己的log，倘若把設定更改一樣會吐debug訊息，由於我還同時使用pytest結合log，會導致全部都會跑出來，這讓我很頭疼，是否能幫忙？

Hello!请问你解决log的问题了吗？ 我也在使用pytest+airtest，也遇到了这个问题，求解决方式！

**Comment by Crapulence123** [comment]
> 您好，我也想提問和樓上相同問題，我同時有使用自己的log，倘若把設定更改一樣會吐debug訊息，由於我還同時使用pytest結合log，會導致全部都會跑出來，這讓我很頭疼，是否能幫忙？

@jennywu0802  Hello!请问你解决log的问题了吗？ 我也在使用pytest+airtest，也遇到了这个问题，求解决方式！

**Comment by jennywu0802** [comment]
沒有，暫時先被我放置了🥲

叉叉 ***@***.***>於 2023年1月19日 週四，下午4:57寫道：
