### ISSUE TITLE
请问支持安卓h5应用吗？

### ISSUE THREAD

**Issue by Nillouise** [AirtestProject/Airtest#567]
安卓h5应用目前只能使用图像来爬取数据？

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/poco_framework/poco_webview/

**Comment by pandalanlam** [comment]
> https://airtest.doc.io.netease.com/IDEdocs/poco_framework/poco_webview/

链接内图裂了
