### ISSUE TITLE
多机运行时，安装minicap依然会选择默认设备

### ISSUE THREAD

**Issue by bittern** [AirtestProject/Airtest#570]
在多设备连接后，先指定set_current()  或者直接init_device(uuid=),然后看log中，其他步骤都是走指定的设备，而在安装minicap时，回到了默认设备，log如下：

D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** shell settings get secure default_input_method
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** shell ime list -a
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** shell dumpsys package com.netease.open.pocoservice
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** shell dumpsys package com.netease.open.pocoservice.test
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** forward --no-rebind tcp:16593 tcp:10080
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** forward --no-rebind tcp:18127 tcp:10081
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** shell ps
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** wait-for-device
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** shell getprop ro.build.version.sdk
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** shell ls /data/local/tmp/minicap
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** shell ls /data/local/tmp/minicap.so
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[01:55:01][DEBUG]<airtest.core.android.minicap> version:5
[01:55:01][DEBUG]<airtest.core.android.minicap> skip install minicap
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **6900cf8** shell dumpsys window displays
“初始化完成，开始执行case”
D:\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s **S2D05278** shell am start -n air.tv.android

日志中可以看到，分别有两个设备，大部分操作都在S2D05278 上，而到了安装minicap时，又切换到了默认设备，想问下这个是什么情况？

python3.7版本
airtest==1.1.1

**Comment by yimelia** [comment]
请完善问题描述，贴出实际运行的代码、运行使用的命令行、如果你有自己的启动脚本也需要将脚本贴出来，描述清楚你的脚本目的，问题所在。

**Comment by bittern** [comment]
目录：
testcase/   具体case
run.py       执行入口

run.py内容：
if __name__ == "__main__":
    connect_device("Android:///{}".format(sys.argv[1]))
    set_current(sys.argv[1])
    filename = tdresult + "//" + date + "_result.html"
    fp = open(filename, mode='wb')
    runner = HTMLTestRunner.HTMLTestRunner(stream=fp, title=u'UI自动化测试报告', description=u'用例执行情况如下：')
    runner.run(all_test_cases)
    fp.close()


执行命令行：  python  run.py uuid(对应设备id)

**Comment by yimelia** [comment]
在set_current之后，把当前设备打出来看看是哪一台
dev = device()
print(dev.uuid)

**Comment by bittern** [comment]
> 在set_current之后，把当前设备打出来看看是哪一台
> dev = device()
> print(dev.uuid)

print之后 打印的是指定的这台， 我运行时候指定的是S2D05278， 打印的就是S2D05278  ；只是日志中minicap 安装的是另外一台

**Comment by yimelia** [comment]
先不管日志里的输出，你的脚本能正确用指定的手机运行吗？

**Comment by bittern** [comment]
> 先不管日志里的输出，你的脚本能正确用指定的手机运行吗？

case没问题，只要过了初始化，case能被正确的识别，不会串设备；

**Comment by yimelia** [comment]
好的，那就说明set_current还是生效的，中途插入了默认手机的初始化（应该是adb devices的第一台结果），可能是某个接口在初始化获取设备时没有直接拿当前设备，而是拿了默认设备。
具体是哪个接口暂时还不清楚，如果你这边方便的话，可以帮忙在log里print几个地方，定位一下看看那个初始化是在什么时候发生的：
- 看看是否是connect_device 和 set_current 这两个接口之间发生的
- 如果case只运行一个（可以直接用你运行时跑的第一个case来看看），是否也会有这个log

**Comment by bittern** [comment]
> 好的，那就说明set_current还是生效的，中途插入了默认手机的初始化（应该是adb devices的第一台结果），可能是某个接口在初始化获取设备时没有直接拿当前设备，而是拿了默认设备。
> 具体是哪个接口暂时还不清楚，如果你这边方便的话，可以帮忙在log里print几个地方，定位一下看看那个初始化是在什么时候发生的：
> 
> * 看看是否是connect_device 和 set_current 这两个接口之间发生的
> * 如果case只运行一个（可以直接用你运行时跑的第一个case来看看），是否也会有这个log

感谢！ 找到了位置。中间case有调用airtest.core.android.Android()类下方法，而没有指定serialno，已经添加了对应uuid，解决了

**Comment by yimelia** [comment]
在代码中如果想使用当前设备，可以直接调用`device()`接口就能获取到了，
也就是说如果想调用Android类里的方法可以
```
dev = device()
dev.shell("ls")
```
