### ISSUE TITLE
图像识别、设备控制相关问题

### ISSUE THREAD

**Issue by WongHungKin** [AirtestProject/Airtest#571]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by WongHungKin** [comment]
touch函数有时候点击一个控件的时候看起来是点击了，但是实际点击后没有反应。
就比如touch(picture1)
           touch(picture2)

然后循环10次这种步骤，就会经常出现touch了没反应，显示上是有点击的动作了，但是就是没效果。
也试着设置了touch函数里的duration时间，但是还是会有这种情况存在
windows10平台
airtest版本：1.0.27
python版本：3.7

**Comment by yimelia** [comment]
duration设置了多长时间？
是偶现的，还是某些操作必现这个问题

**Comment by WongHungKin** [comment]
偶然会出现，duration刚开始是默认0.01  然后我设置0.1 0.5 这种还是会出现。
就反正写个函数 自己循环按两个按钮 一般循环4 5次的时候就会出现这种问题
我昨天写脚本然后挂着今天早上来看测试报告的时候就发现明明执行了touch操作，但是点击无效果

**Comment by WongHungKin** [comment]
你自己观察的时候 按钮也是有点击的操作的，但是点击后就是没效果 很奇怪

**Comment by yimelia** [comment]
请参考：https://github.com/AirtestProject/Poco/issues/288
duration参数控制的是按住的时长，和你想要达成的效果无关。

**Comment by WongHungKin** [comment]
那为什么会touch失败啊有时候

**Comment by yimelia** [comment]
帖子里写得很清楚了

**Comment by WongHungKin** [comment]
画面早就稳定下来了。。。

**Comment by yimelia** [comment]
是点击什么应用？

**Comment by WongHungKin** [comment]
一款游戏。倩女幽魂手游 桌面版
