### ISSUE TITLE
iPhone SE 10.2和xcode 10.3连接AirTest IDE后只能看到手机的部分界面

### ISSUE THREAD

**Issue by zhangdongjia** [AirtestProject/Airtest#572]
这种情况需要设置吗？
![image](https://user-images.githubusercontent.com/26005138/67280727-62ecc500-f500-11e9-8161-2a565253eae4.png)

**Comment by EraChen233** [comment]
https://airtest.doc.io.netease.com/tutorial/6_IOS_automated_testing/#_2
![image](https://user-images.githubusercontent.com/5961185/67348650-22309280-f578-11e9-99ff-ec741bf03225.png)
