### ISSUE TITLE
pip安装airtest三方库失败

### ISSUE THREAD

**Issue by lhbads** [AirtestProject/Airtest#573]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)
**描述问题bug**
1、pip安装airtest三方库，命令：pip3 install -U airtest -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
2、提示ERROR: Could not find a version that satisfies the requirement opencv-contrib-python<=3.4.2.17 (from airtest) (from versions: none)
3、opencv-contrib-python不支持pip安装，链接：https://github.com/piwheels/packages/issues/28

**相关截图**
![image](https://user-images.githubusercontent.com/31372600/67285669-903e7080-f50a-11e9-8ea7-25bf3cad5345.png)

**预期效果**
通过pip安装airtest

**python 版本:** `python3.8`

**设备:**
MacBook Pro

**其他相关环境信息**
操作系统：macOS 10.14.5

**Comment by yimelia** [comment]
- 可以先尝试更新pip到最新版本，然后再重试
- 因为你用了最新版的python3.8，有些第三方库可能还没有完全支持，建议装个虚拟环境用更低一些版本的python
