### ISSUE TITLE
是否可以不使用IDE自带的截图功能，用自己准备的图

### ISSUE THREAD

**Issue by WongHungKin** [AirtestProject/Airtest#575]
IDE自带的截图是PNG格式的，想用自己截的BMP格式来进行图像识别会不会准确度更高一些。毕竟BMP格式是无损的

**Comment by yimelia** [comment]
可以用自己的截图，直接打开.air目录下的同名.py文件，可以看到纯python代码（在IDE里右键选择切换图片/代码模式也可以直接看到代码）。
所有的图片其实都是一个`Template(图片路径)`的对象，可以参考[源码](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/cv.py#L104)。我们暂时没有试过使用非PNG格式的图片，不能确保能够识别。
关于图像识别的算法精确度情况，我们有一个测试代码，可以参考这个[文档](https://github.com/AirtestProject/Airtest/blob/master/benchmark/README_cn.md)，里面列举、对比了目前airtest使用的图像识别算法的效果和效率情况。这个文档比较简略，我们将在星期五的时候放一篇微信公众号文章来说图像识别的算法选择问题，欢迎关注我们的公众号：AirtestProject
