### ISSUE TITLE
急！！！怎么百分比定位，我现在做适应多机型的，元素都不同，只能通过坐标百分比，能适用多机型。

### ISSUE THREAD

**Issue by MaNongXiaoGang** [AirtestProject/Airtest#580]
文档没找到，只有坐标定位的，但是不同分辨率的可能不同。

**Comment by yimelia** [comment]
可以参考这个文章：https://mp.weixin.qq.com/s/6yu0gjCEZQ_x6NwEY_rBjQ
欢迎关注我们的微信公众号：AirtestProject
