### ISSUE TITLE
**设备:**，请问最新的安卓设备支持列表可以在哪里查询？

### ISSUE THREAD

**Issue by RonChu-01** [AirtestProject/Airtest#583]
官方文档上的“安卓设备支持列表”上面的机型好像没有涵盖近两年来的一些热门机型，想咨询一下最新的安卓设备支持列表可以在哪里查询？

**Comment by yimelia** [comment]
由于安卓机型迭代速度非常快，我们有时来不及维护这个设备列表，不过基本上绝大部分机型都是支持的。
Android10的兼容我们正在进行测试，还没有正式外放

**Comment by RonChu-01** [comment]
好的收到 谢谢
