### ISSUE TITLE
小米手机  MIUI 11  不支持连接airtest  

### ISSUE THREAD

**Issue by mi-snoopy** [AirtestProject/Airtest#587]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
看一下系统信息里面的Android版本号是多少？
如果是android10的话暂时还没支持，我们最近正在进行测试，将会尽快更新支持

**Comment by yimelia** [comment]
Duplicate of #504
