### ISSUE TITLE
swipe方法可以重载实现按坐标滑动吗？

### ISSUE THREAD

**Issue by xzhacker123** [AirtestProject/Airtest#588]
因为大多数滑动的操作是单纯的屏幕滑动，而且图片都是随机的，所以按图片滑动反而会更麻烦一些。

**Comment by yimelia** [comment]
可以，传入的参数可以有很多种不同的组合类型，请查文档：https://airtest.readthedocs.io/zh_CN/latest/all_module/airtest.core.api.html#airtest.core.api.swipe

**Comment by xzhacker123** [comment]
ok,谢谢，我看了一下，是支持的
  `  if isinstance(v1, Template):
        pos1 = loop_find(v1, timeout=ST.FIND_TIMEOUT)
    else:
        try_log_screen()
        pos1 = v1`
但是这个怎么体现在IDE操作里面呢，还是要在IED去手动填写坐标？

**Comment by yimelia** [comment]
请自行手工填写哈，如何查看手机坐标可以参考文档：https://airtest.doc.io.netease.com/IDEdocs/settings/1_ide_settings/#2-device

**Comment by xzhacker123** [comment]
非常感谢
