### ISSUE TITLE
ubuntu上运行air脚本会出现libgthread-2.0.so cannot open shared object file的报错，如截图所示

### ISSUE THREAD

**Issue by oaktester** [AirtestProject/Airtest#59]
![image](https://user-images.githubusercontent.com/38458667/40160133-d79a904e-59de-11e8-883f-c5c7008f7b68.png)

**Comment by Meteorix** [comment]
看起来是[opencv-python](https://pypi.org/project/opencv-contrib-python)的问题，请尝试下卸载重装，然后单独``import cv2``试试

**Comment by oaktester** [comment]
多谢，确实重装解决了问题。
