### ISSUE TITLE
安全键盘输入的时候黑屏, 这个问题是不是可以解决? 

### ISSUE THREAD

**Issue by woshichuanqilz** [AirtestProject/Airtest#590]
在输入密码的时候会自动跳出来安全键盘 这个安全键盘跳出来的时候从ide里面看是黑屏的这个问题能不能解决?

**Comment by yimelia** [comment]
请按照问题模板进行填写，写清楚详细情况和你的手机型号、android版本号等情况，并且附上截图

**Comment by Meteorix** [comment]
@woshichuanqilz 最好设置一下，取消安全键盘，这个就是手机保护屏幕不被读取的一个方式，取消就好了
