### ISSUE TITLE
在一个列表里识别问题

### ISSUE THREAD

**Issue by ancining** [AirtestProject/Airtest#593]
假如我想在一个列表里找个图片，但这个图片不在第一页，而是要滑动到后面页才能找到，但airtest在第一页的时候就直接找到了，请问这个怎么解决？
![image](https://user-images.githubusercontent.com/26423615/68194662-5f713780-fff0-11e9-858f-885721d4287d.png)

**Comment by fishfish-yu** [comment]
你可以先在这篇推文里面了解下各个图像识别算法是如何找图的

**Comment by fishfish-yu** [comment]
http://mp.weixin.qq.com/s?__biz=MzUxMDc4NTkwMA==&mid=2247484068&idx=1&sn=8037c1ddec46ec26f2a8eff8b2252d2d&chksm=f97ce2a7ce0b6bb1512451367dceb85eca1073050fb9c3ce06503ebc9db8f10c2f8efc0d1506&mpshare=1&scene=23&srcid=&sharer_sharetime=1573029715727&sharer_shareid=d7c76ec50dd2ddd1acf1ab3095badbf0#rd
你可以在这篇推文里面了解下各个图像识别算法是怎么找图的

**Comment by ancining** [comment]
> http://mp.weixin.qq.com/s?__biz=MzUxMDc4NTkwMA==&mid=2247484068&idx=1&sn=8037c1ddec46ec26f2a8eff8b2252d2d&chksm=f97ce2a7ce0b6bb1512451367dceb85eca1073050fb9c3ce06503ebc9db8f10c2f8efc0d1506&mpshare=1&scene=23&srcid=&sharer_sharetime=1573029715727&sharer_shareid=d7c76ec50dd2ddd1acf1ab3095badbf0#rd
> 你可以在这篇推文里面了解下各个图像识别算法是怎么找图的

嗯，我修改了下阈值，然后就可以了，谢谢回复
