### ISSUE TITLE
【非bug】app内嵌H5，airtest如何结合selenium使用？

### ISSUE THREAD

**Issue by pandalanlam** [AirtestProject/Airtest#599]
需要测试app内嵌h5页面，入口路径通过airtest touch操作或poco操作进入页面。
非浏览器打开状态下，app内进入h5页面后，能否结合selenium使用？

**Comment by yimelia** [comment]
可以先直接使用Poco试一下看看能否使用， 设置方法见：https://airtest.doc.io.netease.com/IDEdocs/poco_framework/poco_webview/

如果一定要使用selenium的话，建议在浏览器上面单独测试H5部分
