### ISSUE TITLE
UnicodeError when install app on android with apk path in Chinese directory

### ISSUE THREAD

**Issue by Meteorix** [AirtestProject/Airtest#6]
![image](https://user-images.githubusercontent.com/3805278/37318308-b6d18722-26a4-11e8-940a-601c541af3f5.png)

**Comment by adolli** [comment]
Fixed in the latest version.

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/commit/f266753cb10d84b959a72623651247a32ff84998 fixed in the commit
