### ISSUE TITLE
批量执行测试脚本，按命名顺序执行脚本

### ISSUE THREAD

**Issue by zhangwk02** [AirtestProject/Airtest#60]
命令行，批量执行脚本，按照脚本命名可顺序执行脚本：airtest run untitled.air(脚本路径) --device Android:///手机设备号 --log log/(log存放路径)

**Comment by Meteorix** [comment]
@zhangwk02 你的问题是什么呢？

**Comment by zhangwk02** [comment]
目前的执行脚本命令都是指定到某个目录：FileNotFoundError: [Errno 2] No such file or directory: 'E:\\F\\zhangwk02\\APP_UIauto\\test.air\\test.py' 。能否做到执行用例集，下面所有的用例都可以执行
<img width="254" alt="test" src="https://user-images.githubusercontent.com/38233062/40361597-7a5b174c-5dfc-11e8-8043-36e1f35cd49d.png">
@Meteorix

**Comment by zhangwk02** [comment]
@Meteorix  我用bat处理，但是执行 airtest run E:\F\zhangwk02\APP_UIauto\\test.air\\1loginout.air --device Android:///T7G5T15A28000712 --log E:\F\zhangwk02\APP_UIauto\log" 命令没有跑起来。
用python xx.py是可以正常运行；
<img width="486" alt="_20180523140200" src="https://user-images.githubusercontent.com/38233062/40406111-f38d7b74-5e91-11e8-9a24-b98941f90455.png">

**Comment by zhangwk02** [comment]
好的我用bat正在实现
