### ISSUE TITLE
一台mac，怎么实现ios多台手机多线程同时执行

### ISSUE THREAD

**Issue by daisy0o** [AirtestProject/Airtest#600]
**描述问题bug**
一台mac，怎么实现ios多台手机多线程同时执行

1.目前我插了两台手机在一个mac上，端口可以打开多个iproxy 8100 8100，iproxy 8105 8100。但是多个端口查看的信息（如：http://127.0.0.1:8105/status）都是同一部手机，脚本执行的时候也是只运行一部手机
2.每次运行脚本之前，连接手机是不是都要启动iOS-Tagent？我试过test wda之后，再关掉，http://127.0.0.1:8100/status，就查看不到设备信息了，是表示手机连不上了吗？

**复现步骤**
1. 启动两个端口
2. 运行脚本

**预期效果**
一台mac上连接的2部手机可以同时运行

**python 版本:** `python3.5`

**airtest 版本:** `1.2.2`

**设备:**
 - 型号: 2部iphone 7
 - 系统: 12.3，12.3.1

**Comment by EraChen233** [comment]
iOS-Tagent还不支持Mac一拖多哦

**Comment by daisy0o** [comment]
什么时候会做这个扩展呢？很需要。Android都可以多线程，ios也做这个扩展吧。

**Comment by EraChen233** [comment]
如果需要及时了解Airtest最新咨询，可以加QQ群 1017250147 ，关注管理员的更新公告
