### ISSUE TITLE
ios多线程扩展什么时候实现，可以类似appium那种实现方式吗

### ISSUE THREAD

**Issue by daisy0o** [AirtestProject/Airtest#603]
**描述问题bug**
ios多线程扩展什么时候实现，可以类似appium那种实现方式吗

现在使用iOS-Tagent，只能连接一台设备，而且一定要开着wda。不管改不改端口号都只认一部手机

**预期效果**
类似这种调用方式
appium -a 127.0.0.1 -p 4725 --webdriveragent-port 8101

不用一直连着xcode

**python 版本:** `python3.5`

**airtest 版本:** `1.2.2`

**设备:**
 - 型号: iphone7，iphone7
 - 系统: ios12.3.1,ios12.3

**Comment by EraChen233** [comment]
iOS-Tagent 目前不支持一拖多

**Comment by daisy0o** [comment]
后期会做扩展吗？希望能扩展这个

**Comment by daisy0o** [comment]
后期会做扩展吗？希望能扩展这个
