### ISSUE TITLE
可以读取到手机复制的文字么

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/Airtest#605]
数据库操作时需要获得当前的游戏ID
可以直接获得么？
游戏本身提供了复制ID的功能，但是现在不能导入到airtest中使用
请问这两个问题有好的处理方法么

**Comment by liubiantao** [comment]
既然能复制，用这个库读取一下剪贴板 
https://pypi.org/project/pyperclip/

**Comment by abcdd12** [comment]
> 既然能复制，用这个库重新一下即可
> https://pypi.org/project/pyperclip/

这个可以复制移动设备的么？
现在是可以操作软件复制移动设备的ID，无法导入到软件中
或者有没有直接把界面中一部分区域的数字和字母直接转换成可以用的

**Comment by EraChen233** [comment]
目前没有提供相关功能
