### ISSUE TITLE
定义本地pytho后， 按F5启动报错   numpy.core.multiarray failed to import 重装无效

### ISSUE THREAD

**Issue by Sinxs** [AirtestProject/Airtest#606]
版本 1.2.2

定义本地pytho后， 写好脚本后按F5启动报错   numpy.core.multiarray failed to import ,尝试过重装numpy，无效
![image](https://user-images.githubusercontent.com/48276048/68659016-788a6300-0571-11ea-9b29-16804795d0f1.png)

右键选中“只运行选中代码”，可以运行
![image](https://user-images.githubusercontent.com/48276048/68659230-db7bfa00-0571-11ea-90f4-36b84edc12cf.png)

使用自带python库，可以运行

设置选项
![image](https://user-images.githubusercontent.com/48276048/68659497-50e7ca80-0572-11ea-9b03-8c27dd4856bc.png)

**Comment by yimelia** [comment]
定义了本地python后，执行的命令行就是这个：
![image](https://user-images.githubusercontent.com/6896468/68730949-84c1ff00-0609-11ea-8e4d-d528b6ced05a.png)

执行不成功的原因应该是你自己的环境有问题，可以检查下这个python.exe是否能正确import airtest，以及py版本号是多少？

右键点只运行选中代码，使用的是IDE里自带的python运行的，所以没问题

**Comment by terieqin** [comment]
我的是一样的错误。
## 环境
> 新装的 python 3.7.4 64bit
> numpy 1.17.3 或 1.18
> opencv-contrib-python 3.4.2.17
> airtest 1.1.1
这些包都是系统全局pip安装的，都可以正常import。

**Comment by terieqin** [comment]
我的脚本是写在IDE下的某个目录中。

我发现如果使用pycharm运行脚本，这个脚本用的python是全局安装的，但是用的库有些是Airtest IDE里面带的，有些是全局pip安装的。这样子运行就会出现错误。

目前我是要么用IDE运行；要么全局安装airtest，numpy，opencv之后，在pycharm中运行，并且拒绝pycharm读取IDE里面的库。
