### ISSUE TITLE
windows连接unity game视窗  游戏区域非全屏导致点击位置偏移 怎么解

### ISSUE THREAD

**Issue by ywj5** [AirtestProject/Airtest#609]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
**windows连接unity game视窗 ，因为game视窗上面有一块黑色的区域，但是也算进游戏部分了，所以poco一个组件算出的坐标就偏移了，有办法正确选择游戏区域吗**   
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
![airtest](https://user-images.githubusercontent.com/57382557/68825758-47777300-06d6-11ea-9e08-1815359a573b.png)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:**下载的最新的1.2.2**
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]     **win10 + unity2017.4.30f1**
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by dinghongyi** [comment]
`poco = UnityPoco(unity_editor = True)`

**Comment by yimelia** [comment]
试一下看看游戏窗口能否被单独拖出来嵌入到IDE中

**Comment by ywj5** [comment]
poco = UnityPoco(unity_editor = True)
用这句话，然后不要手动连接窗口，直接把game视窗单独拖出来放一边，不要有遮挡，然后运行代码，就会自动操控鼠标去点击了。
