### ISSUE TITLE
selenium连接不上

### ISSUE THREAD

**Issue by liuchang6** [AirtestProject/Airtest#61]
`driver = WebChrome(chrome_options=options)`
WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable

谷歌浏览器版本65.

**Comment by zzldjkzxf** [comment]
@liuchang6  这个问题别人也遇到了，可能是端口冲突导致的，你试试把chrome_options这个参数去掉，改成driver=WebChrome()试试能不能用
