### ISSUE TITLE
airtest执行后log.html加载大量图片失败的问题

### ISSUE THREAD

**Issue by yanglei** [AirtestProject/Airtest#62]
使用命令行方式执行脚本，然后生成log。html之后，加载不了图片，并出现重要卡顿；目前只能支持几百张图片的log，但是我这边需要支持大几千张图片的加载，希望能够帮助解决一下，多谢！

**Comment by Meteorix** [comment]
这个是浏览器的问题，很少网页能够同时显示几百张图片

**Comment by yanglei** [comment]
能否单独做一个error_log，把出错的上下文图片和出错原因写进去呢，这样可以方便定位

**Comment by ASmallListener** [comment]
你的测试脚本也太长了，建议切割脚本后分批显示Log
