### ISSUE TITLE
换设备执行脚本后不能正确的识别截图，这个是正常的么

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/Airtest#620]
pixel XL  安卓9 录制的脚本
换机器  三星s9+  安卓9 
执行脚本的时候好多图都不能正确的识别，问下这个正常么？
录制脚本的时候比较费电，所以换了下手机发现的这个问题

**Comment by yimelia** [comment]
请查阅教程 https://airtest.doc.io.netease.com/tutorial/9_Improved_compatibility/
