### ISSUE TITLE
在小米9手机上运行 报权限问题

### ISSUE THREAD

**Issue by VipMinF** [AirtestProject/Airtest#627]
对于Android手机系统的更新换代，可能旧版本的可能无法支持，是否可以把PocoService Yosemite开源出来？
![Uploading image.png…]()

    driver = AndroidUiautomationPoco(self.device, poll_interval=1)
  File "/usr/local/lib/python3.7/site-packages/poco/drivers/android/uiautomation.py", line 173, in __init__
    self.ime.start()
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/ime.py", line 109, in start
    super(YosemiteIme, self).start()
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/ime.py", line 77, in start
    self.adb.shell("ime enable %s" % self.service_name)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/adb.py", line 370, in shell
    raise AdbShellError(err.stdout, err.stderr)
airtest.core.error.AdbShellError: stdout[b''] stderr[b'Caller must have WRITE_SECURE_SETTINGS permissionSecurity exception: Requires permission android.permission.WRITE_SECURE_SETTINGS\n\njava.lang.SecurityException: Requires permission android.permission.WRITE_SECURE_SETTINGS\n\tat com.android.server.InputMethodManagerService.handleShellCommandEnableDisableInputMethod(InputMethodManagerService.java:5019)\n\tat com.android.server.InputMethodManagerService.access$1700(InputMethodManagerService.java:183)\n\tat com.android.server.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:4817)\n\tat android.os.ShellCommand.exec(ShellCommand.java:103)\n\tat com.android.server.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:4783)\n\tat android.os.Binder.shellCommand(Binder.java:634)\n\tat android.os.Binder.onTransact(Binder.java:532)\n\tat com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:496)\n\tat com.android.server.InputMethodManagerService.onTransact(InputMethodManagerService.java:1515)\n\tat android.os.Binder.execTransact(Binder.java:733)\n']

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/70033454-718fc700-15ea-11ea-8e83-08381196ba58.png)
https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4
