### ISSUE TITLE
【录制视频生成的视频分辩率问题】使用start_recording进行录制视频，手机分辨率为1920*1080，录制出来的视频分辨率为1920*1920；

### ISSUE THREAD

**Issue by RonChu-01** [AirtestProject/Airtest#628]
录制视频生成的视频分辩率问题
问题描述：
使用start_recording进行录制视频，手机分辨率为1920*1080，录制出来的视频分辨率为1920*1920；
现象：
生成的视频，一半为视频，一般黑屏；
期望：
start_recording接口是否可以指定分辨率大小？

**Comment by yimelia** [comment]
不能指定，有一半黑屏的原因是，希望能够同时兼容横屏和竖屏的情况，否则还需要额外再指定本次测试是横屏还是竖屏，如果有些测试用例里横竖屏都有的话就会更加麻烦。
