### ISSUE TITLE
避免重复截图 / 简化代码 / minicap失效

### ISSUE THREAD

**Issue by Erimus-Koo** [AirtestProject/Airtest#634]
简单使用了一下，提几个小问题。

现在几乎所有exists等判断，都是内部截一次图，而截图速度又很慢。
有时候一个界面需要判断几处或几种状态，其实截一次图就够了。
能不能增加一个参数，直接传入截图，如果空缺再自动截图。

---

在exists自动生成的Template里，屏幕参数也是反复出现，能不能取个常量放到别处？
exists(Template(r"tpl1575833081863.png", record_pos=(-0.001, 0.59), resolution=(720, 1280)))
类似这里resolution的部分。

而且这里的record_pos用的是百分比，很不直观。
有时候需要修剪一下图标范围，这个参数就不大方便改。

另外也有人提到支持png透明通道图标的判断（比如图标在不同色的背景上）。

---

另外使用了Airtest之后，会影响机器上原本的minicap，导致用回其它工具截图黑屏。

**Comment by yimelia** [comment]
1. 不断截图的原因是，画面可能是不断在改变中的，如果不一直更新截图，可能会导致更多误判问题。
2. 这个参数记录的是截这张图的那台手机设备的屏幕分辨率，用于在回放时与当前连接的手机设备做对比和拉伸（如果分辨率发生变化的话）。
那么，如果不记录在这里的话，没有其他地方可以记录了：
- 这个参数是与这张图片相关的，而不是与整个脚本相关的，它是这个图片的一部分，我们无法独立将它设置为一个常量
- 图片语句是可以独立复制出来粘贴到别的脚本中的，我们不能保证一个脚本中所有的语句都用了同一个设备来截图、并且分辨率相同
- 在手机设备上，resolution参数基本上是固定的，但是airtest不止支持手机设备，还有其他平台，例如windows窗口，而窗口大小是可能发生变化的。

以及这个参数并不是必须传入的，你可以自行忽略它，不传入本参数只是在使用图像识别的其中某一个算法时，匹配成功率会有所下降，依然有其他算法可以生效。
3. record_pos使用百分比的原因也和分辨率有关，这个参数记录的是录制图片时，这张图片在手机画面上的位置信息。
不是每台手机都使用同样的分辨率，因此我们希望记录的不是一个确切的坐标，而是一个更加通用的百分比位置信息，方便在其他分辨率的手机上还原成坐标。
这个参数同样不是必须传入的，你也可以忽略掉。
4. 关于Template的各项参数的介绍，可以参考[教程](https://airtest.doc.io.netease.com/tutorial/2_Airtest_introduction/#template)
5. 关于minicap的问题，参见 https://github.com/AirtestProject/AirtestIDE/issues/643
6. 感谢你的使用，以及提出来的各项建议。
