### ISSUE TITLE
写import csv报错 

### ISSUE THREAD

**Issue by saisai-dan-shift** [AirtestProject/Airtest#638]
报错：
NameError: name 'csv' is not defined

请问怎样才能调用？

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/70518702-c943aa80-1b75-11ea-96ac-a51465f105f1.png)
https://airtest.doc.io.netease.com/IDEdocs/record_script/how_to_get_started/#_2
