### ISSUE TITLE
all runs great, but howto create a loop?

### ISSUE THREAD

**Issue by thedeadseth** [AirtestProject/Airtest#64]
is it possible to create a loop in this ?

**Comment by Meteorix** [comment]
it is just Python. you can:

```
for i in range(10):
    touch(xxxx)
````

or

```
while not exists(xxxx):
    sleep(2)
```

**Comment by thedeadseth** [comment]
love you

**Comment by Meteorix** [comment]
:)

**Comment by thedeadseth** [comment]
now id really like to pick ur brain if u be willing to assist in a project?
thehtes@gmail

all i am looking todo is if four different images are on screen at one time, they wont ever be on screen at same time. but to check for each, if found click that spot and return to loop for however long id set it. 

huh huh.  up for it? if not i still love ya
