### ISSUE TITLE
连接Android设备时adb无法正常工作

### ISSUE THREAD

**Issue by saisai-dan-shift** [AirtestProject/Airtest#642]
测试机型：Pixcel 3a Android10
环境：win10

报错内容：
```
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell dumpsys SurfaceFlinger
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell getevent -p
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell pm path jp.co.cyberagent.stf.rotationwatcher
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-TeSKFqnR9GrvfqfgYuhERw==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell dumpsys window windows
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell ls /data/local/tmp/minicap
D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell ls /data/local/tmp/minicap.so
ADB指令执行失败，可能需要修改部分手机设置才能使用，请访问[帮助文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html)查看如何设置。
```

> 勾选 javacap时可以正常连接

> Android9 升级到 Android10出现此现象

> 更换了Airtest下的adb到最新版本依然无效

**Comment by saisai-dan-shift** [comment]
> 测试机型：Pixcel 3a Android10
> 环境：win10
> 
> 报错内容：
> 
> ```
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell dumpsys SurfaceFlinger
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell getevent -p
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell pm path jp.co.cyberagent.stf.rotationwatcher
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-TeSKFqnR9GrvfqfgYuhERw==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell dumpsys window windows
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell ls /data/local/tmp/minicap
> D:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93FAY0ALWN shell ls /data/local/tmp/minicap.so
> ADB指令执行失败，可能需要修改部分手机设置才能使用，请访问[帮助文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html)查看如何设置。
> ```
> 
> > 勾选 javacap时可以正常连接
> 
> > Android9 升级到 Android10出现此现象
> 
> > 更换了Airtest下的adb到最新版本依然无效

**Comment by yimelia** [comment]
Duplicate of #504 

Android10问题请参考 https://github.com/AirtestProject/Airtest/pull/618

**Comment by saisai-dan-shift** [comment]
非常感谢
