### ISSUE TITLE
遍历view取get_text非常慢

### ISSUE THREAD

**Issue by qtfreet00** [AirtestProject/Airtest#644]
```
for i in range(0,10):
  
  poco("android.widget.LinearLayout").offspring("android.widget.LinearLayout").offspring("android.widget.FrameLayout").child("android.webkit.WebView").child("android.webkit.WebView").child("android.view.View")[i].get_text()
```
如上这种 在遍历多个view时会异常的慢

测试设备：小米5 8.0
airtest：1.1.1

**Comment by yimelia** [comment]
可以参考一下这个接口：https://poco.readthedocs.io/en/latest/source/doc/poco-example/optimize_speed_by_freezing_UI.html#optimize-speed-by-freezing-ui

每次循环里面，都会重新去获取一遍UI树，导致速度很慢。可以先冻结，再遍历，这样就能加快速度了。
