### ISSUE TITLE
Adb don‘t work suddently,while everything go well at last friday.

### ISSUE THREAD

**Issue by oakpromise** [AirtestProject/Airtest#65]
Traceback (most recent call last):
  File "app\plugins\device\device_panel\util.py", line 25, in adbDevices
  File "airtest\core\android\adb.py", line 196, in devices
  File "airtest\core\android\adb.py", line 172, in cmd
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 106-107: illegal multibyte sequence

**Comment by Meteorix** [comment]
run `adb devices` in your cmd, see what the output is

**Comment by oakpromise** [comment]
It runs well in cmd mode

**Comment by Meteorix** [comment]
Is there any software occupying adb on your PC? Maybe restart your PC and try it again?

**Comment by rockywhisper** [comment]
@oakpromise  Hi, buddy. Maybe you can check [the adb conflict issue](https://www.apowersoft.com/community/topic/cannot-connect-due-to-adb-conflict-issue.html) , and see what happens.
