### ISSUE TITLE
VIVO X20每次到点击输入框部分的图片屏幕就是卡主无法跳转，导致后面图像无法寻找到

### ISSUE THREAD

**Issue by kiritotonggu** [AirtestProject/Airtest#651]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
点击输入框以后人工点击airtest点击也是没有反馈，每次只有通过缩小再打开airtest上才能重新点击窗口，但是不缩小屏幕就会一直卡住不会跳动
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/44113463/71340113-b2974d80-2590-11ea-8e8e-5c203a915941.png)

**python 版本:** `python3.7`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: VIVO X20
 - 系统: Android 8.1
 - (别的信息)

**其他相关环境信息**
windows10系统

**Comment by yimelia** [comment]
抱歉，完全看不懂你的问题描述，能否补充更多详细的问题细节，最好是能够附上完整的截图（如果有不方便展示的信息，可以适当打码，但是请务必保留和你问题相关的内容），否则完全不知道你到底遇到了什么问题。
我先关闭此issue，请不要重新建新单，在下面回复即可，我们会视情况重新reopen这个单。

**Comment by kiritotonggu** [comment]
![image](https://user-images.githubusercontent.com/44113463/71340899-276b8700-2593-11ea-9ace-cf9ff62cdc7a.png)
就是每次跑到这个地方，他输入会变成星号的密码点airtest可视化窗口就会卡死，然后报错找不到图片，但是点击输入账号不会变成星号的时候airtest的可视化窗口并不会卡死，而是继续执行

**Comment by kiritotonggu** [comment]
> 抱歉，完全看不懂你的问题描述，能否补充更多详细的问题细节，最好是能够附上完整的截图（如果有不方便展示的信息，可以适当打码，但是请保留保留和你问题相关的内容），否则完全不知道你到底遇到了什么问题。
> 我先关闭此问题，请不要重新建新单，在下面回复即可，我们会视情况重新重新打开这个单。

![image](https://user-images.githubusercontent.com/44113463/71341630-60a4f680-2595-11ea-8729-b9e19d19bade.png)
就是每次跑到这个地方，他输入会变成星号的密码点airtest可视化窗口就会卡死，然后报错找到图片，但是点击输入账号不会变成星号的时候airtest的可视化窗口并不会卡死，而是继续执行

**Comment by kiritotonggu** [comment]
> 抱歉，完全看不懂你的问题描述，能否补充更多详细的问题细节，最好是能够附上完整的截图（如果有不方便展示的信息，可以适当打码，但是请保留保留和你问题相关的内容），否则完全不知道你到底遇到了什么问题。
> 我先关闭此问题，请不要重新建新单，在下面回复即可，我们会视情况重新重新打开这个单。
![image](https://user-images.githubusercontent.com/44113463/71341691-8500d300-2595-11ea-95a8-18cd45e96887.png)
就是每次跑到这个地方，他点击密码框后airtest可视化窗口就会卡死，然后报错找不到图片，但是点击输入账号不会变成星号的框的时候airtest的可视化窗口并不会卡死，继续执行任务

**Comment by yimelia** [comment]
1. “卡死”具体是什么样的，是否是AirtestIDE的窗口卡死，还是手机卡死，还是什么东西卡死？卡死后是如何恢复的？
2. 部分手机在输入密码时，可能需要开启手机的选项才能够输入，请参考这个文档：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#text

**Comment by kiritotonggu** [comment]
> 1. “卡死”具体是什么样的，是否是AirtestIDE的窗口卡死，还是手机卡死，还是什么东西卡死？卡死后是如何恢复的？
> 2. 部分手机在输入密码时，可能需要开启手机的选项才能够输入，请参考这个文档：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#text

感谢帮忙，已经自行找到问题原因，VIVO手机自身的防录屏导致的IDE窗口的卡死

**Comment by yimelia** [comment]
@kiritotonggu 
如果有具体的解决办法（比如开启某个选项就可以避免此问题），可以分享到这里，我们后续加入到文档中

**Comment by kiritotonggu** [comment]
> @kiritotonggu
> 如果有具体的解决办法（比如开启某个选项就可以避免此问题），可以分享到这里，我们后续加入到文档中

![image](https://user-images.githubusercontent.com/44113463/71351423-9a362b80-25ae-11ea-86bd-3b337508ad3c.png)
部分VIVO手机在使用AirtestIDE时候，脚本点击到输入密码窗口的时候，IDE的可视化窗口可能会卡死，不会实时更新手机屏幕画面，导致脚本会报找不到图片的错误，关闭防恶意截录屏和安全输入就不会因为脚本点击到输入密码框时候IDE可视化窗口卡死
