### ISSUE TITLE
编写多个脚本怎么做能只启动一次浏览器运行所有脚本

### ISSUE THREAD

**Issue by zBeady** [AirtestProject/Airtest#653]
- 用命令行运行官方例子里的针对APP测试的多脚本运行器（https://github.com/dreamhighqiu/airtest_project），用脚本运行后每一个.air都要启动一次浏览器。
- 在Web测试的时候只需要运行一次浏览器然后都在这个浏览器里执行操作。

- 把初始化浏览器放到setUpClass()里报错如下：

```
ERROR: setUpClass (main.CustomAirtestCase)
Traceback (most recent call last):
File "runner.py", line 18, in setUpClass
self.scope["driver"] = driver
AttributeError: type object 'CustomAirtestCase' has no attribute 'scope'
```

**Comment by yimelia** [comment]
Duplicate of https://github.com/AirtestProject/airtest-selenium/issues/5

语法问题，请自行解决
