### ISSUE TITLE
设备长时间连接，各设备电池纷纷鼓包

### ISSUE THREAD

**Issue by 1031561252** [AirtestProject/Airtest#654]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**
设备一直长时间连接在电脑上面，用于各种回归冒烟任务、但是时间长了设备都出现电池鼓包现象，看起来像要炸了，这里有什么比较好的方案可以推荐一下避免么

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/71437948-a5b06080-272e-11ea-9df5-675abb64bb20.png)
