### ISSUE TITLE
touch()中duration参数设置无效

### ISSUE THREAD

**Issue by ymirshuai** [AirtestProject/Airtest#661]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
想要实现按住操作时，使用执行选中代码，
使用
touch((551, 691),duration=2)
无效，点击操作瞬间完成
而使用
swipe((551, 691),(551,695),duration=2)
可以达成效果。

**python 版本:** `python3.7`

**airtest 版本:** `1.1.1`

**设备:**
 - 型号: huawei mate9
 - 系统: Android 8.0

**Comment by yimelia** [comment]
发一下你的设备连接是怎么连的看看，就是说，运行时的命令行是怎么传入--device参数的，或者是如果你用了connect_device来连手机，传了什么样的参数？
目前duration这个参数只支持minitouch模式点击，如果用了adbtouch模式是无效的

**Comment by ymirshuai** [comment]
![image](https://user-images.githubusercontent.com/17920713/71510136-c6acb900-28c8-11ea-84b6-f3d6628a79e1.png)
用IDE自带的连接

执行时：
python -m airtest runXXX --device Android:///3HX0217B17000150

**Comment by yimelia** [comment]
试一下点别的东西看看行不行，我们有遇到过某些应用里面长按没效果，但是在桌面上长按是有效的情况

**Comment by ymirshuai** [comment]
@yimelia 
在桌面尝试长按app图标依然无效

**Comment by yimelia** [comment]
我们这里有华为mate9，但是系统版本是Android7，试了下长按是没问题的
另外找了一台Android8的荣耀V9，也没有问题。
暂时无法复现此问题
