### ISSUE TITLE
提个建议，感觉新的报告版本还没有之前的好

### ISSUE THREAD

**Issue by Chersh-Pan** [AirtestProject/Airtest#666]
原来的报告，可以很方便的定位到出错的时间点，现在报告显示每个步骤的耗时，但却没有时间点了。建议可以增加时间节点

**Comment by EraChen233** [comment]
你说的报告，是用 airtest1.1.0 的吧，最新的 AirtestIDE自带1.1.0，我们后面发布了 1.1.1，可以试一下 airtest 1.1.1 的报告

**Comment by Chersh-Pan** [comment]
意思就是1.1.1的报告感觉没有1.1.0的报告好，最新的报告显示了每个步骤的耗时，但没有每个步骤发生的时间点

**Comment by EraChen233** [comment]
众口难调，报告很难让每个用户都满意。但是你说的时间点是个好建议，我们后续会考虑加进来的

**Comment by EraChen233** [comment]
1.1.2版本已发布，增加了步骤的节点时间
![image](https://user-images.githubusercontent.com/5961185/72605268-6a810600-3957-11ea-9eb2-9ec3899f3783.png)
