### ISSUE TITLE
Windows输入框无法输入QQ密码

### ISSUE THREAD

**Issue by NanYeYe** [AirtestProject/Airtest#667]
![image](https://user-images.githubusercontent.com/11953895/71659187-a32eb600-2d81-11ea-83a0-1e882e29c5e4.png)
无法输入也没报错
使用keyevent或者text方法都不行

**Comment by yimelia** [comment]
这个很可能是QQ自己设置的保护机制，不允许自动输入，可以考虑用软键盘来截图输入，或者手工输入

**Comment by NanYeYe** [comment]
> 这个很可能是QQ自己设置的保护机制，不允许自动输入，可以考虑用软键盘来截图输入，或者手工输入

截图输入是什么方式？可自动化吗

**Comment by yimelia** [comment]
关键词不是截图输入，是 “软键盘”

**Comment by NanYeYe** [comment]
> 关键词不是截图输入，是 “软键盘”

是说打开软键盘，然后一个数字一个数字截图点击？

**Comment by NanYeYe** [comment]
> > 关键词不是截图输入，是 “软键盘”
> 
> 是说打开软键盘，然后一个数字一个数字截图点击？

使用pyautogui替换airtest的输入解决
