### ISSUE TITLE
IOS设备横屏展示, touch截图区域不正确

### ISSUE THREAD

**Issue by duhongjun** [AirtestProject/Airtest#670]
IOS设备横屏下, touch截图区域不正确, 如图
**复现步骤：**

**python 版本:** `python2.7.16`

**操作系统:** `mac os 10.15.2`

**手机设备信息:**
 - 手机型号: iphone xs max
 - Iphone系统版本号: [10.13]
 - xcode版本: 11.3

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**截屏**
录了个gif  ↓↓↓
https://tva1.sinaimg.cn/large/006tNbRwly1gajdsygxhqg30s20dwx6q.gif
![Dec-31-2019 17-13-12](https://tva1.sinaimg.cn/large/006tNbRwly1gajdsygxhqg30s20dwx6q.gif)
可以看到, 当截取屏幕右侧时, 提示不在截图范围, 在截图范围内的, 截出来的图位置不对

**Comment by Sammsuo** [comment]
对的，我也遇到了这个问题，在转到poco的时候，能够看到整个app的画面只能识别到左边，右边无法识别。
我的是mac连接ios  在桌面的时候正常竖屏显示，一进app  手机横屏了之后，IDE上面的画面也跟着横屏，然后出现上述情况，调整了识别率之后，上述问题解决，但是截图的位置与实际点击的位置有严重偏差
