### ISSUE TITLE
新版本使用Airtest_selenium生成测试报告无法查看到图片和内容

### ISSUE THREAD

**Issue by WindInMay524** [AirtestProject/Airtest#674]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
测试报告html文件没有内容
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
![image](https://user-images.githubusercontent.com/38344643/72054362-ccac8c00-3303-11ea-8676-16666c5ff9a6.png)

**复现步骤**
# -*- encoding=utf8 -*-
__author__ = "tangtt"

from airtest.core.api import *

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)

driver.get("http://10.106.0.215:8080/")
auto_setup(__file__)
driver.find_element_by_xpath("//input[@type='text']").send_keys("***")
driver.find_element_by_xpath("//input[@type='password']").send_keys("***")
driver.find_element_by_xpath("//button[@type='submit']").click()

**预期效果**
看到每一步的执行效果

**python 版本:** `python3.7`

**airtest 版本:** `1.2.2`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: Chrome  79
 - 系统: Windows 10
 - (别的信息)

**其他相关环境信息**
1.2.1版本可以显示操作但没有截图
![image](https://user-images.githubusercontent.com/38344643/72054547-257c2480-3304-11ea-9d03-3dbce727c955.png)

**Comment by EraChen233** [comment]
换成用chrome浏览器打开报告，注意旧版chome也不支持。
或者，使用更新的airtest版本，比如1.1.1
