### ISSUE TITLE
airtest 图像识别瞬时占用CPU高

### ISSUE THREAD

**Issue by Chersh-Pan** [AirtestProject/Airtest#676]
在用airtest使用图像识别操作软件时会发现瞬时CPU占用很高，会影响到测试软件的功能

环境windows10、airtest 1.1.1版本、python3.7.4

**Comment by Chersh-Pan** [comment]
偶尔瞬时占用100%

**Comment by yimelia** [comment]
可以考虑换一种图像识别算法，具体参考： https://github.com/AirtestProject/Airtest/blob/master/benchmark/README_cn.md
