### ISSUE TITLE
我的页面有几个相同图像，能否指定区域进行touch呢

### ISSUE THREAD

**Issue by xiaoyuerrocketcat** [AirtestProject/Airtest#677]
我是ui结合图像进行识别的，我的页面有几个相同图像，我能否根据ui进行指定一个区域范围，airtest就在我指定的区域寻找这个图像，进行touch呢
很多地方都需要指定区域进行touch，不然会错误点击其他的。
谢谢哈

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/tutorial/9_Improved_compatibility/#21

**Comment by lincoln987** [comment]
构建一个局部找图函数就可以了

        screen = G.DEVICE.snapshot()  #截图到内存
        #图片裁切
        predict_screen = aircv.crop_image(screen, (x_min, y_min, x_max, y_max))
        #找图
        focus_pos = template.match_in(predict_screen) 
        return focus_pos[0]+x_min,focus_pos[1]+y_min

**Comment by azz212** [comment]
> 构建一个局部找图函数就可以了
> 
> ```
>     screen = G.DEVICE.snapshot()  #截图到内存
>     #图片裁切
>     predict_screen = aircv.crop_image(screen, (x_min, y_min, x_max, y_max))
>     #找图
>     focus_pos = template.match_in(predict_screen) 
>     return focus_pos[0]+x_min,focus_pos[1]+y_min 
> ```

这个方法好，可以自己截图来进行查找
