### ISSUE TITLE
使用ADB()的方法报错：set serialno

### ISSUE THREAD

**Issue by NanYeYe** [AirtestProject/Airtest#678]
from airtest.core.android.adb import ADB
adb = ADB()
adb.get_top_activity() //执行该语句会提示set serialno first

这里不会自动选择当前连接的设备吗？怎么获取当前连接设备的serialno呢

**Comment by yimelia** [comment]
不会自动选，必须要在初始化ADB对象的时候指定一下手机序列号，具体可以查阅API的注释部分。
你可以直接把当前设备的序列号作为参数传进去， 也可以先连上手机，再获取到当前手机的adb对象以及调用接口，参见文档：https://airtest.doc.io.netease.com/tutorial/4_Android_automated_testing_one/#android_1

![image](https://user-images.githubusercontent.com/6896468/72244775-f3333580-3629-11ea-8bf3-5ab1f5e6c76a.png)

除上述方式外，也可以这样：
```
dev = device()
dev.adb.get_top_activity()
```
