### ISSUE TITLE
手机重启后，minitouch不能被重新开启。

### ISSUE THREAD

**Issue by matthewdy** [AirtestProject/Airtest#681]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
我们在测试脚本，需要用到重启，但是minitouch在重启以后，不能被重新install and setup.
应该和以下代码有关:
在初次 调用 touch的时候，会install和setup minitouch，但是再设备重启以后，airtest认为环境是setup好的但是设备上实际上是没有setup minitouch的。 请查看以下代码，方便定位
` @on_method_ready('install_and_setup')
    def touch(self, tuple_xy, duration=0.01):
        """
        Perform touch event

        minitouch protocol example::

            d 0 10 10 50
            c
            <wait in your own code>
            u 0
            c

        Args:
            tuple_xy: coordinates (x, y)
            duration: time interval for touch event, default is 0.01

        Returns:
            None

        """
        x, y = tuple_xy
        x, y = self.__transform_xy(x, y)
        self.handle("d 0 {:.0f} {:.0f} 50\nc\n".format(x, y))
        time.sleep(duration)
        self.handle("u 0\nc\n")`
```
@ready_method
    def install_and_setup(self):
        """
        Install and setup minitouch

        Returns:
            None

        """
        self.install()
        self.size_info = self.ori_function()
        self.setup_server()
        if self.backend:
            self.setup_client_backend()
        else:
            self.setup_client()
```
```
def ready_method(func):
    @wraps(func)
    def wrapper(inst, *args, **kwargs):
        key = "_%s_ready" % func.__name__
        ret = func(inst, *args, **kwargs)
        setattr(inst, key, True)
        return ret
    return wrapper
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
可以考虑在执行完重启后，再手工调用一次install_and_setup，因为在初始化的时候设置了一个标志位，不会重复执行这个初始化代码。airtest实际上不知道之前有没有初始化过（每一次初始化都是开一个新端口映射，每次都不同），所以可以考虑在手机重启后，连上之后，dev = device(), dev.minitouch.install_and_setup() 这样去手工执行一遍（minicap也类似）

**Comment by matthewdy** [comment]
@yimelia 谢谢快速回复。
