### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by giangnb-dev** [AirtestProject/Airtest#682]
![image](https://user-images.githubusercontent.com/56757898/72694570-fa959a00-3b67-11ea-9b77-3d5e55419aaf.png)

When i use api Airtest mix Poco and i give error. So how solution?

**Comment by yimelia** [comment]
Because you tried to restart the ADB server, the connection may be disconnected, you can redefine poco after `connect_device()` ( just move `poco = UnityPoco()` after `connect_device`)
