### ISSUE TITLE
使用--export命令无法正确生成报告

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#683]
@yimelia 
airtest升级之后（1.1.2版本），导出报告使用--export命令，log.html打开的内容错乱，见截图
![image](https://user-images.githubusercontent.com/26775694/72713933-d908d280-3ba8-11ea-9cad-fa5c86f77a95.png)

![image](https://user-images.githubusercontent.com/26775694/72714216-516f9380-3ba9-11ea-9875-1bd9e51ecc24.png)

**Comment by yimelia** [comment]
发一下命令行

**Comment by ymdhtt** [comment]
py -3 -m airtest report E:\scripts\test_cases\gok_dachen_up_lv.air --log_root E:\scripts\test_cases\gok_dachen_up_lv.air\log\vivox23 --outfile E:\scripts\test_cases\gok_dachen_up_lv.air\log\vivox23\log.html --lang zh --export E:\report --plugin poco.utils.airtest.report

**Comment by ymdhtt** [comment]
没有升级之前都是正常的

**Comment by yimelia** [comment]
去掉Outfile看看，在export命令里面outfile是无用的

**Comment by yimelia** [comment]
自动生成的Html在 xx.log目录里，会比 log_root高一层级

**Comment by ymdhtt** [comment]
去掉outfile可以了，之前没去掉outfile，在上一层也是没有的

**Comment by yimelia** [comment]
在export报告的时候，实际上outfile这个参数是没有用的，html只会输出到一个固定的路径下（因为html里图片链接全是相对链接）
