### ISSUE TITLE
[Question] Can I get full size screenshots of iphone?

### ISSUE THREAD

**Issue by shyho-gh** [AirtestProject/Airtest#685]
Sorry for the questions, not the problems.

Can I get full size screenshots of iphone?
Can I get a screenshot of iphone in png 32bit?

**Comment by yimelia** [comment]
yes, just use `snapshot`
```
snapshot(filename="xxx")
```
or 
```
dev = device()
dev.snapshot(filename="xxx")
```

**Comment by shyho-gh** [comment]
Even if you use the snapshot function, the image doesn't seem to be the same size as the iPhone screen size.
For example, in the case of iPhone 8, if you take a screenshot on the actual machine side
750x1334 png 48bit
You can create a file
For the snapshot function
674x1200 png 24bit
File.
Can I take an image of the same standard as the screenshot on the actual device?

**Comment by shyho-gh** [comment]
@yimelia 
Excuse me. Please continue to support the comments above.
