### ISSUE TITLE
怎么样关闭cv.py图像识别模块的debug日志

### ISSUE THREAD

**Issue by turkey66** [AirtestProject/Airtest#686]
![image](https://user-images.githubusercontent.com/40119890/73777576-b095f080-47c4-11ea-9ad9-54ba77265ef5.png)

hi，你好，我想问下这个日志怎么关闭
![image](https://user-images.githubusercontent.com/40119890/73777626-c73c4780-47c4-11ea-86b8-80dd8b29266a.png)

**Comment by refactor2** [comment]
+1

**Comment by yimelia** [comment]
https://github.com/AirtestProject/Airtest/issues/562
