### ISSUE TITLE
希望命令行执行air脚本时，能向air脚本里传递参数

### ISSUE THREAD

**Issue by ly-so** [AirtestProject/Airtest#69]
命令行执行 airtest run path.air 时，希望能向 .air目录下的py文件里传递参数

**Comment by Meteorix** [comment]
可以选择用环境变量来传

**Comment by ly-so** [comment]
不太明白，能具体说说是怎么传的吗？比如，我想把一个ID值传进.py文件，在.py文件里操作数据库里面这个ID的数据。

**Comment by Meteorix** [comment]
你可以在命令行中指定环境变量，以windows为例，新建run.bat：
```
set id=1
airtest run path.air
```
然后在py脚本中：
```
import os
ID = os.getenv("id")
```
然后用run.bat来运行

**Comment by OldTiger** [comment]
如果是多个test 同时运行 每个test 传入的变量希望是不一样的， 这该怎么做 @Meteorix

**Comment by yimelia** [comment]
@OldTiger 
可以参考一下这个[文档](http://airtest.netease.com/docs/cn/5_airtest_framework/3_launcherpy.html#id14)
写一个启动器来代替IDE默认用的那个，然后可以自定义想传入的参数名字和内容，这个应该可以满足你的需求

**Comment by OldTiger** [comment]
谢了哥们
