### ISSUE TITLE
name 'args' is not defined

### ISSUE THREAD

**Issue by giangnb-dev** [AirtestProject/Airtest#690]
![image](https://user-images.githubusercontent.com/56757898/74114741-5fc83280-4bde-11ea-9379-221c1456b6b4.png)

i follow http://airtest.netease.com/docs/en/1_online_help/advanced_features.html?highlight=setup and give error. Am I wrong setup?

**Comment by EraChen233** [comment]
It's a syntax error. The traceback is very clear.

**Comment by giangnb-dev** [comment]
@EraChen233 
I tried and it still does not work
https://github.com/AirtestProject/Airtest/blob/master/playground/xy.py

**Comment by yimelia** [comment]
hi @giangnb-dev 
use `airtest run xx.air` to run the script, 
 https://airtest.readthedocs.io/en/latest/README_MORE.html#running-air-from-cli
don't use `unittest` to run xx.air, it may cause errors. or you can just creat a python script, like this: https://airtest.doc.io.netease.com/en/IDEdocs/record_script/create_script/#create-a-new-py-script-new
