### ISSUE TITLE
夜神模拟器连接失败

### ISSUE THREAD

**Issue by gogolzf** [AirtestProject/Airtest#693]
夜神模拟器连接失败
![image](https://user-images.githubusercontent.com/49018133/74796787-8d129000-5304-11ea-91f8-877e60e68d38.png)

**Comment by yimelia** [comment]
请检查模拟器上是否成功自动安装了`yosemite.apk`，如果没有安装的话，检查开发者选项中是否默认阻止了通过USB安装应用，应该选择允许，然后在连接时IDE会自动向模拟器中安装该apk
如果还是装不上，可以在IDE目录下搜索一下这个apk文件，手工安装到模拟器中
