### ISSUE TITLE
Cant clear android log

### ISSUE THREAD

**Issue by farosep** [AirtestProject/Airtest#694]
**Use this code to write device logs**

LogFile = open("name.log","w")
for i in CurrentDevice.logcat(): 
        LogFile.write(str(i)+'\n')
        if Strings >= 40000:
            break

**then i tryed to use** 
os.system('adb -d device_serial_number logcat -c')
**to clean logs**

**but get this** 

adb server version (40) doesn't match this client (41); killing...
could not read ok from ADB Server
* failed to start daemon
- waiting for device -
error: cannot connect to daemon

im using python 3.6.7
airtest version:1.2.3

**tryed with several devices** 
Xiaome Redmi Note 4, Galaxy A51, RedmiGo

**Comment by yimelia** [comment]
`adb server version (40) doesn't match this client (41); killing...`
This is caused by different ADB version numbers, `adb.exe` version in airtest is 40, and in your computer is 41, just to overwrite one with the other and ensure that all version numbers are consistent.
