### ISSUE TITLE
python usb方式不能连接多台手机

### ISSUE THREAD

**Issue by youyebingmu** [AirtestProject/Airtest#698]
**mac 环境 python3.7.5，预期：用python多线程控制多台手机，一直不成功，于是用单线程，发现只能连接一台手机**

`from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco

device1 = connect_device('Android://127.0.0.1:5037/' + 'KWG7N16914004590')
device2 = connect_device('Android://127.0.0.1:5037/' + 'CLB0219426000573')

poco1 = AndroidUiautomationPoco(device1, use_airtest_input=True, screenshot_each_action=False)
poco2 = AndroidUiautomationPoco(device2, use_airtest_input=True, screenshot_each_action=False)
# time.sleep(4)

poco1(text='小红书').wait(5)
poco1(text='小红书').click()

poco2(text='小红书').wait(5)
poco2(text='小红书').click()`

**Comment by lincoln987** [comment]
官方例程里有个多设备交互的例子
需要用set_current（）切换设备
