### ISSUE TITLE
windows上各种语言开发的cs模式客户端监控

### ISSUE THREAD

**Issue by wanghaisheng** [AirtestProject/Airtest#70]
请问 咱这个工具能用于触发windows上各种语言开的cs客户端吗  比如java dephi c#之类的。
想要监控的动作为
打开客户端 点击某个菜单，完成鼠标点击、键盘输出，点击保存按钮以后将当前操作的页面以截图或者虚拟打印的方式输出到某个目录

**Comment by Meteorix** [comment]
你好，可以先试试AirtestIDE连接客户端窗口进行自动化测试：http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/4_windows_connection.html
