### ISSUE TITLE
多进程 Python 控制多台手机报错

### ISSUE THREAD

**Issue by yang152412** [AirtestProject/Airtest#701]
Remove any following parts if does not have details about

**Describe the bug**
本地 Python 环境，用多个窗口跑 Python 脚本，来控制4台手机，刚开始正常跑一会就有报错：

```
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=17959): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x078A5510>: Failed to establish a new connection: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。',))
Exception ignored in: <bound method RpcObjectProxy.__del__ of '<Rpc remote object proxy of com.netease.open.libpoco.Node@959cd83>'>
Traceback (most recent call last):
  File "C:\Users\ddmc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "C:\Users\ddmc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\hrpc\client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "C:\Users\ddmc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\hrpc\transport\http.py", line 26, in send
```

**python version:** `python3.6`

**airtest version:** `最新版`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: 红米 note8
 - OS: MIUI11
 - more information if have

**Comment by EraChen233** [comment]
多机运行我们提供了一个样例，可以参考这个实现
https://github.com/AirtestProject/multi-device-runner

根据提供的报错信息，只能看出是socket套接字冲突，但是信息太少，无法分析更多原因。
如果是开始正常，跑了一段时间报错的话，可以初步猜测你实现的多机运行是可以使用的，可以检查一下运行中途，设备的状态

**Comment by yang152412** [comment]
@EraChen233 设备状态都是正常的，没有出现掉线等情况。现在是  一台电脑只能同时连 2 台红米手机 正常执行脚本没问题。再多就报错了。这个会是什么原因呢？

**Comment by yimelia** [comment]
@yang152412 
没办法实地调试，暂时看不出太多问题，可以考虑排查一下看看是否是USB不稳定导致的（比如USBHUB供电不稳、接口不稳定、USB线质量不好等，并且不要用wifi连手机），因为只要中途有一点波动，就会导致poco断线无法重连。
针对大批量的企业级用户，我们也提供了一个解决方案可以参考一下：https://airlab.163.com/b2b
