### ISSUE TITLE
(raspberry) can find opencv-contrib-python dependence during installing, while opencv already be compiled and installed 

### ISSUE THREAD

**Issue by GerrieWell** [AirtestProject/Airtest#707]
**Describe the bug**
I can't install airtest on raspberry. it stop at install `opencv-contrib-python<=3.4.2.17`. Actually any version of this package can't be found on pypi. So I compile and install opencv-contrib-python follow by this instruction [link](https://www.learnopencv.com/install-opencv-4-on-raspberry-pi/). 
Finally, the opencv was be installed properly:
```
pi@NanoPi-NEO:~/SDKs/opencv/build$ python3 -c 'import cv2;print(cv2.__file__);print(cv2.__version__)'
/usr/local/lib/python3.5/dist-packages/cv2.cpython-35m-arm-linux-gnueabihf.so
3.4.2
```
But the pip can't still find the opencv:
```
 Could not find a version that satisfies the requirement opencv-contrib-python<=3.4.2.17 (from airtest) (from versions: )
No matching distribution found for opencv-contrib-python<=3.4.2.17 (from airtest)
```
Any idea to help me? thank a lot.

**python version:** `python3.5`

**Smartphone (please complete the following information):**
 - OS: [raspberry]

**Comment by yimelia** [comment]
Since you have installed cv2, just skip it?
```
requirement.txt
#opencv-contrib-python<=3.4.2.17
```
and `pip install -r requirement.txt` again

**Comment by GerrieWell** [comment]
thx. The issue is solved by installing from source compile.
