### ISSUE TITLE
其poco（‘’xxxxxxx.VISIBLE”）.children()遍历子节点的时候，子节点的顺序不能够得到保障，违背所见即所得的初衷，能否优化下。

### ISSUE THREAD

**Issue by syz2030** [AirtestProject/Airtest#709]

**Comment by yimelia** [comment]
首先，我们没有遇到过类似的问题，请补充清楚你使用的poco类型是什么，在什么样的app上遇到了这样的问题。
并且请具体描述，最好附上截图，说明”子节点顺序不能得到保障“具体是什么情况，到底是顺序错乱，还是只能看到一部分子节点，还是什么？我们无法猜测到你遇到了什么问题，并不能确认它是一个BUG。
最后，在很多场景下，只能获取到的子节点是”当前画面中显示的子节点列表“（节点顺序是固定的，我们没有遇到过顺序被打乱的情况），而不一定能获取到全部的子节点（画面外的节点可能获取不到）。
在本问题能够被确认为一个BUG之前，我先暂时关闭这个issue，如果有需要的话，请补充完整你的问题再reopen它，感谢。

**Comment by syz2030** [comment]
确实有点问题，大佬：顺序紊乱了。右边的是看到的UI树里面显示的，左边是打印出来的，顺序怎么成这样了呢？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 中午11:29
收件人:&nbsp;"AirtestProject/Airtest"<Airtest@noreply.github.com&gt;;
抄送:&nbsp;"胡汉三又回来了"<2899913417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/Airtest] 其poco（‘’xxxxxxx.VISIBLE”）.children()遍历子节点的时候，子节点的顺序不能够得到保障，违背所见即所得的初衷，能否优化下。 (#709)





 
首先，我们没有遇到过类似的问题，请补充清楚你使用的poco类型是什么，在什么样的app上遇到了这样的问题。
 并且请具体描述，最好附上截图，说明”子节点顺序不能得到保障“具体是什么情况，到底是顺序错乱，还是只能看到一部分子节点，还是什么？我们无法猜测到你遇到了什么问题，并不能确认它是一个BUG。
 最后，在很多场景下，只能获取到的子节点是”当前画面中显示的子节点列表“（节点顺序是固定的，我们没有遇到过顺序被打乱的情况），而不一定能获取到全部的子节点（画面外的节点可能获取不到）。
 在本问题能够被确认为一个BUG之前，我先暂时关闭这个issue，如果有需要的话，请补充完整你的问题再reopen它，感谢。

**Comment by syz2030** [comment]
我想问能重构一下方法sibling（）的查找方法吗，大佬，里面加个选择判断整体从上到下所有的兄弟节点按顺序排，或者以本参考节点为零索引，发散找其他的可能较好，毕竟一般会对自己所关注的节点联系紧密的节点更有意义些，您看呢，大佬。


从0出选中的节点来找其余的，不能整个同辈的兄弟节点都拿出来找，因为前面的节点可能在滑动的时候并没有出来，你选中的节点就失去了意义，但是本节点周围的节点一般会在的。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 中午11:29
收件人:&nbsp;"AirtestProject/Airtest"<Airtest@noreply.github.com&gt;;
抄送:&nbsp;"胡汉三又回来了"<2899913417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/Airtest] 其poco（‘’xxxxxxx.VISIBLE”）.children()遍历子节点的时候，子节点的顺序不能够得到保障，违背所见即所得的初衷，能否优化下。 (#709)





 
首先，我们没有遇到过类似的问题，请补充清楚你使用的poco类型是什么，在什么样的app上遇到了这样的问题。
 并且请具体描述，最好附上截图，说明”子节点顺序不能得到保障“具体是什么情况，到底是顺序错乱，还是只能看到一部分子节点，还是什么？我们无法猜测到你遇到了什么问题，并不能确认它是一个BUG。
 最后，在很多场景下，只能获取到的子节点是”当前画面中显示的子节点列表“（节点顺序是固定的，我们没有遇到过顺序被打乱的情况），而不一定能获取到全部的子节点（画面外的节点可能获取不到）。
 在本问题能够被确认为一个BUG之前，我先暂时关闭这个issue，如果有需要的话，请补充完整你的问题再reopen它，感谢。

**Comment by syz2030** [comment]
感谢大佬关注一下，您看看有什么好的方法可以整一下不呢？如果可以确定顺序那也是可以弥补sibling（）的查找的盲点，您觉得呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 中午11:29
收件人:&nbsp;"AirtestProject/Airtest"<Airtest@noreply.github.com&gt;;
抄送:&nbsp;"胡汉三又回来了"<2899913417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/Airtest] 其poco（‘’xxxxxxx.VISIBLE”）.children()遍历子节点的时候，子节点的顺序不能够得到保障，违背所见即所得的初衷，能否优化下。 (#709)





 
首先，我们没有遇到过类似的问题，请补充清楚你使用的poco类型是什么，在什么样的app上遇到了这样的问题。
 并且请具体描述，最好附上截图，说明”子节点顺序不能得到保障“具体是什么情况，到底是顺序错乱，还是只能看到一部分子节点，还是什么？我们无法猜测到你遇到了什么问题，并不能确认它是一个BUG。
 最后，在很多场景下，只能获取到的子节点是”当前画面中显示的子节点列表“（节点顺序是固定的，我们没有遇到过顺序被打乱的情况），而不一定能获取到全部的子节点（画面外的节点可能获取不到）。
 在本问题能够被确认为一个BUG之前，我先暂时关闭这个issue，如果有需要的话，请补充完整你的问题再reopen它，感谢。

**Comment by yimelia** [comment]
如果可以的话，你可以提交一个PR，把你的修改代码测试通过后上传到poco仓库，我们会进行测试和验证最后merge

**Comment by syz2030** [comment]
我道行还不太够，只是使用的时候发现了可以优化的地方，我现在正在仔细研究源码，到时候能改动好的话，我会提交你们过目审核的，谢谢大佬们的贡献，你们的大牛可能更为熟悉些，可能修改的化更为便捷，我自己先尝试改改，我站在巨人的肩上还是要先学习好你们的源码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 下午2:52
收件人:&nbsp;"AirtestProject/Airtest"<Airtest@noreply.github.com&gt;;
抄送:&nbsp;"胡汉三又回来了"<2899913417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/Airtest] 其poco（‘’xxxxxxx.VISIBLE”）.children()遍历子节点的时候，子节点的顺序不能够得到保障，违背所见即所得的初衷，能否优化下。 (#709)





 
如果可以的话，你可以提交一个PR，把你的修改代码测试通过后上传到poco仓库，我们会进行测试和验证最后merge
