### ISSUE TITLE
selenium插件不支持NoSuchElementException

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/Airtest#71]
############代码
try:
    driver.find_element_by_xpath("//a[@href='editDescription']").assert_text("添加说明")
except (AssertionError, NoSuchElementException),e:
    print "111"
############代码

AirtestIDE执行报错

ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 88, in runTest
  File "D:\xxx\xxx\airtest\my-testflow\airtest_project_temp\xxx.air\xxx.py", line 21, in <module>
    except (AssertionError, NoSuchElementException),e:
NameError: name 'NoSuchElementException' is not defined

**Comment by Meteorix** [comment]
请问你脚本中import这个Exception吗？

**Comment by yuzhujiutian** [comment]
from selenium.common.exceptions import NoSuchElementException

谢谢，加了这行代码后，正常。
