### ISSUE TITLE
网络不好，弹出断网提示怎么处理

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/Airtest#710]
跑脚本过程中如果断网了怎么处理，如果某个点的话可以加判断
关键是任何时候都有可能断网，而且时间不定，地点不定
这种弹窗如何处理，最好能有代码讲解  拜托了(●'◡'●)

**Comment by yimelia** [comment]
可以另外开一个线程一直检查是否有弹窗，有就去点

**Comment by xin7c** [comment]
> 可以另外开一个线程一直检查是否有弹窗，有就去点

用thread吗？
