### ISSUE TITLE
【安卓10 ,miui 11】 ,检测不了屏幕是否锁定  "Couldn't determine screen ON ”

### ISSUE THREAD

**Issue by Pactortester** [AirtestProject/Airtest#711]
【安卓10 ,miui 11】 ,检测不了屏幕是否锁定  "Couldn't determine screen ON “

设备：小米8 miui11 android 10
1.is_screenon()
2.is_locked()

以上2个api，检测屏幕是否锁定时报错："Couldn't determine screen ON “

**Comment by yimelia** [comment]
感谢指出，应该是android10上面这个指令变化了，我们后续兼容一下

**Comment by Pactortester** [comment]
https://github.com/AirtestProject/Airtest/pull/763

**Comment by Pactortester** [comment]
1.1.4已修复
