### ISSUE TITLE
[enhancement]怎么样只截取屏幕部分区域，不截取整个屏幕

### ISSUE THREAD

**Issue by oneTaken** [AirtestProject/Airtest#712]
这应该算是一个enhancement吧，目前还没有找到能实现截取屏幕部分区域的办法。

问题描述：
目前对于截屏的性能要求比较高，而且只会用到屏幕里面的一小部分区域，每次都截屏所有区域会造成很大的性能浪费。

请问怎么能够实现截取屏幕部分区域来进行性能加速啊。

thx.

**Comment by yimelia** [comment]
如果你希望截屏之后，对截图进行裁剪，获取到其中某个部分的图片的话，是有现成接口的，参见`airtest.aircv.crop_image()`接口
但是如果你希望在一开始截图时，就限定好只截某个区域的话，暂时不支持。因为实际上我们使用的minicap的截图方式效率已经很高，能够达到30-40帧每秒（即至少一秒钟能截到30张以上的图片），Javcap模式下截图效率也还是不错的，至少你能够在AirtestIDE中流畅地操作手机屏幕，就说明瓶颈并不在于截图部分。
在你没有补充更多问题细节之前，我们不会将这个issue设为enhancement，如果希望作为需求的话，可以补充更多的细节来清楚明确地描述你的问题

**Comment by oneTaken** [comment]
@yimelia 
我看了下`airtest.aircv.crop_image()`的接口代码，就是crop的逻辑，说明核心的点30fps是minicap的功能。
我目前截屏用的`device._neo_wda_screenshot()`，即`wda.HttpClient().http.get("screenshot").value`的最核心的截屏逻辑，我这边最快能达到18fps，目前的性能瓶颈是在这里，能问下30~40fps是怎么测出来的吗，还是说与网速有关系？

**Comment by yimelia** [comment]
这就是为什么刚才会回复
> 在你没有补充更多问题细节之前，我们不会将这个issue设为enhancement，如果希望作为需求的话，可以补充更多的细节来清楚明确地描述你的问题

你的问题描述中并没有说明清楚使用的是ios设备，30帧以上是android手机上的表现，ios的会偏慢一些。
你的问题描述中也没有说明清楚，到底是希望获取小截图来减少空间浪费，还是希望提升识别速率。

建议再完善一下你的问题，如果是认为截图的速度过慢，但是实际上18fps截出来的图，一秒钟我们也不会识别这么多次图像？
如果是认为图像识别算法慢，我们在截图时有记录截图的坐标位置，在识别时也会优先去识别当时记录下来的坐标位置附近的区域，如果找不到，才会扩展到在全图找，这是目前的实现方式。
