### ISSUE TITLE
为什么要新增一步『根据识别区域，求出结果可信度』

### ISSUE THREAD

**Issue by shouyong** [AirtestProject/Airtest#715]
如SURF这种算法，既然都获得了计算结果，为啥要单独再去计算一个可信度？

我觉得没有必要。如分辨率出现了变化或二次截图这种明显会导致可信度计算非常差，我测试二次截图在第四步的可信度计算哪儿可信度会出现通不过的情况。如果去掉第四步是否可行？

我没有理解到为啥需要这一步，烦请告知！！！

https://github.com/AirtestProject/Airtest/blob/master/airtest/aircv/keypoint_base.py#L86

**Comment by rockywhisper** [comment]
@shouyong  Hi，您好。
图像识别中有好多种算法，各个算法都只是定位的工具、地位上是平等的。同一个图像测试脚本，会轮流使用这些算法依次去定位结果，这个过程中一定要用统一的可信度计算方式来评估识别结果好坏。

比如同一行脚本分别使用了`模板匹配`、`SURF`这两种，不能说模板匹配用可信度A算法评估识别结果，而SURF采用可信度B算法，这种的话识别结果的可信度之间没有对比性，也失去了评估价值；没法判定对于这一行脚本来说，究竟哪一种识别算法的结果是正确的。

因此目前使用的是统一的`归一化相关系数匹配值`作为识别结果评估算法。对于某一行脚本而言，如果发现识别结果可信度较低，有2种解决方式：
 - 修改截图、尽可能去除无效背景；
 - [调低脚本的threshold参数](https://airtest.doc.io.netease.com/tutorial/9_Improved_compatibility/#_4)、让低识别度结果通过。

**Comment by shouyong** [comment]
感谢您的解答，我大概懂你们设计意图了。我查询了一下 可信度使用模板匹配验证 是否是一个『最佳』答案，我这两天也考虑使用其它方法来实现可信度验证，没啥进展。

我看提交记录，你们最初就直接选用的模板匹配，是基于什么考虑的？

**Comment by smartcal1995** [comment]
学到了
