### ISSUE TITLE
oneplus Android10连接ide一直提示：pocoServer此应用为旧版Android打造，因此无法正常运行，请尝试检查更新或与开发者联系

### ISSUE THREAD

**Issue by liyaoyao6342** [AirtestProject/Airtest#717]
Remove any following parts if does not have details about

**Describe the bug**
oneplus Android10连接ide一直提示：pocoServer此应用为旧版Android打造，因此无法正常运行，请尝试检查更新或与开发者联系
IDE版本是1.2.1

**To Reproduce**
1. 连接了手机，屏幕投到IDE上
2.但是在IDE上点击手机的投屏没有反应
3.过一会就提示：pocoServer此应用为旧版Android打造，因此无法正常运行，请尝试检查更新或与开发者联系
4.pocoServer一直在重复安装

**Expected behavior**

**Screenshots**

**python version:** `python3.6`

**airtest version:** `1.2.1`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: oneplus 
 - OS: android 10
**Additional context**

**Comment by yimelia** [comment]
首先，请确认已经更新到最新版本的AirtestIDE（1.2.3），以及假如使用了本地python环境，确认本地环境中的airtest是最新版本（1.1.3），请注意区分这两个版本号是不同的。

然后，
> 连接了手机，屏幕投到IDE上
2.但是在IDE上点击手机的投屏没有反应

能否具体描述下，连接手机时是否勾选了use javacap，是否是最新版本

然后，
> 3.过一会就提示：pocoServer此应用为旧版Android打造，因此无法正常运行，请尝试检查更新或与开发者联系
这个没关系，点确定就行了，功能一样可用

> 4.pocoServer一直在重复安装
这个可能的原因有很多，Poco不可与uiautomator同时使用、电脑和手机不要连VPN、检查手机是否有助手类软件限制了pocoservice.apk的启动和后台运行、尝试重启手机等
