### ISSUE TITLE
selenium插件不支持if __name__ == '__main__':

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/Airtest#72]
```
driver = WebChrome()
driver.implicitly_wait(20)

print "111"
if __name__ == '__main__':
    print "333"  (前面的......用于缩进展示)
print "222"
````
airtestIDE (v0.0.19) 运行后，不会输出333，只输出了
111
222

建议安排个版本修复下

当前临时解决方法，可用 `if 1 == 1:` 方式来替代 `if __name__ == '__main__':`

**Comment by adolli** [comment]
IDE里启动的代码`__name__`并没有设置为`__main__`，而是另一个默认值，因为并不代表标准的python解释器启动。你可以直接开始写你的代码，无需判断`if 1 == 1:`
