### ISSUE TITLE
Windos appliciation connect_device 問題

### ISSUE THREAD

**Issue by youzhuliu** [AirtestProject/Airtest#721]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

用來測試 Windos appliciation 時,進行以下測試
Step1. connect_device("Windows:///?title_re=aaa.*") 
Step2. touch((0,0))
Step3. connect_device("Windows:///?title_re=bbb.*") 
Step4. touch((0,0))

發現Step4 touch((0,0))點擊的是aaa視窗的(0,0)位置 ,要如何才能在step4時點擊的是bbb視窗的(0,0)位置

,

**Comment by yimelia** [comment]
试一下这样：
```
from airtest.core.api import *

auto_setup(__file__, devices=["windows:///"])

dev1 = connect_device("windows:///199140")
dev1.touch((100, 200))
dev2 = connect_device("windows:///199164")
dev2.touch((100, 200))
```

**Comment by youzhuliu** [comment]
您好有幾個問題想請教:

![Uploading 擷取.PNG…]()

1.其中9699566,  29167952這個值如何在一開始就取得?

2.另外dev1.touch(圖片) 似乎無法執行

**Comment by yimelia** [comment]
窗口的句柄handle可以用VisualStudio\Spy++獲取，但是它會變化，用你之前的title_re=xx就挺好的。
dev1.touch(圖片)不支持，直接用touch(圖片)就可以了（默認是剛剛連上的窗口），如果要切換窗口可以用`set_current(0)`接口來切換到第一個窗口
暫時沒有disconnect接口

目前windows的支持比較弱，有些功能可能不夠完善

**Comment by youzhuliu** [comment]
connect_device("Windows:///")
    set_current(0)
    double_click(Template(r"tpl1587018338093.png", record_pos=(0.231, 0.228), resolution=(1920, 
    1080)))
    
    sleep(2)
    
    connect_device("Windows:///?title_re=OTA_AuthorityManagementSystem_Alpha.*")
    set_current(0)
    touch(Template(r"tpl1586830025291.png", rgb=True, record_pos=(1.0, 0.019), resolution=(500, 
    
    sleep(2)

    dev = connect_device("Android://127.0.0.1:5037/0123456789ABCDEF") 
    poco = AndroidUiautomationPoco(dev)
    set_current(0)
    sleep(1)
    touch(Template(r"tpl1587452851644.png", record_pos=(0.06, -0.102), resolution=(1280, 720)))

    poco(text="Settings").click()
    dev.shell("reboot")
    sleep(2)


您好想請教一下:
上面程式碼會依序
1. connect_device("Windows:///")
2.connect_device("Windows:///?title_re=OTA_AuthorityManagementSystem_Alpha.*")
3.connect_device("Android://127.0.0.1:5037/0123456789ABCDEF") 

會錯在第三步的touch(Template(r"tpl1587452851644.png", record_pos=(0.06, -0.102), resolution=(1280, 720))) , 錯誤為找不到圖片。 

我試過先用Aittest IDE連上Android://127.0.0.1:5037/0123456789ABCDEF 裝置 在單獨執行touch(Template(r"tpl1587452851644.png", record_pos=(0.06, -0.102), resolution=(1280, 720)))是可以正常執行的。

想請問為何會找不到圖片 ,謝謝

**Comment by yimelia** [comment]
每次执行`connect_device`，都会添加一个device到全局的设备列表中，`print(G.DEVICE_LIST)` 可以看到所有已经连上的设备，当前选中的设备可以用 `G.DEVICE` 或者 `device()`获取到。

然后 `set_current(0)`是把这个 `G.DEVICE_LIST` 的第0台设备设为当前设备（第一个连上的设备），应该和你的预期不一样，可以改成`set_current(2)`，或者是 `set_current(‘0123456789ABCDEF’)`

如果是按顺序执行的话，每次connect_device后，都会自动设为当前设备，所以不执行那句`set_current`也是可以的

**Comment by youzhuliu** [comment]
您好想另外請教一下:
       我想判斷一張圖片是否存在,如果存在sleep5秒,如果不存在則跳出while 迴圈

我目前code大概如下:
        while True:
        if exists(Template(r"tpl1588576875313.png", record_pos=(1.512, 0.078), resolution=(800, 700))):
            print("111")
            sleep(5)
        else :
            print("5555")
            break

錯誤訊息如下: AttributeError: 'NoneType' object has no attribute '__array_interface__'

我的目標是等一張圖片不存在後才繼續腳本,請問有甚麼方式更好嗎? 謝謝

**Comment by youzhuliu** [comment]
您好想另外請教一下:

我想做到等到圖片消失才繼續腳本。
目前我的code大概如下
.....
....
    while True:
        if exists(Template(r"tpl1588576875313.png", record_pos=(1.512, 0.078), resolution=(800, 700))):
            print("111")
            sleep(5)
        else :
            print("5555")
            break 
......
.....

但會報錯誤 AttributeError: 'NoneType' object has no attribute '__array_interface__'

想請教有甚麼更好的方法嗎 謝謝

**Comment by yimelia** [comment]
`array_interface`是否是你自己定义的一个接口？可以 完整的报错都贴出来看看
