### ISSUE TITLE
通过脚本打开网页的时候，报ImportError: cannot import name 'log_in_func'

### ISSUE THREAD

**Issue by Karlykj** [AirtestProject/Airtest#722]
写脚本通过打开谷歌浏览器，输入游戏作弊后台的地址，然后输入作弊 ，但是在运行的时候报错了
Traceback (most recent call last):
  File "E:/mud_auto_test/test_cases/micro_functions/cheat.py", line 12, in <module>
    from airtest.utils.selenium_proxy import WebChrome
  File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\utils\selenium_proxy.py", line 7, in <module>
    from airtest.core.helper import logwrap, log_in_func
ImportError: cannot import name 'log_in_func'
谷歌浏览器版本：
![image](https://user-images.githubusercontent.com/63385011/79436325-4dfe7380-8003-11ea-8fdc-1dc4df6d68b9.png)

代码截图如下：
![image](https://user-images.githubusercontent.com/63385011/79436233-30c9a500-8003-11ea-9df3-d7de8d0706f6.png)
![image](https://user-images.githubusercontent.com/63385011/79436257-3a530d00-8003-11ea-8fb9-fe3ce15279cd.png)

**Comment by yimelia** [comment]
airtest版本号是多少？更新到最新试一下

**Comment by Karlykj** [comment]
> airtest版本号是多少？更新到最新试一下

升级到1.1.3啦，还是报这个错- -

**Comment by yimelia** [comment]
最新版本的这个文件是有这个函数的，直接索引过去看一下
