### ISSUE TITLE
py脚本打包成exe后运行不了

### ISSUE THREAD

**Issue by LanceSmile** [AirtestProject/Airtest#724]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
将py程序，用pyinstaller打包成exe进行直接执行
程序用到的包，和运行情况如图显示（已经在执行路径下放了adb.exe）
![image](https://user-images.githubusercontent.com/43055496/79535971-79d83280-80b1-11ea-945e-0805e8981862.png)
![image](https://user-images.githubusercontent.com/43055496/79535985-82c90400-80b1-11ea-8c58-6acd59946bd0.png)

**预期效果**
(预期想要得到什么、见到什么)
1  请告知如果想要打包成可正常运行的exe该如何操作？
2 如果windows7 环境没有装python和airtest是否可以使用打包成功的exe

**python 版本:** `python3.7`

**airtest 版本:** `1.1.1`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)
windows7

**Comment by yimelia** [comment]
抱歉，我们没有试过这样做，无法提供帮助
