### ISSUE TITLE
命令行运行py脚本并传入自定义参数 提示 the following arguments are required: script

### ISSUE THREAD

**Issue by NumberShine** [AirtestProject/Airtest#726]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
在执行脚本时会执行arg_analysis函数来解析自定义参数own的传入字符串
但是通过命令行执行py脚本时会出现 the following arguments are required: script 
我初步判断是args = qap.parse_args().own 这一步出了错但是不知道如何解决

!
**相关截图**
![py](https://user-images.githubusercontent.com/63976117/79697695-a6a96700-82b6-11ea-916b-e1519b950861.png)
![cmd](https://user-images.githubusercontent.com/63976117/79697698-a741fd80-82b6-11ea-801b-4810d879b04f.png)

**python 版本:** `python3.6.6`

**airtest 版本:** `1.13`

**Comment by yimelia** [comment]
如果你的try.py是从我们提供的launcher.py改写而来的话，就也需要像airtest的run指令那样传参数，第一个参数是脚本，后面才是其他参数
也就是说，应该是 `python try.py  script.air airtest的参数 --own 其他参数`

**Comment by choubuzhaole** [comment]
直接运行py 脚本，而不是 main.air ,也可使用launcher 吗
