### ISSUE TITLE
【安卓10 MIUI 11 】airtest IDE连接不上

### ISSUE THREAD

**Issue by cheesefaye** [AirtestProject/Airtest#728]
设备 小米8  安卓10 MIUI 11 
adb已经连接上设备，点击connect，IDE连接不上，报错ADB指令执行失败，可能需要修改部分手机设置才能使用
![image](https://user-images.githubusercontent.com/38031847/79850792-0018af80-83f7-11ea-8478-c936b34b9c1c.png)

**airtest version:** 1.2.1
![image](https://user-images.githubusercontent.com/38031847/79851820-67832f00-83f8-11ea-8bad-3ed057bf235c.png)

**Comment by yimelia** [comment]
在官网下载最新版本 1.2.3的AirtestIDE，之前的版本不支持android10

**Comment by cheesefaye** [comment]
下载了最新版本 1.2.3的AirtestIDE，这个问题仍然存在

**Comment by yimelia** [comment]
MIUI11 需要勾选use javacap才可以看到画面

**Comment by cheesefaye** [comment]
可以了，感谢

**Comment by zhuangbiiii** [comment]
请问python包怎么改这个use javacap呢？不知道在哪里提问python包··· 

[14:47:55][DEBUG]<airtest.utils.nbsp> [airtouch_server]b'Aborted'
连接mumu模拟器

**Comment by yimelia** [comment]
文档里有，在连接手机时加?cap_method=javacap参数
或者是直接升级到MIUI12，MIUI12已经解决这个BUG了，不需要勾选javacap
