### ISSUE TITLE
多线程如何判断另一个线程的状态

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/Airtest#736]
之前提了个问题，说是运行测试脚本的时候APP会随时出现网络连接的问题
回复说是弄两个线程一个判断网络情况一个执行脚本

现在遇到另一个问题，就是脚本是持续执行的，不能所有的地方都添加判定网络情况的问题吧，这样脚本执行是不是会很慢啊。

个人感觉比较理想的情况是线程1执行测试脚本，线程2判定网络情况，2判定网络有问题的时候1暂停，2完成连接1再继续，可是python3 threading 不支持暂停和继续，用自己的方法会出现上述的问题，求帮助

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/81699982-a3ab2c00-949a-11ea-8342-c0ca520f71c6.png)

**Comment by abcdd12** [comment]
def run(self):
        while self.__running.isSet():
            self.__flag.wait()      # 为True时立即返回, 为False时阻塞直到内部的标识位为True后返回
            print time.time()
            time.sleep(1)
这一段是做了个循环，每次遇到wait（）的时候才会判断是否停止
也就是说需要在每部操作前都需要加这个判定?  有没有更好的方法
