### ISSUE TITLE
DownEvent is not defined when creating a multi-touch event

### ISSUE THREAD

**Issue by returnzer0** [AirtestProject/Airtest#738]
**Describe the bug**
I am trying to use long press gestures in my testing cases but it says that downevent is not defined. Even though I am following the playground example and importing all dependancies, it still gives me an error.

I want to tap at one point, swipe down, then contiune to hold that swipe for 3 seconds and then let go. Is there another way of achieving this? Thanks.

**The stack trace**
```
Traceback (most recent call last):
  File "airtest/cli/runner.py", line 65, in runTest
  File "six.py", line 686, in reraise
  File "airtest/cli/runner.py", line 61, in runTest
  File "/home/munib/Desktop/Airtest/Android.air/fb.py", line 89, in <module>
    DownEvent((100, 100), 0),
NameError: name 'DownEvent' is not defined
```

**To Reproduce**
Try to run this code https://github.com/AirtestProject/Airtest/blob/master/playground/android_motionevents.py

**Expected behavior**
I should be able to mimic continuous swipe

**python version:** `python3.6.5`

**airtest version:** `1.1.3`

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Latest Android

- Samsung Galaxy S5
- Last supported OS

- Galaxy Tab
- Latest OS supported

**Comment by yimelia** [comment]
sorry, it's a bug caused by us, modify the `from airtest.core.android.minitouch import *` to 
```
from airtest.core.android.base_touch import *
```
We will fix this problem in the next version

**Comment by returnzer0** [comment]
Thanks.

I looked through the documentation but I wasn't able to find any arguments for  DownEvent((100, 100), 0)?

For example, i can see that (100,100) is for the location x,y but what is the 0 for?

**Comment by yimelia** [comment]
0 is the first finger,

```
multitouch_event = [
    DownEvent((100, 100), 0),  // first finger touch (100, 100)
    DownEvent((200, 200), 1),  // second finger touch (200, 200)
    SleepEvent(1),
    UpEvent(0), UpEvent(1)]  // first finger up, second finger up

dev.minitouch.perform(multitouch_event)
```

**Comment by returnzer0** [comment]
Thanks again, where would I be able to find the documentation for this? I looked through the english documentation, and also used google translate to go through the chinese version as well. Would you be able to point me to where one might find all of the possible API methods?

**Comment by yimelia** [comment]
this url may help you: https://airtest.doc.io.netease.com/en/tutorial/0_automated_testing/
We are still working on the English version, so we haven't put it to the index page

**Comment by returnzer0** [comment]
If there is anything I can help with documenting, please let me know. Wouldn't mind expanding the English docs. Thanks again.

**Comment by yimelia** [comment]
hi, version 1.1.4 is updated, we modify `from airtest.core.android.base_touch import *` to

```
from airtest.core.android.touch_methods.base_touch import *
```
refer to https://github.com/AirtestProject/Airtest/releases/tag/v1.1.4
