### ISSUE TITLE
「华为手机」屏幕抓取异常，只抓到了左上角部分

### ISSUE THREAD

**Issue by ryan4yin** [AirtestProject/Airtest#739]
**详细描述问题bug：**
华为荣耀 V9 在长时间不关机地进行自动化测试后，可能会出现屏幕抓取异常的问题，只能抓到左上角部分，或者只抓到屏幕的上半部分。

**复现步骤：**

目前没有有效手段可以保证复现，只能碰运气。
但是一旦出现屏幕抓取异常，那台手机上后续所有的 UI 测试都会出现同样的屏幕异常。
更换 PC (Windows/Linux) 也没有任何效果，所以应该能确定是手机出了某些问题。

**预期效果**

正确地识别出手机的分辨率，抓取到完整的屏幕内容。

**相关截图**

![屏幕抓取不全](https://user-images.githubusercontent.com/22363274/82168937-8a6b0b00-98f2-11ea-8680-0f32c2c7ff3e.png)

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit` 和 `Ubuntu 18.04`

**airtest 版本:** `1.1.3`

**手机设备信息:**
 - 手机型号: 华为 Honor V9
 - Android系统版本号: Android 9
 - EMUI 版本号：9.0.1

**其他相关环境信息**

在 Ubuntu 18.04/WIndows 10 上均有此问题

**Comment by yimelia** [comment]
断开重连后，截到的屏幕内容能恢复正常吗？

**Comment by ryan4yin** [comment]
@yimelia 重连不行，换电脑都不行。

**Comment by yimelia** [comment]
看一下这里有个设置：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_6
那个屏幕分辨率的设置在手机里面是否是最高的选项，如果不是的话调整到最高，然后再插上试试看？

**Comment by ryan4yin** [comment]
自动化是在 Ubuntu 18.04 上跑的，出问题后换到了办公电脑（Windows 10），异常仍然存在。
拔了 USB 重连也没任何效果。

**Comment by ryan4yin** [comment]
@yimelia 可我刚刚重启了下 airtestide，异常突然就消失了。很奇怪

**Comment by yimelia** [comment]
我觉得也可能是因为IDE获取到的横竖屏结果不对，导致竖屏认为是横屏，就只截到了一部分图

**Comment by ryan4yin** [comment]
@yimelia 这里确实是被设成了智能分辨率。。

**Comment by ryan4yin** [comment]
那我把分辨率设为最高，然后把屏幕的自动旋转关掉。看看后续还会不会出这个问题。

**Comment by yimelia** [comment]
好的，可以再观察一下情况，屏幕旋转的判断应该也是有点问题
