### ISSUE TITLE
相對座標的使用方法

### ISSUE THREAD

**Issue by seantung910358** [AirtestProject/Airtest#742]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**

* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
想請教一下相對座標的使用方法  
直接將獲得的相對座標複製於touch中沒有預期效果  
例如 touch([0.608, 0.57])
想請教一下，如果是想直接複製相對位置應該設置甚麼參數嗎?
```



**设备:**
 - 型号: rog phone

**Comment by yimelia** [comment]
Airtest目前是不支持相对坐标的，touch需要传入的参数是绝对坐标
