### ISSUE TITLE
能否进行一次截屏,多个识图?

### ISSUE THREAD

**Issue by imhsz** [AirtestProject/Airtest#743]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
存在在同一个界面,尝试不同匹配的情况,每次都重新截图比较,会不会有性能损失?能否进行一次截屏,多个匹配?

**预期效果**
能否进行一次截屏,多个匹配?

**python 版本:** `python3.5`

**airtest 版本:** `1.2.3`

**其他相关环境信息**
window 10

**Comment by yimelia** [comment]
理论上可以，但是我们会更多考虑到在反复识图的过程中，界面有可能已经发生了新的变化，这样会导致这次识别可能会没有意义。

**Comment by imhsz** [comment]
比如一个UI,他的后续分支,本身可能有多种情况,在下个页面,快速判断走到哪个分支,目前的方式,是取多次图,对比多次.这种场景,就有必要.能否单独开出新方法,需要用的就用新的,不需要的就不影响.

**Comment by yimelia** [comment]
这种情况的话，你们可以考虑在现有接口的基础上做一些二次开发，来定制满足符合你们需求的接口。
