### ISSUE TITLE
请教个问题：touch(Template(r""))方法查找图片时调用的代码在哪里？

### ISSUE THREAD

**Issue by fengnex** [AirtestProject/Airtest#745]
想调整这个：template_matching.py
应该会调用：AirtestIDE_2020-01-21_py3_win64\airtest\aircv\template_matching.py，但是对这个文件改名、删除，下面这行代码仍然还能正常运行：
touch(Template(r"D:/tmp/imgs/tpl1590748457879.png"))

问题：touch(Template(r""))方法查找图片时调用的代码在哪里

**Comment by fengnex** [comment]
调整aircv.py和airtest\core\cv.py也一样，难道是代码被缓存到哪里去了还是怎样处理了？

**Comment by yimelia** [comment]
这样修改无效，因为用的是IDE里已经打包好的python环境。
如果要自己修改airtest代码，请部署自己的本地python环境，然后参考文档进行设置：https://airtest.doc.io.netease.com/IDEdocs/settings/1_ide_settings/#python
