### ISSUE TITLE
@JustinToken 如果对运行时间要求比较低的话，可以在连设备时，加参数 `cap_method=ADBCAP` ，这样使用的是ADB截图，速度会比较慢，但是应该不会报这个错

### ISSUE THREAD

**Issue by C-carrot** [AirtestProject/Airtest#747]
@JustinToken 如果对运行时间要求比较低的话，可以在连设备时，加参数 `cap_method=ADBCAP` ，这样使用的是ADB截图，速度会比较慢，但是应该不会报这个错

_Originally posted by @yimelia in https://github.com/AirtestProject/Airtest/issues/239#issuecomment-464571444_

为什么需要用adb截图呢，是子进程或者子线程里面都没有办法获取到设备的信息，和截图吗

**Comment by yimelia** [comment]
因为线程的机制问题导致的。

**Comment by C-carrot** [comment]
> 因为线程的机制问题导致的。

可以说的再详细一点点吗！

**Comment by yimelia** [comment]
你可以试试不用adb截图啊，然后就会看到报错信息了。

**Comment by C-carrot** [comment]
> 你可以试试不用adb截图啊，然后就会看到报错信息了。

我就是这么做并且报错了，找了许久的原因，发现可能是子进程调用那些api 可能传参有问题。。。

**Comment by C-carrot** [comment]
因为想要一直循环检查会不会有各种弹框，adb截图是不是会慢很多
