### ISSUE TITLE
使用swipe_along函数，报minitouch setup timeout错误

### ISSUE THREAD

**Issue by weiyanfen** [AirtestProject/Airtest#748]
**描述问题bug**
使用swipe_along函数，报minitouch setup timeout错误
只有这个语句会报错，其他不会
![image](https://user-images.githubusercontent.com/9304677/83504416-11290600-a4f7-11ea-8dd9-ef11f4b80461.png)

**python 版本:** `python3.7`
**airtest 版本:** ` 1.1.3`

**设备:**
 - 型号: 华为mate20pro
 - 系统: 10.0.0

**其他相关环境信息**
在Nova4，安卓8.0.0运行swipe_along是正常的

**Comment by yimelia** [comment]
接口发生改动了，下个版本会再对这个接口做一点修改
安卓10可以临时把minitouch改成maxtouch

**Comment by yimelia** [comment]
v1.1.4更新了，参考：https://github.com/AirtestProject/Airtest/releases/tag/v1.1.4
接口发生改动，请更新后注意同步一下
