### ISSUE TITLE
airtest 后台一直弹cmd黑框？

### ISSUE THREAD

**Issue by jekoie** [AirtestProject/Airtest#754]
我用PyQt写了个程序用到了airtest框架, 然后对PyQt打包成exe文件，使用的时候后台一直弹cmd黑框，关也关不掉，我不想让后台弹cmd黑框啊，怎么solve it?

![image](https://user-images.githubusercontent.com/6836400/84497531-8c519f80-ace1-11ea-9171-4939b22d0755.png)

**Comment by yimelia** [comment]
抱歉，这个我也不太清楚，我们没有试过这样操作
