### ISSUE TITLE
弱弱问下是否支持小程序测试？

### ISSUE THREAD

**Issue by BensonMax** [AirtestProject/Airtest#77]

**Comment by Meteorix** [comment]
可以的，跟安卓源生App一样测试

**Comment by XedGo** [comment]
@Meteorix  我下午测试了一下，发现界面录制点击小程序按钮，直接崩了

**Comment by BensonMax** [comment]
@Meteorix 
1.测试后发现:poco 无法获取小程序渲染后dum树， 只能通过opencv 的截图大法处理。感觉断了一只手。
2.同3楼，录制点击小程序控件会崩。
3.我同时尝试appium 系的控件定位（通过Chrome检测Webview），可以解析到小程序渲染后dum树。
![image](https://user-images.githubusercontent.com/31434954/41137906-5cd6acd8-6b10-11e8-9e35-f22a5b024189.png)

期待支持小程序~

**Comment by Meteorix** [comment]
@BensonMax @XedGo 感谢反馈，我们试了下开发版可以识别，会尽快放出可用版本。

另外控件识别录制的体验还在优化中

**Comment by Meteorix** [comment]
BTW，可以试试iOS上自动化微信小程序：https://github.com/AirtestProject/iOS-Tagent/blob/master/README_chs.rst

**Comment by Meteorix** [comment]
已经支持了Android和iOS上的小程序，看这里：https://testerhome.com/topics/14736
