### ISSUE TITLE
Android 10 MaxTouch 传入的 x.y是整数的时候 transform转换出来的总是0 touch方法不work

### ISSUE THREAD

**Issue by fredlluo** [AirtestProject/Airtest#774]
Android 10 MaxTouch 传入的 x.y是整数的时候 transform转换出来的总是0 touch方法不work.
使用的是python 2.7的环境

**Comment by yimelia** [comment]
没有必要调用到底层的maxtouch，更新到最新版，直接调touch语句就可以了，传入参数和以前一样
如果一定要自己调用底层的maxtouch，还得自己处理数据格式做一个归一化，比较麻烦
