### ISSUE TITLE
How airtest ide calculates record_pos for touch events?

### ISSUE THREAD

**Issue by Maciejszuchta** [AirtestProject/Airtest#776]
Simple question.
How is record_pos value calculated when creating touch event.
`touch(Template(r"tpl1595939095607.png", record_pos=(**0.491, 1.017**), resolution=(1440, 2960)))`

**Comment by yimelia** [comment]
It’s a bit complicated, it’s "the percentage of the coordinate offset relative to the resolution"

(maybe not explained clearly enough), here is the code:
```
    def calPosInPercent(mid_pos, resolution):
        _w, _h = resolution
        delta_x = (mid_pos[0] - _w * 0.5) / _w
        delta_y = (mid_pos[1] - _h * 0.5) / _w
        delta_x = round(delta_x, 3)
        delta_y = round(delta_y, 3)
        return delta_x, delta_y
```
