### ISSUE TITLE
android10下，银行类应用的登录界面无法截图（如有工商银行、建设银行)

### ISSUE THREAD

**Issue by rill** [AirtestProject/Airtest#777]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

android10下，银行类应用的登录界面无法截图（如有工商银行、建设银行)
一进入这个登录界面，airtest的连接就断了。其他界面都是正常的

（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1.打开airtest
2. 手机界面切换到工商银行应用的登录界面
3.勾选use Javacap+use orientation两个选项，然后连接手机
4. airtest的连接自动退出。

**预期效果**
(预期想要得到什么、见到什么)


**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到
airtest版本是最新的1.2.5

**设备:**
 - 型号: [红米K30]
 - 系统: [android10,miui11]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
可以尝试关闭手机的“安全键盘”选项，这个选项会导致部分机型不能输入密码的问题
如果还是没法解决的话，这个问题是暂时无解的，因为银行类app对安全的要求比较高，有一定防止自动化的措施
