### ISSUE TITLE
[mac] adb冲突

### ISSUE THREAD

**Issue by zhangliang2013506072** [AirtestProject/Airtest#781]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
本地有下载adb(1.0.41)，airtest(1.1.4)
airtest run 报错 adb server version (41) doesn't match this client (40); killing...

尝试替换/site-packages/airtest/core/android/static/adb/mac/adb 为本地adb(1.0.41) ，执行报错(error: unknown host service)

**相关截图**
![image](https://user-images.githubusercontent.com/42939345/89869355-d0c8c100-dbe6-11ea-820a-50300d7d1de3.png)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7`

**airtest 版本:** `1.1.4`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [华为meta30]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
macbook pro ， airtest run报错

**Comment by yimelia** [comment]
adb可执行文件替换成同一个即可

**Comment by xingBaGan** [comment]
晕死，我也遇到这个问题。这对以前装过adb 很不友好...
