### ISSUE TITLE
touch有什么方法可以复用吗？

### ISSUE THREAD

**Issue by vivian12** [AirtestProject/Airtest#783]
场景：
应用中有控制栏菜单，但是菜单会间隔几秒隐藏
所以在做自动化测试的时候，会反复的调用和隐藏控制栏
如果用touch控制栏图片的话
需要反复touch同一张
有什么办法可以直接把touch的结果设为变量，然后调用吗？

**Comment by yimelia** [comment]
可以，图片本来就是一个变量，a=图片, touch(a)

**Comment by vivian12** [comment]
> 可以，图片本来就是一个变量，a=图片, touch(a)

好的，谢谢
