### ISSUE TITLE
截图，断言后，程序直接挂掉

### ISSUE THREAD

**Issue by zhongqian** [AirtestProject/Airtest#79]
![qq 20180611172538](https://user-images.githubusercontent.com/23111098/41223472-79a49148-6d9c-11e8-9b34-34cdc0f11d51.png)
点击上面的按钮，程序直接挂掉，然后下图是日志
![qq 20180611172634](https://user-images.githubusercontent.com/23111098/41223530-9a238fbe-6d9c-11e8-8e27-28b9c9047707.png)

**Comment by Meteorix** [comment]
这是0.0.19版本的bug，新版本会修复，请先使用0.0.18版本

**Comment by yimelia** [comment]
你好 @zhongqian ，抱歉，这是我们的一个BUG，目前新版本已经修复，同时还支持了PY3，欢迎下载新版本进行体验 http://airtest.netease.com/changelog.html
