### ISSUE TITLE
可以提供terminate的方法给iOS设备。

### ISSUE THREAD

**Issue by chaooe** [AirtestProject/Airtest#793]
最近在使用iOS做自动化，WDA提供 terminate的api接口，用来在IOS上terminte package。
curl -X POST $JSON_HEADER \
-d "{\"bundleId\":\"com.apple.Preferences\"}" \
$DEVICE_URL/session/$SESSION_ID/wda/apps/terminate

如果需要我可以在core/ios/wda_client中增加该接口，并在ios.py提供该接口

**Comment by yimelia** [comment]
下个版本将会更新

**Comment by chaooe** [comment]
好的，我已经本地先用了1.1.5的版本。
