### ISSUE TITLE
Samsung Galaxy S8 - Video feed partially black

### ISSUE THREAD

**Issue by Whiteseeker** [AirtestProject/Airtest#8]
When I connect my Galaxy note 8 part of the video is black, and the main issue is that touch input doesn't seems to be generated at the proper position. See screenshot:

<img width="1116" alt="Note 8 screenshot" src="https://user-images.githubusercontent.com/4581097/37329687-a0f7fab6-2696-11e8-9348-6c7c2a86686e.png">

**Comment by Meteorix** [comment]
Hi, it is a known issue with some Samsung phones. 
Just change screen resolution to max in phone's settings to get over this issue.
![image](https://user-images.githubusercontent.com/3805278/37193199-ece7e4d6-23a3-11e8-9b68-02d0e6c5f1de.png)


replicated here https://github.com/AirtestProject/Airtest/issues/5#issuecomment-371723391
maybe we should add it to FAQ

**Comment by adolli** [comment]
I think the comment above had already solved this issue. So it could be closed.

**Comment by paiguFK** [comment]
谢谢引导，这里特意用中文说一下通过设置-显示-分辨率设置到最大（2960*1440）
