### ISSUE TITLE
卡while循环

### ISSUE THREAD

**Issue by zeryter** [AirtestProject/Airtest#80]
进入一个while循环后就不出来了，这怎么解：
通过ID判断一个返回按钮， 按钮点击页面刷新后没有相同ID的按钮，  但循环不停止。

**Comment by Meteorix** [comment]
请贴代码，不然没法帮你看呀

**Comment by zeryter** [comment]
找到问题了  
![image](https://user-images.githubusercontent.com/5753722/41274090-b3120110-6e4e-11e8-83cd-6c4a372a8b75.png)
这是我的代码 
这里需要重新获取下按钮     然后就可以正常使用了

**Comment by adolli** [comment]
对于cocos2d-x引擎的poco，由于使用的是快照模式，获取到UI状态后如果UI状态确实发生了改变，需要调用`ui.invalidate()`进行重新获取。

**Comment by adolli** [comment]
https://github.com/AirtestProject/AirtestIDE/issues/147
