### ISSUE TITLE
AirTest IDE 能不能支持在Ubuntu 18.04上进行录制，以及录制的时候能不能支持录制鼠标右键操作

### ISSUE THREAD

**Issue by wukunhong** [AirtestProject/Airtest#800]
AirTest IDE 能不能支持在Ubuntu 18.04上进行录制，以及录制的时候能不能支持录制鼠标右键操作

**Comment by yimelia** [comment]
暂时不会支持，可以在其他平台的电脑上面录制了脚本，再放到ubuntu类的Linux系统上面运行
