### ISSUE TITLE
为什么同样的.air脚本，当桌面应用的窗口放大之后， 再次执行就识别不到图片了

### ISSUE THREAD

**Issue by ss7424Refar** [AirtestProject/Airtest#801]
**描述问题bug**

```
为什么同样的.air脚本, 当桌面应用的窗口(比如钉钉桌面版应用)放大之后, 再次执行就识别不到图片了
```

**相关截图**
![log查看](https://user-images.githubusercontent.com/33996924/92987633-e6d3e500-f4f6-11ea-97b8-71e0542f24ae.png)

**复现步骤**
1. 录制一个简单的touch按钮的air脚本.
2. 断开钉钉窗口链接，并且放大一点桌面大小.
3. 再次选定钉钉窗口, 执行脚本
4. 报错

**预期效果**
应该还是能够识别到的.

**python 版本:** `python3.7` (内置版本)

**airtest 版本:** `1.2.5`

**设备:**
 - 型号: [钉钉桌面window版本]
 - 系统: [window10 企业版]

**其他相关环境信息**
(无)

**Comment by yimelia** [comment]
图片太小太简单，特征点不够多，导致特征点识别算法没生效，而用了普通的识别算法极其依赖于图片分辨率是否相同
