### ISSUE TITLE
模拟器支持录屏吗

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Airtest#803]
@yimelia

模拟器运行脚本支持录屏吗？
我连接模拟器，并在运行命令后加--recording，控制台有报错，录屏无法生存，报错截图如下
![image](https://user-images.githubusercontent.com/26775694/93370428-64934a00-f883-11ea-9905-903bb017cb48.png)

**python 版本:** `python3.6`

**airtest 版本:** `1.1.4`

**设备:**
夜神模拟器6.5.0.1

**其他相关环境信息**
windows7 64位

**Comment by yimelia** [comment]
模拟器的画面渲染方式和手机不同，所以不一定能录屏成功，每一款模拟器也各不相同
