### ISSUE TITLE
强烈建议runner用例失败时除了拋异常再截图一张

### ISSUE THREAD

**Issue by songzhenhua** [AirtestProject/Airtest#805]
/airtest/cli/runner.py中的runTest()，第64行log("Final Error", tb)，会在报告中显示错误信息。
但往往除了报错信息还希望看一下当时的UI到底是什么样子，可以极大的方便错误的排查。比如执行点击Button，报错了。但为什么呢？是跳到其他页面了，还是app崩了，还是跳出各种弹框遮挡了？尤其是各种弹框会自己消失的，没有截图很难破案！
所以，希望在63行增加:snapshot()

**Comment by yimelia** [comment]
done
代码已提交，下个版本将会生效，等过几天更新之后就有了

**Comment by songzhenhua** [comment]
点赞！

**Comment by yimelia** [comment]
已修复，请更新至1.1.6以上版本
