### ISSUE TITLE
我单独使用javacap进行投屏显示的时候视频出现了这种撕裂的情况应该如何处理呢

### ISSUE THREAD

**Issue by bzqyzzld** [AirtestProject/Airtest#806]
### 1. 开启javacap
```
adb shell CLASSPATH=package:/data/app/com.netease.nie.yosemite-2/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap -lazy 2>&1
```
### 2. 映射端口
```
adb forward tcp:8000 localabstract:javacap
```

### 3. 使用socket接收图片流信息

```python
import socket
from PIL import Image
from airtest import aircv
import uuid
import struct


client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = ("localhost", 8000)
client.connect(host)
info = client.recv(24)
while 1:
    try:
        client.send(b"1")
        length_size = client.recv(4)
        size = struct.unpack("<I", length_size)
        data = client.recv(size)
        screen = aircv.utils.string_2_img(data)
        img = Image.fromarray(screen)
        name = uuid.uuid1().__str__()
        img.save("./img/{}.png".format(name))
    except:
        pass
```
### 最后发现有些图片会有以下的情况
![e27bb6d0-fe33-11ea-b81f-b00594ec0f62](https://user-images.githubusercontent.com/66686171/94113262-33b1a700-fe79-11ea-890d-92b3722ecc93.png)

### 以下是视频
![blnrg-w4e2s](https://user-images.githubusercontent.com/66686171/94114463-f817dc80-fe7a-11ea-9590-9b69f0441000.gif)

**Comment by yimelia** [comment]
可以直接参考源码：https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/javacap.py
IDE底层也是用了这个

**Comment by bzqyzzld** [comment]
javacap这个文件并没有对上述有问题图片数据进行处理啊， 只是简单的接收了frame数据

**Comment by yimelia** [comment]
因为我们没有遇到问题图片

**Comment by bzqyzzld** [comment]
另外， 在一个循环周期内， 接收到了4位的数据长度， 解析出来之后有的长度非常大， 比如说 快有几千万的长度， 接下来用recv直接一次性 接收几千万的长度会超过buff缓存区的错误， 请问你们的ide大概是如何处理的呢

**Comment by yimelia** [comment]
我们用的源码就是airtest里面的javacap.py，可以直接使用源码啊
