### ISSUE TITLE
iOS设备打开横屏app，home键显示在中间，且识别为竖屏

### ISSUE THREAD

**Issue by yuxiuhui** [AirtestProject/Airtest#809]
**描述问题bug**
iOS设备打开横屏app，home键显示在中间，且识别为竖屏

**相关截图**
![image](https://user-images.githubusercontent.com/18139845/94359328-082cf780-00d9-11eb-970c-09216bd92c5c.png)
![image](https://user-images.githubusercontent.com/18139845/94359333-1844d700-00d9-11eb-8947-43118de9edb3.png)

**AirtestIDE 版本**: 1.2.5

**设备:**
1. iPhone6S   iOS13.1.2
2. iPhone8 iOS13.6
**其他相关环境信息**
Xcode11.7
python3.7

**Comment by yimelia** [comment]
请更新最新版本，包括AirtestIDE，ios-Tagent，和本地python环境中的airtest以及pocoui
