### ISSUE TITLE
JAVACAP内存泄露导致越用越慢

### ISSUE THREAD

**Issue by WangHaoNJU** [AirtestProject/Airtest#81]
JAVACAP生成的副进程stf.capture不断堆积导致内存占用过大，模拟器越跑越慢，超出资源会导致崩溃。

**Comment by Meteorix** [comment]
@codeskyblue 他说的是Javacap的调用问题，退出后没杀掉后台进程

**Comment by adolli** [comment]
增长速度正常，主要是adb shell进程结束后，手机上的stf.capture进程没有结束，所以每次积累下来就导致内存不够了

iPhoneから送信

2018/06/15 19:23、shengxiang <notifications@github.com>のメール:

**Comment by Meteorix** [comment]
fixed in this commit : https://github.com/AirtestProject/Airtest/commit/12ccaf2ce02cf72eca4e12ad4b35b6622a20f465
