### ISSUE TITLE
rgb is not working.

### ISSUE THREAD

**Issue by ids-kinoue** [AirtestProject/Airtest#810]
rgb is not working.

**To Reproduce**
1. Save the target image.
2. Check all of the rgb checkboxes.
3. Change the position.
![image](https://user-images.githubusercontent.com/40589931/94784423-16488400-0409-11eb-87e7-36baa51c9e6c.png)
4. Start Image recognition.

**Expected behavior**
Touch the color-matched Mona Lisa.

**Screenshots**
![test](https://user-images.githubusercontent.com/40589931/94783978-74289c00-0408-11eb-9130-b1451d540c71.gif)

1. [no editing]-> [Purple]
2. [Purple]-> [Green]
3. [Green]-> [no editing]

**python version:** `Airtest bundled version`

**airtest version:** `1.2.5`

**Smartphone:**
 - Device: ASUS_X01AD
 - OS: Android 9

**Comment by ids-kinoue** [comment]
Airtest is now able to recognize colors. Thank you very much. :)

**Comment by yimelia** [comment]
The currently updated airtest>=1.1.9 will have better support for rgb=True  :)
