### ISSUE TITLE
1.2.6版本问题

### ISSUE THREAD

**Issue by YongShing** [AirtestProject/Airtest#816]
1、使用过程中，现在的预览界面画质降低明显
2、使用过程中，存在闪退
3、使用时，截图时框类似于poco里面的乱画
4、使用poco录制时，存在录制点击等操作事件不同步响应的问题

**Comment by yimelia** [comment]
> 2、使用过程中，存在闪退

能否尽量提供闪退时的操作，或者是用命令行启动，在闪退时帮忙提供一些log方便我们检查问题？

> 3、使用时，截图时框类似于poco里面的乱画

这个能否更具体一点描述一下？

**Comment by yimelia** [comment]
目前可以更新1.2.7版本
