### ISSUE TITLE
在官方地址中，缺少：touch_methods 模块

### ISSUE THREAD

**Issue by Crett** [AirtestProject/Airtest#823]
https://airtest.readthedocs.io/en/latest/all_module/airtest.core.android.html
页面列表中缺少：touch_methods 模块
但是在页面左上角搜索中能够搜索到：https://airtest.readthedocs.io/en/latest/all_module/airtest.core.android.touch_methods.html?highlight=touch_methods#module-airtest.core.android.touch_methods
希望能维护下最新官方文档
这对我们很有帮助

**Comment by yimelia** [comment]
现在应该有了，不过实际使用中应该不需要手动指定touch method，交给airtest自行指定就行了
