### ISSUE TITLE
1.1.6版本basetouch无效求助

### ISSUE THREAD

**Issue by masterKLB** [AirtestProject/Airtest#828]
升级到1.1.6版本后，使用如下代码模拟拖动图标操作
longtouch_event = [
    DownEvent([908, 892]),# 待删除应用的坐标
    SleepEvent(2),
    MoveEvent([165,285]),# 删除应用的垃圾桶坐标
    UpEvent(0)]

dev.touch_proxy.perform(longtouch_event)

实际效果为仅拖动了下拉栏的第一行，如下
![image](https://user-images.githubusercontent.com/24997118/98779225-839afc00-242e-11eb-9c50-6cd1e2263614.png)

本地报错如下：
Note: device /dev/input/mouse0 is not supported by libevdev'
Note: device /dev/input/mice is not supported by libevdev'

尝试了安卓7/9的多个机器，现象一样

**Comment by yimelia** [comment]
没看懂问题描述。
可以尝试写一个更简单的点击操作，然后再修改。
airtest底层的所有touch和swipe操作也都是用这个downevent和moveevent完成的，只要能点击就有效，应该是你写的不对
