### ISSUE TITLE
adb.pull 命令报错：Permission denied

### ISSUE THREAD

**Issue by bigsea520** [AirtestProject/Airtest#829]
Remove any following parts if does not have details about

**Describe the bug**

通过adb.pull将手机 /data/data/com.tencent.mm/MicroMsg下的文件拉取到本地，但总是提示权限不够。

shell("su -c 'ls /data/data/com.tencent.mm/MicroMsg'")，可以解决shell命令下，权限不够的问题。虽然该目录chmod 777权限，但仍然adb.pull提示权限不够。

代码：
dev = device()  # 获取当前设备
dev.adb.pull('/data/data/com.tencent.mm/MicroMsg', 'D:/test') 

```
paste traceback here
```

airtest.core.error.AdbError: stdout[b"adb: error: failed to stat remote object '/data/data/com.tencent.mm/MicroMsg': Permission denied\r\n"] stderr[b'']

**Screenshots**

![2020-11-13_172156](https://user-images.githubusercontent.com/25249303/99056114-cbf41e80-25d4-11eb-81d4-1d7e46546a4e.png)
![2020-11-13_172212](https://user-images.githubusercontent.com/25249303/99056121-cd254b80-25d4-11eb-8728-3da0a2c4ff73.png)

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
帮不上忙，每个手机的权限限制是不一样的，具体和手机厂商有关
