### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by buihuuloc** [AirtestProject/Airtest#83]
![screen shot 2018-06-18 at 10 53 10 am](https://user-images.githubusercontent.com/1252560/41517557-fa5ba4e0-72e5-11e8-835b-e5febd0a0708.png)

Is this possible to use Airtest without using login module?

**Comment by Meteorix** [comment]
Here is a troubleshoot https://github.com/AirtestProject/iOS-Tagent/issues/1
> We can avoid error message of loading screen if we give quick command English >> GitHub Log-in right after log-in pop window appears on the screen.

We will fix the bug in next release

**Comment by buihuuloc** [comment]
Is that possible for using the Airtest IDE without login module?

**Comment by Meteorix** [comment]
It is fixed in the latest version: http://airtest.netease.com/changelog.html
