### ISSUE TITLE
airtest能测试mac应用吗？

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/Airtest#831]
如题，不是问能不能安装在mac上，是问**### 能不能测mac平台上的应用呢**？？

**Comment by chenDoInG** [comment]
https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way
个人建议多读几遍呢

**Comment by yimelia** [comment]
暂时还没有推出这个功能，未来会推

**Comment by IcyW** [comment]
> 暂时还没有推出这个功能，未来会推

请问今年或者明年有可能推出吗，期待
