### ISSUE TITLE
断言的识别精度与Image Editor中设置的不符

### ISSUE THREAD

**Issue by jackliujin** [AirtestProject/Airtest#832]
**描述问题bug**
断言的识别精度与Image Editor中设置的不符

Image Editor中：
![image](https://user-images.githubusercontent.com/38674876/99250955-84c19400-2847-11eb-82ea-3cc4f04ba878.png)
是不能匹配到图片的
报告中：
![image](https://user-images.githubusercontent.com/38674876/99251021-9c991800-2847-11eb-9840-d4ad566dda38.png)
报告中却是可以匹配到图片

**预期效果**
想让Image Editor中与报告中的图片识别是一致的

**python 版本:** `python3.5`

**airtest 版本:** `1.2.3`

**Comment by yimelia** [comment]
这个是曾经的设定，现在取消了，请更新至最新版本
