### ISSUE TITLE
windows环境下，start_recording录制失真，且分辨率不对（Android手机是2340x1080，录制后的视频是2340x2340）

### ISSUE THREAD

**Issue by zhangkunbin** [AirtestProject/Airtest#833]
**描述问题bug**
代码
```
    android = device()
    android.start_recording()
    sleep(20.0)
    android.stop_recording(output="v.mp4")
```
手机分辨率 2340x1080
录制后的视频分辨率为2340x2340
视频失真

**相关截图**
录制的视频截图
![1](https://user-images.githubusercontent.com/20456289/99645204-e2ddb980-2a89-11eb-818d-8f2892518643.png)

**预期效果**
录制视频的分辨率与手机一至，且不失真

**python 版本:** `python3.7`

**airtest 版本:** `1.1.6`

**设备:**
 - 型号: VIVO X23
 - 系统: Android9

**Comment by yimelia** [comment]
分辨率那个问题，是我们故意设置的，这样方便在竖屏转横屏的时候还能看到完整的屏幕。
清晰度的问题，可以参考文档：https://airtest.readthedocs.io/zh_CN/latest/wiki/device/android_zh.html#id13 调整一下参数即可
