### ISSUE TITLE
Error: The on-screen keyboard must be present to send keys

### ISSUE THREAD

**Issue by hhh3h** [AirtestProject/Airtest#835]
Hi, I got an error while using your iOS-Tagent with iPhone XS(13.1).
Let me know what problem is.

Error: airtest.core.ios.wda_client.WDAError: WDAError(status=6, value={'message': 'Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}'

**Comment by xzhacker123** [comment]
I have the same question.
iphone 6sp(13.2.2) xcode:11.6

Appears when using' text()' to input characters.

**Comment by xzhacker123** [comment]
It is works well on the lower version.

**Comment by IcyW** [comment]
Same question with iphone X(11.4) and Xcode11.3.1

**Comment by yimelia** [comment]
please update airtest/ios-Tagent/pocoui and try again
