### ISSUE TITLE
how to select/touch the specific part of image

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/Airtest#84]
Hello All,
I want to select a specific part of the image 
for example:
![image](https://user-images.githubusercontent.com/25879455/41519237-19695502-72f1-11e8-8c16-53081c97c1bf.png) 
from above image, I want to click on the 

![image](https://user-images.githubusercontent.com/25879455/41519507-c6d5af14-72f2-11e8-9168-9649adcd2d03.png) (arrow buttons)-- of  --- ![image](https://user-images.githubusercontent.com/25879455/41519265-487189aa-72f1-11e8-8775-3a247d50fac0.png) image.

Is there any way to add logic to touch on the right-left section of the image (by default it always clicks on the center of the image)?

 or any way to print or return the coordinates of the given image?

Thank you

**Comment by SUDARSHANCHAUDHARI** [comment]
Ok Sorry for the trouble.
Now I am able to print the co. ordinates of the given image but still stuck with the first question.

Is there any way to add logic to touch on the right-left section of the image (by default it always clicks on the center of the image)?

**Comment by Meteorix** [comment]
use `target_pos`, reference here: http://airtest.netease.com/docs/docs_AirtestIDE-en_US/1_online_help/airtest_intro.html#image-editor-feature
