### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python<=3.4.2.17 

### ISSUE THREAD

**Issue by app910** [AirtestProject/Airtest#849]
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python<=3.4.2.17 (from airtest) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.
10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 4.1.2.3
0, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.4
6, 4.5.1.48)

**Comment by app910** [comment]
pip install -U airtest


ERROR: Could not find a version that satisfies the requirement opencv-contrib-python<=3.4.2.17

**Comment by yimelia** [comment]
please update to the latest version 1.1.7
