### ISSUE TITLE
通过wda（IOS-target）进行的截图数据，无法通过cv2和pil解析，CV2返回none，pil 报错PIL.UnidentifiedImageError: cannot identify image

### ISSUE THREAD

**Issue by h496022202** [AirtestProject/Airtest#850]
**描述问题bug**
我在进行ios测试时，发现在进行截图比较那一步时，会抛出异常，跟踪发现，airtest在处理wda截图时，通过CV2进行转换时，会得到None，以下是

```
def string_2_img(pngstr):
    nparr = np.frombuffer(pngstr, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    return img
```

**相关截图**

![image](https://user-images.githubusercontent.com/5968479/103845015-24780180-50d6-11eb-8950-94a016f13572.png)

把字符串直接写入文件中，并保存为x.png，能够通过电脑图片浏览器能正常打开，但是通过cv2.imread("x.png")依然会得到None，通过PIL来打开该文件，会出现以下报错：
```
Traceback (most recent call last):
  File "/Users/huangqiang/PycharmProjects/hupanapp_automation/test.py", line 12, in <module>
    img = Image.open("/Users/huangqiang/PycharmProjects/hupanapp_automation/b.png")
  File "/Users/huangqiang/.pyenv/versions/3.7.0/lib/python3.7/site-packages/PIL/Image.py", line 2944, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/Users/huangqiang/PycharmProjects/hupanapp_automation/b.png'
```
请问这种问题有遇到没，怎么解决

**python 版本:** `python3.7`

**airtest 版本:** `1.1.6`
opencv-contrib-python 3.4.2.17
opencv-python         4.5.1.48

**设备:**
 mac os big sur 11.1

**Comment by h496022202** [comment]
发现wda截来的图是heic格式的

**Comment by yimelia** [comment]
更新到最新版本再试试，airtest和ios-tagent都更新一下，或者是换用appium的wda也可以
