### ISSUE TITLE
iOS真机在AirtestIDE1.2.6里，poco pause特别慢，并且点击位置不对（横竖屏问题）

### ISSUE THREAD

**Issue by ouluyao** [AirtestProject/Airtest#851]
### 版本：

- Mac 系统：macOS Catalina 版本10.15.4

- python版本：3.6

- AirtestIDE 版本：1.2.6

- Xcode版本：11.4

- 手机机型：iPhone X 

- 手机系统版本：12.1版本

### 问题描述：

1. 竖屏可以正确识别并点击，转换到横屏之后，可以识别，但是点击不了（用touch或者poco坐标、元素定位都点击不到，在IDE里用鼠标点击也点不到）
2. 用poco assistant 里的poco pause 试图定位元素，发现点击别处才可以框到对应的元素上，基于竖屏时可以点击，怀疑跟横竖屏转换有关系，基于报告来看大体验证了这一点
3. poco assistant 里的poco pause 特别卡，每次锁定之后，鼠标都要转半天都点不到需要定位的元素

### 录屏如下：
本例中是想用 poco("Next").click() 点击绿色的按钮，执行没有报错，从报告中可以看到点击到的位置实际是另一个位置
https://user-images.githubusercontent.com/38283928/104011213-b6702f00-51e8-11eb-9c4e-618615aaf0ff.mp4

**Comment by yimelia** [comment]
airtest更新到最新试试，目前对横屏和新版本ios的支持性都比之前好了很多
