### ISSUE TITLE
请问airtest修改版的minicap的源码有吗

### ISSUE THREAD

**Issue by s866** [AirtestProject/Airtest#854]
我看历史版本的minicap是源码格式的，后来就变成so文件了，由于目前的需求涉及到修改minicap源码，因为airtest的minicap和stf的minicap功能不一致，所以修改起来比较麻烦

**Comment by yimelia** [comment]
[jni.zip](https://github.com/AirtestProject/Airtest/files/5834401/jni.zip)

**Comment by yimelia** [comment]
试一下这个看看能不能下载

**Comment by s866** [comment]
> 试一下这个看看能不能下载

可以了😀
