### ISSUE TITLE
更新后获取ios元素定位特别慢

### ISSUE THREAD

**Issue by zuiqingfengyang** [AirtestProject/Airtest#855]
code11.4  airtest1.2.6 ，ios手机获取元素巨慢，一直处于重新连接中，这种是我版本不匹配吗？之前用的xcode9和ios-tagent没更新前不会出现这猴子那个情况

![image](https://user-images.githubusercontent.com/44047125/105149614-ad635400-5b3e-11eb-96c9-3aae79739da7.png)

**Comment by linjunshi** [comment]
同问，而且有时能被卡死，求解

**Comment by yimelia** [comment]
全部更新到最新看看，airtest，ios-tagent，IDE，pocoui都更到最新，最新版重做了ios部分
