### ISSUE TITLE
启动时报错，请问如何解决

### ISSUE THREAD

**Issue by JinYan527** [AirtestProject/Airtest#856]
**前提条件**
**python 版本:** `python2.7.15`
**airtest 版本:** `1.2.6`

**复现步骤**
1. 启动airtest exe

报错截图如下
![image](https://user-images.githubusercontent.com/78072734/105966111-30e0f000-60bf-11eb-8508-68d03a0a5f1c.png)

**Comment by yimelia** [comment]
如果能启动成功，就直接创建一个新的脚本，在你有权限的目录下面创建就可以了，应该是没问题的。
这个报错应该是第一次启动时，尝试默认创建一个脚本失败了，没有你的系统临时目录的写入权限，但是实际上是启动成功的。
