### ISSUE TITLE
建议修改日志前缀时间为24时制，最好再加上日期

### ISSUE THREAD

**Issue by songzhenhua** [AirtestProject/Airtest#863]
现在日志的时间前缀是12小时制，强烈建议改为24时制！最好再加上日期。

**Comment by yimelia** [comment]
下个版本会改为24小时制，但是加日期会导致log非常长，显示效果不太好看，所以还是没有加上日期

下面是两张示例图，如果能看得到的话。。。

![image](https://user-images.githubusercontent.com/6896468/108620179-4dc1d680-7465-11eb-8e41-d321af5296b5.png)

最终效果：

![image](https://user-images.githubusercontent.com/6896468/108620185-5dd9b600-7465-11eb-82a0-3bcd32890359.png)

**Comment by songzhenhua** [comment]
好的，辛苦~
