### ISSUE TITLE
win10下1.2.7版本无法搜索窗口

### ISSUE THREAD

**Issue by GFWisshit** [AirtestProject/Airtest#864]
**描述问题bug**
win10下1.2.7版本无法搜索窗口

```
pywintypes.error: (0, 'EnumChildWindows', 'No error message is available')
```

**相关截图**
![微信截图_20210222141415](https://user-images.githubusercontent.com/10723135/108669777-a2725980-7518-11eb-84ac-faffd24d75d5.png)

**复现步骤**
1. 点击 “搜索窗口”

**python 版本:** `IDE自带`

**airtest 版本:** `1.2.7`

**其他相关环境信息**
Windows 10 专业版 20H2

**Comment by GFWisshit** [comment]
1.2.6版本没问题

**Comment by yimelia** [comment]
1.2.8版本已经修复
