### ISSUE TITLE
使用本地python环境中连接iPad时，如果不是竖屏，点击位置错误

### ISSUE THREAD

**Issue by jihuer** [AirtestProject/Airtest#865]
## 步骤
1.AirtestIDE 更新到1.2.7版本
2.使用 pip install -U airtest 和 pip install -U pocoui 更新本地的版本
3.使用IDE 连接到ios设备，打开应用后没有转屏，是一个横屏应用
![image](https://user-images.githubusercontent.com/28520781/108673188-372b8600-751e-11eb-89dd-e44a5c95a58b.png)
4.由于没有转屏导致图片识别的位置和实际要点击的位置不同

**Comment by yimelia** [comment]
xcode中使用的ios-tagent有没有更到最新版？
用的ios是什么型号的手机？ios版本号是多少?

**Comment by jihuer** [comment]
ios-tagent没有更新到最新版，iPad mini 2 ios 版本号 12.5




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yimelia"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 下午3:02
收件人: "AirtestProject/Airtest"<Airtest@noreply.github.com&gt;; 
抄送: "i"<3130773247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AirtestProject/Airtest] 使用本地python环境中连接iPad时，如果不是竖屏，点击位置错误 (#865)





 
xcode中使用的ios-tagent有没有更到最新版？
 用的ios是什么型号的手机？ios版本号是多少?

**Comment by yimelia** [comment]
麻烦先把ios-tagent更新到最新再试试看

**Comment by jihuer** [comment]
好的，多谢了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yimelia"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 下午3:05
收件人: "AirtestProject/Airtest"<Airtest@noreply.github.com&gt;; 
抄送: "i"<3130773247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AirtestProject/Airtest] 使用本地python环境中连接iPad时，如果不是竖屏，点击位置错误 (#865)





 
麻烦先把ios-tagent更新到最新再试试看

**Comment by jihuer** [comment]
你好，我把ios-tagent更新到最新以后也还是不行，连接到ipad以后显示有点怪。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yimelia"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 下午3:06
收件人: "AirtestProject/Airtest"<Airtest@noreply.github.com&gt;; 
抄送: "i"<3130773247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AirtestProject/Airtest] 使用本地python环境中连接iPad时，如果不是竖屏，点击位置错误 (#865)





 
Closed #865.
