### ISSUE TITLE
check_app这个方法好像有bug  明明没有找到这个包名但是返回的是true 

### ISSUE THREAD

**Issue by kagamimoe** [AirtestProject/Airtest#87]
目的：每天准备定时出包跑冒烟测试，测试前需要检查包有没有出好。所以先安装，如果安装失败的话那就跳过测试阶段。

代码如下 ：
```python
os.system(adb_install)  #先安装包
a = Android()
if (a.check_app(package_name)):
    print ('测试包安装成功，开始初始化')
    start_app(package_name)
    sleep(10)
    install_init()
    stop_app(package_name)
else:
    print ('未发现测试包，可能出包失败或者安装失败')
```

但是本地测试结果是，**就算package_name不存在  check_app()返回的也是true** ，还是会继续开始测试。

**Comment by kagamimoe** [comment]
看了下代码，代码写的好像是一直return True呢。

```
    def check_app(self, package):
        """
        Perform `adb shell dumpsys package` command and check if package exists on the device
        Args:
            package: package name
        Raises:
            AirtestError: if package is not found
        Returns:
            True if package has been found
        """
        output = self.shell(['dumpsys', 'package', package]).strip()
        if package not in output:
            raise AirtestError('package "{}" not found'.format(package))
        return True
```

**Comment by Meteorix** [comment]
如果包名不在output里面，就会raise异常哦

**Comment by Meteorix** [comment]
@kagamimoe 我验证了下py2和py3版本都没有这个问题哦，先close了，有问题请继续反馈

**Comment by narrative** [comment]
Hello,

I too have run into this issue of `check_app` always returning `True`.

Running the command in `adb` myself, I see the reason why:

```
$ adb -s S8LBTC59U89T5HNR shell dumpsys package com.netease.poco.u3d.tutorial

Dexopt state:
  Unable to find package: com.netease.poco.u3d.tutorial
```

Even when the package is not found, the package name appears in the output.

That being said, it is an easy fix and wouldn't mind creating a PR if you are open to it.

**Comment by adolli** [comment]
@narrative thanks for your feedback. It is true that there is a bug here as the package name appears in the output if it does not really exist. We will have it fixed ASAP.

**Comment by zzldjkzxf** [comment]
@narrative  thanks for your example, we have repaired this bug.
