### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb'

### ISSUE THREAD

**Issue by anandplay17** [AirtestProject/Airtest#875]
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb'

Trying to run the script with python 3 . The solution page is not working as well. Can some one help ?

https://airtest.doc.io.netease.com/en/IDEdocs/run_script/1_useCommond_runScript/#python

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/en/IDEdocs/run_script/1_useCommand_runScript/#deploy-the-python-environment

`chmod +x adb`
