### ISSUE TITLE
On Windows 'tap' action happens with delays, no matter the settings 

### ISSUE THREAD

**Issue by GannaSlizkova** [AirtestProject/Airtest#879]
I'm trying to reuse the set of tests I have for Android
I need to change the step of opening a native app on mobile, so I added extra parameters to emulate a doubleclick on windows:
touch(Template(r"tpl1616700354583.png", record_pos=(-0.351, 0.236), resolution=(1081, 2312)), times=3, duration=0.4)
But it's not working
Is there an obvious way of making this work for Windows?

Thank you!

**Comment by yimelia** [comment]
try `double_click(Template(xxx))` ?

**Comment by GannaSlizkova** [comment]
Awesome, works for both win and mobile
Thank you!
