### ISSUE TITLE
poco自动识别控件位置，会有偏移

### ISSUE THREAD

**Issue by uplk** [AirtestProject/Airtest#881]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
有时候使用poco录制功能，鼠标放置的位置和poco实际框选的位置有些偏移
```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/59159115/112714636-2784d000-8f16-11eb-96cf-36c554b50a15.png)

**python 版本:** `python3.8`

**airtest 版本:** `1.0.81`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [Galaxy A6s]
 - 系统: [Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)
运行环境 window10

**Comment by uplk** [comment]
![image](https://user-images.githubusercontent.com/59159115/112714781-04a6eb80-8f17-11eb-9482-f903cbf26795.png)
这也是一个很离谱的错位

**Comment by uplk** [comment]
使用的app是，2021年3月26号在 网易云音乐官网下载的apk文件

**Comment by yimelia** [comment]
这个和具体的手机型号有关，有部分手机的屏幕渲染尺寸我们很难用通用的办法获取到，导致poco控件有偏移，具体可以查看 https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#ide_1

以及你也可以帮忙提供具体的手机型号和安卓版本号信息，我们后续尝试找方法兼容
