### ISSUE TITLE
There is a possibility that the nbsp_minitouch_server thread will remain.

### ISSUE THREAD

**Issue by ids-kinoue** [AirtestProject/Airtest#890]
https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/touch_methods/base_touch.py#L142

```python3
        if self.nbsp:
            self.nbsp.kill()
```

Why is this code not here?
Why not terminate nbsp in teardown?

https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/rotation.py#L92

```python3
    def teardown(self):
        self._t_kill_event.set()
        if self.ow_proc:
            self.ow_proc.kill()
        if self.nbsp:
            self.nbsp.kill()
```

The rotation watcher terminates the nbsp.

Doesn't this mean that the [nbsp_minitouch_server] thread will continue to remain?
It is possible that this is a bug, but I don't have the IDE source, so I can't confirm it.

**airtest version:** `1.1.9`

**Comment by yimelia** [comment]
hi @ids-kinoue 
Because nbsp is a daemon thread, it will automatically exit when the main process exits, https://github.com/AirtestProject/Airtest/blob/master/airtest/utils/nbsp.py#L48
