### ISSUE TITLE
Api level 26 - test.apk - Touch input not simulated 

### ISSUE THREAD

**Issue by Whiteseeker** [AirtestProject/Airtest#9]
When running on api lvl 26 using the test.apk (for Firebase) it looks as if no touch were simulated on the device. The scripts seems to be running and the logs shows that it find the image using OpenCv but it seems to have issues simulating the inputs (I'll gather logs and a repro script + apk and update the issue)

**Comment by Meteorix** [comment]
maybe we can fix it together this week @Whiteseeker

**Comment by zzldjkzxf** [comment]
I think it works well now. I'll close it. If there are some problem other, let us know. @Whiteseeker
