### ISSUE TITLE
打开特定APK，airtest连接就会断开

### ISSUE THREAD

**Issue by mp55** [AirtestProject/Airtest#908]
IDE1.2.9
连接设备看到手机屏幕以后，只要打开那个APK应用，连接就会断开
FreeOTP这个应用，点击确认权限进入到主界面就会这样

https://github.com/mp55/test/raw/main/error.apk

**Comment by yimelia** [comment]
手机有几个选项可以确认一下：
在输入法或者是安全里面，找到安全输入，选关闭
部分手机有选项“防止恶意截屏”，选关闭

升级到最新版本可以再试试
