### ISSUE TITLE
Device Screen problem - Android 8.0 - Galaxy S7

### ISSUE THREAD

**Issue by bhallionOhbibi** [AirtestProject/Airtest#92]
Hi,

i'm having an issue when connecting my Galaxy S7. The screen shows up like this

![galaxys7airtestide](https://user-images.githubusercontent.com/29798639/41903195-98fbd9ee-7935-11e8-94fc-668333531c97.png)

It would be no problem, but the touch positions are not corresponding.
For instance, on this image, if I want to press "Apps" then I need to press the low-right black section of the screen. (Where the "Apps" icon would have been if the screen was displayed correctly)
This is also an issue when using the touch() as it appear to be broken for elements placed in right/low portion of the screen.

Here's the log of the device screen connection:

> [DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 wait-for-device
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell getprop ro.build.version.sdk
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell ls /data/local/tmp/minicap
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell ls /data/local/tmp/minicap.so
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[DEBUG]<airtest.core.android.minicap> version:5
[DEBUG]<airtest.core.android.minicap> skip install minicap
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell pm path jp.co.cyberagent.stf.rotationwatcher
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-Z3I49nSznx1hzpi2g1aGPA==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 forward --no-rebind tcp:18994 localabstract:minicap_18994
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_18994' -P 1440x2560@450x800/0 -l 2>&1
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 20142'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1440x2560@450x800/0'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:264) Setting buffer options'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:268) Creating CPU consumer'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:272) Creating frame waiter'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_26.cpp:276) Publishing virtual display'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder'
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:473) Server start'
[DEBUG]<airtest.core.android.minicap> (1, 24, 20142, 1440, 2560, 450, 800, 0, 2)
[DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:475) New client connection'
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell getprop ro.product.cpu.abi
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell getprop ro.build.version.sdk
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell ls /data/local/tmp/minitouch
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell ls -l /data/local/tmp/minitouch
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell rm /data/local/tmp/minitouch*
[INFO]<airtest.core.android.rotation> update orientation None->0.0
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell dumpsys display
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 push D:\\Prog\\AirtestIDE\\airtest\\core\\android\\static\\stf_libs\\arm64-v8a\\minitouch /data/local/tmp/minitouch
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell dumpsys SurfaceFlinger
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell chmod 755 /data/local/tmp/minitouch
[INFO]<airtest.core.android.minitouch> install_minitouch finished
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell dumpsys display
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell getevent -p
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 forward --no-rebind tcp:12682 localabstract:minitouch_12682
[DEBUG]<airtest.core.android.adb> D:\Prog\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ce11160b1d16042505 shell /data/local/tmp/minitouch -n 'minitouch_12682' 2>&1
[DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[DEBUG]<airtest.core.android.minicap> update_rotation: 0.0
[DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type B touch device sec_touchscreen (4095x4095 with 10 contacts) detected on /dev/input/event1 (score 25104)'
[DEBUG]<airtest.core.android.minitouch> minitouch header:b'v 1\n^ 10 4095 4095 0\n$ 20184\n'
[DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'

I'm using AirtestIDE v0.1.1 on Windows 10 x64

**Comment by Meteorix** [comment]
Please try this solution https://github.com/AirtestProject/Airtest/issues/5

**Comment by bhallionOhbibi** [comment]
Perfect ! Thanks a lot

**Comment by Meteorix** [comment]
：）
