### ISSUE TITLE
swipe函数逻辑有不合理的地方

### ISSUE THREAD

**Issue by JIMhackKING** [AirtestProject/Airtest#921]
**描述问题bug**
在研究swipe函数的实现方法时，发现在vector参数的处理逻辑部分有不合理之处。vector参数的坐标只能传正数，无法实现拖动到v1参数坐标的左上方

**我个人觉得的预期效果**
vector无论传入正坐标或者负坐标，都能使鼠标能拖动到v1参数的相对位置
```python
# airtest/core/api.py  318行
# 此处如果想移动到左上方的位置，会被这个判断语句拦截，导致变成移动到屏幕百分比位置
if vector[0] <= 1 and vector[1] <= 1:
    w, h = G.DEVICE.get_current_resolution()
    vector = (int(vector[0] * w), int(vector[1] * h))
```
应改为：
```python
# airtest/core/api.py  318行
if 0 <= vector[0] <= 1 and 0 <= vector[1] <= 1:  # 加上判断是否为浮点数会更好，因为如果是坐标则不可能是浮点数
    w, h = G.DEVICE.get_current_resolution()
    vector = (int(vector[0] * w), int(vector[1] * h))
```

**python 版本:** `python3.7`

**airtest 版本:** `1.1.11`

**设备:**
 - Windows10

**Comment by yimelia** [comment]
没看明白你的意思，我这里传负的vector没什么问题啊：
```
swipe(Template(r"tpl1632992730100.png", record_pos=(-0.125, 0.307), resolution=(1080, 2220)), vector=[-0.2088, -0.1402])
```
下面是运行截图，如果你能看得到图片的话，可以看到手机屏幕有一道轨迹，是往左上方滑动的：

![image](https://user-images.githubusercontent.com/6896468/135422993-b2116488-d906-4e74-81fa-87984a7b7c0c.png)
