### ISSUE TITLE
V0.1.2 版本生成的报告匹配度多出一个百分号

### ISSUE THREAD

**Issue by lynnlake** [AirtestProject/Airtest#93]
V0.1.2 版本生成的报告, 匹配度显示多了一个百分号

![image](https://user-images.githubusercontent.com/9314660/41951492-ba0ba948-79fd-11e8-8e5d-49fe05682f05.png)

**Comment by zzldjkzxf** [comment]
@lynnlake 这个在最新版本已经修复。
