### ISSUE TITLE
Airtest IDE升级到1.2.10后touch无法点击

### ISSUE THREAD

**Issue by ttxz** [AirtestProject/Airtest#935]
**设备控制**

**Airtest IDE更新至1.2.10和Airtest 1.2.0后，Touch无法在5.1.1设备上正确执行，在Android5.1.1上不执行点击操作，降回Airtest IDE 1.2.9和Airtest 1.1.11后正常**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.9`

**airtest 版本:** `1.2.0`

**设备:**
 - 系统: [e.g. Android 5.1.1]

**Comment by ttxz** [comment]
没人回复吗，好像旧版本有时也会出现

**Comment by my-autoxuexi** [comment]
我也是发现有这个问题，不是无法点击，是点击位置发生偏移，1.20尤其明显，

**Comment by Irislm** [comment]
而且click点击的时候，会将 android 的顶部菜单栏拉下来一点,，然后恢复
python版本：3.7.8
airtest版本：1.2.0
pocoui：1.0.82
设备：
型号 Huawei Honor 9 STF-AL00
Android 7.0
EMUI5.1.1

**Comment by yimelia** [comment]
可以更新到最新版本再试
