### ISSUE TITLE
android.py的get_top_activity_name()注释写错了

### ISSUE THREAD

**Issue by songzhenhua** [AirtestProject/Airtest#943]
airtest1.2.0
/Users/szh/opt/miniconda3/envs/upgrade/lib/python3.8/site-packages/airtest/core/android/android.py

    def get_top_activity_name(self):
        """
        Get the top activity name

        Returns:
            (package, activity, pid)

        """
        tanp = self.get_top_activity()
        if tanp:
            return tanp[0] + '/' + tanp[1]
        else:
            return None

返回的不是 (package, activity, pid)，是package/activity

**Comment by yimelia** [comment]
感谢指出，我们将在下个版本修改这个问题
