### ISSUE TITLE
图像没有匹配到，但是却通过了wait函数的检测

### ISSUE THREAD

**Issue by AnewG** [AirtestProject/Airtest#948]
**描述问题bug**
图片没有匹配到，但是却通过了wait函数的检测，是哪里有bug吗

![image](https://user-images.githubusercontent.com/1912339/127597050-7ca2e86f-fd07-45a1-921e-87bcf1ebdda2.png)

**复现步骤**
1. 添加wait函数
2. 运行脚本
3. 图像还未出现
4. 提示已找到，脚本继续往下，造成后续流程混乱

**预期效果**
等待直到图片出现或达到超时时间，不应该直接通过

**python 版本:** `Python3.6.5`

**airtest 版本:** `1.2.10`

**手机设备:**
 - oppo R11plus,Android8.1.0

**其他相关环境信息**
mac版airtestIDE

**Comment by 260147169** [comment]
###[我也遇到了相似的问题，我认为可能是图像识别算法mstpl的错误。在Template图片对象中添加参数rbg=True，即提升判定的严格程度可以解决我的问题，你可以尝试类似的方法。具体参数设置可见](https://github.com/AirtestProject/Airtest/releases/tag/v1.2.0)

**Comment by AnewG** [comment]
> 我也遇到了相似的问题，我认为可能是图像识别算法mstpl的错误。在Template图片对象中添加参数rbg=True，即提升判定的严格程度可以解决我的问题，你可以尝试类似的方法。具体参数设置可见(https://github.com/AirtestProject/Airtest/releases/tag/v1.2.0)

谢谢
