### ISSUE TITLE
真机是OLED屏如何保证屏幕在执行case的过程中不息屏

### ISSUE THREAD

**Issue by RockyHomWang** [AirtestProject/Airtest#957]
真机是OLED屏如何保证屏幕在执行case的过程中不息屏

真机实例：HUAWEI Mate30

**Comment by yimelia** [comment]
部分手机（例如OPPO），在开发者选项里有一个**充电时屏幕不休眠**的选项，打开就不会了。华为的话可以找一下看看有没有类似选项
