### ISSUE TITLE
請問如何在腳本中針對 adb 中斷現在連結中的手機呢？

### ISSUE THREAD

**Issue by ts00651266** [AirtestProject/Airtest#959]
連結手機使用 connect_device(), 那請問中斷指定手機的話該怎麼做呢？

**Comment by yimelia** [comment]
暂时没有相关的接口，可以描述一下具体的使用场景吗？

**Comment by ts00651266** [comment]
目的：連結兩隻以上手機執行airtest,電量充不回來100%，所以希望更改成輪流交替的方式來執行自動化測試。

流程：
1. 有A、B兩支手機連接電腦
2. 寫好一個測試流程的腳本指定A手機測試
3. 測試腳本執行到一個指定的規則會判斷手機電量是否低於15%
4. 如果A手機電量低於15%，disconnect A手機, connect_device( B手機 )

5. 依此類推，輪流充電

但是 python import airtest 沒有中斷 devices 的 api 指定可以下disconnect， 而 IDE 有此按鈕。

目前在python 有使用過 os.system("adb disconnect)，但我的 oppo reno3 插著也充不太回來。

請問有更好的方式輪流充電並持續測試嗎？

電腦是 Mac pro

yimelia ***@***.***> 於 2021年9月30日 週四 下午3:40 寫道：

**Comment by yimelia** [comment]
@ts00651266 
这样的功能，可能需要从硬件的方面来考虑了，因为USB线在连接之后就会自动开始充电，很难简单用软件控制。也许可以考虑一些智能硬件，从电源、插座上尝试

**Comment by ts00651266** [comment]
感謝您，我再想想其他方式來解決此問題～

yimelia ***@***.***> 於 2021年10月8日 週五 上午10:14寫道：
