### ISSUE TITLE
MINITOUCH点击位置偏移和解决方案

### ISSUE THREAD

**Issue by bruned12** [AirtestProject/Airtest#973]
版本1.2.2

![image](https://user-images.githubusercontent.com/30997009/135400016-436f08d6-6e67-4091-8461-0b02eeb8b3c2.png)
![image](https://user-images.githubusercontent.com/30997009/135400119-f5b72e91-32b1-4be2-89bd-b7b6f6eeef0a.png)
这样就可以解决了

**Comment by yimelia** [comment]
可以先更新到最新版本1.2.3看看是否还有问题。这个可能是上个版本有部分设备横竖屏有问题导致的
