### ISSUE TITLE
使用 airtest.aircv.sift.find_sift 方法 抛错“Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)”

### ISSUE THREAD

**Issue by Chris8711** [AirtestProject/Airtest#991]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

* 图像识别、设备控制相关问题 -> 按下面的步骤
**描述问题bug**
使用 airtest.aircv.sift.find_sift 方法 抛错“Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)”

```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**复现步骤**

import airtest.aircv.sift as acs
import airtest.aircv.aircv as ac

app = ac.imread('st.png')
st = ac.imread('st.png')
acs.find_sift(app, st, rgb=False)

**python 版本:** `python3.9.7`

**airtest 版本:** `1.2.3`

**其他相关环境信息**
MacBook Pro (16-inch, 2019)
macos 11.3.1 (20E241)

**Comment by yimelia** [comment]
这个问题猜测和opencv版本号有关，但是因为C++层面的报错我们不方便调试，所以暂时还不太清楚原因。

我测试了两个版本的环境：python3.9，`opencv-contrib-python==4.5.2.54`会出现问题：

```
kp_sch, des_sch = sift.detectAndCompute(im_search, None)
cv2.error: Unknown C++ exception from OpenCV code
```

但是在`opencv-contrib-python==4.5.4.60`这个版本下可以正常运行，可以先试试看？
